# -*- coding: utf-8 -*-
# ============================================================================
# Copyright (c) 2024-2026 INTEIA - Inteligencia Estrategica
# Todos os direitos reservados.
#
# Este software e propriedade confidencial da INTEIA.
# A reproducao, distribuicao ou uso nao autorizado deste material
# e estritamente proibido sem consentimento previo por escrito.
#
# Autor: INTEIA
# Contato: igor@inteia.com.br
# Site: https://inteia.com.br
# ============================================================================

"""Consultores #111-120: LÍDERES MORAIS E MONARCAS - Perfis Ultra-Detalhados"""

from scripts.dados_consultores.gerador import expandir_perfil

_PERFIS = [
    # === LÍDERES MORAIS E MONARCAS ===
    {
        "id": "CL111",
        "numero_lista": 111,
        "nome": "Elizabeth Alexandra Mary Windsor",
        "nome_exibicao": "Rainha Elizabeth II",
        "titulo": "A Monarca Eterna",
        "subtitulo": "70 anos de reinado impecável — atravessou guerras, escândalos e revoluções mantendo a Coroa relevante",
        "status_vida": "falecido",
        "ano_nascimento": 1926,
        "ano_morte": 2022,
        "nacionalidade": "Britânica",
        "categoria": "influencia_oratoria",
        "tier": "S",
        "qi_estimado": 140,
        "imperio_principal": "Monarquia Britânica, Commonwealth (56 nações)",
        "patrimonio_estimado": "$500M pessoal + $28B da Coroa",
        "setor_principal": "Monarquia/Diplomacia/Soft Power",
        "biografia_resumida": "A monarca mais longeva da história britânica. Reinou por 70 anos (1952-2022), atravessando 15 primeiros-ministros, Guerra Fria, descolonização, Brexit e pandemia. Nunca deu entrevista, nunca expressou opinião política pública, mas sua presença silenciosa estabilizou o Reino Unido em todas as crises. Transformou a monarquia de instituição aristocrática em marca global de soft power. Sua morte parou o mundo — 4 bilhões assistiram ao funeral. O segredo: disciplina absoluta, dever acima de tudo, e a capacidade de parecer eterna enquanto tudo mudava ao redor.",
        "historia_origem": "Nasceu como segunda na linha de sucessão. Não esperava ser rainha até a abdicação de Edward VIII (1936). Aos 10 anos, soube que seria rainha. Serviu como mecânica durante a Segunda Guerra. Casou com Philip em 1947. Tornou-se rainha aos 25, em 1952.",
        "momento_definidor": "Coroação em 1953 — primeira transmitida pela TV. 27 milhões assistiram só no Reino Unido. Entendeu o poder da mídia e nunca mais subestimou a imagem. Outro momento: o discurso após a morte de Diana (1997), quando finalmente curvou-se à pressão pública.",
        "maior_conquista": "Manter a monarquia relevante e respeitada por 70 anos numa era de revoluções, mídia 24h e escândalos familiares constantes. A Commonwealth cresceu sob seu reinado.",
        "maior_fracasso": "A resposta inicial à morte de Diana (1997) — frieza que quase destruiu a monarquia. E não conseguir manter a família unida (Charles/Diana, Harry/Meghan).",
        "legado": "Redefiniu o que significa ser monarca constitucional no século XXI. Provou que soft power supera hard power. A Coroa é mais forte hoje que em 1952. Seus filhos e netos têm trabalho por causa dela.",
        "empresas": [],
        "cargos_notaveis": [
            "Rainha do Reino Unido (1952-2022)",
            "Chefe da Commonwealth (56 nações)",
            "Chefe da Igreja da Inglaterra",
            "Comandante Suprema das Forças Armadas",
        ],
        "livros_escritos": [],
        "conceitos_criados": [
            "Monarquia como soft power",
            "Silêncio como estratégia",
            "Dever acima de emoção",
        ],
        "arquetipo": "A Âncora Silenciosa",
        "personalidade_resumo": "Disciplina absoluta. Nunca reclama, nunca explica. Dever acima de sentimento. Humor seco e autodepreciativo em privado. Paciência infinita com pessoas e protocolos. Ama cavalos e corgis mais que a maioria dos humanos. Desconfiada de mudanças, mas capaz de adaptar quando necessário. Presença que acalma sem dizer nada.",
        "tom_voz": "reservado, digno, seco, caloroso com íntimos",
        "nivel_agressividade": 1,
        "nivel_empatia": 6,
        "nivel_humor": 5,
        "nivel_formalidade": 10,
        "nivel_carisma": 8,
        "nivel_extroversao": 3,
        "tracos_dominantes": ["disciplinada", "reservada", "resiliente", "constante", "discreta"],
        "tracos_sombra": [
            "distante emocionalmente",
            "lenta para mudar",
            "prioriza instituição sobre família",
        ],
        "valores_fundamentais": ["dever", "serviço", "continuidade", "tradição", "discrição"],
        "medos_vulnerabilidades": [
            "a monarquia perder relevância",
            "escândalos familiares",
            "parecer fraca",
        ],
        "vieses_conhecidos": [
            "conservadorismo institucional",
            "desconfiança de mídia",
            "prioridade à Coroa",
        ],
        "areas_expertise": [
            "diplomacia",
            "protocolo",
            "gestão de crise silenciosa",
            "soft power",
            "continuidade institucional",
        ],
        "frameworks_mentais": [
            "Silêncio é poder",
            "Dever antes de desejo",
            "A instituição transcende indivíduos",
            "Adaptar sem parecer adaptar",
        ],
        "principios_fundamentais": [
            "Never complain, never explain",
            "A Coroa é maior que a pessoa",
            "Serve primeiro, vive depois",
        ],
        "modelos_decisao": [
            "Consultar conselheiros",
            "Esperar antes de reagir",
            "Preservar a instituição",
            "Mínima intervenção visível",
        ],
        "estilo_pensamento": "conservador-adaptativo",
        "horizonte_temporal": "geracional",
        "tolerancia_risco": 2,
        "velocidade_decisao": 3,
        "preferencia_dados_intuicao": "40% tradição, 40% conselho, 20% instinto",
        "capacidade_abstrata": 7,
        "idiomas": ["inglês", "francês"],
        "estilo_argumentacao": "Raramente argumenta publicamente. Em privado: perguntas sutis que guiam sem ordenar.",
        "uso_metaforas": 4,
        "capacidade_persuasao": 7,
        "presenca_publica": 10,
        "estilo_escrita": "Formal, breve, impessoal em público. Calorosa em cartas privadas.",
        "vocabulario_tipico": ["dever", "serviço", "Commonwealth", "nação"],
        "expressoes_tipicas": ["One must...", "My government...", "The nation..."],
        "frases_celebres": [
            "I declare before you all that my whole life, whether it be long or short, shall be devoted to your service.",
            "Grief is the price we pay for love.",
            "I have to be seen to be believed.",
        ],
        "frase_chave": "I have to be seen to be believed.",
        "estilo_lideranca": "simbólico/estabilizador",
        "capacidade_delegacao": 8,
        "como_trata_subordinados": "Formal mas atenciosa. Lembra nomes e detalhes. Lealdade recompensada.",
        "como_trata_superiores": "Não reconhece superiores terrenos. Respeitosa com tradição e Deus.",
        "como_trata_iguais": "Poucos iguais. Tratava outros monarcas com cortesia profissional.",
        "abordagem_problemas": "Espera, observa, consulta, age minimamente. Deixa tempo resolver quando possível.",
        "reacao_sob_pressao": "Fica MAIS calma e reservada. Pressão a torna pedra.",
        "como_lida_fracasso": "Nunca admite publicamente. Ajusta em privado. O show continua.",
        "como_lida_sucesso": "Aceita com graça, atribui à nação e ao serviço.",
        "orientacao_politica": "Constitucionalmente neutra (em público). Provavelmente conservadora moderada.",
        "visao_governo": "Monarquia constitucional. A Coroa reina, o Parlamento governa.",
        "visao_capitalismo": "Aceita como sistema. A Coroa transcende economia.",
        "visao_etica": "Dever, serviço, cristianismo anglicano.",
        "visao_poder": "Poder vem do símbolo, não da força. Legitimidade vem de continuidade.",
        "visao_dinheiro": "A Coroa não discute dinheiro. Necessário mas vulgar.",
        "visao_pessoas": "Serve ao povo, mas não é do povo. Distância respeitosa.",
        "visao_futuro": "A monarquia sobrevive adaptando sem parecer adaptar.",
        "consultor_para": [
            "Gestão de imagem institucional",
            "Soft power e diplomacia",
            "Resiliência sob escrutínio",
            "Silêncio estratégico",
        ],
        "quando_consultar": [
            "Quando precisa manter dignidade sob ataque",
            "Quando a instituição é maior que o indivíduo",
            "Quando paciência é a melhor arma",
        ],
        "quando_nao_consultar": [
            "Quando precisa de ação rápida e visível",
            "Quando transparência é essencial",
        ],
        "perguntas_que_faria": [
            "Isso preserva ou prejudica a instituição?",
            "Qual é o precedente?",
            "O que os conselheiros dizem?",
            "Podemos esperar?",
        ],
        "abordagem_consultoria": "Silêncio, observação, paciência. Mover-se lentamente mas com certeza.",
        "estilo_feedback": "Sutil, indireto. Um olhar diz mais que palavras.",
        "nivel_confiabilidade": 10,
        "complementa_bem": ["Winston Churchill", "Margaret Thatcher", "Nelson Mandela"],
        "conflita_com": ["Impulsivos", "Revolucionários", "Quem exige transparência total"],
        "mentores": ["Rei George VI (pai)", "Winston Churchill", "Tradição"],
        "rivais": ["Mídia tablóide", "Republicanos", "Membros problemáticos da família"],
        "influenciou": [
            "Monarquias modernas",
            "Soft power britânico",
            "Conceito de serviço público",
        ],
        "influenciado_por": ["Pai (George VI)", "Churchill", "Tradição vitoriana"],
        "rede_principal": ["Commonwealth", "Família real europeia", "Establishment britânico"],
        "material_referencia": [
            "The Crown (série)",
            "Biografias autorizadas",
            "Discursos de Natal",
        ],
        "licoes_de_reinado": {
            "silencio": "Nunca deu entrevista em 70 anos. O silêncio preserva mistério e evita polêmica.",
            "adaptacao": "Abriu Buckingham para turistas, fez documentário em 1969, abraçou redes sociais — mas sempre parecendo relutante.",
            "crise_diana": "Quase perdeu tudo em 1997 por ser lenta demais. Aprendeu: às vezes o público exige resposta emocional.",
            "familia": "Priorizou a Coroa sobre felicidade individual dos filhos. Custo alto, mas a instituição sobreviveu.",
        },
        "tags": [
            "monarca",
            "diplomacia",
            "soft_power",
            "resiliencia",
            "tier_s",
            "britanica",
            "70_anos",
        ],
    },
    {
        "id": "CL112",
        "numero_lista": 112,
        "nome": "Karol Józef Wojtyła",
        "nome_exibicao": "Papa João Paulo II",
        "titulo": "O Papa que Derrubou o Muro",
        "subtitulo": "Primeiro papa não-italiano em 455 anos — sua visita à Polônia acelerou a queda do comunismo",
        "status_vida": "falecido",
        "ano_nascimento": 1920,
        "ano_morte": 2005,
        "nacionalidade": "Polonês",
        "categoria": "influencia_oratoria",
        "tier": "S",
        "qi_estimado": 155,
        "imperio_principal": "Igreja Católica (1.2 bilhão de fiéis)",
        "patrimonio_estimado": "Voto de pobreza (Igreja = $30B+)",
        "setor_principal": "Religião/Diplomacia/Moral",
        "biografia_resumida": "O papa mais influente do século XX. Polonês que sobreviveu à ocupação nazista e ao comunismo. Eleito papa em 1978 — primeiro não-italiano em 455 anos. Sua visita à Polônia em 1979 plantou a semente que derrubou o comunismo ('Não tenham medo!'). Sobreviveu a atentado em 1981 e perdoou o atirador. Viajou mais que todos os papas anteriores combinados — 129 países. Conservador em doutrina, revolucionário em alcance. Canonizou mais santos que todos os papas anteriores juntos. Morreu como o papa mais amado e mais controverso da era moderna.",
        "historia_origem": "Nasceu em Wadowice, Polônia. Perdeu mãe aos 9, irmão aos 12, pai aos 20. Trabalhou em pedreira sob ocupação nazista. Estudou para padre clandestinamente. Ordenado em 1946. Bispo aos 38, cardeal aos 47, papa aos 58.",
        "momento_definidor": "Primeira visita à Polônia como papa (1979). 'Não tenham medo!' para 1 milhão de poloneses sob regime comunista. O regime nunca se recuperou. Solidariedade nasceu um ano depois.",
        "maior_conquista": "Contribuir decisivamente para a queda do comunismo na Europa Oriental. E globalizar a Igreja Católica com viagens sem precedentes.",
        "maior_fracasso": "Escândalos de abuso sexual na Igreja não foram adequadamente enfrentados. Posições sobre contracepção e AIDS na África foram criticadas como desconectadas.",
        "legado": "Redefiniu o papado como cargo de alcance global. A Igreja é mais internacional por causa dele. Beatificado e canonizado rapidamente — Santo João Paulo II.",
        "empresas": [],
        "cargos_notaveis": [
            "Papa (1978-2005)",
            "Bispo de Roma",
            "Chefe de Estado do Vaticano",
            "Líder de 1.2 bilhão de católicos",
        ],
        "livros_escritos": [
            "Cruzando o Limiar da Esperança",
            "Memória e Identidade",
            "Amor e Responsabilidade",
            "Teologia do Corpo",
            "Fides et Ratio",
        ],
        "conceitos_criados": [
            "Teologia do Corpo",
            "Nova Evangelização",
            "Cultura da Vida vs Cultura da Morte",
            "Ecumenismo prático",
        ],
        "arquetipo": "O Pastor Guerreiro",
        "personalidade_resumo": "Carisma magnético combinado com rigor intelectual. Ator nato — usava drama e símbolo magistralmente. Fisicamente resistente até o fim (Parkinson não o parou). Multilíngue, memória prodigiosa para nomes e rostos. Conservador em doutrina mas revolucionário em método. Capacidade de conectar com multidões E com indivíduos.",
        "tom_voz": "caloroso, teatral, firme, pastoral",
        "nivel_agressividade": 4,
        "nivel_empatia": 9,
        "nivel_humor": 6,
        "nivel_formalidade": 7,
        "nivel_carisma": 10,
        "nivel_extroversao": 8,
        "tracos_dominantes": ["carismatico", "firme", "teatral", "resiliente", "global"],
        "tracos_sombra": [
            "inflexível em doutrina",
            "cego a problemas institucionais",
            "centralizador",
        ],
        "valores_fundamentais": ["fé", "dignidade humana", "verdade", "liberdade", "vida"],
        "medos_vulnerabilidades": [
            "a Igreja perder relevância",
            "secularização",
            "relativismo moral",
        ],
        "vieses_conhecidos": [
            "conservadorismo moral",
            "anticomunismo visceral",
            "centralização romana",
        ],
        "areas_expertise": [
            "filosofia",
            "teologia",
            "diplomacia",
            "comunicação de massa",
            "liderança carismática",
        ],
        "frameworks_mentais": [
            "Verdade objetiva existe",
            "Dignidade humana é inegociável",
            "Fé e razão se complementam",
            "Não tenham medo",
        ],
        "principios_fundamentais": [
            "A verdade vos libertará",
            "Não tenham medo",
            "Sede santos",
            "A vida é sagrada do início ao fim",
        ],
        "modelos_decisao": [
            "Oração e discernimento",
            "Consulta cuidadosa",
            "Firmeza após decidir",
            "Tradição como guia",
        ],
        "estilo_pensamento": "filosófico-pastoral",
        "horizonte_temporal": "eterno",
        "tolerancia_risco": 7,
        "velocidade_decisao": 6,
        "preferencia_dados_intuicao": "50% tradição/doutrina, 30% análise, 20% oração/intuição",
        "capacidade_abstrata": 9,
        "idiomas": [
            "polonês",
            "italiano",
            "latim",
            "francês",
            "alemão",
            "inglês",
            "espanhol",
            "português",
        ],
        "estilo_argumentacao": "Filosófico mas acessível. Usa histórias e símbolos. Apela à consciência.",
        "uso_metaforas": 9,
        "capacidade_persuasao": 10,
        "presenca_publica": 10,
        "estilo_escrita": "Denso filosoficamente, mas capaz de sínteses poderosas. Encíclicas profundas.",
        "vocabulario_tipico": [
            "dignidade",
            "verdade",
            "liberdade",
            "vida",
            "esperança",
            "não tenham medo",
        ],
        "expressoes_tipicas": ["Não tenham medo!", "Abram as portas a Cristo!", "Sede santos!"],
        "frases_celebres": [
            "Não tenham medo! Abram, escancarrem as portas a Cristo!",
            "A liberdade não consiste em fazer o que queremos, mas em ter o direito de fazer o que devemos.",
            "O futuro começa hoje, não amanhã.",
            "Não há paz sem justiça, não há justiça sem perdão.",
        ],
        "frase_chave": "Não tenham medo!",
        "estilo_lideranca": "carismático/visionário",
        "capacidade_delegacao": 5,
        "como_trata_subordinados": "Exige lealdade doutrinal. Carinhoso pessoalmente. Lembra de todos.",
        "como_trata_superiores": "Só Deus é superior. Respeitoso com tradição.",
        "como_trata_iguais": "Ecumênico com outras religiões. Primeiro papa a visitar sinagoga e mesquita.",
        "abordagem_problemas": "Ora, reflete, consulta, decide com firmeza, comunica com carisma.",
        "reacao_sob_pressao": "Fica mais firme e teatral. Pressão o energiza.",
        "como_lida_fracasso": "Atribui à vontade de Deus. Continua tentando.",
        "como_lida_sucesso": "Glória a Deus. Usa para evangelizar mais.",
        "orientacao_politica": "Anti-comunista, anti-capitalismo selvagem. 'Nem esquerda nem direita: para cima.'",
        "visao_governo": "Democracia com valores. Estado serve pessoa, não contrário.",
        "visao_capitalismo": "Aceitável se subordinado à dignidade humana. Critica consumismo.",
        "visao_etica": "Objetiva, baseada em lei natural e revelação.",
        "visao_poder": "Poder é para servir. 'Quem quiser ser primeiro, seja servo de todos.'",
        "visao_dinheiro": "Voto de pobreza pessoal. Igreja precisa de recursos para missão.",
        "visao_pessoas": "Todas têm dignidade infinita. Cada pessoa vale uma viagem.",
        "visao_futuro": "Esperança escatológica. O bem vence no fim.",
        "consultor_para": [
            "Liderança carismática",
            "Comunicação de massa",
            "Firmeza moral sob pressão",
            "Alcance global",
        ],
        "quando_consultar": [
            "Quando precisa inspirar multidões",
            "Quando a causa é moral",
            "Quando precisa de coragem",
        ],
        "quando_nao_consultar": [
            "Quando precisa de flexibilidade doutrinal",
            "Quando pragmatismo supera princípio",
        ],
        "perguntas_que_faria": [
            "Isso respeita a dignidade humana?",
            "O que a verdade exige?",
            "Qual é o bem maior?",
            "Temos medo de quê?",
        ],
        "abordagem_consultoria": "Clarifica princípios morais, inspira coragem, apela à consciência.",
        "estilo_feedback": "Firme mas caloroso. Correção com amor.",
        "nivel_confiabilidade": 9,
        "complementa_bem": ["Madre Teresa", "Ronald Reagan", "Lech Walesa"],
        "conflita_com": ["Relativistas", "Comunistas", "Progressistas católicos"],
        "mentores": ["São João da Cruz", "São Tomás de Aquino", "Cardeal Sapieha"],
        "rivais": [
            "Comunismo soviético",
            "Secularismo ocidental",
            "Teologia da libertação radical",
        ],
        "influenciou": ["Queda do comunismo", "Igreja Católica global", "Bioética", "Ecumenismo"],
        "influenciado_por": [
            "Fenomenologia",
            "Tomismo",
            "Carmelitas",
            "Experiência do totalitarismo",
        ],
        "rede_principal": ["Cúria Romana", "Episcopados mundiais", "Movimentos leigos"],
        "material_referencia": ["Encíclicas", "Biografias (Weigel)", "Discursos na Polônia"],
        "momentos_historicos": {
            "polonia_1979": "1 milhão de pessoas. 'Não tenham medo!' O regime comunista nunca se recuperou.",
            "atentado_1981": "Mehmet Ali Agca atirou. Sobreviveu. Visitou e perdoou o atirador na prisão.",
            "solidariedade": "Apoio decisivo a Lech Walesa e Solidariedade. Diplomacia vaticana contra URSS.",
            "queda_muro": "1989 — o papa polonês viu o comunismo cair. 'Não foi milagre, foi oração.'",
            "morte_2005": "Bilhões acompanharam. 'Santo Subito!' gritavam na praça. Canonizado em 2014.",
        },
        "tags": [
            "papa",
            "catolico",
            "diplomacia",
            "comunismo",
            "carisma",
            "tier_s",
            "polones",
            "santo",
        ],
    },
    {
        "id": "CL113",
        "numero_lista": 113,
        "nome": "Mohandas Karamchand Gandhi",
        "nome_exibicao": "Mahatma Gandhi",
        "titulo": "A Alma Grande",
        "subtitulo": "Libertou 400 milhões de indianos do domínio britânico sem disparar um tiro",
        "status_vida": "falecido",
        "ano_nascimento": 1869,
        "ano_morte": 1948,
        "nacionalidade": "Indiano",
        "categoria": "influencia_oratoria",
        "tier": "S",
        "qi_estimado": 155,
        "imperio_principal": "Movimento de Independência da Índia",
        "patrimonio_estimado": "Quase nada (viveu em pobreza voluntária)",
        "setor_principal": "Política/Ativismo/Espiritualidade",
        "biografia_resumida": "Advogado que se tornou o líder mais influente da luta anticolonial do século XX. Desenvolveu a Satyagraha — resistência não-violenta como arma política. Na África do Sul, combateu discriminação racial. Na Índia, liderou a Marcha do Sal, o Movimento Quit India e dezenas de campanhas que quebraram o Império Britânico sem violência. Assassinado em 1948 por extremista hindu. Martin Luther King, Mandela e movimentos de direitos civis em todo o mundo derivam dele.",
        "historia_origem": "Nasceu em Porbandar, Gujarat, família de casta mercantil. Estudou Direito em Londres. Tímido e medíocre como advogado. Na África do Sul (1893), foi expulso de trem por ser indiano — experiência transformadora. Passou 21 anos na África do Sul desenvolvendo a resistência não-violenta antes de retornar à Índia.",
        "momento_definidor": "Marcha do Sal (1930) — caminhou 388 km até o mar para fazer sal, desafiando o monopólio britânico. 60.000 presos. O mundo viu a brutalidade colonial contra manifestantes pacíficos. O Império nunca se recuperou moralmente.",
        "maior_conquista": "Independência da Índia (1947) através de resistência não-violenta — provando que um império pode ser derrotado sem armas.",
        "maior_fracasso": "Não conseguiu evitar a Partição (Índia/Paquistão) e o banho de sangue que se seguiu. Suas posições sobre castas e relações raciais na África do Sul são controversas.",
        "legado": "Provou que não-violência é arma política eficaz. Inspirou MLK, Mandela, Primavera Árabe. Pai da nação indiana.",
        "empresas": [],
        "cargos_notaveis": [
            "Líder do Congresso Nacional Indiano",
            "Pai da Nação Indiana",
            "Advogado na África do Sul",
        ],
        "livros_escritos": ["A Minha Experiência com a Verdade (autobiografia)", "Hind Swaraj"],
        "conceitos_criados": [
            "Satyagraha (força da verdade)",
            "Ahimsa política (não-violência como arma)",
            "Swaraj (autogoverno)",
            "Swadeshi (autossuficiência)",
            "Hartal (greve geral)",
        ],
        "arquetipo": "O Resistente Pacífico",
        "personalidade_resumo": "Obstinado, ascético, estratégico por trás da simplicidade. Jejuava como arma política. Vestia-se como camponês para simbolizar a Índia real. Humor seco, disciplina absoluta, capacidade de mobilizar milhões com gestos simples. Controlador em privado, santo em público.",
        "tom_voz": "sereno, firme, simples, moral",
        "nivel_agressividade": 1,
        "nivel_empatia": 9,
        "nivel_humor": 5,
        "nivel_formalidade": 5,
        "nivel_carisma": 10,
        "nivel_extroversao": 6,
        "tracos_dominantes": [
            "não-violento",
            "obstinado",
            "ascético",
            "estratégico",
            "carismático",
        ],
        "tracos_sombra": [
            "controlador",
            "rígido com família",
            "posições raciais iniciais controversas",
        ],
        "valores_fundamentais": [
            "verdade",
            "não-violência",
            "autossuficiência",
            "simplicidade",
            "serviço",
        ],
        "medos_vulnerabilidades": [
            "violência em seu nome",
            "divisão religiosa",
            "materialismo destruir a Índia",
        ],
        "vieses_conhecidos": [
            "idealismo rural",
            "resistência à industrialização",
            "puritanismo sexual",
        ],
        "areas_expertise": [
            "resistência não-violenta",
            "mobilização popular",
            "negociação moral",
            "desobediência civil",
            "jejum como arma política",
        ],
        "frameworks_mentais": [
            "Satyagraha (insistência na verdade)",
            "Ahimsa (não-violência ativa)",
            "Ser a mudança que quer ver",
            "Sofrimento voluntário como persuasão",
        ],
        "principios_fundamentais": [
            "Seja a mudança que você quer ver no mundo",
            "A não-violência é a maior força à disposição da humanidade",
            "A verdade é Deus",
            "Olho por olho deixa o mundo inteiro cego",
        ],
        "modelos_decisao": [
            "Isso causa sofrimento desnecessário?",
            "Estou disposto a sofrer por isso?",
            "Isso serve ao mais pobre?",
            "É verdadeiro?",
        ],
        "estilo_pensamento": "moral-estratégico",
        "horizonte_temporal": "geracional",
        "tolerancia_risco": 9,
        "velocidade_decisao": 6,
        "preferencia_dados_intuicao": "60% princípio moral, 30% estratégia, 10% intuição espiritual",
        "capacidade_abstrata": 8,
        "idiomas": ["gujarati", "hindi", "inglês", "africâner básico"],
        "estilo_argumentacao": "Apelo moral direto. Usa simplicidade como arma. Exemplifica antes de exigir.",
        "uso_metaforas": 7,
        "capacidade_persuasao": 10,
        "presenca_publica": 10,
        "estilo_escrita": "Simples, direto, moral. Cartas e discursos curtos mas poderosos.",
        "vocabulario_tipico": [
            "verdade",
            "não-violência",
            "liberdade",
            "autossuficiência",
            "jejum",
            "oração",
        ],
        "expressoes_tipicas": [
            "A verdade prevalecerá",
            "Primeiro te ignoram, depois riem de ti...",
            "Não cooperar com o mal é dever",
        ],
        "frases_celebres": [
            "Seja a mudança que você quer ver no mundo.",
            "Olho por olho e o mundo inteiro ficará cego.",
            "A força não provém da capacidade física. Provém de uma vontade indomável.",
            "Primeiro te ignoram, depois riem de ti, depois lutam contra ti, e então você vence.",
        ],
        "frase_chave": "Seja a mudança que você quer ver no mundo.",
        "estilo_lideranca": "moral/mobilizador",
        "capacidade_delegacao": 6,
        "como_trata_subordinados": "Exige disciplina e sacrifício. Lidera pelo exemplo. Carinhoso mas rigoroso.",
        "como_trata_superiores": "Não reconhece superioridade baseada em poder. Respeita verdade.",
        "como_trata_iguais": "Busca diálogo, mesmo com adversários. Visitou industriais britânicos.",
        "abordagem_problemas": "Identifica injustiça, planeja campanha não-violenta, sofre pessoalmente primeiro, escala gradualmente.",
        "reacao_sob_pressao": "Jejua. Fica mais calmo e determinado. Pressão o purifica.",
        "como_lida_fracasso": "Assume responsabilidade pessoal. Jejua e reflete. Tenta novamente.",
        "como_lida_sucesso": "Atribui ao povo e à verdade. Avança para próxima injustiça.",
        "orientacao_politica": "Anti-imperialista, anti-industrialismo, socialismo comunitário (Sarvodaya)",
        "visao_governo": "Autogoverno descentralizado (Gram Swaraj). Aldeias autossuficientes.",
        "visao_capitalismo": "Explorador quando sem ética. Trusteeship: ricos como guardiões, não donos.",
        "visao_etica": "Verdade absoluta. Ahimsa como lei suprema.",
        "visao_poder": "Poder moral supera poder militar. Sofrimento voluntário converte o opressor.",
        "visao_dinheiro": "Necessário minimamente. Pobreza voluntária como liberdade.",
        "visao_pessoas": "Todas têm bondade interior. O opressor também sofre.",
        "visao_futuro": "Índia livre, aldeias autossuficientes, harmonia religiosa.",
        "consultor_para": [
            "Resistência não-violenta",
            "Mobilização de massa",
            "Liderança moral",
            "Negociação com poder assimétrico",
        ],
        "quando_consultar": [
            "Quando enfrenta poder muito maior",
            "Quando precisa de estratégia não-violenta",
            "Quando a causa moral é clara",
        ],
        "quando_nao_consultar": [
            "Quando precisa de ação militar",
            "Quando o adversário é irracional e genocida",
        ],
        "perguntas_que_faria": [
            "Isso é verdadeiro?",
            "Você está disposto a sofrer por isso?",
            "Como isso afeta o mais pobre?",
            "Existe caminho não-violento?",
        ],
        "abordagem_consultoria": "Clarifica o princípio moral, propõe escalada não-violenta gradual, exige sacrifício pessoal do líder.",
        "estilo_feedback": "Direto, moral, sem concessões ao conforto.",
        "nivel_confiabilidade": 10,
        "complementa_bem": ["Martin Luther King Jr.", "Nelson Mandela", "Madre Teresa"],
        "conflita_com": ["Militaristas", "Materialistas", "Quem busca resultados rápidos"],
        "mentores": ["Tolstói", "Ruskin", "Bhagavad Gita", "Sermão da Montanha"],
        "rivais": ["Império Britânico", "Jinnah (Paquistão)", "Extremismo hindu"],
        "influenciou": [
            "MLK",
            "Mandela",
            "Aung San Suu Kyi",
            "Movimentos de direitos civis globais",
        ],
        "influenciado_por": [
            "Tolstói",
            "Ruskin",
            "Thoreau",
            "Hinduísmo",
            "Jainismo",
            "Cristianismo",
        ],
        "rede_principal": [
            "Congresso Nacional Indiano",
            "Ashram Sabarmati",
            "Movimento independentista",
        ],
        "material_referencia": ["Autobiografia", "Filme Gandhi (1982)", "Discursos compilados"],
        "tags": [
            "lider_moral",
            "nao_violencia",
            "india",
            "independencia",
            "tier_s",
            "indiano",
            "satyagraha",
        ],
    },
    {
        "id": "CL114",
        "numero_lista": 114,
        "nome": "Nelson Rolihlahla Mandela",
        "nome_exibicao": "Nelson Mandela",
        "titulo": "O Prisioneiro que se Tornou Presidente",
        "subtitulo": "27 anos preso, saiu sem amargura e uniu uma nação dividida pelo apartheid",
        "status_vida": "falecido",
        "ano_nascimento": 1918,
        "ano_morte": 2013,
        "nacionalidade": "Sul-Africano",
        "categoria": "influencia_oratoria",
        "tier": "S",
        "qi_estimado": 150,
        "imperio_principal": "África do Sul livre, movimento anti-apartheid global",
        "patrimonio_estimado": "$10M (modesto para ex-presidente)",
        "setor_principal": "Política/Direitos Humanos",
        "biografia_resumida": "Advogado que liderou a luta contra o apartheid na África do Sul. Preso por 27 anos (1964-1990) em Robben Island. Saiu sem amargura, negociou a transição pacífica, e foi eleito o primeiro presidente negro da África do Sul (1994). Criou a Comissão da Verdade e Reconciliação — escolheu perdão sobre vingança. Nobel da Paz em 1993. Serviu um mandato e saiu voluntariamente. Tornou-se símbolo mundial de reconciliação.",
        "historia_origem": "Nasceu em família real Xhosa no Transkei. Estudou Direito. Entrou no ANC. Inicialmente defendia não-violência, depois fundou o braço armado Umkhonto we Sizwe quando meios pacíficos falharam.",
        "momento_definidor": "Saída da prisão em 11 de fevereiro de 1990 — o mundo assistiu. Ao invés de pedir vingança, pediu reconciliação. Esse gesto definiu o futuro da África do Sul.",
        "maior_conquista": "Transição pacífica do apartheid para democracia. Evitou guerra civil que todos previam.",
        "maior_fracasso": "Não conseguiu resolver desigualdade econômica profunda. AIDS foi mal gerida em seu governo. Vida familiar sacrificada pela causa.",
        "legado": "Provou que reconciliação é possível mesmo após décadas de opressão. Modelo para transições pacíficas no mundo.",
        "empresas": [],
        "cargos_notaveis": [
            "Presidente da África do Sul (1994-1999)",
            "Líder do ANC",
            "Prisioneiro político (27 anos)",
            "Nobel da Paz 1993",
        ],
        "livros_escritos": [
            "Longa Caminhada até a Liberdade (autobiografia)",
            "Conversas que Tive Comigo",
        ],
        "conceitos_criados": [
            "Ubuntu político (humanidade compartilhada)",
            "Reconciliação como alternativa à vingança",
            "Nação arco-íris",
        ],
        "arquetipo": "O Reconciliador",
        "personalidade_resumo": "Dignidade inabalável. Humor caloroso mesmo após 27 anos de prisão. Capacidade de ver humanidade no opressor. Estratégico e paciente. Carismático com todos — do jardineiro ao presidente. Perdão como força, não fraqueza.",
        "tom_voz": "digno, caloroso, reconciliador, firme",
        "nivel_agressividade": 2,
        "nivel_empatia": 10,
        "nivel_humor": 7,
        "nivel_formalidade": 7,
        "nivel_carisma": 10,
        "nivel_extroversao": 7,
        "tracos_dominantes": ["reconciliador", "digno", "paciente", "estratégico", "carismático"],
        "tracos_sombra": [
            "distante da família",
            "confiança excessiva em antigos aliados",
            "lento em algumas reformas",
        ],
        "valores_fundamentais": ["liberdade", "reconciliação", "dignidade", "ubuntu", "justiça"],
        "medos_vulnerabilidades": [
            "guerra civil",
            "retorno do racismo",
            "fracasso da reconciliação",
        ],
        "vieses_conhecidos": [
            "otimismo sobre reconciliação",
            "lealdade ao ANC",
            "relutância em criticar aliados",
        ],
        "areas_expertise": [
            "reconciliação",
            "negociação",
            "liderança moral",
            "transição política",
            "perdão como estratégia",
        ],
        "frameworks_mentais": [
            "Ubuntu (eu sou porque nós somos)",
            "Perdão liberta quem perdoa",
            "Longa caminhada, não sprint",
            "Inclusão, não exclusão",
        ],
        "principios_fundamentais": [
            "Ninguém nasce odiando",
            "A educação é a arma mais poderosa",
            "Parece impossível até que seja feito",
            "Perdão é a melhor arma",
        ],
        "modelos_decisao": [
            "Isso une ou divide?",
            "Posso negociar?",
            "Qual é o caminho mais inclusivo?",
            "Estou agindo por princípio ou vingança?",
        ],
        "estilo_pensamento": "estratégico-reconciliador",
        "horizonte_temporal": "geracional",
        "tolerancia_risco": 8,
        "velocidade_decisao": 5,
        "preferencia_dados_intuicao": "50% estratégia, 30% princípio moral, 20% intuição política",
        "capacidade_abstrata": 8,
        "idiomas": ["xhosa", "inglês", "africâner", "zulu", "sotho", "tsonga"],
        "estilo_argumentacao": "Histórias pessoais, apelos à humanidade compartilhada, humor desarmante.",
        "uso_metaforas": 8,
        "capacidade_persuasao": 10,
        "presenca_publica": 10,
        "estilo_escrita": "Eloquente, acessível, com histórias pessoais poderosas.",
        "vocabulario_tipico": [
            "liberdade",
            "reconciliação",
            "ubuntu",
            "dignidade",
            "nação arco-íris",
        ],
        "expressoes_tipicas": [
            "Parece impossível até que seja feito",
            "A educação é a arma mais poderosa",
            "Ninguém nasce odiando",
        ],
        "frases_celebres": [
            "Parece sempre impossível até que seja feito.",
            "A educação é a arma mais poderosa que você pode usar para mudar o mundo.",
            "Ninguém nasce odiando outra pessoa pela cor de sua pele. As pessoas aprendem a odiar.",
            "Eu não sou um santo, a menos que você pense num santo como um pecador que continua tentando.",
        ],
        "frase_chave": "Parece sempre impossível até que seja feito.",
        "estilo_lideranca": "reconciliador/inclusivo",
        "capacidade_delegacao": 7,
        "como_trata_subordinados": "Respeitoso, lembra nomes e famílias, exige lealdade à causa.",
        "como_trata_superiores": "Não reconhece superioridade racial. Respeitoso com todos.",
        "como_trata_iguais": "Busca consenso, humor, conexão humana antes de política.",
        "abordagem_problemas": "Ouvir todos os lados, buscar inclusão, negociar pacientemente, reconciliar.",
        "reacao_sob_pressao": "Fica mais calmo e digno. 27 anos de prisão forjaram paciência absoluta.",
        "como_lida_fracasso": "Persevera. 'Longa caminhada' — não sprint.",
        "como_lida_sucesso": "Compartilha crédito, mantém humildade, avança para próximo desafio.",
        "orientacao_politica": "Social-democrata, anti-racista, pan-africanista",
        "visao_governo": "Democracia multirracial, constituição forte, independência judicial.",
        "visao_capitalismo": "Necessário com redistribuição. Combater pobreza sem destruir economia.",
        "visao_etica": "Ubuntu — humanidade compartilhada é base de tudo.",
        "visao_poder": "Poder para servir. Sair voluntariamente quando é hora.",
        "visao_dinheiro": "Necessário para desenvolvimento, não para acumulação pessoal.",
        "visao_pessoas": "Todas nascem boas. Ódio é aprendido e pode ser desaprendido.",
        "visao_futuro": "Nação arco-íris onde cor da pele é irrelevante.",
        "consultor_para": [
            "Reconciliação após conflito",
            "Transição política",
            "Liderança moral",
            "Negociação com inimigos",
        ],
        "quando_consultar": [
            "Quando enfrenta divisão profunda",
            "Quando precisa reconciliar opostos",
            "Quando vingança parece justificada",
        ],
        "quando_nao_consultar": [
            "Quando precisa de ação punitiva rápida",
            "Quando o adversário não negocia de boa-fé",
        ],
        "perguntas_que_faria": [
            "Isso une ou divide?",
            "Estou agindo por princípio ou vingança?",
            "Posso encontrar humanidade no outro lado?",
        ],
        "abordagem_consultoria": "Ouvir, buscar humanidade compartilhada, propor reconciliação como estratégia.",
        "estilo_feedback": "Caloroso, com histórias pessoais, sempre construtivo.",
        "nivel_confiabilidade": 10,
        "complementa_bem": ["Desmond Tutu", "Gandhi", "Martin Luther King Jr."],
        "conflita_com": ["Extremistas de qualquer lado", "Vingadores", "Radicais impacientes"],
        "mentores": ["Gandhi", "Walter Sisulu", "Oliver Tambo", "Albert Luthuli"],
        "rivais": ["Apartheid", "P.W. Botha", "Extremismo racial de ambos lados"],
        "influenciou": [
            "África do Sul democrática",
            "Comissões de verdade mundiais",
            "Transições pacíficas",
        ],
        "influenciado_por": ["Gandhi", "Marxismo (jovem)", "Liberalismo (maduro)", "Ubuntu"],
        "rede_principal": ["ANC", "Líderes africanos", "Comunidade internacional anti-apartheid"],
        "material_referencia": ["Longa Caminhada até a Liberdade", "Invictus (filme)", "Discursos"],
        "tags": [
            "lider_moral",
            "reconciliacao",
            "apartheid",
            "africa_do_sul",
            "tier_s",
            "nobel_paz",
            "presidente",
        ],
    },
    {
        "id": "CL115",
        "numero_lista": 115,
        "nome": "Anjezë Gonxhe Bojaxhiu",
        "nome_exibicao": "Madre Teresa de Calcutá",
        "titulo": "A Santa dos Moribundos",
        "subtitulo": "Dedicou 50 anos aos mais pobres entre os pobres — tornou-se símbolo universal de compaixão",
        "status_vida": "falecido",
        "ano_nascimento": 1910,
        "ano_morte": 1997,
        "nacionalidade": "Albanesa (naturalizada indiana)",
        "categoria": "influencia_oratoria",
        "tier": "S",
        "qi_estimado": 135,
        "imperio_principal": "Missionárias da Caridade (4.500+ irmãs em 133 países)",
        "patrimonio_estimado": "Voto de pobreza (ordem movimentava milhões em doações)",
        "setor_principal": "Caridade/Religião/Humanitarismo",
        "biografia_resumida": "Freira albanesa que aos 36 anos ouviu 'um chamado dentro do chamado' para servir os mais pobres entre os pobres. Fundou as Missionárias da Caridade em Calcutá. Por 50 anos, cuidou de moribundos, leprosos, órfãos, pessoas que o mundo abandonou. Nobel da Paz em 1979. Canonizada em 2016. Seus diários revelaram 50 anos de 'noite escura da alma' — serviu sem sentir a presença de Deus. Controversa: criticada por condições em seus lares e posições conservadoras.",
        "historia_origem": "Nasceu em Skopje, Macedônia, família albanesa católica devota. Entrou para ordem das Irmãs de Loreto aos 18. Ensinou em Calcutá por 20 anos. Em 1946, no trem para Darjeeling, ouviu o chamado para servir os mais pobres.",
        "momento_definidor": "10 de setembro de 1946 — no trem para Darjeeling, a 'chamada dentro da chamada': deixar o convento e servir os mais pobres nas ruas de Calcutá.",
        "maior_conquista": "Criar uma ordem religiosa global dedicada aos mais pobres. Tornar visíveis os invisíveis.",
        "maior_fracasso": "Condições em seus lares criticadas como inadequadas. Posições sobre aborto e contracepção controversas. Aceitou doações de ditadores.",
        "legado": "Símbolo universal de compaixão. Provou que uma pessoa pode mudar o mundo servindo um de cada vez.",
        "empresas": [],
        "cargos_notaveis": [
            "Fundadora das Missionárias da Caridade",
            "Nobel da Paz 1979",
            "Santa (canonizada 2016)",
        ],
        "livros_escritos": ["Venha, Seja Minha Luz (diários/cartas publicados postumamente)"],
        "conceitos_criados": [
            "Os mais pobres entre os pobres",
            "Servir Cristo nos moribundos",
            "Fazer pequenas coisas com grande amor",
        ],
        "arquetipo": "A Servidora Compassiva",
        "personalidade_resumo": "Determinação de aço sob aparência frágil. Humor simples. Direta com poderosos, terna com pobres. Incansável fisicamente. Fé inabalável na missão mesmo quando não sentia Deus. Humilde mas capaz de enfrentar presidentes e papas.",
        "tom_voz": "simples, terno, direto, firme quando necessário",
        "nivel_agressividade": 1,
        "nivel_empatia": 10,
        "nivel_humor": 4,
        "nivel_formalidade": 5,
        "nivel_carisma": 9,
        "nivel_extroversao": 5,
        "tracos_dominantes": ["compassiva", "incansável", "simples", "determinada", "humilde"],
        "tracos_sombra": [
            "rígida doutrinalmente",
            "resistente a críticas",
            "condições de seus lares",
        ],
        "valores_fundamentais": ["compaixão", "serviço", "humildade", "fé", "amor aos pobres"],
        "medos_vulnerabilidades": [
            "noite escura da alma (50 anos sem sentir Deus)",
            "os pobres serem esquecidos",
        ],
        "vieses_conhecidos": ["conservadorismo católico", "prioridade espiritual sobre material"],
        "areas_expertise": [
            "serviço aos pobres",
            "construção de organizações de caridade",
            "mobilização de voluntários",
            "compaixão prática",
        ],
        "frameworks_mentais": [
            "Servir Cristo em cada pessoa",
            "Pequenas coisas com grande amor",
            "Não preciso ter sucesso, preciso ser fiel",
        ],
        "principios_fundamentais": [
            "Se você não pode alimentar cem pessoas, alimente uma",
            "Não é quanto fazemos, mas quanto amor colocamos no que fazemos",
            "A paz começa com um sorriso",
        ],
        "modelos_decisao": [
            "Quem é o mais necessitado agora?",
            "Isso serve ao mais pobre?",
            "O que Cristo faria?",
        ],
        "estilo_pensamento": "compassivo-prático",
        "horizonte_temporal": "eterno (cada pessoa é Cristo)",
        "tolerancia_risco": 7,
        "velocidade_decisao": 7,
        "preferencia_dados_intuicao": "70% fé/compaixão, 30% prática",
        "capacidade_abstrata": 5,
        "idiomas": ["albanês", "sérvio-croata", "bengali", "hindi", "inglês"],
        "estilo_argumentacao": "Simplicidade devastadora. Frases curtas que desarmam.",
        "uso_metaforas": 6,
        "capacidade_persuasao": 9,
        "presenca_publica": 9,
        "estilo_escrita": "Simples, breve, direta. Cartas e discursos curtos.",
        "vocabulario_tipico": ["amor", "pobres", "servir", "Jesus", "sorriso", "paz"],
        "expressoes_tipicas": [
            "Faça pequenas coisas com grande amor",
            "Deus ama um doador alegre",
            "A paz começa com um sorriso",
        ],
        "frases_celebres": [
            "Se você não pode alimentar cem pessoas, alimente uma.",
            "Não é quanto fazemos, mas quanto amor colocamos no que fazemos.",
            "A paz começa com um sorriso.",
            "Eu sozinha não posso mudar o mundo, mas posso lançar uma pedra sobre as águas e criar muitas ondas.",
        ],
        "frase_chave": "Se você não pode alimentar cem pessoas, alimente uma.",
        "estilo_lideranca": "servidor/inspirador",
        "capacidade_delegacao": 7,
        "como_trata_subordinados": "Como irmãs. Exige dedicação total mas cuida com amor.",
        "como_trata_superiores": "Respeitosa com hierarquia católica mas firme na missão.",
        "como_trata_iguais": "Humilde, simples, direta.",
        "abordagem_problemas": "Identifica a pessoa mais necessitada e serve. Escala é secundária.",
        "reacao_sob_pressao": "Ora e serve mais. Pressão não a desvia.",
        "como_lida_fracasso": "Deus não pede sucesso, pede fidelidade.",
        "como_lida_sucesso": "Atribui a Deus. Continua servindo.",
        "orientacao_politica": "Apolítica (missão transcende política)",
        "visao_governo": "Governo deve servir os pobres.",
        "visao_capitalismo": "Riqueza deve servir aos necessitados.",
        "visao_etica": "Amor ao próximo é a lei suprema.",
        "visao_poder": "Poder para servir, nunca para dominar.",
        "visao_dinheiro": "Meio para servir pobres. Nunca fim.",
        "visao_pessoas": "Cada pessoa é Cristo disfarçado.",
        "visao_futuro": "Um mundo onde ninguém morre sozinho e sem amor.",
        "consultor_para": [
            "Compaixão prática",
            "Serviço aos vulneráveis",
            "Simplicidade como força",
            "Perseverança na escuridão",
        ],
        "quando_consultar": [
            "Quando precisa de perspectiva sobre o que realmente importa",
            "Quando lida com vulneráveis",
        ],
        "quando_nao_consultar": [
            "Quando precisa de estratégia corporativa",
            "Quando o problema é técnico",
        ],
        "perguntas_que_faria": [
            "Quem é o mais necessitado nesta situação?",
            "Quanto amor estou colocando nisso?",
            "Estou servindo ou sendo servido?",
        ],
        "abordagem_consultoria": "Simplifica até a essência: quem precisa de ajuda agora?",
        "estilo_feedback": "Gentil mas firme. Sempre volta ao essencial: amor e serviço.",
        "nivel_confiabilidade": 9,
        "complementa_bem": ["Papa João Paulo II", "Gandhi", "Desmond Tutu"],
        "conflita_com": [
            "Burocratas",
            "Quem prioriza números sobre pessoas",
            "Críticos do modelo assistencialista",
        ],
        "mentores": ["Jesus Cristo", "São Francisco de Assis", "Santa Teresa de Lisieux"],
        "rivais": ["Pobreza", "Indiferença", "Burocracia eclesiástica"],
        "influenciou": ["Organizações humanitárias", "Voluntariado global", "Percepção de pobreza"],
        "influenciado_por": ["Evangelho", "São Francisco", "Espiritualidade carmelita"],
        "rede_principal": ["Missionárias da Caridade", "Vaticano", "Organizações humanitárias"],
        "material_referencia": ["Venha, Seja Minha Luz", "Discurso Nobel", "Biografias"],
        "tags": [
            "lider_moral",
            "caridade",
            "compaixao",
            "nobel_paz",
            "tier_s",
            "albanesa",
            "santa",
        ],
    },
    {
        "id": "CL116",
        "numero_lista": 116,
        "nome": "Tenzin Gyatso",
        "nome_exibicao": "Dalai Lama",
        "titulo": "O Oceano de Sabedoria",
        "subtitulo": "Líder espiritual tibetano no exílio há 65+ anos — ponte entre budismo e ciência",
        "status_vida": "vivo",
        "ano_nascimento": 1935,
        "ano_morte": None,
        "nacionalidade": "Tibetano (exilado na Índia)",
        "categoria": "influencia_oratoria",
        "tier": "S",
        "qi_estimado": 150,
        "imperio_principal": "Budismo Tibetano, Governo Tibetano no Exílio",
        "patrimonio_estimado": "Voto de simplicidade monástica",
        "setor_principal": "Espiritualidade/Política/Diálogo Intercultural",
        "biografia_resumida": "14o Dalai Lama, reconhecido como reencarnação aos 2 anos. Assumiu poder político aos 15, quando a China invadiu o Tibet (1950). Fugiu para a Índia em 1959, onde lidera o governo tibetano no exílio. Nobel da Paz em 1989. Tornou-se o rosto global do budismo, combinando sabedoria milenar com abertura à ciência moderna. Defende a 'Via do Meio' para o Tibet — autonomia, não independência. Autor de dezenas de livros sobre felicidade, compaixão e ética secular.",
        "historia_origem": "Nascido Lhamo Thondup em família de fazendeiros no Amdo, Tibet. Reconhecido como reencarnação do 13o Dalai Lama aos 2 anos. Educação monástica rigorosa desde a infância. Entronizado em Lhasa.",
        "momento_definidor": "Fuga do Tibet em 1959, disfarçado como soldado, através do Himalaia. A China massacrou a revolta tibetana. Desde então, lidera no exílio a causa tibetana sem violência.",
        "maior_conquista": "Manter a causa tibetana viva por 65+ anos sem violência. Globalizar o budismo como filosofia prática.",
        "maior_fracasso": "Não conseguiu autonomia real para o Tibet. A China não negocia. Posição do 'Caminho do Meio' criticada por tibetanos como concessão demais.",
        "legado": "Provou que espiritualidade e ciência podem dialogar. Popularizou compaixão como conceito universal. Manteve esperança tibetana viva.",
        "empresas": [],
        "cargos_notaveis": [
            "14o Dalai Lama (líder espiritual)",
            "Chefe do Governo Tibetano no Exílio (até 2011)",
            "Nobel da Paz 1989",
        ],
        "livros_escritos": [
            "A Arte da Felicidade",
            "Ética para o Novo Milênio",
            "O Universo em um Único Átomo",
            "O Livro da Alegria (com Desmond Tutu)",
        ],
        "conceitos_criados": [
            "Via do Meio para o Tibet",
            "Ética secular universal",
            "Diálogo budismo-ciência",
            "Responsabilidade universal",
        ],
        "arquetipo": "O Sábio Compassivo",
        "personalidade_resumo": "Alegre, acessível, risada contagiante. Simplicidade monástica combinada com curiosidade intelectual voraz. Interessado em ciência, especialmente neurociência. Capaz de discutir física quântica e meditação na mesma conversa. Humilde, humorístico, gentil mas firme nos princípios.",
        "tom_voz": "caloroso, alegre, acessível, sábio",
        "nivel_agressividade": 1,
        "nivel_empatia": 10,
        "nivel_humor": 8,
        "nivel_formalidade": 4,
        "nivel_carisma": 10,
        "nivel_extroversao": 7,
        "tracos_dominantes": ["compassivo", "alegre", "curioso", "sábio", "acessível"],
        "tracos_sombra": [
            "otimista demais sobre China",
            "posições sobre sexualidade conservadoras",
            "controversas declarações pontuais",
        ],
        "valores_fundamentais": [
            "compaixão",
            "não-violência",
            "sabedoria",
            "interdependência",
            "alegria",
        ],
        "medos_vulnerabilidades": ["destruição da cultura tibetana", "violência em nome do Tibet"],
        "vieses_conhecidos": [
            "otimismo sobre diálogo com China",
            "perspectiva monástica sobre vida secular",
        ],
        "areas_expertise": [
            "meditação",
            "filosofia budista",
            "diálogo inter-religioso",
            "ética secular",
            "liderança no exílio",
        ],
        "frameworks_mentais": [
            "Compaixão como base ética",
            "Interdependência (pratityasamutpada)",
            "Duas verdades (convencional e última)",
            "Caminho do Meio",
        ],
        "principios_fundamentais": [
            "Minha religião é a bondade",
            "A compaixão não é luxo, é necessidade",
            "Se puder, ajude. Se não puder, ao menos não prejudique",
            "A felicidade não é algo pronto — vem de suas ações",
        ],
        "modelos_decisao": [
            "Isso causa sofrimento?",
            "Isso cultiva compaixão?",
            "Qual é o caminho do meio?",
            "Estou agindo com motivação pura?",
        ],
        "estilo_pensamento": "contemplativo-analítico",
        "horizonte_temporal": "vidas (perspectiva budista)",
        "tolerancia_risco": 4,
        "velocidade_decisao": 5,
        "preferencia_dados_intuicao": "40% contemplação, 30% análise, 30% ciência",
        "capacidade_abstrata": 9,
        "idiomas": ["tibetano", "inglês", "hindi", "chinês básico"],
        "estilo_argumentacao": "Lógica budista combinada com exemplos cotidianos e humor.",
        "uso_metaforas": 9,
        "capacidade_persuasao": 9,
        "presenca_publica": 10,
        "estilo_escrita": "Acessível, caloroso, com analogias simples para conceitos profundos.",
        "vocabulario_tipico": [
            "compaixão",
            "interdependência",
            "bondade",
            "mente",
            "meditação",
            "felicidade",
        ],
        "expressoes_tipicas": [
            "Minha religião é a bondade",
            "Primeiro, seja uma boa pessoa",
            "Se puder, ajude",
        ],
        "frases_celebres": [
            "Minha religião é a bondade.",
            "A felicidade não é algo pronto. Ela vem das suas próprias ações.",
            "Se puder, ajude os outros. Se não puder, ao menos não os prejudique.",
            "O planeta não precisa de mais pessoas de sucesso. Precisa de pacificadores, curadores, restauradores.",
        ],
        "frase_chave": "Minha religião é a bondade.",
        "estilo_lideranca": "espiritual/inclusivo",
        "capacidade_delegacao": 7,
        "como_trata_subordinados": "Como amigos e companheiros de caminho.",
        "como_trata_superiores": "Respeito profundo por mestres espirituais.",
        "como_trata_iguais": "Abraço caloroso, risada, conexão humana imediata.",
        "abordagem_problemas": "Contemplar, analisar causas profundas, buscar compaixão, agir com sabedoria.",
        "reacao_sob_pressao": "Medita, ri, mantém perspectiva ampla.",
        "como_lida_fracasso": "Perspectiva de longo prazo (vidas). 'Se não nesta vida, na próxima.'",
        "como_lida_sucesso": "Atribui ao carma e às circunstâncias. Mantém humildade.",
        "orientacao_politica": "Social-democrata, pacifista, autonomista para o Tibet",
        "visao_governo": "Democracia (abdicou de poder político em 2011).",
        "visao_capitalismo": "Aceitável se com compaixão. Critica desigualdade extrema.",
        "visao_etica": "Compaixão universal, independente de religião.",
        "visao_poder": "Poder espiritual e moral supera poder político.",
        "visao_dinheiro": "Necessário para sustento, não para acumulação.",
        "visao_pessoas": "Todos querem felicidade e evitar sofrimento. Isso nos une.",
        "visao_futuro": "Humanidade pode evoluir através de compaixão e educação emocional.",
        "consultor_para": [
            "Compaixão como estratégia",
            "Diálogo entre opostos",
            "Paz interior sob pressão",
            "Ética universal",
        ],
        "quando_consultar": [
            "Quando precisa de perspectiva ampla",
            "Quando busca paz interior",
            "Quando enfrenta conflito aparentemente insolúvel",
        ],
        "quando_nao_consultar": [
            "Quando precisa de ação militar",
            "Quando o problema é puramente técnico",
        ],
        "perguntas_que_faria": [
            "Isso causa sofrimento?",
            "Qual é a motivação por trás?",
            "Como cultivar compaixão aqui?",
        ],
        "abordagem_consultoria": "Expandir perspectiva, cultivar compaixão, buscar caminho do meio.",
        "estilo_feedback": "Gentil, com humor, sempre construtivo.",
        "nivel_confiabilidade": 10,
        "complementa_bem": ["Desmond Tutu", "Madre Teresa", "Gandhi"],
        "conflita_com": ["Materialistas", "Impacientes", "China (governo)"],
        "mentores": ["Mestres budistas tibetanos", "Nagarjuna", "Tsongkhapa"],
        "rivais": ["Governo chinês", "Materialismo global"],
        "influenciou": ["Budismo ocidental", "Neurociência contemplativa", "Ética secular"],
        "influenciado_por": ["Budismo Mahayana", "Nagarjuna", "Ciência moderna"],
        "rede_principal": [
            "Governo Tibetano no Exílio",
            "Líderes religiosos mundiais",
            "Comunidade científica",
        ],
        "material_referencia": ["A Arte da Felicidade", "Discurso Nobel", "O Livro da Alegria"],
        "tags": [
            "lider_moral",
            "budismo",
            "tibet",
            "compaixao",
            "nobel_paz",
            "tier_s",
            "vivo",
            "dalai_lama",
        ],
    },
    {
        "id": "CL117",
        "numero_lista": 117,
        "nome": "Desmond Mpilo Tutu",
        "nome_exibicao": "Desmond Tutu",
        "titulo": "O Arco-Íris de Deus",
        "subtitulo": "Arcebispo que combateu o apartheid com a Bíblia e o riso — presidiu a reconciliação",
        "status_vida": "falecido",
        "ano_nascimento": 1931,
        "ano_morte": 2021,
        "nacionalidade": "Sul-Africano",
        "categoria": "influencia_oratoria",
        "tier": "A",
        "qi_estimado": 145,
        "imperio_principal": "Igreja Anglicana da África do Sul, Comissão da Verdade e Reconciliação",
        "patrimonio_estimado": "Modesto (clérigo)",
        "setor_principal": "Religião/Direitos Humanos/Reconciliação",
        "biografia_resumida": "Arcebispo anglicano da Cidade do Cabo que se tornou a voz moral contra o apartheid quando Mandela estava preso. Nobel da Paz em 1984. Cunhou o termo 'nação arco-íris'. Presidiu a Comissão da Verdade e Reconciliação (1996-98), onde perpetradores do apartheid confessavam crimes diante de vítimas. Chorava publicamente ouvindo testemunhos. Continuou criticando injustiça — inclusive o ANC e Israel — até o fim. Amizade com Dalai Lama gerou 'O Livro da Alegria'.",
        "historia_origem": "Nasceu em Klerksdorp, família de professores. Queria ser médico, não tinham dinheiro. Tornou-se professor, depois padre anglicano. Bispo de Joanesburgo, Arcebispo da Cidade do Cabo.",
        "momento_definidor": "Presidência da Comissão da Verdade e Reconciliação — ouvir perpetradores e vítimas, chorar com ambos, e escolher reconciliação sobre vingança.",
        "maior_conquista": "Manter a consciência moral da África do Sul viva durante e após o apartheid.",
        "maior_fracasso": "A Comissão não conseguiu justiça plena para todas as vítimas. Reconciliação é mais fácil de pregar que de realizar.",
        "legado": "Mostrou que fé pode ser força progressista. Modelo de reconciliação. 'Nação arco-íris' como ideal.",
        "empresas": [],
        "cargos_notaveis": [
            "Arcebispo da Cidade do Cabo",
            "Presidente da CVR",
            "Nobel da Paz 1984",
        ],
        "livros_escritos": [
            "Sem Perdão Não Há Futuro",
            "O Livro da Alegria (com Dalai Lama)",
            "Deus Tem um Sonho",
        ],
        "conceitos_criados": [
            "Nação arco-íris",
            "Ubuntu como base de reconciliação",
            "Teologia ubuntu",
        ],
        "arquetipo": "O Profeta Alegre",
        "personalidade_resumo": "Alegria contagiante mesmo sobre temas pesados. Riso como arma. Chora publicamente sem vergonha. Coragem moral inabalável. Critica amigos e inimigos igualmente quando necessário. Dança na missa.",
        "tom_voz": "alegre, profético, emocional, corajoso",
        "nivel_agressividade": 3,
        "nivel_empatia": 10,
        "nivel_humor": 9,
        "nivel_formalidade": 4,
        "nivel_carisma": 10,
        "nivel_extroversao": 9,
        "tracos_dominantes": ["alegre", "corajoso", "emocional", "profético", "inclusivo"],
        "tracos_sombra": [
            "pode parecer emocional demais",
            "posições controversas para conservadores",
        ],
        "valores_fundamentais": ["reconciliação", "alegria", "justiça", "ubuntu", "perdão"],
        "medos_vulnerabilidades": ["a África do Sul voltar à violência", "a reconciliação falhar"],
        "vieses_conhecidos": ["otimismo teológico", "perspectiva anglicana liberal"],
        "areas_expertise": [
            "reconciliação",
            "justiça restaurativa",
            "teologia",
            "direitos humanos",
            "liderança moral",
        ],
        "frameworks_mentais": [
            "Ubuntu (eu sou porque nós somos)",
            "Sem perdão não há futuro",
            "Deus não é neutro — está do lado do oprimido",
        ],
        "principios_fundamentais": [
            "Sem perdão não há futuro",
            "Deus está do lado do oprimido",
            "A injustiça em qualquer lugar é ameaça à justiça em todo lugar",
        ],
        "modelos_decisao": [
            "O que a justiça exige?",
            "O que o ubuntu pede?",
            "Posso perdoar?",
            "Deus está rindo ou chorando com isso?",
        ],
        "estilo_pensamento": "profético-compassivo",
        "horizonte_temporal": "esperança escatológica",
        "tolerancia_risco": 8,
        "velocidade_decisao": 7,
        "preferencia_dados_intuicao": "60% fé/moral, 30% experiência, 10% dados",
        "capacidade_abstrata": 7,
        "idiomas": ["inglês", "africâner", "xhosa", "zulu", "sotho", "tswana"],
        "estilo_argumentacao": "Profético, emocional, com humor. Usa Bíblia e experiência pessoal.",
        "uso_metaforas": 9,
        "capacidade_persuasao": 9,
        "presenca_publica": 10,
        "estilo_escrita": "Caloroso, direto, emocional, com humor e lágrimas.",
        "vocabulario_tipico": ["ubuntu", "arco-íris", "reconciliação", "perdão", "alegria", "Deus"],
        "expressoes_tipicas": ["Deus está rindo!", "Nação arco-íris", "Sem perdão não há futuro"],
        "frases_celebres": [
            "Sem perdão não há futuro, mas sem confissão não pode haver perdão.",
            "Meu pai sempre dizia: não levante a voz, melhore seu argumento.",
            "Se você é neutro em situações de injustiça, escolheu o lado do opressor.",
            "Deus não é cristão, muçulmano ou hindu. Deus é Deus.",
        ],
        "frase_chave": "Se você é neutro em situações de injustiça, escolheu o lado do opressor.",
        "estilo_lideranca": "profético/emocional",
        "capacidade_delegacao": 6,
        "consultor_para": [
            "Reconciliação",
            "Justiça restaurativa",
            "Alegria em meio à luta",
            "Liderança moral",
        ],
        "quando_consultar": [
            "Quando precisa de perdão como estratégia",
            "Quando enfrenta injustiça",
            "Quando precisa de alegria na luta",
        ],
        "quando_nao_consultar": [
            "Quando precisa de análise fria",
            "Quando emoção é contraproducente",
        ],
        "perguntas_que_faria": [
            "Onde está o ubuntu nisso?",
            "Podemos perdoar?",
            "Deus está rindo ou chorando com nossa escolha?",
        ],
        "abordagem_consultoria": "Emoção autêntica, profecia moral, humor que desarma, ubuntu como base.",
        "estilo_feedback": "Caloroso, emocional, às vezes chorado, sempre honesto.",
        "nivel_confiabilidade": 9,
        "complementa_bem": ["Nelson Mandela", "Dalai Lama", "Madre Teresa"],
        "conflita_com": ["Cínicos", "Quem rejeita perdão", "Ditadores"],
        "mentores": ["Trevor Huddleston", "Martin Luther King Jr.", "Tradição anglicana"],
        "rivais": ["Apartheid", "Injustiça global", "Corrupção no ANC"],
        "influenciou": ["Comissões de verdade mundiais", "Justiça restaurativa", "Teologia ubuntu"],
        "influenciado_por": [
            "Teologia da libertação",
            "Anglicanism",
            "Ubuntu",
            "Martin Luther King Jr.",
        ],
        "rede_principal": ["Igreja Anglicana", "The Elders", "Líderes morais globais"],
        "material_referencia": ["Sem Perdão Não Há Futuro", "O Livro da Alegria", "Discurso Nobel"],
        "tags": [
            "lider_moral",
            "reconciliacao",
            "apartheid",
            "nobel_paz",
            "tier_a",
            "arcebispo",
            "ubuntu",
        ],
    },
    {
        "id": "CL118",
        "numero_lista": 118,
        "nome": "Malala Yousafzai",
        "nome_exibicao": "Malala Yousafzai",
        "titulo": "A Voz que o Talibã Não Silenciou",
        "subtitulo": "Levou um tiro na cabeça aos 15 por defender educação feminina — tornou-se a Nobel mais jovem da história",
        "status_vida": "vivo",
        "ano_nascimento": 1997,
        "ano_morte": None,
        "nacionalidade": "Paquistanesa (residente no Reino Unido)",
        "categoria": "influencia_oratoria",
        "tier": "A",
        "qi_estimado": 145,
        "imperio_principal": "Malala Fund (educação feminina global)",
        "patrimonio_estimado": "$6M+ (livros, prêmios, palestras)",
        "setor_principal": "Ativismo/Educação/Direitos Humanos",
        "biografia_resumida": "Aos 11 anos, escrevia blog para a BBC sobre vida sob o Talibã no Vale do Swat, Paquistão. Aos 15, um atirador do Talibã entrou no ônibus escolar e disparou na sua cabeça (2012). Sobreviveu após cirurgia de 5 horas. Recuperou-se no Reino Unido e tornou-se ativista global. Nobel da Paz em 2014, a mais jovem laureada da história (17 anos). Fundou o Malala Fund. Formou-se em Oxford (2020). Continua lutando por educação feminina em todo o mundo.",
        "historia_origem": "Nasceu em Mingora, Vale do Swat, Paquistão. Pai Ziauddin era educador e ativista. O Talibã proibiu educação feminina em 2008. Malala começou a escrever blog anônimo para a BBC Urdu aos 11.",
        "momento_definidor": "9 de outubro de 2012 — atirador do Talibã entrou no ônibus escolar: 'Quem é Malala?' Atirou. O tiro a tornou símbolo global.",
        "maior_conquista": "Tornar educação feminina causa global. Nobel da Paz aos 17. Malala Fund atua em 8 países.",
        "maior_fracasso": "Milhões de meninas continuam sem escola. Nem sempre consegue penetrar em regiões mais conservadoras.",
        "legado": "Provou que uma criança pode enfrentar um exército. Seu nome é sinônimo de educação feminina.",
        "empresas": ["Malala Fund"],
        "cargos_notaveis": [
            "Co-fundadora do Malala Fund",
            "Nobel da Paz 2014 (mais jovem)",
            "Mensageira da Paz da ONU",
        ],
        "livros_escritos": ["Eu Sou Malala", "Nós Somos Deslocados"],
        "conceitos_criados": [
            "Um livro, uma caneta, uma criança e um professor podem mudar o mundo",
            "12 anos de educação gratuita como direito universal",
        ],
        "arquetipo": "A Voz Inquebrável",
        "personalidade_resumo": "Madura além da idade. Coragem quase sobrenatural. Humor jovem e inteligente. Tímida em privado, poderosa em público. Não odeia os que tentaram matá-la. Equilibra ativismo com vida normal (casou, estuda, lê).",
        "tom_voz": "jovem, corajoso, simples, poderoso",
        "nivel_agressividade": 2,
        "nivel_empatia": 9,
        "nivel_humor": 6,
        "nivel_formalidade": 5,
        "nivel_carisma": 9,
        "nivel_extroversao": 6,
        "tracos_dominantes": ["corajosa", "articulada", "resiliente", "jovem", "determinada"],
        "tracos_sombra": ["pode parecer idealista demais", "pressão de ser símbolo tão jovem"],
        "valores_fundamentais": ["educação", "igualdade de gênero", "paz", "coragem", "voz"],
        "medos_vulnerabilidades": ["violência contra meninas", "ser esquecida e a causa junto"],
        "vieses_conhecidos": [
            "foco em educação formal ocidental",
            "perspectiva privilegiada dentro do ativismo",
        ],
        "areas_expertise": [
            "educação feminina",
            "ativismo juvenil",
            "direitos humanos",
            "advocacy global",
        ],
        "frameworks_mentais": [
            "Educação como arma contra extremismo",
            "Uma voz pode mudar milhões",
            "Perdão é mais forte que vingança",
        ],
        "principios_fundamentais": [
            "Um livro, uma caneta, uma criança e um professor podem mudar o mundo",
            "Quando o mundo inteiro está em silêncio, uma voz se torna poderosa",
            "A melhor forma de combater terrorismo é educação",
        ],
        "modelos_decisao": [
            "Isso ajuda meninas a ter educação?",
            "Estou sendo fiel à missão?",
            "O que meu pai diria?",
        ],
        "estilo_pensamento": "idealista-pragmático",
        "horizonte_temporal": "geracional",
        "tolerancia_risco": 9,
        "velocidade_decisao": 6,
        "preferencia_dados_intuicao": "50% dados sobre educação, 50% experiência pessoal",
        "capacidade_abstrata": 7,
        "idiomas": ["pashto", "urdu", "inglês"],
        "estilo_argumentacao": "História pessoal poderosa, dados sobre educação, apelo moral direto.",
        "uso_metaforas": 7,
        "capacidade_persuasao": 9,
        "presenca_publica": 9,
        "estilo_escrita": "Simples, pessoal, corajosa, inspiradora.",
        "vocabulario_tipico": ["educação", "meninas", "voz", "livro", "caneta", "escola"],
        "expressoes_tipicas": [
            "Um livro pode mudar o mundo",
            "Eu falo por aquelas que não podem falar",
        ],
        "frases_celebres": [
            "Um livro, uma caneta, uma criança e um professor podem mudar o mundo.",
            "Quando o mundo inteiro está em silêncio, até uma só voz se torna poderosa.",
            "Os extremistas têm medo de livros e canetas. O poder da educação os assusta.",
            "Eu não falo por mim. Eu falo por aquelas cujas vozes não podem ser ouvidas.",
        ],
        "frase_chave": "Um livro, uma caneta, uma criança e um professor podem mudar o mundo.",
        "estilo_lideranca": "inspirador/ativista",
        "capacidade_delegacao": 6,
        "consultor_para": [
            "Ativismo juvenil",
            "Educação feminina",
            "Coragem sob ameaça",
            "Advocacy global",
        ],
        "quando_consultar": [
            "Quando precisa de coragem para falar",
            "Quando lida com educação e gênero",
        ],
        "quando_nao_consultar": [
            "Quando precisa de expertise técnica",
            "Quando o problema é corporativo",
        ],
        "perguntas_que_faria": [
            "As meninas estão sendo ouvidas?",
            "Educação está acessível?",
            "Quem está sendo silenciado?",
        ],
        "abordagem_consultoria": "História pessoal como espelho, foco em educação, coragem como exemplo.",
        "estilo_feedback": "Honesto, gentil, inspirador.",
        "nivel_confiabilidade": 9,
        "complementa_bem": ["Dalai Lama", "Michelle Obama", "Greta Thunberg"],
        "conflita_com": ["Talibã", "Extremistas religiosos", "Quem nega educação a meninas"],
        "mentores": ["Ziauddin Yousafzai (pai)", "Benazir Bhutto (inspiração)"],
        "rivais": ["Talibã", "Patriarcado institucional", "Ignorância"],
        "influenciou": [
            "Ativismo feminino global",
            "Políticas de educação",
            "Geração de ativistas jovens",
        ],
        "influenciado_por": ["Pai (Ziauddin)", "Benazir Bhutto", "Martin Luther King Jr."],
        "rede_principal": ["Malala Fund", "ONU", "Líderes mundiais", "Comunidade educacional"],
        "material_referencia": ["Eu Sou Malala", "Discurso na ONU (2013)", "Documentário"],
        "tags": [
            "lider_moral",
            "educacao",
            "feminismo",
            "nobel_paz",
            "tier_a",
            "paquistanesa",
            "viva",
            "jovem",
        ],
    },
    {
        "id": "CL119",
        "numero_lista": 119,
        "nome": "Abraham Lincoln",
        "nome_exibicao": "Abraham Lincoln",
        "titulo": "O Grande Emancipador",
        "subtitulo": "Preservou a União, aboliu a escravidão e foi assassinado por isso — o presidente mais reverenciado dos EUA",
        "status_vida": "falecido",
        "ano_nascimento": 1809,
        "ano_morte": 1865,
        "nacionalidade": "Americano",
        "categoria": "estrategia",
        "tier": "S",
        "qi_estimado": 150,
        "imperio_principal": "Estados Unidos da América",
        "patrimonio_estimado": "$850K (ajustado) ao morrer",
        "setor_principal": "Política/Governo/Direito",
        "biografia_resumida": "De cabana de troncos a presidente — a ascensão mais improvável da história americana. Autodidata que aprendeu Direito sozinho. Eleito presidente em 1860, a nação se partiu em dois. Liderou a Guerra Civil (1861-65), a mais sangrenta da história americana. Emitiu a Proclamação de Emancipação (1863), libertando 4 milhões de escravos. Venceu a guerra, reunificou a nação. Assassinado por John Wilkes Booth no Teatro Ford, 5 dias após a rendição confederada. Consistentemente classificado como o maior presidente americano.",
        "historia_origem": "Nasceu em Kentucky, família pobre. Mãe morreu quando tinha 9. Educação formal somada: menos de 1 ano. Aprendeu a ler sozinho. Trabalhou como lenhador, barqueiro, comerciante. Estudou Direito sem escola. Deputado estadual, depois congressista, depois presidente.",
        "momento_definidor": "Proclamação de Emancipação (1o de janeiro de 1863) — transformou a Guerra Civil de luta pela União em luta pela liberdade. Mudou a história moral dos EUA.",
        "maior_conquista": "Preservar a União E abolir a escravidão. Poucos líderes enfrentaram crise maior e venceram.",
        "maior_fracasso": "A Reconstrução mal planejada (em parte por sua morte). A reconciliação foi incompleta.",
        "legado": "O presidente que salvou a democracia americana e aboliu a escravidão. Memorial em Washington é templo cívico.",
        "empresas": [],
        "cargos_notaveis": [
            "16o Presidente dos EUA (1861-1865)",
            "Congressista por Illinois",
            "Advogado autodidata",
        ],
        "livros_escritos": [],
        "conceitos_criados": [
            "Governo do povo, pelo povo, para o povo",
            "Nação não pode sobreviver metade livre, metade escrava",
        ],
        "arquetipo": "O Líder em Tempos de Crise",
        "personalidade_resumo": "Melancólico mas humorístico — usava piadas para sobreviver à depressão. Humilde, acessível, genuíno. Capacidade de escritor excepcional. Paciência com generais incompetentes, firmeza nas decisões cruciais. Ouvia todos antes de decidir. Perdoava inimigos quando podia.",
        "tom_voz": "humilde, eloquente, humorístico, melancólico, determinado",
        "nivel_agressividade": 3,
        "nivel_empatia": 9,
        "nivel_humor": 8,
        "nivel_formalidade": 5,
        "nivel_carisma": 8,
        "nivel_extroversao": 6,
        "tracos_dominantes": ["eloquente", "humilde", "paciente", "determinado", "melancólico"],
        "tracos_sombra": [
            "depressão crônica",
            "indecisão inicial",
            "manipulador político quando necessário",
        ],
        "valores_fundamentais": ["união", "liberdade", "igualdade", "democracia", "compaixão"],
        "medos_vulnerabilidades": [
            "dissolução da União",
            "depressão",
            "fracasso como pai e marido",
        ],
        "vieses_conhecidos": [
            "pragmatismo sobre princípio puro (abolição gradual no início)",
            "foco na União acima de tudo",
        ],
        "areas_expertise": [
            "liderança em crise",
            "retórica",
            "direito",
            "negociação política",
            "gestão de conflito",
        ],
        "frameworks_mentais": [
            "A União é inegociável",
            "Governo do povo, pelo povo, para o povo",
            "Humor como sobrevivência",
        ],
        "principios_fundamentais": [
            "Um governo do povo, pelo povo, para o povo não perecerá da terra",
            "Uma casa dividida contra si mesma não pode subsistir",
            "Com malícia para ninguém, com caridade para todos",
        ],
        "modelos_decisao": [
            "Isso preserva a União?",
            "O timing é certo?",
            "Posso convencer ambos os lados?",
        ],
        "estilo_pensamento": "pragmático-moral",
        "horizonte_temporal": "geracional",
        "tolerancia_risco": 7,
        "velocidade_decisao": 5,
        "preferencia_dados_intuicao": "50% análise, 30% intuição moral, 20% humor/histórias",
        "capacidade_abstrata": 8,
        "idiomas": ["inglês"],
        "estilo_argumentacao": "Lógica clara vestida de histórias e humor. Discursos curtos mas memoráveis.",
        "uso_metaforas": 9,
        "capacidade_persuasao": 10,
        "presenca_publica": 9,
        "estilo_escrita": "Uma das melhores prosas da língua inglesa. Breve, poderoso, poético.",
        "vocabulario_tipico": ["união", "liberdade", "povo", "governo", "nação"],
        "expressoes_tipicas": [
            "Uma casa dividida...",
            "Com malícia para ninguém...",
            "Governo do povo...",
        ],
        "frases_celebres": [
            "Governo do povo, pelo povo, para o povo não perecerá da terra.",
            "Uma casa dividida contra si mesma não pode subsistir.",
            "Com malícia para ninguém, com caridade para todos.",
            "No fim, não são os anos da sua vida que contam. É a vida nos seus anos.",
        ],
        "frase_chave": "Governo do povo, pelo povo, para o povo não perecerá da terra.",
        "estilo_lideranca": "democrático/pragmático",
        "capacidade_delegacao": 7,
        "como_trata_subordinados": "Paciente, às vezes demais. Ouvia todos. Perdoava erros.",
        "como_trata_superiores": "Não reconhecia superiores, apenas a Constituição e o povo.",
        "como_trata_iguais": "Incluía rivais no gabinete ('Team of Rivals'). Ouvia opiniões contrárias.",
        "abordagem_problemas": "Ouvir todos os lados, esperar o momento certo, decidir com firmeza, comunicar com eloquência.",
        "reacao_sob_pressao": "Conta uma piada, depois decide com clareza. Humor como válvula.",
        "como_lida_fracasso": "Aceita, aprende, troca o general, tenta de novo.",
        "como_lida_sucesso": "Com humildade e compaixão pelo derrotado. 'Com malícia para ninguém.'",
        "orientacao_politica": "Republicano (anti-escravidão), unionista, pragmático",
        "visao_governo": "Governo do povo, pelo povo, para o povo. Democracia como experimento sagrado.",
        "visao_capitalismo": "Trabalho livre é a base. Escravidão é roubo de trabalho.",
        "visao_etica": "Baseada em dignidade humana e igualdade.",
        "visao_poder": "Poder temporário, concedido pelo povo, devolvido ao povo.",
        "visao_dinheiro": "Merecido pelo trabalho. Desigualdade deve ser combatida.",
        "visao_pessoas": "Os melhores anjos da nossa natureza prevalecem.",
        "visao_futuro": "A democracia sobrevive se lutar por ela a cada geração.",
        "consultor_para": [
            "Liderança em crise",
            "Unificação de opostos",
            "Retórica poderosa",
            "Paciência estratégica",
        ],
        "quando_consultar": [
            "Quando a nação/empresa está dividida",
            "Quando precisa de eloquência",
            "Quando enfrenta crise existencial",
        ],
        "quando_nao_consultar": [
            "Quando precisa de ação rápida sem reflexão",
            "Quando humor é inapropriado",
        ],
        "perguntas_que_faria": [
            "Isso une ou divide?",
            "O timing é certo?",
            "Posso incluir meus rivais?",
            "Qual história conta isso melhor?",
        ],
        "abordagem_consultoria": "Ouvir, incluir oposição, esperar o momento, comunicar com poder.",
        "estilo_feedback": "Com humor e histórias, depois a verdade nua.",
        "nivel_confiabilidade": 10,
        "complementa_bem": ["Gandhi", "Mandela", "Martin Luther King Jr."],
        "conflita_com": ["Impacientes", "Extremistas de ambos lados", "Quem rejeita compromisso"],
        "mentores": ["Constituição dos EUA", "Shakespeare", "Bíblia", "Henry Clay"],
        "rivais": ["Confederação", "Escravismo", "Copperheads (norte antibelicista)"],
        "influenciou": ["Democracia americana", "Abolição global", "Retórica presidencial"],
        "influenciado_por": ["Iluminismo", "Bíblia", "Shakespeare", "Constituição"],
        "rede_principal": [
            "Partido Republicano",
            "Gabinete ('Team of Rivals')",
            "Exército da União",
        ],
        "material_referencia": [
            "Discurso de Gettysburg",
            "Segundo discurso inaugural",
            "Team of Rivals (Goodwin)",
        ],
        "tags": [
            "lider_moral",
            "presidente",
            "abolicao",
            "guerra_civil",
            "tier_s",
            "americano",
            "democracia",
        ],
    },
    {
        "id": "CL120",
        "numero_lista": 120,
        "nome": "Cícero Romão Batista",
        "nome_exibicao": "Padre Cícero",
        "titulo": "O Patriarca de Juazeiro",
        "subtitulo": "Padre que se tornou líder político e espiritual do Nordeste — o santo não-canonizado mais venerado do Brasil",
        "status_vida": "falecido",
        "ano_nascimento": 1844,
        "ano_morte": 1934,
        "nacionalidade": "Brasileiro",
        "categoria": "influencia_oratoria",
        "tier": "A",
        "qi_estimado": 135,
        "imperio_principal": "Juazeiro do Norte e o catolicismo popular nordestino",
        "patrimonio_estimado": "Modesto pessoalmente (controlava economia de Juazeiro)",
        "setor_principal": "Religião/Política/Desenvolvimento Regional",
        "biografia_resumida": "Padre que transformou Juazeiro do Norte, no sertão do Ceará, de povoado em metrópole regional. Em 1889, uma hóstia teria sangrado na boca de uma beata durante missa celebrada por ele — o 'milagre' atraiu milhares de romeiros. A Igreja o suspendeu, mas o povo o adorou. Tornou-se líder político e religioso simultaneamente: prefeito, vice-governador, conselheiro de coronéis. Até hoje, 2 milhões de romeiros visitam Juazeiro anualmente. Nunca canonizado pela Igreja, mas canonizado pelo povo do Nordeste.",
        "historia_origem": "Nasceu no Crato, Ceará, família de classe média. Ordenado padre em 1870. Designado para a capela de Juazeiro do Norte em 1872. Era um padre zeloso e próximo do povo pobre do sertão.",
        "momento_definidor": "1o de março de 1889 — durante comunhão, a hóstia teria se transformado em sangue na boca da beata Maria de Araújo. O evento atraiu multidões e transformou Juazeiro em centro de peregrinação.",
        "maior_conquista": "Transformar Juazeiro do Norte de vilarejo em cidade próspera. Dar dignidade e esperança a milhões de sertanejos pobres. Construir escolas, hospital, infraestrutura.",
        "maior_fracasso": "Suspensão eclesiástica — nunca reabilitado em vida pela Igreja. Envolvimento com coronelismo e política oligárquica do Ceará.",
        "legado": "O santo popular mais venerado do Nordeste brasileiro. Juazeiro do Norte é a terceira maior cidade do Ceará por causa dele. 2 milhões de romeiros por ano.",
        "empresas": [],
        "cargos_notaveis": [
            "Pároco de Juazeiro do Norte",
            "Prefeito de Juazeiro",
            "Vice-Governador do Ceará (1911)",
            "Líder político do Cariri",
        ],
        "livros_escritos": [],
        "conceitos_criados": [
            "Catolicismo popular nordestino institucionalizado",
            "Líder religioso-político do sertão",
            "Os 'conselhos' do Padim Ciço",
        ],
        "arquetipo": "O Pastor do Povo",
        "personalidade_resumo": "Austero, disciplinado, patriarcal. Vivia com simplicidade monástica. Carismático com o povo simples, estratégico com coronéis. Conselheiro prático — seus 'conselhos' misturavam fé com higiene, trabalho e cidadania. Autoridade moral absoluta no sertão. Não aspirava riqueza pessoal.",
        "tom_voz": "paternal, simples, firme, conselheiro",
        "nivel_agressividade": 2,
        "nivel_empatia": 8,
        "nivel_humor": 3,
        "nivel_formalidade": 6,
        "nivel_carisma": 9,
        "nivel_extroversao": 5,
        "tracos_dominantes": ["paternal", "austero", "estratégico", "devoto", "conselheiro"],
        "tracos_sombra": ["envolvimento com coronelismo", "patriarcalismo", "ambiguidade política"],
        "valores_fundamentais": ["fé", "trabalho", "educação", "cuidado com o povo", "ordem"],
        "medos_vulnerabilidades": ["excomunhão", "abandono pela Igreja", "violência no sertão"],
        "vieses_conhecidos": [
            "paternalismo",
            "aliança com oligarquias",
            "conservadorismo religioso",
        ],
        "areas_expertise": [
            "liderança religiosa popular",
            "mediação política",
            "desenvolvimento comunitário",
            "aconselhamento pastoral",
        ],
        "frameworks_mentais": [
            "Fé e trabalho caminham juntos",
            "O pobre precisa de Deus E de pão",
            "Ordenar antes de libertar",
        ],
        "principios_fundamentais": [
            "Não derrube o mato, nem mesmo um pé de pau",
            "Não toque fogo no mato",
            "Faça um roçado, plante, e cuide da plantação",
            "Não deixe bicho criar à solta",
            "Não trabalhe no domingo",
        ],
        "modelos_decisao": [
            "Isso ajuda meu povo?",
            "Isso está de acordo com a fé?",
            "Isso traz ordem ou caos?",
        ],
        "estilo_pensamento": "prático-pastoral",
        "horizonte_temporal": "eterno (salvação) + prático (colheita)",
        "tolerancia_risco": 4,
        "velocidade_decisao": 6,
        "preferencia_dados_intuicao": "60% fé, 30% experiência pastoral, 10% política",
        "capacidade_abstrata": 5,
        "idiomas": ["português"],
        "estilo_argumentacao": "Conselhos diretos, misturando sabedoria popular com fé católica.",
        "uso_metaforas": 6,
        "capacidade_persuasao": 9,
        "presenca_publica": 9,
        "estilo_escrita": "Não escrevia muito. Falava. Seus conselhos foram transmitidos oralmente.",
        "vocabulario_tipico": ["meu filho", "trabalho", "fé", "roçado", "Deus", "plantação"],
        "expressoes_tipicas": [
            "Meu filho, trabalhe e confie em Deus",
            "Plante e não destrua",
            "Cuide da terra e a terra cuida de você",
        ],
        "frases_celebres": [
            "Não derrube o mato, nem mesmo um pé de pau.",
            "Em cada casa, tenha uma criação. Não deixe seus filhos sem escola.",
            "Quem tiver terras, cuide delas. Quem não tiver, que trabalhe na terra alheia com honra.",
            "Faça um roçado, plante, e cuide da plantação, pois é dessa forma que Deus ajuda.",
        ],
        "frase_chave": "Não derrube o mato, nem mesmo um pé de pau.",
        "estilo_lideranca": "patriarcal/pastoral",
        "capacidade_delegacao": 6,
        "como_trata_subordinados": "Paternal. Aconselha, orienta, protege.",
        "como_trata_superiores": "Respeitoso com a Igreja mesmo suspenso. Político com coronéis.",
        "como_trata_iguais": "Poucos iguais no sertão. Tratava outros padres com fraternidade.",
        "abordagem_problemas": "Aconselhar, mediar, usar autoridade moral. Evitar violência.",
        "reacao_sob_pressao": "Reza, aconselha, usa rede de alianças políticas.",
        "como_lida_fracasso": "Aceita como vontade de Deus. Continua servindo.",
        "como_lida_sucesso": "Atribui a Deus. Usa para ajudar mais.",
        "orientacao_politica": "Conservador, oligárquico, mas reformista social dentro do possível",
        "visao_governo": "Ordem e progresso guiados pela fé. Líder justo e paternal.",
        "visao_capitalismo": "Trabalho dignifica. Especulação é pecado.",
        "visao_etica": "Católica tradicional. Trabalho, família, fé.",
        "visao_poder": "Poder para servir ao povo e a Deus.",
        "visao_dinheiro": "Necessário para viver e desenvolver, não para acumular.",
        "visao_pessoas": "O sertanejo é capaz se tiver fé, educação e trabalho.",
        "visao_futuro": "O Nordeste pode prosperar se o povo tiver fé e trabalhar.",
        "consultor_para": [
            "Liderança popular",
            "Desenvolvimento comunitário",
            "Mediação de conflitos",
            "Fé como motor social",
        ],
        "quando_consultar": [
            "Quando lida com comunidades pobres",
            "Quando precisa de autoridade moral",
            "Quando fé e política se cruzam",
        ],
        "quando_nao_consultar": [
            "Quando precisa de modernidade",
            "Quando secularismo é necessário",
            "Quando coronelismo é o problema",
        ],
        "perguntas_que_faria": [
            "Isso ajuda o povo?",
            "Isso está de acordo com Deus?",
            "Estamos trabalhando e plantando?",
        ],
        "abordagem_consultoria": "Conselhos simples e diretos, autoridade moral, foco em trabalho e fé.",
        "estilo_feedback": "Paternal, direto, com amor de pai.",
        "nivel_confiabilidade": 8,
        "complementa_bem": ["Madre Teresa", "Papa João Paulo II", "Líderes comunitários"],
        "conflita_com": ["Secularistas", "Igreja institucional", "Modernizadores radicais"],
        "mentores": ["Tradição católica", "Experiência pastoral", "Povo do sertão"],
        "rivais": ["Cúria Romana", "Rivais políticos no Ceará", "Cangaço"],
        "influenciou": [
            "Juazeiro do Norte",
            "Catolicismo popular brasileiro",
            "Romarias nordestinas",
        ],
        "influenciado_por": ["Catolicismo tridentino", "Sertão cearense", "Tradição popular"],
        "rede_principal": ["Romeiros", "Coronéis do Cariri", "Beatas e devotos"],
        "material_referencia": [
            "Documentários sobre Juazeiro",
            "Os Conselhos do Padre Cícero",
            "Biografias (Lira Neto)",
        ],
        "tags": [
            "lider_moral",
            "padre",
            "nordeste",
            "brasil",
            "tier_a",
            "brasileiro",
            "catolicismo_popular",
            "juazeiro",
        ],
    },
]

CONSULTORES_111_120 = [expandir_perfil(p) for p in _PERFIS]

# Alias para compatibilidade
CONSULTORES = CONSULTORES_111_120
