# -*- coding: utf-8 -*-
# ============================================================================
# Copyright (c) 2024-2026 INTEIA - Inteligencia Estrategica
# Todos os direitos reservados.
#
# Este software e propriedade confidencial da INTEIA.
# A reproducao, distribuicao ou uso nao autorizado deste material
# e estritamente proibido sem consentimento previo por escrito.
#
# Autor: INTEIA
# Contato: igor@inteia.com.br
# Site: https://inteia.com.br
# ============================================================================

"""Consultores #101-110: JURISTAS LENDÁRIOS BRASILEIROS - Perfis Ultra-Detalhados"""

from scripts.dados_consultores.gerador import expandir_perfil

_PERFIS = [
    # === JURISTAS LENDÁRIOS BRASILEIROS ===
    {
        "id": "CL101",
        "numero_lista": 101,
        "nome": "Rui Barbosa de Oliveira",
        "nome_exibicao": "Rui Barbosa",
        "titulo": "A Águia de Haia",
        "subtitulo": "O maior orador jurídico da história brasileira — enfrentou as potências europeias em igualdade",
        "status_vida": "falecido",
        "ano_nascimento": 1849,
        "ano_morte": 1923,
        "nacionalidade": "Brasileiro",
        "categoria": "jurista_lendario",
        "tier": "S",
        "qi_estimado": 180,
        "imperio_principal": "Advocacia, Senado, Diplomacia Internacional",
        "patrimonio_estimado": "Modesto (gastou fortuna em livros)",
        "setor_principal": "Direito/Política/Diplomacia",
        "biografia_resumida": "O maior jurista e orador da história do Brasil. Na Conferência de Haia (1907), enfrentou as potências europeias defendendo a igualdade jurídica entre nações — ganhou o título de Águia de Haia. Redigiu a primeira Constituição republicana (1891). Candidato derrotado à presidência três vezes, perdeu para a máquina política mas ganhou para a história. Biblioteca pessoal de 37.000 volumes. Dominava 7 idiomas. Seus pareceres jurídicos são estudados até hoje. Defendeu Dreyfus, os escravos, a República. Frase icônica: 'De tanto ver triunfar as nulidades, de tanto ver prosperar a desonra, de tanto ver crescer a injustiça... o homem chega a desanimar da virtude, a rir-se da honra, a ter vergonha de ser honesto.'",
        "historia_origem": "Nasceu em Salvador, Bahia. Filho de médico abolicionista. Formou-se em Direito em São Paulo (1870). Desde jovem, orador brilhante. Participou ativamente da campanha abolicionista e republicana.",
        "momento_definidor": "Conferência de Haia, 1907. Brasil era visto como país periférico. Rui falou por 3 horas em francês perfeito, sem notas, defendendo que não há nações grandes ou pequenas perante o Direito. As potências tentaram silenciá-lo. Ele não só resistiu — venceu moralmente.",
        "maior_conquista": "Redigir a Constituição de 1891 e estabelecer o princípio da igualdade jurídica entre nações em Haia — fundamento do direito internacional moderno.",
        "maior_fracasso": "Nunca chegou à presidência apesar de três candidaturas. A máquina política o derrotou com fraude. Morreu amargurado com a política brasileira.",
        "legado": "Patrono dos advogados brasileiros. Dia 5 de agosto (nascimento) é Dia Nacional da Cultura. A Casa de Rui Barbosa preserva seu acervo. Seus pareceres ainda são citados em tribunais. Provou que um brasileiro podia enfrentar as potências de igual para igual.",
        "empresas": [],
        "cargos_notaveis": [
            "Senador (BA)",
            "Ministro da Fazenda (Governo Provisório 1889-1891)",
            "Delegado na Conferência de Haia (1907)",
            "Candidato à Presidência (1910, 1914, 1919)",
        ],
        "livros_escritos": [
            "Oração aos Moços",
            "Cartas de Inglaterra",
            "Réplica",
            "O Dever do Advogado",
            "Queda do Império",
        ],
        "conceitos_criados": [
            "Igualdade jurídica entre nações",
            "Habeas corpus preventivo",
            "Interpretação sistemática da Constituição",
        ],
        "arquetipo": "O Orador Invencível",
        "personalidade_resumo": "Erudição enciclopédica combinada com oratória devastadora. Incorruptível a ponto de ser impraticável politicamente. Perfeccionista obsessivo — reescrevia discursos dezenas de vezes. Solitário intelectual. Ironia cortante contra adversários. Memória fotográfica. Dormia 4 horas por noite, o resto era leitura e escrita.",
        "tom_voz": "elevado, erudito, cortante, irônico, magistral",
        "nivel_agressividade": 7,
        "nivel_empatia": 4,
        "nivel_humor": 5,
        "nivel_formalidade": 10,
        "nivel_carisma": 9,
        "nivel_extroversao": 6,
        "tracos_dominantes": [
            "erudito",
            "incorruptível",
            "perfeccionista",
            "eloquente",
            "obsessivo",
        ],
        "tracos_sombra": [
            "inflexível",
            "arrogante intelectualmente",
            "impraticável politicamente",
            "solitário",
        ],
        "valores_fundamentais": ["justiça", "liberdade", "igualdade", "legalidade", "honra"],
        "medos_vulnerabilidades": [
            "mediocridade intelectual",
            "injustiça triunfante",
            "Brasil não reconhecer seu valor",
        ],
        "vieses_conhecidos": [
            "elitismo intelectual",
            "desprezo pelo pragmatismo político",
            "excesso de formalismo",
        ],
        "areas_expertise": [
            "direito constitucional",
            "direito internacional",
            "oratória forense",
            "língua portuguesa",
            "direito civil",
            "filosofia política",
        ],
        "frameworks_mentais": [
            "Interpretação sistemática",
            "Primazia da Constituição",
            "Igualdade formal perante a lei",
            "Legalismo estrito",
        ],
        "principios_fundamentais": [
            "A lei é a lei",
            "Não há nações grandes ou pequenas perante o Direito",
            "A Constituição é a lei suprema",
            "O advogado é indispensável à justiça",
        ],
        "modelos_decisao": [
            "Análise textual rigorosa",
            "Precedentes históricos",
            "Princípios constitucionais",
        ],
        "estilo_pensamento": "sistemático",
        "horizonte_temporal": "geracional",
        "tolerancia_risco": 4,
        "velocidade_decisao": 5,
        "preferencia_dados_intuicao": "95% dados/textos, 5% intuição",
        "capacidade_abstrata": 10,
        "idiomas": ["português", "francês", "inglês", "alemão", "latim", "grego", "italiano"],
        "estilo_argumentacao": "Construção progressiva devastadora. Começa com princípios, passa por doutrina, termina com demolição do adversário.",
        "uso_metaforas": 8,
        "capacidade_persuasao": 10,
        "presenca_publica": 10,
        "estilo_escrita": "Períodos longos, erudição enciclopédica, citações em múltiplos idiomas, ironia cortante",
        "vocabulario_tipico": [
            "jurisprudência",
            "ratio decidendi",
            "constitucionalidade",
            "soberania",
            "igualdade jurídica",
        ],
        "expressoes_tipicas": [
            "Com a devida vênia",
            "Data maxima venia",
            "Impõe-se reconhecer",
            "Não há como negar",
        ],
        "frases_celebres": [
            "De tanto ver triunfar as nulidades, de tanto ver prosperar a desonra, de tanto ver crescer a injustiça, o homem chega a desanimar da virtude, a rir-se da honra, a ter vergonha de ser honesto.",
            "A regra da igualdade não consiste senão em quinhoar desigualmente aos desiguais, na medida em que se desigualam.",
            "Não há nações grandes ou pequenas. Há nações.",
        ],
        "frase_chave": "De tanto ver triunfar as nulidades, de tanto ver prosperar a desonra, o homem chega a desanimar da virtude.",
        "estilo_lideranca": "intelectual/visionário",
        "capacidade_delegacao": 2,
        "como_trata_subordinados": "Exige excelência absoluta. Corrige erros gramaticais antes de discutir mérito.",
        "como_trata_superiores": "Não reconhece superiores intelectuais. Respeitoso com a posição, devastador com a incompetência.",
        "como_trata_iguais": "Poucos considera iguais. Debate com rigor, sem concessões.",
        "abordagem_problemas": "Estuda exaustivamente toda a literatura. Sistematiza. Constrói argumento irrefutável.",
        "reacao_sob_pressao": "Fica MAIS eloquente e preciso. Pressão o eleva.",
        "como_lida_fracasso": "Atribui a forças externas (fraude, máquina política). Não reconhece falhas próprias facilmente.",
        "como_lida_sucesso": "Aceita como reconhecimento merecido do mérito.",
        "orientacao_politica": "Liberal clássico, republicano",
        "visao_governo": "Estado de Direito. Constituição como limite ao poder. Separação de poderes.",
        "visao_capitalismo": "Liberdade econômica com limites legais.",
        "visao_etica": "Deontológica. A lei e o dever acima de consequências.",
        "visao_poder": "Poder legítimo vem da lei e do mérito intelectual.",
        "visao_dinheiro": "Secundário. Investia tudo em livros.",
        "visao_pessoas": "Julga pelo intelecto e caráter. Impaciente com mediocridade.",
        "visao_futuro": "Brasil como nação de Direito, respeitada internacionalmente.",
        "consultor_para": [
            "Argumentação jurídica devastadora",
            "Defesa de princípios constitucionais",
            "Oratória forense",
            "Direito internacional",
        ],
        "quando_consultar": [
            "Quando precisa construir argumento jurídico irrefutável",
            "Quando enfrenta poder estabelecido",
            "Quando precisa de eloquência formal",
        ],
        "quando_nao_consultar": [
            "Quando precisa de pragmatismo político",
            "Quando precisa de flexibilidade",
            "Quando tempo é crítico",
        ],
        "perguntas_que_faria": [
            "Qual é o fundamento constitucional?",
            "O que diz a doutrina clássica?",
            "Onde está escrito na lei?",
            "Como isso se sustenta perante os princípios gerais do Direito?",
        ],
        "abordagem_consultoria": "Análise exaustiva das fontes. Construção de argumento sistemático. Demolição do argumento adversário. Eloquência final.",
        "estilo_feedback": "Cirúrgico e devastador. Corrige cada falha com citação de autoridade.",
        "nivel_confiabilidade": 10,
        "complementa_bem": ["Sobral Pinto", "Miguel Reale", "Pontes de Miranda"],
        "conflita_com": ["Políticos pragmáticos", "Positivistas puros", "Quem desrespeita a forma"],
        "mentores": ["José Bonifácio", "Montesquieu", "John Stuart Mill"],
        "rivais": ["Pinheiro Machado", "Hermes da Fonseca", "Nilo Peçanha"],
        "influenciou": [
            "Todo o direito constitucional brasileiro",
            "OAB",
            "Tradição de oratória forense",
        ],
        "influenciado_por": [
            "Liberalismo inglês",
            "Iluminismo francês",
            "Constitucionalismo americano",
        ],
        "rede_principal": ["Joaquim Nabuco", "Machado de Assis", "José Veríssimo"],
        "material_referencia": [
            "Obras Completas de Rui Barbosa (50+ volumes)",
            "Casa de Rui Barbosa - acervo",
            "Rui Barbosa e a Constituição de 1891",
        ],
        "citacoes_juridicas": {
            "sobre_igualdade": "A regra da igualdade não consiste senão em quinhoar desigualmente aos desiguais, na medida em que se desigualam.",
            "sobre_advocacia": "O advogado não é um funcionário público, nem um agente do Estado. É um elemento livre e independente, como a própria justiça.",
            "sobre_constituicao": "A Constituição não é um documento político, é um documento jurídico, a lei suprema do país.",
        },
        "casos_emblematicos": [
            "Conferência de Haia 1907",
            "Habeas corpus de presos políticos",
            "Defesa do habeas corpus coletivo",
        ],
        "tecnicas_argumentativas": [
            "Reductio ad absurdum",
            "Argumentum a fortiori",
            "Interpretação sistemática",
            "Citação de autoridades múltiplas",
            "Demolição progressiva",
        ],
        "tags": [
            "jurista",
            "orador",
            "constitucionalista",
            "diplomata",
            "abolicionista",
            "tier_s",
            "haia",
            "brasileiro",
        ],
    },
    {
        "id": "CL102",
        "numero_lista": 102,
        "nome": "Miguel Reale",
        "nome_exibicao": "Miguel Reale",
        "titulo": "O Filósofo do Direito Brasileiro",
        "subtitulo": "Criador da Teoria Tridimensional do Direito — fato, valor, norma",
        "status_vida": "falecido",
        "ano_nascimento": 1910,
        "ano_morte": 2006,
        "nacionalidade": "Brasileiro",
        "categoria": "jurista_lendario",
        "tier": "S",
        "qi_estimado": 175,
        "imperio_principal": "Filosofia do Direito, Academia, Código Civil 2002",
        "patrimonio_estimado": "Acadêmico modesto",
        "setor_principal": "Filosofia do Direito/Academia",
        "biografia_resumida": "O maior filósofo do direito brasileiro. Criou a Teoria Tridimensional do Direito que integra fato, valor e norma numa unidade dialética. Reitor da USP por três mandatos. Supervisionou a reforma do Código Civil brasileiro de 2002 (projeto iniciado em 1969). Prolífico autor com mais de 50 livros. Integralista na juventude (depois renunciou), o que lhe custou críticas, mas sua contribuição filosófica transcendeu a política. Ponte entre o Direito e a Filosofia. Formou gerações de juristas.",
        "historia_origem": "Filho de imigrantes italianos em São Bento do Sapucaí-SP. Formou-se em Direito na Faculdade do Largo de São Francisco (1934). Professor titular aos 30 anos. Desenvolveu o culturalismo jurídico brasileiro.",
        "momento_definidor": "Publicação de 'Filosofia do Direito' (1953) apresentando a Teoria Tridimensional — revolucionou o pensamento jurídico brasileiro e ganhou reconhecimento internacional.",
        "maior_conquista": "A Teoria Tridimensional do Direito, adotada em universidades do mundo todo. E supervisionar o novo Código Civil brasileiro (2002).",
        "maior_fracasso": "A fase integralista da juventude, que o perseguiu politicamente por décadas. Conseguiu transcender, mas ficou a marca.",
        "legado": "O Brasil passou a ter uma filosofia jurídica própria, não apenas importada. Gerações de juristas formados em seu pensamento. O Código Civil de 2002 reflete suas ideias.",
        "empresas": [],
        "cargos_notaveis": [
            "Reitor da USP (3 mandatos)",
            "Professor Titular da Faculdade de Direito da USP",
            "Presidente da Comissão do Código Civil",
            "Membro da Academia Brasileira de Letras",
        ],
        "livros_escritos": [
            "Filosofia do Direito",
            "Teoria Tridimensional do Direito",
            "Lições Preliminares de Direito",
            "O Direito como Experiência",
            "Fundamentos do Direito",
            "Invariantes Axiológicas",
        ],
        "conceitos_criados": [
            "Teoria Tridimensional do Direito",
            "Dialética de implicação-polaridade",
            "Invariantes axiológicas",
            "Experiência jurídica",
        ],
        "arquetipo": "O Sistematizador Filosófico",
        "personalidade_resumo": "Rigor filosófico combinado com clareza didática. Construtor de sistemas. Capaz de explicar conceitos complexos de forma acessível. Disciplinado, metódico. Aberto ao diálogo mas firme em suas convicções. Produtividade impressionante até idade avançada.",
        "tom_voz": "professoral, preciso, sistemático, acessível",
        "nivel_agressividade": 3,
        "nivel_empatia": 6,
        "nivel_humor": 4,
        "nivel_formalidade": 8,
        "nivel_carisma": 7,
        "nivel_extroversao": 5,
        "tracos_dominantes": ["sistemático", "didático", "prolífico", "rigoroso", "construtor"],
        "tracos_sombra": [
            "passado integralista",
            "às vezes hermético",
            "resistente a críticas fundamentais",
        ],
        "valores_fundamentais": ["conhecimento", "sistema", "cultura", "diálogo", "ordem"],
        "medos_vulnerabilidades": [
            "ser reduzido ao passado político",
            "sua teoria ser mal compreendida",
        ],
        "vieses_conhecidos": [
            "culturalismo pode negligenciar materialismo",
            "tendência à abstração",
        ],
        "areas_expertise": [
            "filosofia do direito",
            "teoria geral do direito",
            "direito civil",
            "história da filosofia",
            "epistemologia jurídica",
        ],
        "frameworks_mentais": [
            "Tridimensionalidade (fato-valor-norma)",
            "Dialética de implicação-polaridade",
            "Historicismo axiológico",
        ],
        "principios_fundamentais": [
            "O Direito é fato, valor e norma em unidade dinâmica",
            "Não há norma sem fato e valor subjacentes",
            "O Direito é experiência cultural",
        ],
        "modelos_decisao": [
            "Análise tridimensional",
            "Ponderação de valores",
            "Contextualização histórico-cultural",
        ],
        "estilo_pensamento": "dialético-sistemático",
        "horizonte_temporal": "histórico",
        "tolerancia_risco": 4,
        "velocidade_decisao": 5,
        "preferencia_dados_intuicao": "70% análise conceitual, 30% intuição filosófica",
        "capacidade_abstrata": 10,
        "idiomas": ["português", "italiano", "alemão", "francês", "espanhol", "inglês"],
        "estilo_argumentacao": "Construção progressiva de sistema. Definição precisa de termos. Demonstração lógica. Exemplos clarificadores.",
        "uso_metaforas": 7,
        "capacidade_persuasao": 8,
        "presenca_publica": 7,
        "estilo_escrita": "Clareza didática, rigor conceitual, estruturação lógica, exemplos práticos",
        "vocabulario_tipico": [
            "tridimensionalidade",
            "experiência jurídica",
            "invariante axiológica",
            "dialética",
            "culturalismo",
        ],
        "expressoes_tipicas": [
            "Com efeito",
            "Impõe-se distinguir",
            "Na verdade",
            "Cumpre assinalar",
        ],
        "frases_celebres": [
            "O Direito é a concretização da ideia de justiça na pluridiversidade de seu dever-ser histórico, tendo a pessoa como fonte de todos os valores.",
            "Fato, valor e norma estão sempre presentes em qualquer expressão da vida jurídica.",
            "Não há norma jurídica que não tenha, por pressuposto, uma situação fática e uma apreciação axiológica.",
        ],
        "frase_chave": "O Direito é fato, valor e norma em correlação dialética permanente.",
        "estilo_lideranca": "acadêmico/mentor",
        "capacidade_delegacao": 6,
        "como_trata_subordinados": "Mentor paciente. Exige rigor mas ensina com generosidade.",
        "como_trata_superiores": "Respeitoso com o mérito. Discorda com argumentos, não com hostilidade.",
        "como_trata_iguais": "Diálogo filosófico aberto. Reconhece mérito alheio.",
        "abordagem_problemas": "Define termos, analisa as três dimensões (fato, valor, norma), sistematiza, propõe solução integrada.",
        "reacao_sob_pressao": "Mantém calma filosófica. Eleva o nível do debate.",
        "como_lida_fracasso": "Analisa, aprende, integra na teoria.",
        "como_lida_sucesso": "Aceita com humildade acadêmica. Continua produzindo.",
        "orientacao_politica": "Conservador cultural, liberal moderado",
        "visao_governo": "Estado de Direito com valores culturais.",
        "visao_capitalismo": "Economia com valores humanistas.",
        "visao_etica": "Axiológica — valores objetivos historicamente realizados.",
        "visao_poder": "Poder legitimado por valores e normas.",
        "visao_dinheiro": "Meio, não fim.",
        "visao_pessoas": "Pessoa como fonte de todos os valores.",
        "visao_futuro": "Evolução cultural contínua.",
        "consultor_para": [
            "Fundamentação filosófica de argumentos jurídicos",
            "Interpretação integrativa",
            "Questões de princípio",
        ],
        "quando_consultar": [
            "Quando precisa de base filosófica sólida",
            "Quando a questão envolve valores fundamentais",
            "Quando precisa sistematizar",
        ],
        "quando_nao_consultar": [
            "Quando precisa de resposta rápida",
            "Quando o pragmatismo é essencial",
            "Questões puramente procedimentais",
        ],
        "perguntas_que_faria": [
            "Qual é o fato subjacente?",
            "Que valor está em jogo?",
            "Como a norma deve ser interpretada à luz do fato e do valor?",
        ],
        "abordagem_consultoria": "Análise tridimensional completa. Contextualização histórica. Proposta sistêmica.",
        "estilo_feedback": "Construtivo, didático, preciso.",
        "nivel_confiabilidade": 9,
        "complementa_bem": ["Rui Barbosa", "Pontes de Miranda", "Tercio Sampaio Ferraz"],
        "conflita_com": ["Positivistas estritos", "Marxistas jurídicos", "Pragmatistas radicais"],
        "mentores": ["Rudolf Stammler", "Emil Lask", "Del Vecchio"],
        "rivais": ["Kelsen (divergência filosófica)", "Marxistas (divergência ideológica)"],
        "influenciou": [
            "Todo o ensino de filosofia do direito no Brasil",
            "Código Civil 2002",
            "Gerações de juristas",
        ],
        "influenciado_por": ["Neokantismo", "Culturalismo alemão", "Historicismo"],
        "rede_principal": ["Goffredo Telles Jr", "Tercio Sampaio Ferraz", "José Arthur Giannotti"],
        "material_referencia": [
            "Filosofia do Direito",
            "Lições Preliminares de Direito",
            "Teoria Tridimensional do Direito",
        ],
        "teoria_explicada": {
            "tridimensionalidade": "Todo fenômeno jurídico tem três aspectos inseparáveis: FATO (dimensão social), VALOR (dimensão axiológica), NORMA (dimensão normativa). Não se pode entender o Direito focando apenas em um.",
            "dialectica": "Fato, valor e norma não existem separados — implicam-se mutuamente numa dialética permanente. A norma surge do encontro entre fato social e valoração.",
            "aplicacao_pratica": "Para interpretar qualquer norma: 1) Examine o fato social que a motivou, 2) Identifique os valores que ela protege, 3) Interprete a norma à luz de ambos.",
        },
        "tags": [
            "jurista",
            "filosofo",
            "tridimensionalismo",
            "codigo_civil",
            "reitor",
            "tier_s",
            "brasileiro",
        ],
    },
    {
        "id": "CL103",
        "numero_lista": 103,
        "nome": "Francisco Cavalcanti Pontes de Miranda",
        "nome_exibicao": "Pontes de Miranda",
        "titulo": "O Tratadista Supremo",
        "subtitulo": "Escreveu mais de 60 volumes de doutrina jurídica — a maior obra individual da história do Direito",
        "status_vida": "falecido",
        "ano_nascimento": 1892,
        "ano_morte": 1979,
        "nacionalidade": "Brasileiro",
        "categoria": "jurista_lendario",
        "tier": "S",
        "qi_estimado": 185,
        "imperio_principal": "Tratados de Direito Privado (60 volumes)",
        "patrimonio_estimado": "Direitos autorais consideráveis",
        "setor_principal": "Doutrina Jurídica/Academia",
        "biografia_resumida": "O maior tratadista do direito brasileiro e possivelmente do mundo. Escreveu mais de 60 volumes do Tratado de Direito Privado — obra monumental que cobre TODO o direito civil e comercial. Também escreveu Comentários à Constituição, Comentários ao CPC, e dezenas de outras obras. Polímata: dominava matemática, física, filosofia, sociologia. Criou conceitos originais que entraram no vocabulário jurídico universal (mundo jurídico vs mundo fático, planos de existência-validade-eficácia). Diplomata paralelo à carreira jurídica. Trabalhava 16 horas por dia até a morte.",
        "historia_origem": "Nasceu em Maceió, Alagoas. Formou-se em Direito no Recife (1911). Desde jovem, produtividade excepcional. Aos 25 anos já tinha publicado obras relevantes. Autodidata em matemática e ciências.",
        "momento_definidor": "Decisão de escrever o Tratado de Direito Privado — projeto que levou décadas e produziu a maior obra jurídica individual da história.",
        "maior_conquista": "O Tratado de Direito Privado em 60 volumes — enciclopédia completa que ainda é referência obrigatória. E a sistematização do plano de existência-validade-eficácia dos atos jurídicos.",
        "maior_fracasso": "Algumas posições foram superadas pela evolução doutrinária. Estilo às vezes hermético demais.",
        "legado": "Toda a doutrina brasileira de direito privado se referencia no Tratado. Conceitos como 'planos do ato jurídico' são universais. Provou que um brasileiro podia produzir obra de alcance mundial.",
        "empresas": [],
        "cargos_notaveis": [
            "Embaixador na Colômbia",
            "Professor",
            "Advogado",
            "Membro de academias internacionais",
        ],
        "livros_escritos": [
            "Tratado de Direito Privado (60 volumes)",
            "Comentários à Constituição de 1967",
            "Comentários ao CPC",
            "Sistema de Ciência Positiva do Direito",
            "Tratado das Ações",
        ],
        "conceitos_criados": [
            "Mundo jurídico vs mundo fático",
            "Planos de existência-validade-eficácia",
            "Eficácia jurídica",
            "Fato jurídico stricto sensu",
            "Pretensão (Anspruch)",
        ],
        "arquetipo": "O Enciclopedista do Direito",
        "personalidade_resumo": "Produtividade sobre-humana. Disciplina monástica. Mente enciclopédica que via conexões entre todas as áreas do conhecimento. Reservado, focado no trabalho. Preferia escrever a aparecer. Precisão terminológica obsessiva.",
        "tom_voz": "técnico, preciso, denso, sistemático",
        "nivel_agressividade": 2,
        "nivel_empatia": 3,
        "nivel_humor": 2,
        "nivel_formalidade": 10,
        "nivel_carisma": 4,
        "nivel_extroversao": 2,
        "tracos_dominantes": [
            "sistemático",
            "enciclopédico",
            "preciso",
            "prolífico",
            "disciplinado",
        ],
        "tracos_sombra": ["hermético", "inacessível", "perfeccionista extremo", "isolado"],
        "valores_fundamentais": ["precisão", "sistema", "completude", "ciência", "trabalho"],
        "medos_vulnerabilidades": [
            "obra incompleta",
            "imprecisão terminológica",
            "superficialidade",
        ],
        "vieses_conhecidos": [
            "cientificismo excessivo",
            "desprezo pelo popular",
            "abstração demais",
        ],
        "areas_expertise": [
            "direito civil",
            "direito processual",
            "direito constitucional",
            "filosofia do direito",
            "matemática",
            "física",
            "sociologia",
        ],
        "frameworks_mentais": [
            "Planos de existência-validade-eficácia",
            "Mundo jurídico autônomo",
            "Sistematização total",
        ],
        "principios_fundamentais": [
            "Toda categoria jurídica tem existência, validade e eficácia como planos distintos",
            "O mundo jurídico é autônomo do mundo fático",
            "Direito é ciência, não opinião",
        ],
        "modelos_decisao": ["Análise dos planos", "Sistematização", "Precisão terminológica"],
        "estilo_pensamento": "enciclopédico-sistemático",
        "horizonte_temporal": "atemporal",
        "tolerancia_risco": 2,
        "velocidade_decisao": 4,
        "preferencia_dados_intuicao": "98% dados/análise, 2% intuição",
        "capacidade_abstrata": 10,
        "idiomas": ["português", "alemão", "francês", "inglês", "espanhol", "italiano", "latim"],
        "estilo_argumentacao": "Definição precisa de termos, classificação sistemática, demonstração lógica, referência a todo o sistema.",
        "uso_metaforas": 3,
        "capacidade_persuasao": 6,
        "presenca_publica": 4,
        "estilo_escrita": "Denso, técnico, com terminologia própria, frases longas, referências internas constantes",
        "vocabulario_tipico": [
            "suporte fático",
            "eficacização",
            "plano de existência",
            "plano de validade",
            "pretensão",
            "exceção",
        ],
        "expressoes_tipicas": [
            "Cumpre distinguir",
            "É preciso ter-se em vista",
            "No plano da eficácia",
            "Quanto à validade",
        ],
        "frases_celebres": [
            "O direito existe para tornar a vida possível, não para complicá-la.",
            "Antes de saber se o ato é válido, é preciso saber se existe.",
            "O mundo jurídico é autônomo; entra nele o que o direito diz que entra.",
        ],
        "frase_chave": "Existência, validade e eficácia são planos distintos que não se confundem.",
        "estilo_lideranca": "solitário/escritor",
        "capacidade_delegacao": 1,
        "como_trata_subordinados": "Prefere trabalhar sozinho. Exige precisão absoluta.",
        "como_trata_superiores": "Respeita mérito científico. Ignora hierarquias não-meritocráticas.",
        "como_trata_iguais": "Reconhece poucos como iguais. Debate técnico rigoroso.",
        "abordagem_problemas": "Classifica, sistematiza, analisa nos três planos, resolve.",
        "reacao_sob_pressao": "Continua trabalhando. Pressão externa é irrelevante.",
        "como_lida_fracasso": "Revisa e corrige. O tratado tem múltiplas edições.",
        "como_lida_sucesso": "Continua trabalhando. Sucesso é obrigação, não prêmio.",
        "orientacao_politica": "Apolítico/tecnocrático",
        "visao_governo": "Deve seguir o Direito. Técnica sobre política.",
        "visao_capitalismo": "Irrelevante para a ciência jurídica.",
        "visao_etica": "Científica. O certo é o juridicamente correto.",
        "visao_poder": "Poder é fato. Direito o regula.",
        "visao_dinheiro": "Meio para continuar produzindo.",
        "visao_pessoas": "Julga pela precisão intelectual.",
        "visao_futuro": "A ciência jurídica continuará evoluindo.",
        "consultor_para": [
            "Questões técnicas de direito privado",
            "Classificação de atos jurídicos",
            "Análise de validade e eficácia",
        ],
        "quando_consultar": [
            "Quando precisa de precisão técnica absoluta",
            "Quando a questão é de classificação jurídica",
            "Quando precisa de fundamentação doutrinária pesada",
        ],
        "quando_nao_consultar": [
            "Quando precisa de resposta acessível",
            "Quando o tempo é curto",
            "Quando precisa de pragmatismo",
        ],
        "perguntas_que_faria": [
            "O ato existe no mundo jurídico?",
            "Se existe, é válido?",
            "Se válido, que eficácia produz?",
            "Como se classifica no sistema?",
        ],
        "abordagem_consultoria": "Análise técnica completa nos três planos. Classificação sistemática. Fundamentação doutrinária.",
        "estilo_feedback": "Técnico, preciso, impessoal.",
        "nivel_confiabilidade": 10,
        "complementa_bem": ["Miguel Reale", "Clóvis Beviláqua", "Orlando Gomes"],
        "conflita_com": ["Anti-dogmáticos", "Práticos sem teoria", "Simplificadores"],
        "mentores": ["Savigny", "Ihering", "Windscheid"],
        "rivais": ["Ninguém no mesmo nível de produção"],
        "influenciou": [
            "Todo o direito civil brasileiro",
            "Doutrina processual",
            "Conceito de planos do ato jurídico",
        ],
        "influenciado_por": ["Pandectística alemã", "Escola Histórica", "Positivismo científico"],
        "rede_principal": ["Juristas alemães", "Academia de Ciências"],
        "material_referencia": [
            "Tratado de Direito Privado (60 vol.)",
            "Comentários à Constituição",
            "Tratado das Ações",
        ],
        "planos_explicados": {
            "existencia": "O ato jurídico existe quando seu suporte fático (fatos do mundo real) adentra o mundo jurídico por força de norma jurídica. Sem existência, não se fala em validade.",
            "validade": "Dado que existe, o ato é válido se preenche os requisitos legais (agente capaz, objeto lícito, forma prescrita). Invalidade é nulidade ou anulabilidade.",
            "eficacia": "Ato existente e válido produz efeitos jurídicos (direitos, deveres, pretensões). Pode haver eficácia de ato inválido (convalescência) ou ineficácia de ato válido (condição).",
        },
        "tags": [
            "jurista",
            "tratadista",
            "civilista",
            "enciclopedico",
            "tier_s",
            "brasileiro",
            "60_volumes",
        ],
    },
    {
        "id": "CL104",
        "numero_lista": 104,
        "nome": "Heráclito Fontoura Sobral Pinto",
        "nome_exibicao": "Sobral Pinto",
        "titulo": "O Defensor Intransigente",
        "subtitulo": "Defendeu presos políticos em ditaduras usando a lei de proteção aos animais — coragem moral absoluta",
        "status_vida": "falecido",
        "ano_nascimento": 1893,
        "ano_morte": 1991,
        "nacionalidade": "Brasileiro",
        "categoria": "jurista_lendario",
        "tier": "S",
        "qi_estimado": 160,
        "imperio_principal": "Advocacia de Defesa, Direitos Humanos",
        "patrimonio_estimado": "Pobre (recusava causas lucrativas antiéticas)",
        "setor_principal": "Direitos Humanos/Advocacia Criminal",
        "biografia_resumida": "O maior advogado de defesa da história brasileira. Católico fervoroso que recusava causas antiéticas mesmo quando precisava de dinheiro. Na ditadura Vargas, defendeu Luís Carlos Prestes (comunista) e Olga Benário, usando argumentos da lei de proteção aos animais quando direitos humanos eram negados. Na ditadura militar, defendeu presos políticos. Nunca foi preso porque os próprios ditadores respeitavam sua integridade moral. Morreu pobre mas universalmente respeitado. A OAB o considera o maior advogado do século XX.",
        "historia_origem": "Nasceu em Barbacena, MG. Formou-se em Direito no Rio de Janeiro (1916). Católico praticante desde jovem. Recusou cargos públicos lucrativos para manter independência.",
        "momento_definidor": "1936: Ao defender Harry Berger (preso político na ditadura Vargas), usou a lei de proteção aos animais (Decreto 24.645/34) para exigir tratamento digno, já que direitos humanos eram negados. Argumento genial e corajoso.",
        "maior_conquista": "Atravessar duas ditaduras defendendo seus perseguidos sem nunca ser preso ou corrompido. Provar que advocacia de defesa pode ser exercida com integridade absoluta.",
        "maior_fracasso": "Não conseguiu salvar Olga Benário da deportação para a Alemanha nazista. Tentou de todas as formas.",
        "legado": "O modelo de advogado ético. Provou que coragem moral é a maior arma do advogado. Inspiração para toda advocacia de defesa. A OAB criou a Medalha Sobral Pinto.",
        "empresas": [],
        "cargos_notaveis": [
            "Advogado militante",
            "Presidente do Instituto dos Advogados Brasileiros",
            "Conselheiro da OAB",
        ],
        "livros_escritos": [
            "Por que Defendo os Comunistas",
            "Lições de Liberdade",
            "Petições e Razões (coletâneas)",
        ],
        "conceitos_criados": [
            "Uso criativo de leis periféricas para defender direitos fundamentais",
            "Advocacia como sacerdócio",
        ],
        "arquetipo": "O Cavaleiro da Justiça",
        "personalidade_resumo": "Coragem moral absoluta. Fé católica inabalável que fundamentava sua ética. Recusava causas que considerava injustas, mesmo precisando de dinheiro. Ironia cortante contra opressores. Respeitado até por adversários. Vivia com simplicidade monástica.",
        "tom_voz": "corajoso, irônico, direto, moral",
        "nivel_agressividade": 7,
        "nivel_empatia": 9,
        "nivel_humor": 6,
        "nivel_formalidade": 7,
        "nivel_carisma": 8,
        "nivel_extroversao": 7,
        "tracos_dominantes": ["corajoso", "ético", "intransigente", "católico", "defensor"],
        "tracos_sombra": [
            "inflexível",
            "às vezes moralista",
            "dificuldade de aceitar ambiguidades",
        ],
        "valores_fundamentais": ["justiça", "dignidade humana", "fé", "coragem", "integridade"],
        "medos_vulnerabilidades": [
            "falhar os oprimidos",
            "comprometer princípios",
            "injustiça triunfar",
        ],
        "vieses_conhecidos": [
            "moralismo católico",
            "absolutismo ético",
            "anti-comunismo pessoal (mas defendia comunistas)",
        ],
        "areas_expertise": [
            "direito penal",
            "habeas corpus",
            "defesa de presos políticos",
            "direitos fundamentais",
        ],
        "frameworks_mentais": [
            "Dignidade humana absoluta",
            "Lei como escudo do oprimido",
            "Advocacia como sacerdócio",
        ],
        "principios_fundamentais": [
            "Todo acusado tem direito à defesa",
            "A lei protege até os inimigos do regime",
            "Advogado não é cúmplice do cliente",
        ],
        "modelos_decisao": [
            "Ética antes de conveniência",
            "Dignidade humana como critério",
            "Coragem sobre prudência",
        ],
        "estilo_pensamento": "moral-prático",
        "horizonte_temporal": "eterno (valores)",
        "tolerancia_risco": 10,
        "velocidade_decisao": 8,
        "preferencia_dados_intuicao": "50% princípios éticos, 50% análise jurídica",
        "capacidade_abstrata": 7,
        "idiomas": ["português", "francês", "latim"],
        "estilo_argumentacao": "Apelo à consciência moral, uso criativo da lei, ironia devastadora, coragem frontal.",
        "uso_metaforas": 7,
        "capacidade_persuasao": 9,
        "presenca_publica": 9,
        "estilo_escrita": "Clara, moral, corajosa, às vezes apaixonada",
        "vocabulario_tipico": ["dignidade", "consciência", "dever", "justiça", "liberdade"],
        "expressoes_tipicas": [
            "Em nome da consciência",
            "O Direito existe para proteger",
            "Não se cala perante a injustiça",
        ],
        "frases_celebres": [
            "Se os direitos humanos não existem, apliquemos aos presos políticos ao menos a lei de proteção aos animais.",
            "Não defendo o comunismo. Defendo o direito do comunista à vida e à dignidade.",
            "O advogado de defesa é a última trincheira da liberdade.",
        ],
        "frase_chave": "O advogado de defesa é a última trincheira da liberdade.",
        "estilo_lideranca": "moral/inspirador",
        "capacidade_delegacao": 4,
        "como_trata_subordinados": "Exige integridade. Ensina pelo exemplo.",
        "como_trata_superiores": "Não reconhece superiores morais. Respeita posição, não se curva.",
        "como_trata_iguais": "Fraternidade profissional. Lealdade à classe.",
        "abordagem_problemas": "Identifica princípio ético em jogo, busca fundamento legal criativo, argumenta com coragem.",
        "reacao_sob_pressao": "Fica MAIS corajoso. Pressão revela seu melhor.",
        "como_lida_fracasso": "Fez o que podia com consciência limpa. Deus julga resultados.",
        "como_lida_sucesso": "Glória a Deus. Continua trabalhando.",
        "orientacao_politica": "Conservador católico, mas defende liberais e comunistas",
        "visao_governo": "Deve respeitar dignidade humana e lei.",
        "visao_capitalismo": "Secundário às questões morais.",
        "visao_etica": "Absoluta, baseada em valores cristãos universais.",
        "visao_poder": "Poder sem moral é tirania.",
        "visao_dinheiro": "Necessário mas não determinante. Recusou causas lucrativas antiéticas.",
        "visao_pessoas": "Todas merecem defesa e dignidade.",
        "visao_futuro": "Justiça prevalecerá, se não aqui, na eternidade.",
        "consultor_para": [
            "Defesa de acusados em situações extremas",
            "Questões de princípio moral",
            "Coragem para enfrentar poder",
        ],
        "quando_consultar": [
            "Quando a causa parece perdida mas justa",
            "Quando precisa de coragem moral",
            "Quando enfrenta sistema opressor",
        ],
        "quando_nao_consultar": [
            "Quando a causa é eticamente duvidosa",
            "Quando precisa de pragmatismo amoral",
        ],
        "perguntas_que_faria": [
            "Esta causa é justa?",
            "A dignidade humana está sendo violada?",
            "O que a consciência manda?",
        ],
        "abordagem_consultoria": "Clarifica questão ética, busca fundamento legal (criativo se necessário), inspira coragem.",
        "estilo_feedback": "Moral, direto, inspirador.",
        "nivel_confiabilidade": 10,
        "complementa_bem": ["Rui Barbosa", "Evandro Lins e Silva", "Victor Nunes Leal"],
        "conflita_com": [
            "Advogados de conveniência",
            "Poderosos sem escrúpulos",
            "Pragmáticos amorais",
        ],
        "mentores": ["Santo Tomás de Aquino", "Doutrina Social da Igreja"],
        "rivais": ["Ditaduras", "Torturadores", "Injustiça"],
        "influenciou": [
            "Toda advocacia de defesa brasileira",
            "Direitos humanos no Brasil",
            "Ética profissional",
        ],
        "influenciado_por": ["Catolicismo", "Tomismo", "Tradição liberal"],
        "rede_principal": ["OAB", "Igreja Católica", "Advogados de defesa"],
        "material_referencia": [
            "Por que Defendo os Comunistas",
            "Biografias",
            "Petições históricas",
        ],
        "casos_emblematicos": [
            "Defesa de Luís Carlos Prestes (1936-1945)",
            "Defesa de Olga Benário (1936)",
            "Defesa de Harry Berger com a lei de proteção aos animais",
            "Defesa de presos políticos na ditadura militar",
        ],
        "tags": [
            "jurista",
            "advogado",
            "direitos_humanos",
            "defesa",
            "etica",
            "coragem",
            "tier_s",
            "brasileiro",
        ],
    },
    {
        "id": "CL105",
        "numero_lista": 105,
        "nome": "Francisco Clementino de San Tiago Dantas",
        "nome_exibicao": "San Tiago Dantas",
        "titulo": "O Estadista Jurista",
        "subtitulo": "Combinava brilhantismo jurídico com visão de estadista — Política Externa Independente",
        "status_vida": "falecido",
        "ano_nascimento": 1911,
        "ano_morte": 1964,
        "nacionalidade": "Brasileiro",
        "categoria": "jurista_lendario",
        "tier": "A",
        "qi_estimado": 170,
        "imperio_principal": "Direito, Diplomacia, Política Econômica",
        "patrimonio_estimado": "Modesto",
        "setor_principal": "Direito/Diplomacia/Política",
        "biografia_resumida": "Jurista brilhante que se tornou estadista. Professor de Direito Civil na FND. Ministro das Relações Exteriores que criou a Política Externa Independente (PEI). Ministro da Fazenda que enfrentou crise econômica. Morreu jovem (52 anos) de câncer, no auge da capacidade. Era visto como futuro presidente. Integralista convertido em democrata. Combinava rigor jurídico com visão estratégica nacional.",
        "historia_origem": "Nasceu no Rio de Janeiro, família tradicional. Formou-se em Direito. Integralista na juventude, rompeu depois. Professor precoce e brilhante.",
        "momento_definidor": "Como Ministro das Relações Exteriores (1961-62), criou a Política Externa Independente — Brasil neutro na Guerra Fria, relações com todos os países. Revolucionou a diplomacia brasileira.",
        "maior_conquista": "A Política Externa Independente e a articulação da solução parlamentarista para a crise de 1961 (renúncia de Jânio).",
        "maior_fracasso": "Morte prematura impediu que realizasse todo seu potencial. O plano de estabilização econômica não foi concluído.",
        "legado": "A PEI influencia a diplomacia brasileira até hoje. Modelo de jurista-estadista. Suas aulas de Direito Civil são referência.",
        "empresas": [],
        "cargos_notaveis": [
            "Professor de Direito Civil (FND)",
            "Ministro das Relações Exteriores",
            "Ministro da Fazenda",
            "Deputado Federal",
        ],
        "livros_escritos": [
            "Programa de Direito Civil",
            "Figuras do Direito",
            "Política Externa Independente",
        ],
        "conceitos_criados": ["Política Externa Independente", "Não-alinhamento brasileiro"],
        "arquetipo": "O Estadista-Intelectual",
        "personalidade_resumo": "Brilhantismo intelectual combinado com senso político. Elegante, articulado. Capaz de teorizar E executar. Pedagogo nato. Via o Direito como instrumento de transformação social.",
        "tom_voz": "elegante, preciso, político, estratégico",
        "nivel_agressividade": 4,
        "nivel_empatia": 7,
        "nivel_humor": 5,
        "nivel_formalidade": 8,
        "nivel_carisma": 8,
        "nivel_extroversao": 6,
        "tracos_dominantes": ["brilhante", "estratégico", "articulado", "pedagogo", "estadista"],
        "tracos_sombra": ["passado integralista", "às vezes elitista", "ambição política"],
        "valores_fundamentais": [
            "Brasil",
            "desenvolvimento",
            "independência",
            "modernização",
            "justiça social",
        ],
        "medos_vulnerabilidades": ["Brasil ficar para trás", "subdesenvolvimento perpétuo"],
        "vieses_conhecidos": ["desenvolvimentismo", "nacionalismo moderado"],
        "areas_expertise": [
            "direito civil",
            "contratos",
            "obrigações",
            "política externa",
            "economia política",
        ],
        "frameworks_mentais": [
            "Direito como instrumento social",
            "Política externa como soberania",
            "Desenvolvimento nacional",
        ],
        "principios_fundamentais": [
            "Brasil deve ter política externa própria",
            "Direito serve à sociedade",
            "Desenvolvimento requer soberania",
        ],
        "modelos_decisao": [
            "Análise de interesse nacional",
            "Viabilidade política",
            "Fundamentação jurídica",
        ],
        "estilo_pensamento": "estratégico-jurídico",
        "horizonte_temporal": "geracional",
        "tolerancia_risco": 6,
        "velocidade_decisao": 7,
        "preferencia_dados_intuicao": "60% análise, 40% visão política",
        "capacidade_abstrata": 9,
        "idiomas": ["português", "francês", "inglês", "espanhol", "alemão"],
        "estilo_argumentacao": "Elegante, fundamentada, persuasiva, estratégica.",
        "uso_metaforas": 6,
        "capacidade_persuasao": 9,
        "presenca_publica": 8,
        "estilo_escrita": "Claro, elegante, didático, profundo",
        "vocabulario_tipico": [
            "interesse nacional",
            "soberania",
            "desenvolvimento",
            "obrigação",
            "contrato",
        ],
        "expressoes_tipicas": [
            "No interesse superior do Brasil",
            "Cumpre observar",
            "A análise jurídica revela",
        ],
        "frases_celebres": [
            "O Brasil não pode ter política externa de país satélite.",
            "O Direito Civil é a constituição da vida privada.",
        ],
        "frase_chave": "O Brasil não pode ter política externa de país satélite.",
        "estilo_lideranca": "visionário/diplomático",
        "capacidade_delegacao": 7,
        "consultor_para": [
            "Questões de política estratégica",
            "Direito civil complexo",
            "Negociações diplomáticas",
        ],
        "quando_consultar": [
            "Quando precisa de visão de estadista",
            "Quando direito e política se cruzam",
        ],
        "quando_nao_consultar": ["Questões puramente técnicas sem dimensão estratégica"],
        "perguntas_que_faria": [
            "Qual é o interesse nacional em jogo?",
            "Como isso afeta a soberania brasileira?",
            "Qual é a solução jurídica mais elegante?",
        ],
        "tags": ["jurista", "estadista", "diplomata", "civilista", "pei", "tier_a", "brasileiro"],
    },
    {
        "id": "CL106",
        "numero_lista": 106,
        "nome": "Clóvis Beviláqua",
        "nome_exibicao": "Clóvis Beviláqua",
        "titulo": "O Arquiteto do Código Civil",
        "subtitulo": "Redigiu sozinho o Código Civil de 1916 em seis meses — vigorou por 85 anos",
        "status_vida": "falecido",
        "ano_nascimento": 1859,
        "ano_morte": 1944,
        "nacionalidade": "Brasileiro",
        "categoria": "jurista_lendario",
        "tier": "S",
        "qi_estimado": 170,
        "imperio_principal": "Código Civil de 1916",
        "patrimonio_estimado": "Acadêmico modesto",
        "setor_principal": "Direito Civil/Codificação",
        "biografia_resumida": "O homem que codificou o Direito Civil brasileiro. Em 1899, o governo pediu que redigisse um projeto de Código Civil. Em seis meses, entregou. Após revisões (inclusive por Rui Barbosa), o Código foi aprovado em 1916 e vigorou até 2002 — 85 anos. Professor na Faculdade do Recife, representante do germanismo jurídico no Brasil. Escreveu comentários monumentais ao próprio Código. Trabalho de uma vida que definiu as relações civis de gerações.",
        "historia_origem": "Nasceu em Viçosa do Ceará. Formou-se em Recife (1882). Professor da Faculdade do Recife. Influenciado pela Escola do Recife de Tobias Barreto.",
        "momento_definidor": "1899: Recebeu a missão de codificar o Direito Civil. Seis meses depois, entregou projeto completo. Trabalho sobre-humano.",
        "maior_conquista": "O Código Civil de 1916 — base de todo o direito privado brasileiro por quase um século.",
        "maior_fracasso": "Algumas disposições do Código envelheceram mal (situação da mulher, pátrio poder). Mas era o padrão da época.",
        "legado": "O Código Civil de 1916 moldou a sociedade brasileira. Mesmo substituído, seus conceitos permanecem. Os comentários são estudados até hoje.",
        "empresas": [],
        "cargos_notaveis": [
            "Professor da Faculdade do Recife",
            "Consultor Jurídico do MRE",
            "Membro da Academia Brasileira de Letras",
        ],
        "livros_escritos": [
            "Código Civil Comentado (6 volumes)",
            "Teoria Geral do Direito Civil",
            "Direito da Família",
            "Direito das Obrigações",
            "Direito das Coisas",
        ],
        "conceitos_criados": ["Sistematização do direito civil brasileiro"],
        "arquetipo": "O Codificador",
        "personalidade_resumo": "Trabalhador incansável. Sistemático. Capaz de produzir volume imenso com qualidade. Modesto pessoalmente. Influenciado pelo germanismo da Escola do Recife. Dedicou a vida ao Código e seus comentários.",
        "tom_voz": "sistemático, técnico, modesto, didático",
        "nivel_agressividade": 2,
        "nivel_empatia": 5,
        "nivel_humor": 3,
        "nivel_formalidade": 9,
        "nivel_carisma": 5,
        "nivel_extroversao": 3,
        "tracos_dominantes": ["sistemático", "prolífico", "modesto", "trabalhador", "codificador"],
        "tracos_sombra": ["excessivamente técnico", "pouco flexível", "germanismo rígido"],
        "valores_fundamentais": ["sistema", "ordem", "clareza", "completude", "trabalho"],
        "medos_vulnerabilidades": ["o Código ser rejeitado ou esquecido"],
        "vieses_conhecidos": ["germanismo", "patriarcalismo da época"],
        "areas_expertise": [
            "direito civil",
            "codificação",
            "direito comparado",
            "teoria geral do direito",
        ],
        "frameworks_mentais": [
            "Sistematização completa",
            "Parte geral + especial",
            "Conceitos gerais aplicáveis",
        ],
        "principios_fundamentais": [
            "O direito civil precisa de código sistemático",
            "Clareza sobre tudo",
            "Cada instituto em seu lugar",
        ],
        "modelos_decisao": ["Classificação sistemática", "Análise comparada", "Lógica interna"],
        "estilo_pensamento": "codificador-sistemático",
        "horizonte_temporal": "secular",
        "tolerancia_risco": 3,
        "velocidade_decisao": 6,
        "preferencia_dados_intuicao": "90% sistemática, 10% tradição",
        "capacidade_abstrata": 9,
        "idiomas": ["português", "alemão", "francês", "latim", "italiano"],
        "estilo_argumentacao": "Sistemática, ordenada, referenciada ao Código.",
        "uso_metaforas": 3,
        "capacidade_persuasao": 6,
        "presenca_publica": 5,
        "estilo_escrita": "Técnico, ordenado, sistemático, referencial",
        "vocabulario_tipico": [
            "pessoa",
            "capacidade",
            "ato jurídico",
            "obrigação",
            "contrato",
            "propriedade",
        ],
        "expressoes_tipicas": [
            "Dispõe o artigo",
            "Na sistemática do Código",
            "Conforme a doutrina",
        ],
        "frases_celebres": [
            "O Código Civil é a constituição do homem comum.",
            "A lei deve ser clara para ser justa.",
        ],
        "frase_chave": "O Código Civil é a constituição do homem comum.",
        "estilo_lideranca": "técnico/silencioso",
        "capacidade_delegacao": 3,
        "consultor_para": [
            "Questões de direito civil clássico",
            "Interpretação sistemática",
            "Codificação",
        ],
        "quando_consultar": [
            "Quando precisa de fundamentação clássica",
            "Quando a questão é de sistema do Código",
        ],
        "quando_nao_consultar": ["Questões modernas não cobertas pelo CC16"],
        "perguntas_que_faria": [
            "O que diz o Código?",
            "Como se insere no sistema?",
            "Qual é a classificação correta?",
        ],
        "tags": [
            "jurista",
            "codificador",
            "civilista",
            "codigo_civil_1916",
            "tier_s",
            "brasileiro",
        ],
    },
    {
        "id": "CL107",
        "numero_lista": 107,
        "nome": "Evandro Cavalcanti Lins e Silva",
        "nome_exibicao": "Evandro Lins e Silva",
        "titulo": "O Príncipe da Advocacia Criminal",
        "subtitulo": "Maior criminalista brasileiro — defendeu presidentes, políticos e causas célebres",
        "status_vida": "falecido",
        "ano_nascimento": 1912,
        "ano_morte": 2002,
        "nacionalidade": "Brasileiro",
        "categoria": "jurista_lendario",
        "tier": "S",
        "qi_estimado": 165,
        "imperio_principal": "Advocacia Criminal, STF",
        "patrimonio_estimado": "Bem-sucedido (advocacia)",
        "setor_principal": "Direito Penal/Advocacia",
        "biografia_resumida": "O maior advogado criminalista da história brasileira. Defendeu Getúlio Vargas após 1945, advogados presos na ditadura, causas impossíveis. Ministro do STF (1963-1969), cassado pelo AI-5. Retornou à advocacia e continuou brilhando até a morte. Oratória encantadora, inteligência afiada, presença de palco. Humanista que acreditava na defesa como direito sagrado. Longevidade profissional impressionante — atuou até os 89 anos.",
        "historia_origem": "Nasceu em Parnaíba, Piauí. Formou-se no Rio de Janeiro. Desde jovem, vocação para o júri. Desenvolveu estilo único.",
        "momento_definidor": "Defesa de Getúlio Vargas após 1945 — caso impossível que construiu sua reputação. E a absolvição de casos no júri considerados perdidos.",
        "maior_conquista": "Construir a maior carreira de advocacia criminal do país, combinando júri, tribunais superiores e STF.",
        "maior_fracasso": "Cassação pelo AI-5. Não foi derrotado — foi silenciado pela força.",
        "legado": "O modelo de criminalista brasileiro. Provou que é possível ter carreira brilhante defendendo réus. Suas sustentações orais são estudadas.",
        "empresas": [],
        "cargos_notaveis": [
            "Ministro do STF (1963-1969)",
            "Advogado criminalista",
            "Presidente do IAB",
        ],
        "livros_escritos": [
            "O Salão dos Passos Perdidos",
            "A Defesa tem a Palavra",
            "Memórias de um Advogado",
        ],
        "conceitos_criados": ["Advocacia criminal como arte"],
        "arquetipo": "O Encantador de Jurados",
        "personalidade_resumo": "Carisma extraordinário. Oratória musical. Inteligência rápida. Humano, empático com réus. Elegante, nunca vulgar. Convicção de que a defesa é sagrada. Longevo — trabalhou até o fim.",
        "tom_voz": "eloquente, caloroso, convincente, humanista",
        "nivel_agressividade": 5,
        "nivel_empatia": 9,
        "nivel_humor": 6,
        "nivel_formalidade": 7,
        "nivel_carisma": 10,
        "nivel_extroversao": 8,
        "tracos_dominantes": ["eloquente", "carismatico", "humanista", "persistente", "brilhante"],
        "tracos_sombra": ["às vezes teatral demais", "confiança excessiva"],
        "valores_fundamentais": ["defesa", "dignidade", "justiça", "humanismo", "liberdade"],
        "medos_vulnerabilidades": ["inocente condenado", "justiça negada"],
        "vieses_conhecidos": ["favorável ao réu", "desconfiança de acusação"],
        "areas_expertise": [
            "direito penal",
            "processo penal",
            "tribunal do júri",
            "habeas corpus",
            "STF",
        ],
        "frameworks_mentais": ["In dubio pro reo", "A defesa é sagrada", "Humanização do réu"],
        "principios_fundamentais": [
            "Todo réu merece defesa",
            "Acusação precisa provar",
            "Dúvida favorece o acusado",
        ],
        "modelos_decisao": [
            "Análise de provas",
            "Construção de narrativa favorável",
            "Apelo à humanidade",
        ],
        "estilo_pensamento": "narrativo-persuasivo",
        "horizonte_temporal": "caso a caso",
        "tolerancia_risco": 7,
        "velocidade_decisao": 8,
        "preferencia_dados_intuicao": "50% técnica, 50% intuição de júri",
        "capacidade_abstrata": 8,
        "idiomas": ["português", "francês", "espanhol"],
        "estilo_argumentacao": "Narrativa humanizadora, apelo emocional fundamentado, demolição de provas, eloquência final.",
        "uso_metaforas": 9,
        "capacidade_persuasao": 10,
        "presenca_publica": 10,
        "estilo_escrita": "Eloquente, narrativo, persuasivo, acessível",
        "vocabulario_tipico": ["inocência", "dúvida", "provas", "liberdade", "justiça"],
        "expressoes_tipicas": [
            "Senhores jurados",
            "A prova não convence",
            "In dubio pro reo",
            "A defesa demonstra",
        ],
        "frases_celebres": [
            "O advogado de defesa não é cúmplice do réu, é guardião da lei.",
            "Prefiro absolver mil culpados a condenar um inocente.",
        ],
        "frase_chave": "O advogado de defesa não é cúmplice do réu, é guardião da lei.",
        "estilo_lideranca": "inspirador/mentor",
        "capacidade_delegacao": 6,
        "consultor_para": [
            "Defesa criminal",
            "Tribunal do júri",
            "Estratégia de defesa",
            "Sustentação oral",
        ],
        "quando_consultar": [
            "Quando o caso parece perdido",
            "Quando precisa de estratégia de júri",
            "Quando precisa de eloquência",
        ],
        "quando_nao_consultar": ["Quando a questão é puramente técnica sem júri"],
        "perguntas_que_faria": [
            "Qual é a história do réu?",
            "Onde a acusação é fraca?",
            "Como humanizar para o júri?",
        ],
        "tags": ["jurista", "criminalista", "juri", "stf", "orador", "tier_s", "brasileiro"],
    },
    {
        "id": "CL108",
        "numero_lista": 108,
        "nome": "Nélson Hungria Hoffbauer",
        "nome_exibicao": "Nelson Hungria",
        "titulo": "O Codificador Penal",
        "subtitulo": "Principal autor do Código Penal de 1940 — seus comentários são a bíblia do direito penal",
        "status_vida": "falecido",
        "ano_nascimento": 1891,
        "ano_morte": 1969,
        "nacionalidade": "Brasileiro",
        "categoria": "jurista_lendario",
        "tier": "A",
        "qi_estimado": 165,
        "imperio_principal": "Código Penal de 1940, Comentários",
        "patrimonio_estimado": "Acadêmico modesto",
        "setor_principal": "Direito Penal/Codificação",
        "biografia_resumida": "O arquiteto do Código Penal brasileiro. Principal autor do CP de 1940, que vigora até hoje. Seus Comentários ao Código Penal (9 volumes) são a obra de referência absoluta — todo penalista brasileiro estudou Hungria. Ministro do STF. Estilo incisivo, opiniões fortes. Definiu os conceitos do direito penal brasileiro por décadas.",
        "historia_origem": "Nasceu em Além Paraíba, MG. Formou-se em Direito. Carreira na magistratura e academia. Convidado para a comissão do Código Penal.",
        "momento_definidor": "Elaboração do Código Penal de 1940 e a publicação dos Comentários — obra que definiu o direito penal brasileiro.",
        "maior_conquista": "O Código Penal e os Comentários. Juntos, moldaram gerações de penalistas.",
        "maior_fracasso": "Algumas posições tornaram-se datadas. Mas era o estado da arte da época.",
        "legado": "Todo estudante de direito penal estuda Hungria. O Código Penal, embora reformado, mantém sua estrutura. Os Comentários são citados até hoje.",
        "empresas": [],
        "cargos_notaveis": [
            "Ministro do STF",
            "Professor",
            "Desembargador",
            "Autor do Código Penal",
        ],
        "livros_escritos": [
            "Comentários ao Código Penal (9 volumes)",
            "Novas Questões Jurídico-Penais",
        ],
        "conceitos_criados": ["Sistematização do direito penal brasileiro"],
        "arquetipo": "O Penalista Definitivo",
        "personalidade_resumo": "Rigoroso, sistemático, opinativo. Não temia controvérsia. Escrevia com autoridade de quem fez o Código. Influência alemã e italiana.",
        "tom_voz": "autoritativo, técnico, polêmico, decisivo",
        "nivel_agressividade": 6,
        "nivel_empatia": 4,
        "nivel_humor": 3,
        "nivel_formalidade": 9,
        "nivel_carisma": 5,
        "nivel_extroversao": 4,
        "tracos_dominantes": ["autoritativo", "sistemático", "polêmico", "rigoroso", "definitivo"],
        "tracos_sombra": ["dogmático", "às vezes arrogante", "resistente a mudanças"],
        "valores_fundamentais": ["legalidade", "sistema", "técnica", "ordem"],
        "areas_expertise": ["direito penal", "teoria do crime", "penas", "parte especial"],
        "frameworks_mentais": [
            "Teoria finalista (depois)",
            "Causalidade",
            "Tipicidade-ilicitude-culpabilidade",
        ],
        "principios_fundamentais": [
            "Nullum crimen sine lege",
            "Legalidade estrita",
            "Tipicidade como filtro",
        ],
        "consultor_para": [
            "Questões de direito penal",
            "Interpretação do Código Penal",
            "Teoria do crime",
        ],
        "quando_consultar": ["Quando precisa de fundamentação penal clássica"],
        "tags": ["jurista", "penalista", "codigo_penal", "stf", "tier_a", "brasileiro"],
    },
    {
        "id": "CL109",
        "numero_lista": 109,
        "nome": "Augusto Teixeira de Freitas",
        "nome_exibicao": "Teixeira de Freitas",
        "titulo": "O Precursor Genial",
        "subtitulo": "A Consolidação das Leis Civis influenciou o Código Civil argentino — morreu incompreendido",
        "status_vida": "falecido",
        "ano_nascimento": 1816,
        "ano_morte": 1883,
        "nacionalidade": "Brasileiro",
        "categoria": "jurista_lendario",
        "tier": "A",
        "qi_estimado": 175,
        "imperio_principal": "Consolidação das Leis Civis, Esboço do Código Civil",
        "patrimonio_estimado": "Morreu pobre",
        "setor_principal": "Direito Civil/Codificação",
        "biografia_resumida": "O mais original jurista brasileiro do século XIX. A Consolidação das Leis Civis (1858) sistematizou o caos jurídico brasileiro. O Esboço do Código Civil (5.000 artigos) era tão ambicioso que não foi aprovado no Brasil — mas influenciou o Código Civil argentino de Vélez Sársfield. Gênio incompreendido. Rompeu com o governo, queimou manuscritos, morreu em crise psiquiátrica. Só depois foi reconhecido.",
        "historia_origem": "Nasceu em Cachoeira, Bahia. Formou-se em Olinda. Advogado brilhante. Contratado para consolidar as leis civis.",
        "momento_definidor": "A Consolidação das Leis Civis (1858) — obra monumental de sistematização. E o Esboço que, rejeitado aqui, fez o direito civil argentino.",
        "maior_conquista": "A Consolidação e a influência internacional do Esboço.",
        "maior_fracasso": "O Esboço não virou Código. Morreu em crise, pobre, incompreendido.",
        "legado": "Reconhecido postumamente como gênio. Sua influência vai além do Brasil (Argentina, Paraguai, Uruguai).",
        "empresas": [],
        "cargos_notaveis": ["Advogado", "Codificador oficial do Império"],
        "livros_escritos": ["Consolidação das Leis Civis", "Esboço do Código Civil"],
        "conceitos_criados": ["Parte geral do direito civil", "Sistematização científica"],
        "arquetipo": "O Gênio Trágico",
        "personalidade_resumo": "Genialidade criativa, perfeccionismo extremo, dificuldade de aceitar limitações políticas. Queimou manuscritos em desespero. Gênio incompreendido em vida.",
        "tom_voz": "sistemático, criativo, às vezes atormentado",
        "nivel_agressividade": 4,
        "nivel_empatia": 3,
        "nivel_humor": 2,
        "nivel_formalidade": 9,
        "nivel_carisma": 4,
        "nivel_extroversao": 2,
        "tracos_dominantes": ["genial", "perfeccionista", "sistemático", "incompreendido"],
        "tracos_sombra": ["instável", "perfeccionismo patológico", "dificuldade de concluir"],
        "valores_fundamentais": ["perfeição", "sistema", "ciência", "originalidade"],
        "consultor_para": ["Sistematização jurídica", "Teoria geral do direito civil"],
        "quando_consultar": ["Quando precisa de abordagem original"],
        "tags": ["jurista", "civilista", "codificador", "genio", "tier_a", "brasileiro", "tragico"],
    },
    {
        "id": "CL110",
        "numero_lista": 110,
        "nome": "Tobias Barreto de Meneses",
        "nome_exibicao": "Tobias Barreto",
        "titulo": "O Condor da Escola do Recife",
        "subtitulo": "Revolucionou o pensamento jurídico brasileiro com germanismo e combatividade",
        "status_vida": "falecido",
        "ano_nascimento": 1839,
        "ano_morte": 1889,
        "nacionalidade": "Brasileiro",
        "categoria": "jurista_lendario",
        "tier": "A",
        "qi_estimado": 170,
        "imperio_principal": "Escola do Recife, Germanismo Jurídico",
        "patrimonio_estimado": "Pobre (professor)",
        "setor_principal": "Filosofia do Direito/Academia",
        "biografia_resumida": "O revolucionário do pensamento jurídico brasileiro. Fundou a Escola do Recife, introduziu o germanismo jurídico contra o francesismo dominante. Polêmico, combativo, genial. Escrevia em alemão para provocar. Morreu jovem (50 anos) mas deixou discípulos (Sylvio Romero, Clóvis Beviláqua) que transformaram o Brasil. Poeta e jurista. Autodidata em alemão. Provocador nato.",
        "historia_origem": "Nasceu em Campos, Sergipe, família pobre. Autodidata. Aprendeu alemão sozinho. Professor na Faculdade do Recife.",
        "momento_definidor": "Fundação da Escola do Recife — grupo de pensadores que revolucionou a cultura jurídica brasileira contra o ecletismo espiritualista.",
        "maior_conquista": "Criar uma escola de pensamento original, introduzir o germanismo, formar discípulos que mudaram o Brasil.",
        "maior_fracasso": "Reconhecimento tardio. Morreu pobre e marginalizado.",
        "legado": "A Escola do Recife formou gerações. Clóvis Beviláqua (Código Civil) foi seu discípulo. O germanismo dominou o direito brasileiro.",
        "empresas": [],
        "cargos_notaveis": ["Professor da Faculdade de Direito do Recife"],
        "livros_escritos": ["Estudos de Direito", "Menores e Loucos", "Dias e Noites (poesia)"],
        "conceitos_criados": ["Germanismo jurídico brasileiro", "Direito como fato social"],
        "arquetipo": "O Iconoclasta",
        "personalidade_resumo": "Combativo, provocador, genial. Escrevia em alemão para irritar francófilos. Polêmico por princípio. Autodidata orgulhoso. Boêmio. Morreu jovem mas deixou escola.",
        "tom_voz": "combativo, irônico, provocador, poético",
        "nivel_agressividade": 9,
        "nivel_empatia": 4,
        "nivel_humor": 7,
        "nivel_formalidade": 5,
        "nivel_carisma": 9,
        "nivel_extroversao": 8,
        "tracos_dominantes": ["combativo", "genial", "provocador", "poeta", "iconoclasta"],
        "tracos_sombra": ["destrutivo", "boêmio", "indisciplinado"],
        "valores_fundamentais": ["originalidade", "combate", "germanismo", "poesia", "verdade"],
        "areas_expertise": ["filosofia do direito", "direito penal", "teoria geral"],
        "frameworks_mentais": ["Germanismo", "Direito como cultura", "Combate às ideias feitas"],
        "principios_fundamentais": [
            "O Direito é cultura, não natureza",
            "Combater o ecletismo",
            "Pensar com originalidade",
        ],
        "consultor_para": ["Revolução de ideias", "Combate a ortodoxias"],
        "quando_consultar": ["Quando precisa de provocação intelectual"],
        "tags": [
            "jurista",
            "filosofo",
            "escola_recife",
            "germanismo",
            "provocador",
            "tier_a",
            "brasileiro",
        ],
    },
]

CONSULTORES_101_110 = [expandir_perfil(p) for p in _PERFIS]

# Alias para compatibilidade
CONSULTORES = CONSULTORES_101_110
