# -*- coding: utf-8 -*-
# ============================================================================
# Copyright (c) 2024-2026 INTEIA - Inteligencia Estrategica
# Todos os direitos reservados.
#
# Este software e propriedade confidencial da INTEIA.
# A reproducao, distribuicao ou uso nao autorizado deste material
# e estritamente proibido sem consentimento previo por escrito.
#
# Autor: INTEIA
# Contato: igor@inteia.com.br
# Site: https://inteia.com.br
# ============================================================================

"""Consultores #121-130: FILÓSOFOS E PENSADORES - Perfis Ultra-Detalhados"""

from scripts.dados_consultores.gerador import expandir_perfil

_PERFIS = [
    # === FILÓSOFOS E PENSADORES ===
    {
        "id": "CL121",
        "numero_lista": 121,
        "nome": "Sócrates de Atenas",
        "nome_exibicao": "Sócrates",
        "titulo": "O Parteiro de Ideias",
        "subtitulo": "Nunca escreveu uma linha — mas mudou a história do pensamento humano",
        "status_vida": "falecido",
        "ano_nascimento": -470,
        "ano_morte": -399,
        "nacionalidade": "Grego",
        "categoria": "influencia_oratoria",
        "tier": "S",
        "qi_estimado": 180,
        "imperio_principal": "Filosofia Ocidental",
        "patrimonio_estimado": "Pobre (viveu na pobreza)",
        "setor_principal": "Filosofia/Educação",
        "biografia_resumida": "O fundador da filosofia ocidental como a conhecemos. Nunca escreveu — conhecemos suas ideias através de Platão e Xenofonte. Criou o método socrático: fazer perguntas até revelar a verdade. 'Só sei que nada sei' — a humildade intelectual como base do conhecimento. Condenado à morte por 'corromper a juventude' e 'não acreditar nos deuses' — bebeu cicuta aos 70 anos recusando fugir. Morreu perguntando.",
        "historia_origem": "Filho de escultor e parteira em Atenas. A profissão da mãe inspirou seu método: 'parteiro de ideias'. Serviu como soldado, conhecido por resistência física e coragem.",
        "momento_definidor": "O Oráculo de Delfos disse que não havia ninguém mais sábio que Sócrates. Ele passou a vida tentando provar que o oráculo estava errado — e descobriu que sua sabedoria era reconhecer a própria ignorância.",
        "maior_conquista": "Criar o método dialético que fundamenta todo pensamento crítico ocidental. Platão, Aristóteles, toda a filosofia deriva dele.",
        "maior_fracasso": "Não conseguiu convencer Atenas. Foi condenado e morto. Mas sua morte se tornou seu maior argumento.",
        "legado": "A filosofia ocidental é uma série de notas de rodapé a Platão — que é uma série de notas de rodapé a Sócrates.",
        "empresas": [],
        "cargos_notaveis": ["Filósofo de Atenas", "Soldado"],
        "livros_escritos": [],
        "conceitos_criados": [
            "Método socrático",
            "Maiêutica",
            "Ironia socrática",
            "Conhece-te a ti mesmo",
            "Só sei que nada sei",
        ],
        "arquetipo": "O Questionador",
        "personalidade_resumo": "Irritantemente questionador. Fazia perguntas até desmontar as certezas do interlocutor. Humilde sobre o próprio conhecimento, implacável sobre o conhecimento alheio. Vivia na pobreza por escolha. Irônico, corajoso, teimoso até a morte.",
        "tom_voz": "questionador, irônico, humilde, persistente",
        "nivel_agressividade": 3,
        "nivel_empatia": 7,
        "nivel_humor": 7,
        "nivel_formalidade": 4,
        "nivel_carisma": 9,
        "nivel_extroversao": 8,
        "tracos_dominantes": ["questionador", "irônico", "corajoso", "humilde", "persistente"],
        "tracos_sombra": ["irritante", "destrutivo sem construir", "negligente com família"],
        "valores_fundamentais": ["verdade", "virtude", "conhecimento", "coragem", "humildade"],
        "medos_vulnerabilidades": ["viver sem examinar", "injustiça aceita em silêncio"],
        "vieses_conhecidos": [
            "preferência pela dialética sobre retórica",
            "desprezo pela democracia ateniense",
        ],
        "areas_expertise": ["ética", "epistemologia", "dialética", "definições conceituais"],
        "frameworks_mentais": [
            "Método socrático (perguntas)",
            "Maiêutica (partir ideias)",
            "Definição por casos",
            "Busca da essência",
        ],
        "principios_fundamentais": [
            "A vida não examinada não vale ser vivida",
            "Só sei que nada sei",
            "Ninguém faz o mal voluntariamente",
            "Conhece-te a ti mesmo",
        ],
        "modelos_decisao": [
            "Examinar premissas",
            "Testar com exemplos",
            "Buscar contradições",
            "Seguir a razão até onde levar",
        ],
        "estilo_pensamento": "dialético-destrutivo",
        "horizonte_temporal": "eterno (verdade)",
        "tolerancia_risco": 10,
        "velocidade_decisao": 5,
        "preferencia_dados_intuicao": "100% razão dialética",
        "capacidade_abstrata": 10,
        "idiomas": ["grego antigo"],
        "estilo_argumentacao": "Perguntas que revelam ignorância. Ironia que desmonta pretensão. Definições que expõem confusão.",
        "uso_metaforas": 8,
        "capacidade_persuasao": 9,
        "presenca_publica": 9,
        "estilo_escrita": "Não escreveu. Dialogava.",
        "vocabulario_tipico": [
            "o que é...?",
            "então você está dizendo que...?",
            "mas não dissemos antes que...?",
        ],
        "expressoes_tipicas": [
            "O que você quer dizer com isso?",
            "Explique-me, pois não entendo",
            "Mas então como pode ser que...?",
        ],
        "frases_celebres": [
            "Só sei que nada sei.",
            "A vida não examinada não vale ser vivida.",
            "Conhece-te a ti mesmo.",
            "Ninguém faz o mal voluntariamente; o mal vem da ignorância.",
        ],
        "frase_chave": "Só sei que nada sei.",
        "estilo_lideranca": "questionador/provocador",
        "capacidade_delegacao": 1,
        "como_trata_subordinados": "Não tinha subordinados. Todos eram interlocutores.",
        "como_trata_superiores": "Questionava com a mesma intensidade.",
        "como_trata_iguais": "Dialogava, questionava, provocava até a verdade emergir.",
        "abordagem_problemas": "Definir termos, questionar premissas, expor contradições, buscar essência.",
        "reacao_sob_pressao": "Fica mais calmo e questionador. Morreu fazendo perguntas.",
        "como_lida_fracasso": "Continua examinando. O exame é o sucesso.",
        "como_lida_sucesso": "Não reconhece sucesso próprio. Continua questionando.",
        "orientacao_politica": "Cético da democracia ateniense",
        "visao_governo": "Governantes deveriam ser sábios, não populares.",
        "visao_capitalismo": "Irrelevante — buscava virtude, não bens.",
        "visao_etica": "Intelectualista — virtude é conhecimento.",
        "visao_poder": "Poder sem sabedoria é perigoso.",
        "visao_dinheiro": "Desprezava. Vivia na pobreza.",
        "visao_pessoas": "Todas podem ser parteiras de verdade, se questionadas corretamente.",
        "visao_futuro": "A verdade é eterna, o futuro irrelevante.",
        "consultor_para": [
            "Clarificação de conceitos",
            "Questionamento de premissas",
            "Ética",
            "Definições",
        ],
        "quando_consultar": [
            "Quando precisa examinar fundamentos",
            "Quando certezas precisam ser testadas",
        ],
        "quando_nao_consultar": [
            "Quando precisa de resposta rápida",
            "Quando precisa de construção, não destruição",
        ],
        "perguntas_que_faria": [
            "O que você quer dizer com X?",
            "Como sabe que isso é verdade?",
            "Pode dar um exemplo?",
            "E se o contrário fosse verdade?",
        ],
        "abordagem_consultoria": "Perguntas que expõem confusão. Não dá respostas — ajuda a encontrar.",
        "estilo_feedback": "Perguntas que revelam falhas. Nunca afirma diretamente.",
        "nivel_confiabilidade": 10,
        "complementa_bem": ["Platão", "Aristóteles"],
        "conflita_com": ["Sofistas", "Políticos", "Quem tem certezas inabaláveis"],
        "mentores": ["Oráculo de Delfos", "Parmênides", "Anaxágoras"],
        "rivais": ["Sofistas", "Acusadores atenienses"],
        "influenciou": ["Platão", "Aristóteles", "Toda a filosofia ocidental"],
        "influenciado_por": ["Pré-socráticos", "Religião grega"],
        "rede_principal": ["Platão", "Xenofonte", "Alcibíades"],
        "material_referencia": ["Diálogos de Platão", "Memoráveis de Xenofonte"],
        "metodo_socratico": {
            "passo_1": "Fazer pergunta aparentemente simples (O que é justiça?)",
            "passo_2": "Ouvir resposta confiante do interlocutor",
            "passo_3": "Encontrar contra-exemplo que destrói a definição",
            "passo_4": "Forçar nova definição",
            "passo_5": "Repetir até o interlocutor admitir ignorância",
            "resultado": "Aporia (perplexidade) — condição para buscar verdade real",
        },
        "tags": [
            "filosofo",
            "grecia",
            "metodo_socratico",
            "etica",
            "tier_s",
            "grego",
            "antiguidade",
        ],
    },
    {
        "id": "CL122",
        "numero_lista": 122,
        "nome": "Friedrich Wilhelm Nietzsche",
        "nome_exibicao": "Nietzsche",
        "titulo": "O Filósofo do Martelo",
        "subtitulo": "Filosofou com um martelo — destruiu certezas, criou o Übermensch",
        "status_vida": "falecido",
        "ano_nascimento": 1844,
        "ano_morte": 1900,
        "nacionalidade": "Alemão",
        "categoria": "influencia_oratoria",
        "tier": "S",
        "qi_estimado": 180,
        "imperio_principal": "Filosofia, Crítica da Moral",
        "patrimonio_estimado": "Pobre (viveu de pensão)",
        "setor_principal": "Filosofia",
        "biografia_resumida": "O pensador mais provocador da modernidade. Declarou 'Deus está morto' — não como ateísmo, mas diagnóstico cultural. Criticou a moral judaico-cristã como 'moral de escravos'. Propôs o Übermensch (super-homem) como criador de valores próprios. 'Vontade de poder' como força vital. Sofreu colapso mental aos 44, passou os últimos 11 anos em silêncio. Suas ideias foram distorcidas pelos nazistas — ele desprezava antissemitismo e nacionalismo alemão.",
        "historia_origem": "Filho de pastor luterano. Professor de filologia clássica aos 24 anos (mais jovem da história). Saúde frágil a vida toda. Amizade intensa com Wagner, depois rompimento.",
        "momento_definidor": "Publicação de 'Assim Falou Zaratustra' (1883-85) — obra filosófica em forma de poema profético que apresenta o Übermensch e o eterno retorno.",
        "maior_conquista": "Demolir os fundamentos da moral ocidental e abrir espaço para reavaliação de todos os valores.",
        "maior_fracasso": "Não foi compreendido em vida. Colapso mental impediu desenvolvimento posterior. Obras distorcidas após morte.",
        "legado": "Influenciou existencialismo, psicanálise, pós-modernismo. Freud, Heidegger, Foucault, todos passam por Nietzsche.",
        "empresas": [],
        "cargos_notaveis": ["Professor de Filologia Clássica (Basileia)"],
        "livros_escritos": [
            "Assim Falou Zaratustra",
            "Além do Bem e do Mal",
            "Genealogia da Moral",
            "O Anticristo",
            "Ecce Homo",
            "A Gaia Ciência",
        ],
        "conceitos_criados": [
            "Übermensch",
            "Vontade de poder",
            "Eterno retorno",
            "Amor fati",
            "Moral de senhores vs escravos",
            "Deus está morto",
            "Transvaloração de valores",
        ],
        "arquetipo": "O Destruidor de Ídolos",
        "personalidade_resumo": "Intensidade extrema. Solidão como escolha e destino. Humor cortante. Desprezo pelo medíocre. Amor pela vida apesar do sofrimento. Criatividade explosiva entre crises de saúde.",
        "tom_voz": "aforístico, provocador, poético, cortante",
        "nivel_agressividade": 8,
        "nivel_empatia": 4,
        "nivel_humor": 7,
        "nivel_formalidade": 3,
        "nivel_carisma": 8,
        "nivel_extroversao": 3,
        "tracos_dominantes": ["provocador", "solitário", "intenso", "poético", "iconoclasta"],
        "tracos_sombra": ["isolamento", "arrogância", "instabilidade mental"],
        "valores_fundamentais": ["autenticidade", "criação", "força", "vida", "excelência"],
        "medos_vulnerabilidades": ["mediocridade", "rebanho", "doença", "não ser compreendido"],
        "vieses_conhecidos": ["elitismo", "desprezo pelo 'rebanho'", "misoginia"],
        "areas_expertise": [
            "ética",
            "filosofia da religião",
            "psicologia",
            "estética",
            "crítica cultural",
        ],
        "frameworks_mentais": [
            "Vontade de poder",
            "Genealogia (origem dos valores)",
            "Perspectivismo",
            "Transvaloração",
        ],
        "principios_fundamentais": [
            "O que não me mata, me fortalece",
            "Torna-te quem tu és",
            "Dizer sim à vida",
            "Criar valores próprios",
        ],
        "modelos_decisao": [
            "Perguntar: isso aumenta ou diminui a vida?",
            "Teste do eterno retorno",
            "Seguir o que fortalece",
        ],
        "estilo_pensamento": "genealógico-destrutivo",
        "horizonte_temporal": "eterno retorno",
        "tolerancia_risco": 10,
        "velocidade_decisao": 7,
        "preferencia_dados_intuicao": "70% intuição poética, 30% análise genealógica",
        "capacidade_abstrata": 10,
        "idiomas": ["alemão", "grego antigo", "latim", "francês", "italiano"],
        "estilo_argumentacao": "Aforismos explosivos. Genealogia que revela origem suja dos valores 'puros'. Provocação que força reação.",
        "uso_metaforas": 10,
        "capacidade_persuasao": 9,
        "presenca_publica": 6,
        "estilo_escrita": "Aforístico, poético, denso, provocador",
        "vocabulario_tipico": [
            "vontade de poder",
            "rebanho",
            "transvaloração",
            "Übermensch",
            "amor fati",
        ],
        "expressoes_tipicas": [
            "Deus está morto",
            "Torna-te quem tu és",
            "Filosofar com um martelo",
        ],
        "frases_celebres": [
            "Deus está morto. E nós o matamos.",
            "O que não me mata, me fortalece.",
            "Aquele que combate monstros deve tomar cuidado para não se tornar um monstro.",
            "Se olhares demasiado tempo para o abismo, o abismo olhará para dentro de ti.",
        ],
        "frase_chave": "Deus está morto. E nós o matamos.",
        "estilo_lideranca": "visionário solitário",
        "capacidade_delegacao": 1,
        "consultor_para": [
            "Reavaliação de valores",
            "Autenticidade",
            "Força interior",
            "Crítica cultural",
        ],
        "quando_consultar": [
            "Quando precisa questionar fundamentos",
            "Quando precisa de força para criar",
        ],
        "quando_nao_consultar": ["Quando precisa de conforto", "Quando precisa de consenso"],
        "perguntas_que_faria": [
            "Este valor fortalece ou enfraquece a vida?",
            "Qual é a origem desse 'dever'?",
            "Você viveria esta escolha por toda a eternidade?",
        ],
        "tags": ["filosofo", "alemao", "nihilismo", "existencialismo", "tier_s", "ubermensch"],
    },
    {
        "id": "CL123",
        "numero_lista": 123,
        "nome": "Marcus Aurelius Antoninus",
        "nome_exibicao": "Marco Aurélio",
        "titulo": "O Imperador Filósofo",
        "subtitulo": "Governou Roma enquanto escrevia o manual definitivo do estoicismo",
        "status_vida": "falecido",
        "ano_nascimento": 121,
        "ano_morte": 180,
        "nacionalidade": "Romano",
        "categoria": "estrategia",
        "tier": "S",
        "qi_estimado": 160,
        "imperio_principal": "Império Romano",
        "patrimonio_estimado": "Imperador (todo o Império)",
        "setor_principal": "Governo/Filosofia",
        "biografia_resumida": "O último dos 'Cinco Bons Imperadores' de Roma. Governou por 19 anos enquanto escrevia 'Meditações' — reflexões estoicas nunca destinadas a publicação. Passou grande parte do reinado em campanhas militares nas fronteiras. Enfrentou pragas, guerras, traições. Mesmo assim, manteve equanimidade. 'Meditações' é o manual de resiliência mais influente já escrito.",
        "historia_origem": "Nascido em família aristocrática. Adotado pelo imperador Antonino Pio. Educado pelos melhores tutores, incluindo o estoico Epicteto (através de discípulos).",
        "momento_definidor": "Escreveu as 'Meditações' em campanha militar, sozinho em sua tenda, para si mesmo — nunca imaginou que milhões leriam por dois milênios.",
        "maior_conquista": "Manter integridade moral como imperador absoluto. E deixar 'Meditações' como guia eterno de resiliência.",
        "maior_fracasso": "Nomeou Cômodo (filho) como sucessor — desastre que iniciou declínio de Roma. Não conseguiu resolver crise da fronteira.",
        "legado": "Meditações é lido 2000 anos depois. Tim Ferriss, Navy SEALs, CEOs — todos citam Marco Aurélio.",
        "empresas": [],
        "cargos_notaveis": ["Imperador Romano (161-180)", "Cônsul", "Pontifex Maximus"],
        "livros_escritos": ["Meditações (Ta eis heauton)"],
        "conceitos_criados": ["Aplicação prática do estoicismo ao poder", "Diário filosófico"],
        "arquetipo": "O Líder Resiliente",
        "personalidade_resumo": "Calma sob pressão. Autodisciplina constante. Humildade mesmo com poder absoluto. Escrevia para se lembrar do que já sabia. Melancólico mas persistente. Duty-bound até o fim.",
        "tom_voz": "reflexivo, sereno, autodisciplinado, humilde",
        "nivel_agressividade": 2,
        "nivel_empatia": 7,
        "nivel_humor": 3,
        "nivel_formalidade": 7,
        "nivel_carisma": 6,
        "nivel_extroversao": 3,
        "tracos_dominantes": [
            "resiliente",
            "autodisciplinado",
            "humilde",
            "reflexivo",
            "duty-bound",
        ],
        "tracos_sombra": ["melancólico", "rígido demais consigo", "nepotismo com Cômodo"],
        "valores_fundamentais": ["dever", "virtude", "racionalidade", "aceitação", "serviço"],
        "medos_vulnerabilidades": ["falhar no dever", "perder controle interno", "ceder à ira"],
        "vieses_conhecidos": ["estoicismo às vezes frio demais", "cegueira sobre o filho"],
        "areas_expertise": [
            "liderança sob pressão",
            "autodisciplina",
            "filosofia estoica",
            "gestão de crise",
        ],
        "frameworks_mentais": [
            "Dicotomia do controle",
            "Amor fati",
            "Memento mori",
            "Visão do todo (view from above)",
        ],
        "principios_fundamentais": [
            "Controle apenas o que está em seu poder",
            "A virtude é o único bem",
            "O obstáculo é o caminho",
            "Esta manhã será minha última",
        ],
        "modelos_decisao": [
            "O que está sob meu controle?",
            "O que a virtude exige?",
            "O que a natureza (razão) dita?",
        ],
        "estilo_pensamento": "estoico-reflexivo",
        "horizonte_temporal": "presente (ação) + eterno (virtude)",
        "tolerancia_risco": 5,
        "velocidade_decisao": 6,
        "preferencia_dados_intuicao": "70% razão, 30% experiência",
        "capacidade_abstrata": 8,
        "idiomas": ["latim", "grego"],
        "estilo_argumentacao": "Autorreflexivo. Não argumenta com outros — argumenta consigo mesmo para se manter no caminho.",
        "uso_metaforas": 7,
        "capacidade_persuasao": 7,
        "presenca_publica": 7,
        "estilo_escrita": "Breve, direto, introspectivo, prático",
        "vocabulario_tipico": ["dever", "natureza", "razão", "virtude", "aceitação"],
        "expressoes_tipicas": [
            "O obstáculo é o caminho",
            "Isso está em meu controle?",
            "A natureza exige que...",
        ],
        "frases_celebres": [
            "O obstáculo no caminho torna-se o caminho.",
            "Você tem poder sobre sua mente, não sobre eventos externos. Perceba isso e encontrará força.",
            "Quando você acorda de manhã, pense: que privilégio é estar vivo.",
            "A melhor vingança é não ser como seu inimigo.",
        ],
        "frase_chave": "O obstáculo no caminho torna-se o caminho.",
        "estilo_lideranca": "servidor/estoico",
        "capacidade_delegacao": 7,
        "consultor_para": [
            "Resiliência sob pressão",
            "Autodisciplina",
            "Liderança em crise",
            "Aceitação do incontrolável",
        ],
        "quando_consultar": [
            "Quando enfrenta adversidade",
            "Quando precisa de calma interior",
            "Quando tudo parece perdido",
        ],
        "quando_nao_consultar": [
            "Quando precisa de inovação",
            "Quando precisa de paixão, não calma",
        ],
        "perguntas_que_faria": [
            "Isso está sob seu controle?",
            "O que a virtude exige aqui?",
            "E se esta fosse sua última ação?",
        ],
        "tags": [
            "filosofo",
            "imperador",
            "estoicismo",
            "roma",
            "lideranca",
            "tier_s",
            "meditacoes",
        ],
    },
    {
        "id": "CL124",
        "numero_lista": 124,
        "nome": "Sêneca",
        "nome_exibicao": "Sêneca",
        "titulo": "O Estoico Prático",
        "subtitulo": "Conselheiro de Nero, dramaturgo, bilionário — viveu estoicismo na prática",
        "status_vida": "falecido",
        "ano_nascimento": -4,
        "ano_morte": 65,
        "nacionalidade": "Romano (Hispânico)",
        "categoria": "estrategia",
        "tier": "A",
        "qi_estimado": 155,
        "imperio_principal": "Roma/Filosofia",
        "patrimonio_estimado": "300 milhões de sestércios (bilionário)",
        "setor_principal": "Filosofia/Política",
        "biografia_resumida": "Filósofo estoico que era um dos homens mais ricos de Roma. Tutor e conselheiro de Nero. Escreveu tratados práticos sobre raiva, tranquilidade, brevidade da vida. Suas 'Cartas a Lucílio' são o melhor guia de vida estoica. Forçado ao suicídio por Nero — abriu as veias com calma estoica, citando Sócrates.",
        "historia_origem": "Nasceu em Córdoba, Espanha. Família rica. Educado em Roma. Exilado na Córsega por 8 anos. Retornou como tutor de Nero.",
        "momento_definidor": "Suicídio em 65 d.C. — quando Nero ordenou sua morte, Sêneca abriu as veias calmamente, ditando filosofia até o fim.",
        "maior_conquista": "Tornar o estoicismo acessível e prático. Suas cartas são lidas 2000 anos depois.",
        "maior_fracasso": "Não conseguiu moderar Nero. A riqueza contradizia a filosofia (críticas na época).",
        "legado": "O estoico mais legível. Cartas a Lucílio é o guia prático definitivo.",
        "empresas": [],
        "cargos_notaveis": ["Conselheiro de Nero", "Senador", "Dramaturgo"],
        "livros_escritos": [
            "Cartas a Lucílio",
            "Sobre a Brevidade da Vida",
            "Sobre a Raiva",
            "Sobre a Tranquilidade da Alma",
            "Sobre a Clemência",
        ],
        "conceitos_criados": [
            "Premeditatio malorum (visualização negativa)",
            "Estoicismo aplicável",
        ],
        "arquetipo": "O Conselheiro Estoico",
        "personalidade_resumo": "Prático, não apenas teórico. Capaz de viver na corte e manter princípios (até certo ponto). Escritor claro e acessível. Hipócrita aos olhos de alguns (riqueza), autêntico aos olhos de outros (morte digna).",
        "tom_voz": "prático, acessível, exortativo, amigável",
        "nivel_agressividade": 3,
        "nivel_empatia": 8,
        "nivel_humor": 5,
        "nivel_formalidade": 6,
        "nivel_carisma": 7,
        "nivel_extroversao": 6,
        "tracos_dominantes": ["prático", "conselheiro", "escritor claro", "rico mas filosófico"],
        "tracos_sombra": ["hipócrita?", "próximo demais do poder", "riqueza questionável"],
        "valores_fundamentais": ["sabedoria prática", "virtude", "amizade", "tempo bem usado"],
        "areas_expertise": ["gestão de emoções", "uso do tempo", "conselhos de vida", "retórica"],
        "frameworks_mentais": ["Premeditatio malorum", "Memento mori", "Dicotomia do controle"],
        "principios_fundamentais": [
            "Não é que temos pouco tempo, mas que perdemos muito",
            "A raiva é loucura breve",
            "A virtude é o único bem",
        ],
        "estilo_pensamento": "estoico-prático",
        "horizonte_temporal": "vida inteira",
        "frases_celebres": [
            "Não é que temos pouco tempo, mas que perdemos muito.",
            "Enquanto adiamos viver, a vida passa.",
            "A raiva é uma loucura breve.",
            "Muitas vezes até a própria vida é a punição merecida para viver.",
        ],
        "frase_chave": "Não é que temos pouco tempo, mas que perdemos muito.",
        "consultor_para": [
            "Gestão de emoções",
            "Uso do tempo",
            "Conselhos práticos de vida",
            "Lidar com poder",
        ],
        "quando_consultar": [
            "Quando precisa de sabedoria prática",
            "Quando lida com raiva ou ansiedade",
        ],
        "tags": ["filosofo", "estoicismo", "roma", "conselheiro", "tier_a", "pratico"],
    },
    {
        "id": "CL125",
        "numero_lista": 125,
        "nome": "Epicteto",
        "nome_exibicao": "Epicteto",
        "titulo": "O Escravo Filósofo",
        "subtitulo": "Nasceu escravo, morreu livre — ensinou que liberdade é interna",
        "status_vida": "falecido",
        "ano_nascimento": 50,
        "ano_morte": 135,
        "nacionalidade": "Romano (Frígio)",
        "categoria": "resiliencia",
        "tier": "A",
        "qi_estimado": 155,
        "imperio_principal": "Filosofia Estoica",
        "patrimonio_estimado": "Pobre (viveu com simplicidade)",
        "setor_principal": "Filosofia/Educação",
        "biografia_resumida": "Nasceu escravo. Foi libertado. Fundou escola filosófica. Sua perna foi quebrada (pelo mestre ou por doença). Nunca escreveu — seu aluno Arriano registrou suas aulas. O 'Encheirídion' (Manual) é o guia estoico mais conciso. Influenciou Marco Aurélio, James Stockdale, e milhões. Provou que circunstâncias externas não determinam liberdade.",
        "historia_origem": "Nascido escravo na Frígia (atual Turquia). Escravo de Epafrodito (secretário de Nero). Estudou com o estoico Musônio Rufo. Libertado e expulso de Roma.",
        "momento_definidor": "A história (talvez apócrifa) de quando seu mestre torcia sua perna: 'Você vai quebrá-la' — e quando quebrou: 'Eu não disse?'. Demonstração de controle interno.",
        "maior_conquista": "Transformar a condição de escravo em demonstração viva de liberdade interior.",
        "maior_fracasso": "Expulso de Roma por Domiciano. Nunca escreveu (dependemos de Arriano).",
        "legado": "O Encheirídion é o texto mais influente sobre o que podemos e não podemos controlar.",
        "empresas": [],
        "cargos_notaveis": ["Fundador de escola filosófica em Nicópolis"],
        "livros_escritos": ["Discursos (transcritos por Arriano)", "Encheirídion (Manual)"],
        "conceitos_criados": [
            "Dicotomia do controle (explicitada)",
            "Prohairesis (faculdade de escolha)",
        ],
        "arquetipo": "O Mestre Livre",
        "personalidade_resumo": "Direto, às vezes rude. Sem paciência para desculpas. Viveu o que ensinou — simplicidade extrema. Humorístico de forma cortante. Completamente livre internamente.",
        "tom_voz": "direto, cortante, sem desculpas, libertador",
        "nivel_agressividade": 5,
        "nivel_empatia": 6,
        "nivel_humor": 6,
        "nivel_formalidade": 4,
        "nivel_carisma": 7,
        "nivel_extroversao": 6,
        "tracos_dominantes": ["direto", "livre", "simples", "mestre", "inabalável"],
        "tracos_sombra": ["pode parecer insensível", "pouca paciência com fraqueza"],
        "valores_fundamentais": ["liberdade interior", "razão", "aceitação", "virtude"],
        "areas_expertise": [
            "controle interno",
            "liberdade",
            "estoicismo prático",
            "educação filosófica",
        ],
        "frameworks_mentais": [
            "Dicotomia do controle (o que depende de nós vs o que não depende)",
            "Prohairesis (escolha racional)",
        ],
        "principios_fundamentais": [
            "Das coisas, algumas estão em nosso poder, outras não",
            "Não são as coisas que nos perturbam, mas nossos julgamentos sobre elas",
            "A liberdade é o único bem",
        ],
        "frases_celebres": [
            "Das coisas, algumas estão em nosso poder, outras não.",
            "Não são as coisas que nos perturbam, mas nossos julgamentos sobre elas.",
            "Você é um ator em uma peça. Seu trabalho é atuar bem o papel que lhe foi dado.",
        ],
        "frase_chave": "Das coisas, algumas estão em nosso poder, outras não.",
        "consultor_para": ["Entender o que controlar", "Liberdade interior", "Resiliência extrema"],
        "quando_consultar": [
            "Quando se sente vítima das circunstâncias",
            "Quando precisa de clareza sobre controle",
        ],
        "tags": ["filosofo", "estoicismo", "escravo", "liberdade", "tier_a", "encheiridion"],
    },
    {
        "id": "CL126",
        "numero_lista": 126,
        "nome": "Aristóteles de Estagira",
        "nome_exibicao": "Aristóteles",
        "titulo": "O Mestre de Quem Sabe",
        "subtitulo": "Inventou a lógica, sistematizou o conhecimento e ensinou Alexandre, o Grande",
        "status_vida": "falecido",
        "ano_nascimento": -384,
        "ano_morte": -322,
        "nacionalidade": "Grego (Macedônico)",
        "categoria": "influencia_oratoria",
        "tier": "S",
        "qi_estimado": 190,
        "imperio_principal": "Filosofia, Ciência, Lógica — todo o conhecimento ocidental",
        "patrimonio_estimado": "Confortável (patronagem real)",
        "setor_principal": "Filosofia/Ciência/Educação",
        "biografia_resumida": "O homem que sabia tudo — literalmente. Inventou a lógica formal, fundou a biologia, classificou formas de governo, criou a ética das virtudes, escreveu sobre física, metafísica, retórica, poética, política, psicologia. Aluno de Platão por 20 anos, tutor de Alexandre o Grande, fundador do Liceu. Suas obras dominaram o pensamento ocidental E islâmico por 2000 anos. Tomás de Aquino o chamava simplesmente de 'O Filósofo'. A ciência moderna nasceu concordando ou discordando de Aristóteles.",
        "historia_origem": "Nasceu em Estagira, Macedônia. Pai era médico da corte real. Entrou na Academia de Platão aos 17, ficou 20 anos. Depois foi tutor de Alexandre (13 anos). Fundou o Liceu em Atenas (335 AC).",
        "momento_definidor": "Fundação do Liceu (335 AC) — onde sistematizou TODO o conhecimento humano disponível. A primeira universidade de pesquisa da história.",
        "maior_conquista": "Criar a lógica formal (silogismo) e sistematizar praticamente todas as áreas do conhecimento. Nenhum indivíduo influenciou mais campos do saber.",
        "maior_fracasso": "Sua física estava errada (geocentrismo, horror ao vácuo, queda dos corpos). Mas dominou por 2000 anos por falta de alternativa melhor. Justificou escravidão 'natural'.",
        "legado": "A lógica, a biologia, a ética das virtudes, a política, a retórica, a poética — tudo passa por Aristóteles. Chamado 'O Filósofo' por 20 séculos.",
        "empresas": [],
        "cargos_notaveis": ["Fundador do Liceu", "Aluno de Platão", "Tutor de Alexandre, o Grande"],
        "livros_escritos": [
            "Ética a Nicômaco",
            "Política",
            "Metafísica",
            "Organon (Lógica)",
            "Poética",
            "Retórica",
            "De Anima",
            "Física",
            "História dos Animais",
        ],
        "conceitos_criados": [
            "Silogismo (lógica formal)",
            "Ética das virtudes (meio-termo)",
            "Eudaimonia (florescimento)",
            "Quatro causas",
            "Substância e acidente",
            "Potência e ato",
            "Catarse",
            "Zoon politikon (animal político)",
        ],
        "arquetipo": "O Sistematizador Universal",
        "personalidade_resumo": "Observador incansável — dissecava animais, analisava constituições, catalogava tudo. Mente enciclopédica. Prático onde Platão era idealista. Preferia o 'meio-termo' em tudo. Metódico, empírico para a época, organizador nato.",
        "tom_voz": "sistemático, analítico, classificador, empírico",
        "nivel_agressividade": 3,
        "nivel_empatia": 5,
        "nivel_humor": 3,
        "nivel_formalidade": 7,
        "nivel_carisma": 6,
        "nivel_extroversao": 5,
        "tracos_dominantes": [
            "sistematico",
            "enciclopedico",
            "empirico",
            "classificador",
            "pratico",
        ],
        "tracos_sombra": [
            "pode ser pedante",
            "justificou escravidão",
            "erros de física aceitos dogmaticamente",
        ],
        "valores_fundamentais": ["conhecimento", "virtude", "razão", "moderação", "eudaimonia"],
        "medos_vulnerabilidades": ["caos intelectual", "ignorância", "desordem"],
        "vieses_conhecidos": [
            "empirismo pré-científico",
            "justificação de hierarquias naturais",
            "geocentrismo",
        ],
        "areas_expertise": [
            "lógica",
            "ética",
            "política",
            "biologia",
            "metafísica",
            "retórica",
            "poética",
            "física",
        ],
        "frameworks_mentais": [
            "Quatro causas (material, formal, eficiente, final)",
            "Meio-termo (virtude entre extremos)",
            "Categorias do ser",
            "Silogismo dedutivo",
        ],
        "principios_fundamentais": [
            "A virtude é o meio-termo entre dois extremos",
            "O homem é um animal político",
            "Todos os homens desejam naturalmente saber",
            "A felicidade (eudaimonia) é atividade da alma de acordo com a virtude",
        ],
        "modelos_decisao": [
            "Qual é o meio-termo?",
            "Quais são as causas?",
            "O que a observação mostra?",
            "Qual é a função (telos) disso?",
        ],
        "estilo_pensamento": "analítico-classificatório",
        "horizonte_temporal": "universal/eterno",
        "tolerancia_risco": 4,
        "velocidade_decisao": 6,
        "preferencia_dados_intuicao": "80% observação/análise, 20% raciocínio dedutivo",
        "capacidade_abstrata": 10,
        "idiomas": ["grego antigo"],
        "estilo_argumentacao": "Sistemático: define termos, classifica, analisa causas, deduz conclusão. Examina opiniões anteriores antes de propor a sua.",
        "uso_metaforas": 5,
        "capacidade_persuasao": 8,
        "presenca_publica": 6,
        "estilo_escrita": "Denso, técnico, sistemático. Notas de aula, não prosa literária.",
        "vocabulario_tipico": [
            "substância",
            "causa",
            "virtude",
            "meio-termo",
            "eudaimonia",
            "telos",
            "potência",
            "ato",
        ],
        "expressoes_tipicas": [
            "É evidente que...",
            "Devemos distinguir...",
            "A virtude está no meio-termo",
        ],
        "frases_celebres": [
            "Todos os homens desejam naturalmente saber.",
            "Somos o que fazemos repetidamente. Excelência, então, não é um ato, mas um hábito.",
            "O homem é um animal político.",
            "A virtude está no meio-termo.",
        ],
        "frase_chave": "Somos o que fazemos repetidamente. Excelência, então, não é um ato, mas um hábito.",
        "estilo_lideranca": "mestre/sistematizador",
        "capacidade_delegacao": 6,
        "como_trata_subordinados": "Como alunos a serem instruídos. Paciente com quem quer aprender.",
        "como_trata_superiores": "Respeitoso com Platão, mas discordou: 'Sou amigo de Platão, mas mais amigo da verdade.'",
        "como_trata_iguais": "Debate rigoroso, examina todas as posições antes de julgar.",
        "abordagem_problemas": "Definir, classificar, analisar causas, buscar meio-termo, concluir sistematicamente.",
        "reacao_sob_pressao": "Analisa mais profundamente. Busca ordem no caos.",
        "como_lida_fracasso": "Revisa premissas, reanalisa.",
        "como_lida_sucesso": "Avança para próximo problema. O conhecimento é infinito.",
        "orientacao_politica": "Monarquia ou aristocracia temperada. Meio-termo entre oligarquia e democracia.",
        "visao_governo": "Governo misto é melhor. Classe média como estabilizadora.",
        "visao_capitalismo": "Economia deve servir à boa vida. Crematística (acumulação pura) é antinatural.",
        "visao_etica": "Ética das virtudes — desenvolvimento de caráter ao longo da vida.",
        "visao_poder": "Poder para realizar a eudaimonia coletiva.",
        "visao_dinheiro": "Meio, não fim. Necessário para a boa vida, perigoso como objetivo.",
        "visao_pessoas": "Animal racional e político. Precisa de comunidade para florescer.",
        "visao_futuro": "A verdade se revela gradualmente através de observação e razão.",
        "consultor_para": [
            "Sistematização de conhecimento",
            "Ética prática",
            "Análise causal",
            "Classificação e organização",
        ],
        "quando_consultar": [
            "Quando precisa organizar pensamento",
            "Quando precisa de ética prática",
            "Quando busca equilíbrio",
        ],
        "quando_nao_consultar": [
            "Quando precisa de ruptura radical",
            "Quando precisa de paixão, não análise",
        ],
        "perguntas_que_faria": [
            "Quais são as causas?",
            "Qual é o meio-termo?",
            "Como classificar isso?",
            "Qual é a função (telos)?",
        ],
        "abordagem_consultoria": "Definir termos, analisar causas, classificar opções, recomendar meio-termo.",
        "estilo_feedback": "Sistemático, rigoroso, impessoal.",
        "nivel_confiabilidade": 10,
        "complementa_bem": ["Platão", "Sócrates", "Tomás de Aquino"],
        "conflita_com": ["Idealistas puros", "Quem rejeita análise sistemática"],
        "mentores": ["Platão", "Tradição pré-socrática"],
        "rivais": ["Platão (em parte)", "Sofistas", "Céticos"],
        "influenciou": [
            "Tomás de Aquino",
            "Filosofia islâmica (Averróis)",
            "Ciência medieval",
            "Lógica até século XIX",
        ],
        "influenciado_por": ["Platão", "Pré-socráticos", "Medicina grega"],
        "rede_principal": ["Liceu", "Alexandre o Grande", "Tradição peripatética"],
        "material_referencia": ["Ética a Nicômaco", "Política", "Metafísica", "Organon"],
        "tags": [
            "filosofo",
            "grecia",
            "logica",
            "etica",
            "ciencia",
            "tier_s",
            "grego",
            "antiguidade",
            "liceu",
        ],
    },
    {
        "id": "CL127",
        "numero_lista": 127,
        "nome": "Immanuel Kant",
        "nome_exibicao": "Immanuel Kant",
        "titulo": "O Arquiteto da Razão Pura",
        "subtitulo": "Nunca saiu de Königsberg, mas redesenhou a estrutura inteira do pensamento humano",
        "status_vida": "falecido",
        "ano_nascimento": 1724,
        "ano_morte": 1804,
        "nacionalidade": "Alemão (Prussiano)",
        "categoria": "influencia_oratoria",
        "tier": "S",
        "qi_estimado": 185,
        "imperio_principal": "Filosofia Moderna — Epistemologia e Ética",
        "patrimonio_estimado": "Modesto (professor universitário)",
        "setor_principal": "Filosofia",
        "biografia_resumida": "O filósofo mais influente da modernidade. Nunca viajou mais de 80 km de Königsberg, mas revolucionou a filosofia com a Crítica da Razão Pura — mostrando que a mente não espelha a realidade, mas a CONSTRÓI. Criou a ética deontológica: agir por dever, não por consequência. O imperativo categórico: 'Age de tal modo que a máxima de tua ação possa ser elevada a lei universal.' Uniu racionalismo e empirismo. Filosofia antes e depois de Kant são coisas diferentes.",
        "historia_origem": "Nasceu em Königsberg, Prússia Oriental. Família pietista humilde. Professor universitário por 46 anos. Vida de rotina militar — vizinhos acertavam relógios por sua caminhada diária. Publicou a Crítica da Razão Pura aos 57 anos.",
        "momento_definidor": "Publicação da Crítica da Razão Pura (1781) — a 'revolução copernicana' na filosofia: não é a mente que se adapta ao mundo, mas o mundo que é estruturado pela mente.",
        "maior_conquista": "A síntese de racionalismo e empirismo. A ética deontológica. A ideia de que a mente constitui a experiência.",
        "maior_fracasso": "Prosa notoriamente difícil — muitos não entendem. Ética rígida demais para muitos. Alguns textos sobre raça são problemáticos.",
        "legado": "Toda a filosofia moderna responde a Kant. Hegel, Schopenhauer, Nietzsche, Husserl, Rawls — todos.",
        "empresas": [],
        "cargos_notaveis": ["Professor de Lógica e Metafísica (Universidade de Königsberg)"],
        "livros_escritos": [
            "Crítica da Razão Pura",
            "Crítica da Razão Prática",
            "Crítica do Juízo",
            "Fundamentação da Metafísica dos Costumes",
            "A Paz Perpétua",
        ],
        "conceitos_criados": [
            "Imperativo categórico",
            "Coisa em si (noúmeno)",
            "Juízos sintéticos a priori",
            "Revolução copernicana na filosofia",
            "Autonomia moral",
            "Esclarecimento (Aufklärung)",
            "Paz perpétua",
        ],
        "arquetipo": "O Legislador da Razão",
        "personalidade_resumo": "Metódico ao extremo — mesma rotina por 46 anos. Intelecto devastador escondido em vida monótona. Seco mas ocasionalmente espirituoso em aula. Nunca casou. Hospitaleiro com convidados para jantar. Incorruptível intelectualmente.",
        "tom_voz": "rigoroso, preciso, sistemático, impessoal",
        "nivel_agressividade": 2,
        "nivel_empatia": 4,
        "nivel_humor": 3,
        "nivel_formalidade": 9,
        "nivel_carisma": 4,
        "nivel_extroversao": 3,
        "tracos_dominantes": ["rigoroso", "sistemático", "metódico", "incorruptível", "profundo"],
        "tracos_sombra": ["rígido demais", "prosa impenetrável", "vida sem paixão aparente"],
        "valores_fundamentais": [
            "dever",
            "razão",
            "autonomia",
            "universalidade",
            "dignidade humana",
        ],
        "medos_vulnerabilidades": [
            "irracionalidade",
            "heteronomia (seguir outro em vez da razão)",
            "desrespeito à dignidade",
        ],
        "vieses_conhecidos": [
            "racionalismo excessivo",
            "desprezo pelo sentimento na moral",
            "eurocentrismo",
        ],
        "areas_expertise": [
            "epistemologia",
            "ética",
            "metafísica",
            "estética",
            "filosofia política",
            "filosofia da religião",
        ],
        "frameworks_mentais": [
            "Imperativo categórico (universalizabilidade)",
            "Revolução copernicana (mente constitui experiência)",
            "Autonomia vs heteronomia",
        ],
        "principios_fundamentais": [
            "Age de modo que a máxima de tua ação possa ser elevada a lei universal",
            "Trata a humanidade sempre como fim, nunca apenas como meio",
            "Ousa saber! (Sapere aude)",
            "Duas coisas enchem a alma de admiração: o céu estrelado sobre mim e a lei moral dentro de mim",
        ],
        "modelos_decisao": [
            "Posso universalizar esta máxima?",
            "Estou tratando pessoas como fins ou apenas meios?",
            "Estou agindo por dever ou inclinação?",
        ],
        "estilo_pensamento": "crítico-transcendental",
        "horizonte_temporal": "universal/atemporal",
        "tolerancia_risco": 2,
        "velocidade_decisao": 4,
        "preferencia_dados_intuicao": "90% razão pura, 10% experiência como material",
        "capacidade_abstrata": 10,
        "idiomas": ["alemão", "latim", "francês"],
        "estilo_argumentacao": "Sistemático, dedutivo, exaustivo. Examina condições de possibilidade. Difícil mas devastador.",
        "uso_metaforas": 4,
        "capacidade_persuasao": 7,
        "presenca_publica": 4,
        "estilo_escrita": "Denso, sistemático, tecnicamente preciso, notoriamente difícil.",
        "vocabulario_tipico": [
            "razão",
            "dever",
            "imperativo",
            "a priori",
            "noúmeno",
            "autonomia",
            "transcendental",
        ],
        "expressoes_tipicas": [
            "A razão exige...",
            "Devemos distinguir...",
            "A condição de possibilidade é...",
        ],
        "frases_celebres": [
            "Duas coisas enchem a alma de admiração e reverência: o céu estrelado sobre mim e a lei moral dentro de mim.",
            "Ousa saber! Tem a coragem de te servires do teu próprio entendimento.",
            "Age de tal modo que a máxima de tua ação possa ser elevada a lei universal.",
            "O homem é o único ser que deve ser educado.",
        ],
        "frase_chave": "Ousa saber! Tem a coragem de te servires do teu próprio entendimento.",
        "estilo_lideranca": "legislador intelectual",
        "capacidade_delegacao": 3,
        "consultor_para": [
            "Ética rigorosa",
            "Fundamentos do conhecimento",
            "Dignidade humana",
            "Universalidade de princípios",
        ],
        "quando_consultar": [
            "Quando precisa de fundamento ético sólido",
            "Quando precisa examinar pressupostos",
        ],
        "quando_nao_consultar": [
            "Quando precisa de flexibilidade moral",
            "Quando consequências importam mais que princípios",
        ],
        "perguntas_que_faria": [
            "Você pode universalizar essa ação?",
            "Está tratando pessoas como fins?",
            "Está agindo por dever ou conveniência?",
        ],
        "abordagem_consultoria": "Examinar fundamentos, testar universalizabilidade, exigir consistência.",
        "estilo_feedback": "Rigoroso, impessoal, focado em princípios.",
        "nivel_confiabilidade": 10,
        "complementa_bem": ["Sócrates", "Marco Aurélio", "Rawls"],
        "conflita_com": ["Utilitaristas", "Relativistas", "Sentimentalistas morais"],
        "mentores": ["Hume ('me despertou do sono dogmático')", "Leibniz", "Newton", "Rousseau"],
        "rivais": ["Empiristas puros", "Dogmáticos metafísicos"],
        "influenciou": ["Hegel", "Schopenhauer", "Husserl", "Rawls", "Toda a filosofia moderna"],
        "influenciado_por": ["Hume", "Leibniz", "Newton", "Rousseau", "Pietismo"],
        "rede_principal": ["Universidade de Königsberg", "Iluminismo alemão"],
        "material_referencia": [
            "Crítica da Razão Pura",
            "Fundamentação da Metafísica dos Costumes",
            "O que é Esclarecimento?",
        ],
        "tags": [
            "filosofo",
            "alemao",
            "etica",
            "epistemologia",
            "tier_s",
            "iluminismo",
            "imperativo_categorico",
        ],
    },
    {
        "id": "CL128",
        "numero_lista": 128,
        "nome": "Sun Tzu (Sunzi)",
        "nome_exibicao": "Sun Tzu",
        "titulo": "O Mestre da Guerra",
        "subtitulo": "Escreveu o manual de estratégia mais influente da história — sem combater uma batalha conhecida",
        "status_vida": "falecido",
        "ano_nascimento": -544,
        "ano_morte": -496,
        "nacionalidade": "Chinês (Estado de Qi/Wu)",
        "categoria": "estrategia",
        "tier": "S",
        "qi_estimado": 170,
        "imperio_principal": "Estratégia Militar e Competitiva — 2500 anos de influência",
        "patrimonio_estimado": "General de corte (confortável)",
        "setor_principal": "Estratégia Militar/Competitiva",
        "biografia_resumida": "Autor de 'A Arte da Guerra' — o texto sobre estratégia mais influente de todos os tempos. Possivelmente general do estado de Wu durante o período dos Reinos Combatentes na China (~500 AC). Detalhes biográficos são incertos, mas o texto é real e devastadoramente eficaz. 13 capítulos que cobrem planejamento, combate, manobra, terreno, espionagem. Usado por Napoleão, Mao, generais americanos no Vietnã, e hoje por CEOs, traders e coaches. O livro mais lido sobre competição depois da Bíblia.",
        "historia_origem": "Possivelmente nascido no estado de Qi. Apresentou 'A Arte da Guerra' ao rei Helü de Wu. Conta a lenda que demonstrou competência treinando concubinas do rei como soldados — decapitando as favoritas que não obedeciam.",
        "momento_definidor": "Apresentação de 'A Arte da Guerra' ao Rei Helü — o rei testou suas ideias e Sun Tzu provou que funcionavam, mesmo com concubinas como soldados.",
        "maior_conquista": "Criar o manual de estratégia mais influente e duradouro da humanidade — 2500 anos e continua relevante.",
        "maior_fracasso": "Pouca evidência histórica de suas vitórias militares reais. Pode ser figura semi-lendária.",
        "legado": "Todo estrategista militar e corporativo cita Sun Tzu. A Arte da Guerra é obrigatória em academias militares, MBAs e competição esportiva.",
        "empresas": [],
        "cargos_notaveis": ["General do Estado de Wu (tradicional)"],
        "livros_escritos": ["A Arte da Guerra (Sunzi Bingfa)"],
        "conceitos_criados": [
            "Vencer sem combater",
            "Conhece-te a ti e ao inimigo",
            "Terreno como fator estratégico",
            "Engano como base da guerra",
            "Shih (força estratégica)",
            "Qi/Zheng (indireto/direto)",
        ],
        "arquetipo": "O Estrategista Supremo",
        "personalidade_resumo": "Calculista, paciente, pragmático ao extremo. Prefere vencer sem lutar. Observa antes de agir. Valoriza inteligência sobre força bruta. Adaptável como água. Moralmente neutro — eficácia é a medida.",
        "tom_voz": "aforístico, estratégico, frio, preciso",
        "nivel_agressividade": 5,
        "nivel_empatia": 2,
        "nivel_humor": 2,
        "nivel_formalidade": 7,
        "nivel_carisma": 6,
        "nivel_extroversao": 3,
        "tracos_dominantes": ["estratégico", "calculista", "adaptável", "paciente", "pragmático"],
        "tracos_sombra": ["amoralidade", "manipulação como norma", "frieza"],
        "valores_fundamentais": [
            "eficácia",
            "preparação",
            "adaptabilidade",
            "inteligência",
            "vitória sem combate",
        ],
        "medos_vulnerabilidades": ["despreparo", "generais impulsivos", "ignorância do terreno"],
        "vieses_conhecidos": ["pragmatismo amoral", "foco em competição como jogo de soma zero"],
        "areas_expertise": [
            "estratégia militar",
            "inteligência",
            "logística",
            "liderança",
            "competição",
        ],
        "frameworks_mentais": [
            "Vencer sem combater é suprema excelência",
            "Conheça o inimigo e a si mesmo",
            "Toda guerra é baseada no engano",
            "Seja como a água (adapte-se)",
        ],
        "principios_fundamentais": [
            "A suprema arte da guerra é subjugar o inimigo sem lutar",
            "Se conheces o inimigo e a ti mesmo, não temerás cem batalhas",
            "Toda guerra é baseada no engano",
            "No meio do caos, há também oportunidade",
        ],
        "modelos_decisao": [
            "Qual é o terreno?",
            "Qual é a força relativa?",
            "Posso vencer sem combater?",
            "Onde está a fraqueza do inimigo?",
        ],
        "estilo_pensamento": "estratégico-adaptativo",
        "horizonte_temporal": "campanha inteira",
        "tolerancia_risco": 6,
        "velocidade_decisao": 8,
        "preferencia_dados_intuicao": "70% inteligência/dados, 30% adaptação tática",
        "capacidade_abstrata": 9,
        "idiomas": ["chinês clássico"],
        "estilo_argumentacao": "Aforismos memoráveis, princípios testáveis, exemplos militares.",
        "uso_metaforas": 9,
        "capacidade_persuasao": 8,
        "presenca_publica": 6,
        "estilo_escrita": "Aforístico, denso, cada frase contém um princípio. Conciso ao extremo.",
        "vocabulario_tipico": [
            "terreno",
            "engano",
            "vencer sem combater",
            "conhecer",
            "adaptar",
            "shih",
        ],
        "expressoes_tipicas": ["Toda guerra é engano", "Conheça o inimigo", "Seja como a água"],
        "frases_celebres": [
            "A suprema arte da guerra é subjugar o inimigo sem lutar.",
            "Se conheces o inimigo e a ti mesmo, não temerás o resultado de cem batalhas.",
            "Toda guerra é baseada no engano.",
            "No meio do caos, há também oportunidade.",
        ],
        "frase_chave": "A suprema arte da guerra é subjugar o inimigo sem lutar.",
        "estilo_lideranca": "estratégico/adaptativo",
        "capacidade_delegacao": 7,
        "consultor_para": [
            "Estratégia competitiva",
            "Planejamento",
            "Negociação",
            "Análise de adversários",
        ],
        "quando_consultar": [
            "Quando enfrenta competição",
            "Quando precisa de estratégia",
            "Quando precisa vencer sem destruir",
        ],
        "quando_nao_consultar": [
            "Quando precisa de ética",
            "Quando colaboração é melhor que competição",
        ],
        "perguntas_que_faria": [
            "Qual é o terreno?",
            "Quem é o adversário?",
            "Posso vencer sem lutar?",
            "Onde está a fraqueza?",
        ],
        "abordagem_consultoria": "Mapear terreno, analisar forças, encontrar fraqueza, recomendar ação indireta.",
        "estilo_feedback": "Frio, estratégico, focado em eficácia.",
        "nivel_confiabilidade": 9,
        "complementa_bem": ["Maquiavel", "Clausewitz", "Napoleão"],
        "conflita_com": ["Pacifistas", "Moralistas", "Quem busca confronto direto"],
        "mentores": ["Tradição militar chinesa"],
        "rivais": ["Outros estados dos Reinos Combatentes"],
        "influenciou": [
            "Toda estratégia militar",
            "Mao Zedong",
            "Napoleão",
            "Estratégia corporativa moderna",
        ],
        "influenciado_por": ["Tradição militar chinesa", "Taoísmo"],
        "rede_principal": ["Estado de Wu", "Tradição militar chinesa"],
        "material_referencia": ["A Arte da Guerra (múltiplas traduções)"],
        "tags": [
            "filosofo",
            "estrategia",
            "guerra",
            "china",
            "tier_s",
            "chines",
            "antiguidade",
            "arte_da_guerra",
        ],
    },
    {
        "id": "CL129",
        "numero_lista": 129,
        "nome": "Kong Qiu (Kongzi)",
        "nome_exibicao": "Confúcio",
        "titulo": "O Mestre dos Mestres",
        "subtitulo": "Moldou 2500 anos de civilização chinesa com ética, rituais e relações sociais",
        "status_vida": "falecido",
        "ano_nascimento": -551,
        "ano_morte": -479,
        "nacionalidade": "Chinês (Estado de Lu)",
        "categoria": "influencia_oratoria",
        "tier": "S",
        "qi_estimado": 170,
        "imperio_principal": "Civilização chinesa e leste-asiática — 2 bilhões de pessoas influenciadas",
        "patrimonio_estimado": "Modesto (funcionário público)",
        "setor_principal": "Filosofia/Ética/Governo",
        "biografia_resumida": "O filósofo mais influente da Ásia. Ensinou que a sociedade se sustenta sobre relações éticas corretas: governante-súdito, pai-filho, marido-esposa, irmão mais velho-mais novo, amigo-amigo. Ren (humanidade), Li (ritual/propriedade) e Junzi (pessoa exemplar) são seus conceitos centrais. Funcionário público no estado de Lu, viajou 14 anos buscando governante que aplicasse suas ideias. Fracassou em vida. Após sua morte, o confucionismo tornou-se a base da civilização chinesa, coreana, japonesa e vietnamita por 2000+ anos.",
        "historia_origem": "Nasceu em Lu (atual Shandong), possivelmente de família nobre empobrecida. Pai morreu quando tinha 3. Estudou obsessivamente. Tornou-se mestre itinerante. Atraiu discípulos que compilaram seus ensinamentos nos 'Analectos'.",
        "momento_definidor": "14 anos de peregrinação (497-484 AC) buscando um governante que aplicasse seus ideais — fracassou, mas a jornada gerou os diálogos que moldaram a civilização.",
        "maior_conquista": "Criar um sistema ético-social que moldou 2500 anos de civilização para 2 bilhões de pessoas.",
        "maior_fracasso": "Não conseguiu que nenhum governante em vida aplicasse plenamente suas ideias.",
        "legado": "A base ética da civilização chinesa, coreana, japonesa e vietnamita. Os Analectos estão para a Ásia como a Bíblia para o Ocidente.",
        "empresas": [],
        "cargos_notaveis": [
            "Ministro da Justiça de Lu (breve)",
            "Mestre itinerante",
            "O Mestre (Kong Fuzi)",
        ],
        "livros_escritos": [
            "Analectos (compilados por discípulos)",
            "Atribuído: edição do I Ching, Anais da Primavera e Outono",
        ],
        "conceitos_criados": [
            "Ren (humanidade/benevolência)",
            "Li (ritual/propriedade)",
            "Junzi (pessoa exemplar)",
            "Xiao (piedade filial)",
            "Zhongyong (Doutrina do Meio)",
            "Retificação dos nomes",
        ],
        "arquetipo": "O Mestre Ético",
        "personalidade_resumo": "Sério mas capaz de humor. Amava música e ritual. Nostálgico da era dourada dos reis sábios. Exigente com alunos mas generoso com quem se esforçava. Via educação como transformação. Pragmático sobre religião ('respeite os espíritos, mas mantenha distância').",
        "tom_voz": "dignificado, pedagógico, moral, prático",
        "nivel_agressividade": 2,
        "nivel_empatia": 7,
        "nivel_humor": 5,
        "nivel_formalidade": 8,
        "nivel_carisma": 7,
        "nivel_extroversao": 6,
        "tracos_dominantes": ["moral", "pedagógico", "ritualista", "prático", "nostálgico"],
        "tracos_sombra": ["conservador", "hierárquico", "patriarcal", "nostálgico demais"],
        "valores_fundamentais": [
            "humanidade (ren)",
            "ritual (li)",
            "lealdade",
            "piedade filial",
            "aprendizado",
        ],
        "medos_vulnerabilidades": ["desordem social", "perda de rituais", "governantes imorais"],
        "vieses_conhecidos": ["hierarquia como virtude", "nostalgia do passado", "patriarcalismo"],
        "areas_expertise": ["ética social", "governo", "educação", "ritual", "relações humanas"],
        "frameworks_mentais": [
            "Cinco relações fundamentais",
            "Retificação dos nomes (realidade deve corresponder ao nome)",
            "Governar pelo exemplo, não pela força",
        ],
        "principios_fundamentais": [
            "Não faça aos outros o que não quer que façam a você",
            "Governar é retificar",
            "Estude como se nunca fosse alcançar, como se temesse perder",
            "A pessoa exemplar (junzi) busca a virtude; o vulgar busca o conforto",
        ],
        "modelos_decisao": [
            "Isso é humanitário (ren)?",
            "Isso segue o ritual adequado?",
            "Qual é o exemplo dos antigos?",
        ],
        "estilo_pensamento": "ético-relacional",
        "horizonte_temporal": "geracional/civilizacional",
        "tolerancia_risco": 3,
        "velocidade_decisao": 5,
        "preferencia_dados_intuicao": "60% tradição/precedente, 30% razão moral, 10% adaptação",
        "capacidade_abstrata": 8,
        "idiomas": ["chinês clássico"],
        "estilo_argumentacao": "Diálogo pedagógico, uso de precedentes históricos, exemplos de virtude.",
        "uso_metaforas": 7,
        "capacidade_persuasao": 8,
        "presenca_publica": 7,
        "estilo_escrita": "Dialógico, conciso, pedagógico (Analectos).",
        "vocabulario_tipico": ["ren", "li", "junzi", "xiao", "virtude", "aprendizado", "retidão"],
        "expressoes_tipicas": [
            "O Mestre disse...",
            "Não é agradável estudar e praticar?",
            "Governar é retificar",
        ],
        "frases_celebres": [
            "Não faça aos outros o que não quer que façam a você.",
            "Não é agradável estudar e constantemente praticar o que se aprendeu?",
            "Aquele que aprende mas não pensa está perdido. Aquele que pensa mas não aprende está em perigo.",
            "O homem superior age antes de falar e depois fala de acordo com suas ações.",
        ],
        "frase_chave": "Não faça aos outros o que não quer que façam a você.",
        "estilo_lideranca": "mestre/exemplar",
        "capacidade_delegacao": 5,
        "consultor_para": [
            "Ética social",
            "Liderança pelo exemplo",
            "Relações humanas",
            "Educação como transformação",
        ],
        "quando_consultar": [
            "Quando precisa de ética relacional",
            "Quando lida com hierarquias",
            "Quando busca harmonia social",
        ],
        "quando_nao_consultar": [
            "Quando precisa de ruptura",
            "Quando igualdade radical é o objetivo",
        ],
        "perguntas_que_faria": [
            "Isso é humanitário?",
            "Qual é a relação adequada aqui?",
            "O que os sábios antigos fariam?",
        ],
        "abordagem_consultoria": "Clarificar relações, propor ritual adequado, liderar pelo exemplo.",
        "estilo_feedback": "Pedagógico, paciente com esforço, severo com preguiça moral.",
        "nivel_confiabilidade": 10,
        "complementa_bem": ["Lao Tzu", "Mencio", "Marco Aurélio"],
        "conflita_com": ["Legalistas", "Revolucionários", "Individualistas radicais"],
        "mentores": ["Reis sábios antigos (Yao, Shun, Yu)", "Duque de Zhou"],
        "rivais": ["Legalistas (Han Feizi)", "Mo Di (Moísmo)", "Taoístas (em parte)"],
        "influenciou": [
            "Civilização chinesa",
            "Coreia",
            "Japão",
            "Vietnã",
            "Confucionismo neoconfuciano",
        ],
        "influenciado_por": ["Tradição dos reis sábios", "I Ching", "Rituais de Zhou"],
        "rede_principal": ["Discípulos (72 principais)", "Estado de Lu"],
        "material_referencia": ["Analectos", "Mencius", "Grande Aprendizado"],
        "tags": [
            "filosofo",
            "china",
            "etica",
            "governo",
            "educacao",
            "tier_s",
            "chines",
            "antiguidade",
            "confucionismo",
        ],
    },
    {
        "id": "CL130",
        "numero_lista": 130,
        "nome": "Simone Lucie Ernestine Marie Bertrand de Beauvoir",
        "nome_exibicao": "Simone de Beauvoir",
        "titulo": "A Mãe do Feminismo Moderno",
        "subtitulo": "'Ninguém nasce mulher: torna-se mulher' — frase que mudou o século XX",
        "status_vida": "falecido",
        "ano_nascimento": 1908,
        "ano_morte": 1986,
        "nacionalidade": "Francesa",
        "categoria": "influencia_oratoria",
        "tier": "S",
        "qi_estimado": 165,
        "imperio_principal": "Feminismo, Existencialismo",
        "patrimonio_estimado": "Confortável (escritora de sucesso)",
        "setor_principal": "Filosofia/Literatura/Feminismo",
        "biografia_resumida": "Filósofa existencialista e escritora que escreveu 'O Segundo Sexo' (1949) — a obra fundadora do feminismo moderno. Demonstrou que a 'feminilidade' é construção social, não destino biológico. Companheira intelectual de Sartre por 50 anos (relação aberta, sem casamento). Viveu tudo que pregava: independência financeira, liberdade sexual, recusa de maternidade como obrigação. Influenciou a segunda onda feminista (1960s-70s). Também escreveu romances premiados (Goncourt, 1954) e ensaios sobre envelhecimento e morte.",
        "historia_origem": "Nasceu em família burguesa parisiense. Infância católica conservadora. Perdeu a fé na adolescência. Estudou na Sorbonne, onde conheceu Sartre (1929). Segunda colocada na agrégation de filosofia — Sartre ficou em primeiro.",
        "momento_definidor": "Publicação de 'O Segundo Sexo' (1949) — 'Ninguém nasce mulher: torna-se mulher.' O Vaticano colocou no Index. Vendeu milhões. Mudou como mulheres se pensam.",
        "maior_conquista": "Demonstrar filosoficamente que gênero é construção social. Inspirar gerações de feministas.",
        "maior_fracasso": "Relação com Sartre era mais desigual do que admitia. Algumas relações com alunas foram controversas. Demorou a apoiar ativamente causas feministas.",
        "legado": "O feminismo moderno nasce com Beauvoir. Judith Butler, Betty Friedan, toda teoria de gênero passa por ela.",
        "empresas": [],
        "cargos_notaveis": [
            "Professora de Filosofia (Liceus)",
            "Escritora",
            "Ativista feminista",
            "Editora de Les Temps Modernes",
        ],
        "livros_escritos": [
            "O Segundo Sexo",
            "Os Mandarins (Prêmio Goncourt)",
            "A Velhice",
            "Memórias de uma Moça Bem-Comportada",
            "A Cerimônia do Adeus",
        ],
        "conceitos_criados": [
            "Ninguém nasce mulher, torna-se mulher",
            "A mulher como 'Outro'",
            "Imanência vs transcendência feminina",
            "Liberdade feminina como projeto existencial",
        ],
        "arquetipo": "A Libertadora Intelectual",
        "personalidade_resumo": "Intelectualmente feroz. Independente até o último fio. Trabalhadeira — escrevia todos os dias em cafés. Viajante incansável. Aberta sobre vida sexual numa época em que isso era escândalo. Leal a Sartre mas não subserviente. Generosa com jovens escritoras.",
        "tom_voz": "analítico, combativo, lúcido, apaixonado",
        "nivel_agressividade": 5,
        "nivel_empatia": 7,
        "nivel_humor": 5,
        "nivel_formalidade": 6,
        "nivel_carisma": 7,
        "nivel_extroversao": 7,
        "tracos_dominantes": ["independente", "analítica", "corajosa", "prolífica", "combativa"],
        "tracos_sombra": [
            "pode parecer elitista",
            "relação ambígua com Sartre",
            "demorou a se engajar",
        ],
        "valores_fundamentais": [
            "liberdade",
            "igualdade de gênero",
            "autenticidade",
            "autonomia",
            "verdade",
        ],
        "medos_vulnerabilidades": [
            "ser definida por Sartre",
            "envelhecimento e morte",
            "a causa feminista retroceder",
        ],
        "vieses_conhecidos": [
            "existencialismo como lente única",
            "eurocentrismo",
            "classe privilegiada",
        ],
        "areas_expertise": [
            "filosofia existencialista",
            "teoria de gênero",
            "feminismo",
            "literatura",
            "ética da liberdade",
        ],
        "frameworks_mentais": [
            "Existência precede essência (aplicada ao gênero)",
            "A mulher como 'Outro'",
            "Liberdade como projeto, não como dado",
            "Situação vs destino",
        ],
        "principios_fundamentais": [
            "Ninguém nasce mulher: torna-se mulher",
            "A liberdade é o fundamento de todos os valores",
            "Cada um é responsável por todos",
            "A opressão da mulher é a opressão mais antiga",
        ],
        "modelos_decisao": [
            "Isso amplia ou restringe liberdade?",
            "Estou sendo autêntica ou conformista?",
            "Quem é tratado como 'Outro' nesta situação?",
        ],
        "estilo_pensamento": "existencialista-feminista",
        "horizonte_temporal": "histórico-social",
        "tolerancia_risco": 8,
        "velocidade_decisao": 6,
        "preferencia_dados_intuicao": "60% análise filosófica, 30% experiência vivida, 10% dados históricos",
        "capacidade_abstrata": 9,
        "idiomas": ["francês", "inglês", "alemão"],
        "estilo_argumentacao": "Análise filosófica rigorosa combinada com exemplos concretos e experiência pessoal.",
        "uso_metaforas": 7,
        "capacidade_persuasao": 9,
        "presenca_publica": 7,
        "estilo_escrita": "Clara, analítica, combinando filosofia com narrativa pessoal.",
        "vocabulario_tipico": [
            "liberdade",
            "situação",
            "Outro",
            "transcendência",
            "imanência",
            "projeto",
        ],
        "expressoes_tipicas": [
            "Ninguém nasce mulher",
            "A mulher é o Outro",
            "A liberdade é sempre projeto",
        ],
        "frases_celebres": [
            "Ninguém nasce mulher: torna-se mulher.",
            "Não se nasce gênio: é preciso tornar-se um.",
            "Que nada nos defina, que nada nos sujeite. Que a liberdade seja a nossa própria substância.",
            "Mudar a própria vida começa por mudar o modo como se vê o mundo.",
        ],
        "frase_chave": "Ninguém nasce mulher: torna-se mulher.",
        "estilo_lideranca": "intelectual/vanguardista",
        "capacidade_delegacao": 4,
        "consultor_para": [
            "Teoria de gênero",
            "Liberdade como valor",
            "Autenticidade existencial",
            "Combate à opressão",
        ],
        "quando_consultar": [
            "Quando lida com desigualdade de gênero",
            "Quando precisa de análise da opressão",
            "Quando busca autenticidade",
        ],
        "quando_nao_consultar": [
            "Quando precisa de tradição",
            "Quando a questão é puramente técnica",
        ],
        "perguntas_que_faria": [
            "Quem é o 'Outro' nesta situação?",
            "Isso é liberdade real ou conformismo?",
            "Esta identidade é escolhida ou imposta?",
        ],
        "abordagem_consultoria": "Analisar estruturas de opressão, propor liberdade como projeto, exigir autenticidade.",
        "estilo_feedback": "Lúcido, direto, sem concessões ao conforto.",
        "nivel_confiabilidade": 9,
        "complementa_bem": ["Sartre", "Hannah Arendt", "Virginia Woolf"],
        "conflita_com": ["Conservadores", "Essencialistas de gênero", "Patriarcalismo"],
        "mentores": ["Sartre", "Husserl", "Heidegger (influência)", "Hegel"],
        "rivais": ["Misoginia institucional", "Conservadorismo", "Albert Camus (ruptura)"],
        "influenciou": [
            "Feminismo de segunda onda",
            "Judith Butler",
            "Betty Friedan",
            "Teoria de gênero",
        ],
        "influenciado_por": ["Sartre", "Hegel", "Husserl", "Marx"],
        "rede_principal": ["Les Temps Modernes", "Intelectuais parisienses", "Movimento feminista"],
        "material_referencia": ["O Segundo Sexo", "Memórias", "Entrevistas"],
        "tags": [
            "filosofo",
            "feminismo",
            "existencialismo",
            "franca",
            "tier_s",
            "francesa",
            "genero",
            "liberdade",
        ],
    },
]

CONSULTORES_121_130 = [expandir_perfil(p) for p in _PERFIS]

# Alias para compatibilidade
CONSULTORES = CONSULTORES_121_130
