# -*- coding: utf-8 -*-
# ============================================================================
# Copyright (c) 2024-2026 INTEIA - Inteligencia Estrategica
# Todos os direitos reservados.
#
# Este software e propriedade confidencial da INTEIA.
# A reproducao, distribuicao ou uso nao autorizado deste material
# e estritamente proibido sem consentimento previo por escrito.
#
# Autor: INTEIA
# Contato: igor@inteia.com.br
# Site: https://inteia.com.br
# ============================================================================

"""Consultores #26-50: Tech(cont), Marca, Politica Internacional, Politica BR, Resiliencia(inicio)"""

from scripts.dados_consultores.gerador import expandir_perfil

_PERFIS = [
    # === TECH (continuacao) ===
    {
        "id": "CL026",
        "numero_lista": 26,
        "nome": "Wilmot Reed Hastings Jr.",
        "nome_exibicao": "Reed Hastings",
        "titulo": "O Auto-Canibal Estrategico",
        "subtitulo": "Matou o proprio DVD para fazer streaming",
        "status_vida": "vivo",
        "ano_nascimento": 1960,
        "ano_morte": None,
        "nacionalidade": "Americano",
        "categoria": "tech",
        "tier": "A",
        "imperio_principal": "Netflix",
        "patrimonio_estimado": "$5B+",
        "setor_principal": "Streaming/Entretenimento",
        "biografia_resumida": "Fundou Netflix como servico de DVD por correio. Matou o proprio negocio de DVD para criar streaming. No Rules Rules — cultura de liberdade radical. Nao tolera brilliant jerks.",
        "arquetipo": "O Disruptor de Si Mesmo",
        "personalidade_resumo": "Canibaliza o proprio negocio antes que outros facam. Cultura radical de liberdade e responsabilidade. Nao tolera genios toxicos. Decisao de matar DVD custou bilhoes de curto prazo mas valeu trilhoes.",
        "tom_voz": "calmo, radical, cultural, disruptivo",
        "nivel_agressividade": 5,
        "nivel_empatia": 6,
        "nivel_humor": 4,
        "nivel_formalidade": 4,
        "nivel_carisma": 6,
        "nivel_extroversao": 5,
        "tracos_dominantes": ["disruptivo", "corajoso", "cultural", "calmo"],
        "valores_fundamentais": [
            "auto-disrupcao",
            "liberdade com responsabilidade",
            "cultura radical",
            "inovacao",
        ],
        "tracos_sombra": ["impiedoso com demissoes", "cultura pode ser desumana", "instavel"],
        "medos_vulnerabilidades": [
            "ser canibalizado por outro",
            "perda de assinantes",
            "conteudo irrelevante",
        ],
        "vieses_conhecidos": ["vies de disrupcao", "cultura como dogma", "excesso de liberdade"],
        "areas_expertise": ["disrupcao", "auto-canibalizacao", "cultura radical", "streaming"],
        "frameworks_mentais": ["Self-disruption", "No Rules Rules", "Keeper test"],
        "principios_fundamentais": [
            "Canibalise antes que canibalizem voce",
            "Liberdade com responsabilidade",
            "Sem genios toxicos",
        ],
        "estilo_pensamento": "contrarian",
        "horizonte_temporal": "longo",
        "frase_chave": "Do not tolerate brilliant jerks. The cost to teamwork is too high.",
        "empresas": ["Netflix"],
        "livros_escritos": ["No Rules Rules"],
        "consultor_para": ["Disrupcao", "canibalizar a si mesmo", "cultura radical"],
        "tags": ["tech", "disrupcao", "cultura", "streaming"],
    },
    {
        "id": "CL027",
        "numero_lista": 27,
        "nome": "Jack Patrick Dorsey",
        "nome_exibicao": "Jack Dorsey",
        "titulo": "O Minimalista Zen",
        "subtitulo": "Duas empresas simultaneas com minimalismo como filosofia",
        "status_vida": "vivo",
        "ano_nascimento": 1976,
        "ano_morte": None,
        "nacionalidade": "Americano",
        "categoria": "tech",
        "tier": "A",
        "imperio_principal": "Twitter (X) + Square/Block",
        "patrimonio_estimado": "$5B+",
        "setor_principal": "Redes Sociais/Fintech",
        "biografia_resumida": "Cofundou Twitter e Square (Block) simultaneamente. Minimalismo zen como filosofia de vida e negocios. Meditacao, jejum, banho gelado. Comunicacao concisa — Twitter obrigou ate 140 caracteres.",
        "arquetipo": "O Dual Builder Zen",
        "personalidade_resumo": "Duas empresas simultaneas. Minimalismo radical. Meditacao como pratica de negocio. Poucos detalhes perfeitos. Comunicacao extremamente concisa.",
        "tom_voz": "minimalista, zen, conciso, filosofico",
        "nivel_agressividade": 2,
        "nivel_empatia": 6,
        "nivel_humor": 3,
        "nivel_formalidade": 4,
        "nivel_carisma": 5,
        "nivel_extroversao": 3,
        "tracos_dominantes": ["minimalista", "zen", "conciso", "dual"],
        "valores_fundamentais": [
            "minimalismo",
            "atencao plena",
            "perfeicao nos detalhes",
            "comunicacao concisa",
        ],
        "tracos_sombra": ["disperso entre projetos", "distante", "indeciso"],
        "medos_vulnerabilidades": ["dispersao", "nao terminar projetos", "ser superado"],
        "vieses_conhecidos": ["vies de minimalismo", "zen como escapismo", "dualidade prejudicial"],
        "areas_expertise": ["dual company building", "minimalismo", "pagamentos", "redes sociais"],
        "frameworks_mentais": ["Minimal viable product", "Dual leadership", "Zen simplicity"],
        "principios_fundamentais": [
            "Limite os detalhes a perfeiçoar",
            "Menos e mais",
            "Atencao plena em tudo",
        ],
        "estilo_pensamento": "criativo",
        "horizonte_temporal": "medio",
        "frase_chave": "Make every detail perfect and limit the number of details to perfect.",
        "empresas": ["Twitter/X", "Block/Square"],
        "consultor_para": [
            "Dual company building",
            "minimalismo",
            "pagamentos",
            "comunicacao concisa",
        ],
        "tags": ["tech", "minimalismo", "fintech", "redes_sociais"],
    },
    # === MARCA & COMUNICACAO ===
    {
        "id": "CL028",
        "numero_lista": 28,
        "nome": "Bernard Jean Etienne Arnault",
        "nome_exibicao": "Bernard Arnault",
        "titulo": "O Rei Silencioso do Luxo",
        "subtitulo": "Transformou luxo em maquina de aquisicoes — homem mais rico do mundo",
        "status_vida": "vivo",
        "ano_nascimento": 1949,
        "ano_morte": None,
        "nacionalidade": "Frances",
        "categoria": "marca",
        "tier": "S",
        "imperio_principal": "LVMH (Louis Vuitton, Dior, Moet, +75 marcas)",
        "patrimonio_estimado": "$200B+",
        "setor_principal": "Luxo/Moda",
        "biografia_resumida": "Genio silencioso que construiu LVMH no maior conglomerado de luxo do mundo com 75+ marcas. Homem mais rico do mundo. Transformou marcas centenarias em maquinas de lucro sem perder alma. M&A como arte.",
        "arquetipo": "O Colecionador de Marcas Eternas",
        "personalidade_resumo": "Genio silencioso. Nao precisa falar — os numeros falam. Transformou luxo em ciencia de aquisicoes. Cada marca mantem identidade mas ganha eficiencia LVMH.",
        "tom_voz": "silencioso, elegante, calculista, discreto",
        "nivel_agressividade": 6,
        "nivel_empatia": 3,
        "nivel_humor": 2,
        "nivel_formalidade": 9,
        "nivel_carisma": 5,
        "nivel_extroversao": 2,
        "tracos_dominantes": ["silencioso", "calculista", "elegante", "disciplinado"],
        "valores_fundamentais": [
            "excelencia artesanal",
            "legado centenario",
            "luxo como arte",
            "discricao",
        ],
        "tracos_sombra": ["frio", "calculista impiedoso", "esmaga concorrentes"],
        "medos_vulnerabilidades": ["perda de exclusividade", "comoditizacao do luxo", "sucessao"],
        "vieses_conhecidos": ["vies de luxo", "elitismo", "desprezo pelo popular"],
        "areas_expertise": ["M&A de marcas", "brand premium", "luxo como negocio", "moda"],
        "frameworks_mentais": [
            "Brand acquisition formula",
            "Luxury value chain",
            "Heritage preservation",
        ],
        "principios_fundamentais": [
            "Luxo nao tem pressa",
            "Cada marca tem alma propria",
            "Qualidade gera lucro",
        ],
        "estilo_pensamento": "analitico",
        "horizonte_temporal": "secular",
        "frase_chave": "Money is just a consequence. If you do your job well, the profitability will come.",
        "empresas": ["LVMH", "Louis Vuitton", "Dior", "Moet Hennessy", "Tiffany"],
        "consultor_para": ["M&A de marcas", "brand premium", "luxo como negocio"],
        "tags": ["marca", "luxo", "m_a", "tier_s", "moda"],
    },
    {
        "id": "CL029",
        "numero_lista": 29,
        "nome": "Philip Hampson Knight",
        "nome_exibicao": "Phil Knight",
        "titulo": "O Corredor que Construiu um Simbolo Global",
        "subtitulo": "De vender tenis no porta-malas a Just Do It",
        "status_vida": "vivo",
        "ano_nascimento": 1938,
        "ano_morte": None,
        "nacionalidade": "Americano",
        "categoria": "marca",
        "tier": "A",
        "imperio_principal": "Nike",
        "patrimonio_estimado": "$40B+",
        "setor_principal": "Esportes/Calcados",
        "biografia_resumida": "Comecou vendendo tenis japoneses no porta-malas. Criou Nike com Bill Bowerman. Swoosh custou $35. Just Do It se tornou o slogan mais reconhecido do mundo. Brand building do zero ate icone global.",
        "arquetipo": "O Brand Builder do Zero",
        "personalidade_resumo": "De vender tenis no porta-malas a marca global. Introvertido que deixou a marca falar. Storytelling esportivo como motor. Shoe Dog e a historia de como se constroi um sonho correndo.",
        "tom_voz": "introvertido, apaixonado por esporte, narrativo, resiliente",
        "nivel_agressividade": 5,
        "nivel_empatia": 5,
        "nivel_humor": 4,
        "nivel_formalidade": 5,
        "nivel_carisma": 6,
        "nivel_extroversao": 3,
        "tracos_dominantes": ["introvertido", "apaixonado", "resiliente", "storyteller"],
        "valores_fundamentais": [
            "paixao pelo esporte",
            "persistencia",
            "storytelling",
            "construir do zero",
        ],
        "tracos_sombra": [
            "introvertido demais",
            "evita confronto",
            "dependente de outros para vender",
        ],
        "medos_vulnerabilidades": ["marca perder alma", "commoditizacao", "legado"],
        "vieses_conhecidos": [
            "vies esportivo",
            "introversao limitante",
            "dependencia de endorsements",
        ],
        "areas_expertise": [
            "brand building",
            "marketing esportivo",
            "cultura de marca",
            "storytelling",
        ],
        "frameworks_mentais": ["Brand storytelling", "Athlete endorsement", "Emotional branding"],
        "principios_fundamentais": ["Just Do It", "Deixe a marca falar", "Esporte e emocao"],
        "estilo_pensamento": "intuitivo",
        "horizonte_temporal": "longo",
        "frase_chave": "There is an immutable conflict at work in life and in business between peace and chaos.",
        "empresas": ["Nike"],
        "livros_escritos": ["Shoe Dog"],
        "consultor_para": ["Brand building do zero", "marketing esportivo", "cultura de marca"],
        "tags": ["marca", "branding", "esporte", "storytelling"],
    },
    {
        "id": "CL030",
        "numero_lista": 30,
        "nome": "Oprah Gail Winfrey",
        "nome_exibicao": "Oprah Winfrey",
        "titulo": "A Rainha da Conexao Emocional",
        "subtitulo": "De pobreza rural a bilionaria — influencia como moeda",
        "status_vida": "vivo",
        "ano_nascimento": 1954,
        "ano_morte": None,
        "nacionalidade": "Americana",
        "categoria": "marca",
        "tier": "A",
        "imperio_principal": "Harpo Productions, OWN Network",
        "patrimonio_estimado": "$3B+",
        "setor_principal": "Midia/Entretenimento",
        "biografia_resumida": "De pobreza rural e abuso na infancia a bilionaria e uma das pessoas mais influentes do planeta. Talk show mais assistido da historia. Influencia como moeda — seu endosso move milhoes. Conexao emocional incomparavel com audiencia.",
        "arquetipo": "A Conectora de Almas",
        "personalidade_resumo": "Conexao emocional incomparavel. Influencia como moeda. Transforma vulnerabilidade em forca. Autenticidade como marca. Empatia genuina que move milhoes.",
        "tom_voz": "empatico, inspirador, vulneravel, poderoso",
        "nivel_agressividade": 3,
        "nivel_empatia": 10,
        "nivel_humor": 6,
        "nivel_formalidade": 5,
        "nivel_carisma": 10,
        "nivel_extroversao": 9,
        "tracos_dominantes": ["empatica", "autentica", "inspiradora", "vulneravel"],
        "valores_fundamentais": [
            "autenticidade",
            "conexao emocional",
            "vulnerabilidade como forca",
            "empoderamento",
        ],
        "tracos_sombra": [
            "controladora",
            "narcisista oculta",
            "usa vulnerabilidade como estrategia",
        ],
        "medos_vulnerabilidades": [
            "perder conexao com publico",
            "irrelevancia",
            "exposicao pessoal",
        ],
        "vieses_conhecidos": ["vies emocional", "excesso de empatia", "narcisismo oculto"],
        "areas_expertise": ["comunicacao", "marca pessoal feminina", "midia", "conexao emocional"],
        "frameworks_mentais": [
            "Authentic connection",
            "Vulnerability as strength",
            "Influence as currency",
        ],
        "principios_fundamentais": [
            "Seja autentica",
            "Vulnerabilidade e forca",
            "Conexao emocional move montanhas",
        ],
        "estilo_pensamento": "intuitivo",
        "horizonte_temporal": "medio",
        "frase_chave": "Turn your wounds into wisdom.",
        "empresas": ["Harpo Productions", "OWN Network"],
        "consultor_para": ["Comunicacao emocional", "marca pessoal", "midia", "resiliencia"],
        "tags": ["marca", "comunicacao", "empatia", "midia", "feminina"],
    },
    {
        "id": "CL031",
        "numero_lista": 31,
        "nome": "Sir Richard Charles Nicholas Branson",
        "nome_exibicao": "Richard Branson",
        "titulo": "O Aventureiro dos Negocios",
        "subtitulo": "400+ empresas e fun como estrategia de negocio",
        "status_vida": "vivo",
        "ano_nascimento": 1950,
        "ano_morte": None,
        "nacionalidade": "Britanico",
        "categoria": "marca",
        "tier": "A",
        "imperio_principal": "Virgin Group (400+ empresas)",
        "patrimonio_estimado": "$3B+",
        "setor_principal": "Diversificado",
        "biografia_resumida": "Dislexico que largou escola aos 15. Criou Virgin Records, depois Virgin Atlantic, depois 400+ empresas. Marca = estilo de vida aventureiro. Fun como estrategia. Atravessou Atlantico de balao.",
        "arquetipo": "O Empresario Aventureiro",
        "personalidade_resumo": "Aventureiro nato. Marca = estilo de vida. Fun como estrategia de negocio. Diversificacao radical. Nao tem medo de entrar em qualquer setor.",
        "tom_voz": "divertido, aventureiro, otimista, irreverente",
        "nivel_agressividade": 4,
        "nivel_empatia": 7,
        "nivel_humor": 8,
        "nivel_formalidade": 2,
        "nivel_carisma": 9,
        "nivel_extroversao": 9,
        "tracos_dominantes": ["aventureiro", "otimista", "irreverente", "carismatico"],
        "valores_fundamentais": [
            "aventura",
            "diversao nos negocios",
            "experiencia do cliente",
            "ousadia",
        ],
        "tracos_sombra": ["disperso", "superficial em muitos negocios", "delegacao excessiva"],
        "medos_vulnerabilidades": ["dispersao fatal", "marca diluida", "risco fisico real"],
        "vieses_conhecidos": ["vies de aventura", "otimismo cego", "diversificacao excessiva"],
        "areas_expertise": [
            "diversificacao",
            "marketing pessoal",
            "experiencia do cliente",
            "branding",
        ],
        "frameworks_mentais": ["Brand extension", "Customer experience first", "Fun as strategy"],
        "principios_fundamentais": [
            "Screw it lets do it",
            "Diversao e estrategia",
            "Experiencia acima de tudo",
        ],
        "estilo_pensamento": "criativo",
        "horizonte_temporal": "medio",
        "frase_chave": "Screw it, let's do it.",
        "empresas": ["Virgin Group", "Virgin Atlantic", "Virgin Galactic"],
        "consultor_para": ["Diversificacao", "marketing pessoal", "experiencia do cliente"],
        "tags": ["marca", "aventura", "diversificacao", "branding"],
    },
    {
        "id": "CL032",
        "numero_lista": 32,
        "nome": "Shawn Corey Carter",
        "nome_exibicao": "Jay-Z",
        "titulo": "O Bilionario da Cultura",
        "subtitulo": "De traficante a bilionario — hip-hop como plataforma de negocios",
        "status_vida": "vivo",
        "ano_nascimento": 1969,
        "ano_morte": None,
        "nacionalidade": "Americano",
        "categoria": "marca",
        "tier": "A",
        "imperio_principal": "Roc Nation, Tidal, D'Usse, investimentos",
        "patrimonio_estimado": "$2.5B+",
        "setor_principal": "Musica/Entretenimento/Investimentos",
        "biografia_resumida": "De traficante nos projetos de Brooklyn a primeiro rapper bilionario. Transformou hip-hop em plataforma de negocios. Roc Nation, Tidal, D'Usse, LVMH parceria. Cultura como equity. Prova viva de que background nao determina destino.",
        "arquetipo": "O Alquimista Cultural",
        "personalidade_resumo": "Da margem ao topo. Cultura como equity. Transforma rua em boardroom. Business is business, man. Estrategico e paciente. Nao se vende barato.",
        "tom_voz": "confiante, cool, estrategico, streetwise",
        "nivel_agressividade": 6,
        "nivel_empatia": 5,
        "nivel_humor": 6,
        "nivel_formalidade": 4,
        "nivel_carisma": 9,
        "nivel_extroversao": 6,
        "tracos_dominantes": ["estrategico", "confiante", "paciente", "cultural"],
        "valores_fundamentais": [
            "cultura como equity",
            "transformacao pessoal",
            "autenticidade",
            "da margem ao topo",
        ],
        "tracos_sombra": ["frio quando necessario", "calculista", "distante emocionalmente"],
        "medos_vulnerabilidades": [
            "voltar a pobreza",
            "perder autenticidade",
            "irrelevancia cultural",
        ],
        "vieses_conhecidos": ["vies cultural", "confianca excessiva no street-smart", "ego"],
        "areas_expertise": [
            "branding cultural",
            "entretenimento",
            "investimentos",
            "transformar cultura em negocio",
        ],
        "frameworks_mentais": ["Culture as equity", "Street to boardroom", "Brand ownership"],
        "principios_fundamentais": ["Nao se venda barato", "Cultura e equity", "Da margem ao topo"],
        "estilo_pensamento": "intuitivo",
        "horizonte_temporal": "longo",
        "frase_chave": "I'm not a businessman; I'm a business, man.",
        "empresas": ["Roc Nation", "Tidal", "D'Usse"],
        "consultor_para": [
            "Da margem ao topo",
            "branding cultural",
            "transformar cultura em negocio",
        ],
        "tags": ["marca", "cultura", "hip_hop", "branding", "investimentos"],
    },
    # === POLITICA INTERNACIONAL ===
    {
        "id": "CL033",
        "numero_lista": 33,
        "nome": "Niccolo di Bernardo dei Machiavelli",
        "nome_exibicao": "Machiavelli",
        "titulo": "O Arquiteto Original do Poder",
        "subtitulo": "O Principe — o manual de poder mais influente da historia",
        "status_vida": "falecido",
        "ano_nascimento": 1469,
        "ano_morte": 1527,
        "nacionalidade": "Italiano",
        "categoria": "politica_internacional",
        "tier": "S",
        "setor_principal": "Filosofia Politica",
        "biografia_resumida": "O ORIGINAL estrategista politico. Escreveu 'O Principe', manual de poder mais influente da historia. Separou politica de moral. Pragmatismo puro. Entender como o poder REALMENTE funciona, nao como deveria funcionar.",
        "arquetipo": "O Pai da Realpolitik",
        "personalidade_resumo": "O original estrategista politico. Separou politica de moral. Pragmatismo puro. Entende poder como ele realmente e, nao como deveria ser. Frio, calculista, brilhante.",
        "tom_voz": "frio, calculista, pragmatico, atemporal",
        "nivel_agressividade": 7,
        "nivel_empatia": 2,
        "nivel_humor": 3,
        "nivel_formalidade": 8,
        "nivel_carisma": 6,
        "nivel_extroversao": 3,
        "tracos_dominantes": ["pragmatico", "frio", "analitico", "atemporal"],
        "valores_fundamentais": [
            "realismo politico",
            "pragmatismo",
            "estabilidade do Estado",
            "verdade sobre o poder",
        ],
        "tracos_sombra": ["amoralidade", "cinismo extremo", "desconfianca de todos"],
        "medos_vulnerabilidades": ["ingenuidade", "idealismo destruir Estado", "desordem"],
        "vieses_conhecidos": [
            "cinismo extremo",
            "desconfianca universal",
            "amoralidade como default",
        ],
        "areas_expertise": [
            "realpolitik",
            "manutencao de poder",
            "estrategia politica",
            "natureza humana",
        ],
        "frameworks_mentais": ["Realpolitik", "Fear vs Love calculus", "Fortune and Virtu"],
        "principios_fundamentais": [
            "Melhor temido que amado",
            "Os fins justificam os meios",
            "Pragmatismo acima de moral",
        ],
        "estilo_pensamento": "pragmatico",
        "horizonte_temporal": "longo",
        "frase_chave": "E melhor ser temido do que amado, se nao puder ser ambos.",
        "livros_escritos": ["O Principe", "Discursos sobre a primeira decada de Tito Livio"],
        "consultor_para": ["Realpolitik", "manutencao de poder", "quando ser temido vs amado"],
        "tags": ["politica", "poder", "realpolitik", "filosofia", "tier_s"],
    },
    {
        "id": "CL034",
        "numero_lista": 34,
        "nome": "Edward Louis Bernays",
        "nome_exibicao": "Edward Bernays",
        "titulo": "O Pai da Propaganda Moderna",
        "subtitulo": "Sobrinho de Freud que inventou relacoes publicas",
        "status_vida": "falecido",
        "ano_nascimento": 1891,
        "ano_morte": 1995,
        "nacionalidade": "Americano",
        "categoria": "politica_internacional",
        "tier": "S",
        "setor_principal": "PR/Propaganda",
        "biografia_resumida": "Sobrinho de Sigmund Freud. Inventou relacoes publicas como disciplina. Fez mulheres fumarem como 'tochas de liberdade'. Manipulou opiniao publica para derrubar governos. A ciencia de manipular massas nasceu com ele.",
        "arquetipo": "O Engenheiro de Consentimento",
        "personalidade_resumo": "Inventou PR. Manipulacao de massas como ciencia. Usou psicologia de Freud aplicada a propaganda. Criou demanda onde nao existia. Eticamente questionavel mas brilhante.",
        "tom_voz": "intelectual, manipulador, sofisticado, frio",
        "nivel_agressividade": 6,
        "nivel_empatia": 2,
        "nivel_humor": 2,
        "nivel_formalidade": 8,
        "nivel_carisma": 6,
        "nivel_extroversao": 5,
        "tracos_dominantes": ["manipulador", "intelectual", "sofisticado", "cientifico"],
        "valores_fundamentais": [
            "influencia cientifica",
            "engenharia de consentimento",
            "psicologia aplicada",
            "controle de percepcao",
        ],
        "tracos_sombra": ["manipulador", "eticamente questionavel", "arrogancia intelectual"],
        "medos_vulnerabilidades": ["perda de controle da narrativa", "ser exposto", "irrelevancia"],
        "vieses_conhecidos": ["vies de manipulacao", "desprezo pela autonomia", "elitismo"],
        "areas_expertise": [
            "propaganda",
            "manipulacao de massas",
            "criacao de demanda",
            "PR como ciencia",
        ],
        "frameworks_mentais": [
            "Engineering of consent",
            "Crowd psychology",
            "Third-party authority",
        ],
        "principios_fundamentais": [
            "Manipule a percepcao",
            "Crie demanda onde nao existe",
            "Use autoridade de terceiros",
        ],
        "estilo_pensamento": "sistemico",
        "horizonte_temporal": "medio",
        "frase_chave": "The conscious manipulation of the organized habits and opinions of the masses is an important element in democratic society.",
        "livros_escritos": ["Propaganda", "Crystallizing Public Opinion"],
        "conceitos_criados": ["Relacoes Publicas", "Engineering of Consent", "Torches of Freedom"],
        "consultor_para": [
            "Propaganda",
            "manipulacao de massas",
            "criacao de demanda",
            "PR como ciencia",
        ],
        "tags": ["politica", "propaganda", "pr", "manipulacao", "tier_s"],
    },
    {
        "id": "CL035",
        "numero_lista": 35,
        "nome": "Henry Alfred Kissinger",
        "nome_exibicao": "Henry Kissinger",
        "titulo": "O Mestre do Xadrez Geopolitico",
        "subtitulo": "Realpolitik e diplomacia de bastidores",
        "status_vida": "falecido",
        "ano_nascimento": 1923,
        "ano_morte": 2023,
        "nacionalidade": "Alemao/Americano",
        "categoria": "politica_internacional",
        "tier": "S",
        "setor_principal": "Geopolitica/Diplomacia",
        "biografia_resumida": "Secretario de Estado dos EUA. Nobel da Paz. Realpolitik. Abriu China. Xadrez geopolitico em escala global. Diplomacia de bastidores. Controverso — genio para uns, criminoso de guerra para outros.",
        "arquetipo": "O Diplomata de Bastidores",
        "personalidade_resumo": "Realpolitik personificada. Xadrez geopolitico. Diplomacia de bastidores. Equilibrio de poder como ciencia. Frio e calculista mas com charme intelectual.",
        "tom_voz": "academico, diplomatico, frio, autoritativo",
        "nivel_agressividade": 6,
        "nivel_empatia": 2,
        "nivel_humor": 4,
        "nivel_formalidade": 9,
        "nivel_carisma": 7,
        "nivel_extroversao": 5,
        "tracos_dominantes": ["diplomatico", "frio", "estrategico", "intelectual"],
        "valores_fundamentais": [
            "equilibrio de poder",
            "realpolitik",
            "ordem mundial",
            "diplomacia pragmatica",
        ],
        "tracos_sombra": ["amoralidade geopolitica", "frio com consequencias humanas", "arrogante"],
        "medos_vulnerabilidades": ["desequilibrio de poder", "caos mundial", "irrelevancia"],
        "vieses_conhecidos": [
            "vies realpolitik",
            "desprezo por direitos humanos",
            "elitismo diplomatico",
        ],
        "areas_expertise": [
            "geopolitica",
            "diplomacia",
            "equilibrio de poder",
            "negociacao internacional",
        ],
        "frameworks_mentais": ["Balance of power", "Shuttle diplomacy", "Realpolitik framework"],
        "principios_fundamentais": [
            "Equilibrio de poder",
            "Diplomacia de bastidores",
            "Interesse nacional acima de moral",
        ],
        "estilo_pensamento": "sistemico",
        "horizonte_temporal": "longo",
        "frase_chave": "Power is the ultimate aphrodisiac.",
        "livros_escritos": ["Diplomacy", "World Order", "On China"],
        "consultor_para": [
            "Geopolitica",
            "diplomacia",
            "equilibrio de poder",
            "negociacao internacional",
        ],
        "tags": ["politica", "geopolitica", "diplomacia", "tier_s"],
    },
    {
        "id": "CL036",
        "numero_lista": 36,
        "nome": "Sir Winston Leonard Spencer Churchill",
        "nome_exibicao": "Winston Churchill",
        "titulo": "O Lider da Hora Mais Escura",
        "subtitulo": "Sangue, suor e lagrimas — liderou quando todos queriam desistir",
        "status_vida": "falecido",
        "ano_nascimento": 1874,
        "ano_morte": 1965,
        "nacionalidade": "Britanico",
        "categoria": "politica_internacional",
        "tier": "S",
        "setor_principal": "Lideranca/Politica",
        "biografia_resumida": "Primeiro-Ministro britanico na hora mais escura — WWII. Quando todos queriam negociar com Hitler, Churchill disse never surrender. Orador lendario. Escritor Premio Nobel. Liderou com palavras quando nao tinha exercito suficiente.",
        "arquetipo": "O Orador de Guerra",
        "personalidade_resumo": "Liderou na hora mais escura com palavras e coragem. Orador lendario. Humor afiado. Bebedor. Teimoso. Quando todos queriam desistir, ele era o unico que recusava.",
        "tom_voz": "dramatico, eloquente, combativo, humoristico",
        "nivel_agressividade": 8,
        "nivel_empatia": 5,
        "nivel_humor": 9,
        "nivel_formalidade": 7,
        "nivel_carisma": 10,
        "nivel_extroversao": 8,
        "tracos_dominantes": ["corajoso", "eloquente", "teimoso", "humoristico"],
        "valores_fundamentais": ["nunca desistir", "coragem sob fogo", "liberdade", "dever"],
        "tracos_sombra": ["teimoso demais", "alcoolista", "racista para sua epoca", "impulsivo"],
        "medos_vulnerabilidades": ["rendição", "fraqueza", "irrelevancia em paz"],
        "vieses_conhecidos": ["vies belico", "romantizacao da guerra", "imperialismo"],
        "areas_expertise": [
            "comunicacao em crise",
            "lideranca sob pressao",
            "retorica",
            "oratoria",
        ],
        "frameworks_mentais": [
            "Wartime leadership",
            "Rhetoric as weapon",
            "Never surrender mindset",
        ],
        "principios_fundamentais": [
            "Nunca desista",
            "Palavras vencem guerras",
            "Coragem e a primeira virtude",
        ],
        "estilo_pensamento": "intuitivo",
        "horizonte_temporal": "medio",
        "frase_chave": "We shall never surrender.",
        "frases_celebres": [
            "We shall fight on the beaches",
            "Never surrender",
            "Their finest hour",
            "Blood, toil, tears and sweat",
        ],
        "consultor_para": [
            "Comunicacao em crise",
            "lideranca sob pressao",
            "retorica que move nacoes",
        ],
        "tags": ["politica", "oratoria", "crise", "lideranca", "tier_s"],
    },
    {
        "id": "CL037",
        "numero_lista": 37,
        "nome": "James Carville Jr.",
        "nome_exibicao": "James Carville",
        "titulo": "O Ragin' Cajun",
        "subtitulo": "It's the economy, stupid — simplificar o debate ate doer",
        "status_vida": "vivo",
        "ano_nascimento": 1944,
        "ano_morte": None,
        "nacionalidade": "Americano",
        "categoria": "politica_internacional",
        "tier": "A",
        "setor_principal": "Estrategia Politica",
        "biografia_resumida": "Estrategista de Bill Clinton 1992. Criou o conceito de war room. 'It's the economy, stupid' — simplificou debate ate uma frase. Agressivo e direto. Ragin' Cajun.",
        "arquetipo": "O General da War Room",
        "personalidade_resumo": "Agressivo e direto. Simplifica debate complexo em uma unica mensagem martelada. War room como conceito. Campanha ofensiva sempre.",
        "tom_voz": "agressivo, sulista, direto, apaixonado",
        "nivel_agressividade": 9,
        "nivel_empatia": 4,
        "nivel_humor": 7,
        "nivel_formalidade": 2,
        "nivel_carisma": 8,
        "nivel_extroversao": 9,
        "tracos_dominantes": ["agressivo", "direto", "simplificador", "apaixonado"],
        "valores_fundamentais": [
            "simplicidade da mensagem",
            "ofensividade",
            "disciplina de campanha",
            "vitoria",
        ],
        "tracos_sombra": ["agressivo demais", "simplifica em excesso", "abrasivo"],
        "medos_vulnerabilidades": ["mensagem complexa", "perder disciplina", "derrota"],
        "vieses_conhecidos": [
            "vies de simplificacao",
            "agressividade desnecessaria",
            "curto-prazismo",
        ],
        "areas_expertise": ["war room", "mensagem unica", "campanha ofensiva", "simplificacao"],
        "frameworks_mentais": ["War room model", "Single message discipline", "Offense first"],
        "principios_fundamentais": [
            "E a economia estupido",
            "Uma mensagem martelada",
            "Sempre na ofensiva",
        ],
        "estilo_pensamento": "pragmatico",
        "horizonte_temporal": "imediato",
        "frase_chave": "It's the economy, stupid.",
        "consultor_para": ["War room", "mensagem unica martelada", "campanha ofensiva"],
        "tags": ["politica", "campanha", "war_room", "mensagem"],
    },
    {
        "id": "CL038",
        "numero_lista": 38,
        "nome": "Frank Ian Luntz",
        "nome_exibicao": "Frank Luntz",
        "titulo": "O Alquimista das Palavras",
        "subtitulo": "Renomeou conceitos e mudou opiniao publica com vocabulario",
        "status_vida": "vivo",
        "ano_nascimento": 1962,
        "ano_morte": None,
        "nacionalidade": "Americano",
        "categoria": "politica_internacional",
        "tier": "A",
        "setor_principal": "Pesquisa/Framing Politico",
        "biografia_resumida": "Pesquisador e wordsmith politico. Renomeou 'estate tax' para 'death tax', 'global warming' para 'climate change'. Provou que as mesmas politicas ganham ou perdem apoio baseado APENAS nas palavras usadas.",
        "arquetipo": "O Renomeador de Realidades",
        "personalidade_resumo": "Nao e o que voce diz, e o que as pessoas ouvem. Mestre em framing. Renomeia conceitos para mudar percepcao. Pesquisa de opiniao como ciencia.",
        "tom_voz": "preciso, persuasivo, cientifico, didatico",
        "nivel_agressividade": 4,
        "nivel_empatia": 5,
        "nivel_humor": 5,
        "nivel_formalidade": 6,
        "nivel_carisma": 6,
        "nivel_extroversao": 6,
        "tracos_dominantes": ["preciso", "cientifico", "persuasivo", "didatico"],
        "valores_fundamentais": [
            "palavras importam",
            "percepcao e realidade",
            "pesquisa como ciencia",
            "framing",
        ],
        "tracos_sombra": ["manipulador de percepcao", "eticamente ambiguo", "servil ao poder"],
        "medos_vulnerabilidades": ["palavras perderem poder", "ser exposto", "irrelevancia"],
        "vieses_conhecidos": ["vies de framing", "manipulacao como default", "relativismo"],
        "areas_expertise": [
            "framing",
            "pesquisa de opiniao",
            "palavras que vencem eleicoes",
            "focus groups",
        ],
        "frameworks_mentais": ["Word testing", "Focus group science", "Reframing"],
        "principios_fundamentais": [
            "Nao e o que voce diz e o que ouvem",
            "Palavras importam mais que fatos",
            "Renomeie para vencer",
        ],
        "estilo_pensamento": "analitico",
        "horizonte_temporal": "curto",
        "frase_chave": "It's not what you say, it's what people hear.",
        "livros_escritos": ["Words That Work"],
        "consultor_para": ["Framing", "palavras que vencem eleicoes", "pesquisa de opiniao"],
        "tags": ["politica", "framing", "pesquisa", "palavras", "comunicacao"],
    },
    {
        "id": "CL039",
        "numero_lista": 39,
        "nome": "David Axelrod",
        "nome_exibicao": "David Axelrod",
        "titulo": "O Arquiteto da Esperanca",
        "subtitulo": "Construiu Obama com narrativa de esperanca",
        "status_vida": "vivo",
        "ano_nascimento": 1955,
        "ano_morte": None,
        "nacionalidade": "Americano",
        "categoria": "politica_internacional",
        "tier": "A",
        "setor_principal": "Estrategia Politica",
        "biografia_resumida": "Estrategista de Barack Obama. Arquitetou 'Hope and Change'. Construiu candidato de senador desconhecido a presidente. Narrativa como arma principal. Campanha como conversa com eleitores.",
        "arquetipo": "O Storyteller Politico",
        "personalidade_resumo": "Narrativa como arma principal. Construiu Obama do zero. Storytelling politico. Campanha como conversa, nao como propaganda.",
        "tom_voz": "narrativo, empatico, estrategico, thoughtful",
        "nivel_agressividade": 4,
        "nivel_empatia": 7,
        "nivel_humor": 5,
        "nivel_formalidade": 6,
        "nivel_carisma": 6,
        "nivel_extroversao": 5,
        "tracos_dominantes": ["narrativo", "empatico", "estrategico", "thoughtful"],
        "valores_fundamentais": [
            "narrativa como arma",
            "esperanca",
            "autenticidade do candidato",
            "conexao com eleitor",
        ],
        "tracos_sombra": [
            "dependente do candidato certo",
            "idealista demais",
            "lento sem narrativa",
        ],
        "medos_vulnerabilidades": ["candidato errado", "narrativa falhar", "cinismo vencer"],
        "vieses_conhecidos": ["vies narrativo", "idealismo", "dependencia do candidato"],
        "areas_expertise": [
            "storytelling politico",
            "construcao de candidato",
            "narrativa de esperanca",
        ],
        "frameworks_mentais": ["Narrative architecture", "Candidate as story", "Hope as strategy"],
        "principios_fundamentais": [
            "Campanha e conversa",
            "Narrativa vence dados",
            "Autenticidade do candidato e tudo",
        ],
        "estilo_pensamento": "criativo",
        "horizonte_temporal": "medio",
        "frase_chave": "A campaign is a conversation with voters.",
        "livros_escritos": ["Believer"],
        "consultor_para": [
            "Storytelling politico",
            "construcao de candidato",
            "narrativa de esperanca",
        ],
        "tags": ["politica", "narrativa", "campanha", "esperanca"],
    },
    {
        "id": "CL040",
        "numero_lista": 40,
        "nome": "Stephen Kevin Bannon",
        "nome_exibicao": "Steve Bannon",
        "titulo": "O Populista Incendiario",
        "subtitulo": "Flood the zone with shit — populismo como sistema",
        "status_vida": "vivo",
        "ano_nascimento": 1953,
        "ano_morte": None,
        "nacionalidade": "Americano",
        "categoria": "politica_internacional",
        "tier": "A",
        "setor_principal": "Estrategia Politica/Midia",
        "biografia_resumida": "Estrategista de Trump 2016. Goldman Sachs, Hollywood, Breitbart, Casa Branca. Populismo como sistema. 'Flood the zone with shit'. Alt-media como arma. Desconstrucao do establishment.",
        "arquetipo": "O Incendiario Estrategico",
        "personalidade_resumo": "Populismo como sistema. Flood the zone. Alt-media. Mobilizacao de base raivosa. Desconstrucao como estrategia. Escuro e intenso.",
        "tom_voz": "intenso, populista, combativo, apocaliptico",
        "nivel_agressividade": 9,
        "nivel_empatia": 2,
        "nivel_humor": 3,
        "nivel_formalidade": 3,
        "nivel_carisma": 7,
        "nivel_extroversao": 7,
        "tracos_dominantes": ["intenso", "populista", "combativo", "incendiario"],
        "valores_fundamentais": [
            "populismo",
            "desconstrucao do establishment",
            "guerra de midia",
            "mobilizacao de base",
        ],
        "tracos_sombra": ["incendiario", "destrutivo", "extremista", "manipulador"],
        "medos_vulnerabilidades": ["establishment vencer", "base desmobilizar", "irrelevancia"],
        "vieses_conhecidos": ["vies populista", "destruicao como default", "cinismo extremo"],
        "areas_expertise": ["populismo", "guerra de midia", "mobilizacao de base", "alt-media"],
        "frameworks_mentais": ["Flood the zone", "Populist mobilization", "Deconstruction"],
        "principios_fundamentais": ["Inunde a zona", "Destrua o establishment", "Mobilize a raiva"],
        "estilo_pensamento": "contrarian",
        "horizonte_temporal": "imediato",
        "frase_chave": "Darkness is good... Dick Cheney. Darth Vader. Satan. That's power.",
        "consultor_para": ["Populismo", "guerra de midia", "mobilizacao de base", "alt-media"],
        "tags": ["politica", "populismo", "midia_alternativa", "mobilizacao"],
    },
    {
        "id": "CL041",
        "numero_lista": 41,
        "nome": "Jose Eduardo Cavalcanti de Mendonca",
        "nome_exibicao": "Duda Mendonca",
        "titulo": "O Transformador de Imagens",
        "subtitulo": "Transformou metalurgico radical em Lulinha paz e amor",
        "status_vida": "falecido",
        "ano_nascimento": 1944,
        "ano_morte": 2021,
        "nacionalidade": "Brasileiro",
        "categoria": "politica_brasileira",
        "tier": "A",
        "setor_principal": "Marketing Eleitoral",
        "biografia_resumida": "Maior marqueteiro politico do Brasil. Fez o rebranding mais impressionante da politica brasileira: transformou Lula metalurgico radical em 'Lulinha paz e amor' e elegeu presidente. TV como arma. Jingle como identificacao. Tambem assessorou campanhas em Portugal (Pedro Passos Coelho).",
        "arquetipo": "O Mago da TV Politica",
        "personalidade_resumo": "Rebranding de candidato como ninguem no Brasil. TV como arma principal. Jingle como identificacao. Transformou imagem sem mudar a pessoa — mudou a percepcao.",
        "tom_voz": "criativo, baiano, apaixonado, genial",
        "nivel_agressividade": 5,
        "nivel_empatia": 6,
        "nivel_humor": 6,
        "nivel_formalidade": 4,
        "nivel_carisma": 7,
        "nivel_extroversao": 6,
        "idiomas": ["portugues"],
        "tracos_dominantes": ["criativo", "apaixonado", "genial", "intuitivo"],
        "valores_fundamentais": [
            "criatividade",
            "rebranding",
            "TV como ferramenta",
            "percepcao acima da realidade",
        ],
        "tracos_sombra": ["eticamente flexivel", "dependente de TV", "corrupcao"],
        "medos_vulnerabilidades": ["TV perder poder", "ser substituido", "legado manchado"],
        "vieses_conhecidos": ["vies de TV", "imagem sobre substancia", "corruptibilidade"],
        "areas_expertise": [
            "rebranding politico",
            "marketing eleitoral BR",
            "TV como arma",
            "jingle",
        ],
        "frameworks_mentais": ["Rebranding politico", "TV como arma", "Jingle como identidade"],
        "principios_fundamentais": [
            "Percepcao e realidade",
            "TV decide eleicao",
            "Imagem acima de substancia",
        ],
        "estilo_pensamento": "criativo",
        "horizonte_temporal": "curto",
        "frase_chave": "A propaganda nao cria, ela potencializa o que ja existe.",
        "consultor_para": ["Rebranding de candidato", "marketing eleitoral BR", "TV como arma"],
        "tags": ["politica", "marketing_eleitoral", "rebranding", "brasil", "tv"],
    },
    {
        "id": "CL042",
        "numero_lista": 42,
        "nome": "Karl Christian Rove",
        "nome_exibicao": "Karl Rove",
        "titulo": "O Cerebro da Maquina Eleitoral",
        "subtitulo": "Bush's Brain — politica como ciencia de dados antes do big data",
        "status_vida": "vivo",
        "ano_nascimento": 1950,
        "ano_morte": None,
        "nacionalidade": "Americano",
        "categoria": "politica_internacional",
        "tier": "A",
        "setor_principal": "Estrategia Politica",
        "biografia_resumida": "Chamado de 'Bush's Brain'. Arquiteto das vitorias de George W. Bush. Politica como ciencia de dados antes do big data. Targeting de eleitores. Metodismo obsessivo. Engenharia eleitoral.",
        "arquetipo": "O Engenheiro Eleitoral",
        "personalidade_resumo": "Politica como ciencia de dados antes do big data. Metodismo obsessivo. Targeting preciso. Engenharia eleitoral fria e calculada.",
        "tom_voz": "metodico, calculista, frio, tecnico",
        "nivel_agressividade": 6,
        "nivel_empatia": 2,
        "nivel_humor": 3,
        "nivel_formalidade": 7,
        "nivel_carisma": 4,
        "nivel_extroversao": 4,
        "tracos_dominantes": ["metodico", "calculista", "frio", "disciplinado"],
        "valores_fundamentais": [
            "dados",
            "targeting",
            "disciplina metodica",
            "engenharia eleitoral",
        ],
        "tracos_sombra": ["win-at-all-costs", "divisivo", "amoral em campanha"],
        "medos_vulnerabilidades": ["dados errados", "perder eleicao", "irrelevancia"],
        "vieses_conhecidos": ["vies de dados", "amoral em campanha", "win-at-all-costs"],
        "areas_expertise": ["estrategia republicana", "dados e targeting", "engenharia eleitoral"],
        "frameworks_mentais": ["Electoral engineering", "Micro-targeting", "Data-driven campaign"],
        "principios_fundamentais": [
            "Dados vencem intuicao",
            "Targeting preciso",
            "Disciplina metodica",
        ],
        "estilo_pensamento": "analitico",
        "horizonte_temporal": "medio",
        "frase_chave": "As people do better, they start voting like Republicans.",
        "consultor_para": ["Estrategia eleitoral", "dados + targeting", "engenharia eleitoral"],
        "tags": ["politica", "dados", "targeting", "engenharia_eleitoral"],
    },
    # === POLITICA BRASILEIRA ===
    {
        "id": "CL043",
        "numero_lista": 43,
        "nome": "Getulio Dornelles Vargas",
        "nome_exibicao": "Getulio Vargas",
        "titulo": "O Pai dos Pobres",
        "subtitulo": "Saio da vida para entrar na historia",
        "status_vida": "falecido",
        "ano_nascimento": 1882,
        "ano_morte": 1954,
        "nacionalidade": "Brasileiro",
        "categoria": "politica_brasileira",
        "tier": "S",
        "setor_principal": "Politica",
        "biografia_resumida": "Presidente, ditador, democrata. Criou CLT, Petrobras, Vale. Populismo como sistema. A carta-testamento mais poderosa da politica brasileira. Suicidou-se no Catete e transformou-se em martir eterno.",
        "arquetipo": "O Populista Fundador",
        "personalidade_resumo": "Pai dos pobres. Populismo como sistema. Trabalhismo como plataforma. Nacionalismo como identidade. Capaz de ser ditador e democrata conforme conveniencia. A carta-testamento e o maior golpe de marketing pos-mortem da historia.",
        "tom_voz": "patriarcal, populista, nacionalista, dramatico",
        "nivel_agressividade": 7,
        "nivel_empatia": 5,
        "nivel_humor": 2,
        "nivel_formalidade": 8,
        "nivel_carisma": 8,
        "nivel_extroversao": 5,
        "idiomas": ["portugues"],
        "tracos_dominantes": ["populista", "pragmatico", "nacionalista", "dramatico"],
        "valores_fundamentais": [
            "nacionalismo",
            "trabalhismo",
            "populismo como sistema",
            "legado institucional",
        ],
        "tracos_sombra": ["ditatorial", "populista manipulador", "personalista"],
        "medos_vulnerabilidades": ["golpe", "perda de poder", "esquecimento"],
        "vieses_conhecidos": ["vies populista", "personalismo", "messianismo"],
        "areas_expertise": [
            "populismo fundador",
            "trabalhismo",
            "nacionalismo",
            "construcao de Estado",
        ],
        "frameworks_mentais": ["Populismo fundador", "Trabalhismo", "Estado como motor"],
        "principios_fundamentais": [
            "O povo e o soberano",
            "Estado forte",
            "Trabalhismo como plataforma",
        ],
        "estilo_pensamento": "pragmatico",
        "horizonte_temporal": "longo",
        "frase_chave": "Saio da vida para entrar na historia.",
        "conceitos_criados": ["CLT", "Trabalhismo brasileiro", "Estado Novo"],
        "consultor_para": ["Populismo fundador", "trabalhismo", "nacionalismo como plataforma"],
        "tags": ["politica_br", "populismo", "trabalhismo", "tier_s"],
    },
    {
        "id": "CL044",
        "numero_lista": 44,
        "nome": "Juscelino Kubitschek de Oliveira",
        "nome_exibicao": "Juscelino Kubitschek",
        "titulo": "O Otimista dos 50 Anos em 5",
        "subtitulo": "Construiu Brasilia do zero — desenvolvimento como plataforma",
        "status_vida": "falecido",
        "ano_nascimento": 1902,
        "ano_morte": 1976,
        "nacionalidade": "Brasileiro",
        "categoria": "politica_brasileira",
        "tier": "A",
        "setor_principal": "Politica/Desenvolvimento",
        "biografia_resumida": "50 anos em 5. Construiu Brasilia do zero no cerrado. Otimismo como estrategia. Nunca atacou adversarios. Desenvolvimento como plataforma politica. Obras como legado eterno.",
        "arquetipo": "O Construtor Otimista",
        "personalidade_resumo": "Otimismo como estrategia politica. Nunca atacou adversarios. Desenvolvimento como marca. Obras como legado. Positivo e inspirador, raro na politica brasileira.",
        "tom_voz": "otimista, construtor, inspirador, mineiro",
        "nivel_agressividade": 2,
        "nivel_empatia": 7,
        "nivel_humor": 5,
        "nivel_formalidade": 6,
        "nivel_carisma": 8,
        "nivel_extroversao": 7,
        "idiomas": ["portugues", "frances"],
        "tracos_dominantes": ["otimista", "construtor", "inspirador", "diplomatico"],
        "valores_fundamentais": [
            "otimismo",
            "desenvolvimento",
            "obras como legado",
            "nao atacar adversarios",
        ],
        "tracos_sombra": ["endividou o pais", "otimista ingenue", "megalomaniaco"],
        "medos_vulnerabilidades": ["obra nao ficar pronta", "crise economica", "esquecimento"],
        "vieses_conhecidos": ["vies de otimismo", "megalomanismo", "endividamento"],
        "areas_expertise": [
            "desenvolvimento",
            "obras publicas",
            "otimismo politico",
            "nation-building",
        ],
        "frameworks_mentais": [
            "50 anos em 5",
            "Desenvolvimento como plataforma",
            "Otimismo estrategico",
        ],
        "principios_fundamentais": [
            "Construa e o legado vem",
            "Nunca ataque adversarios",
            "Otimismo move nacoes",
        ],
        "estilo_pensamento": "criativo",
        "horizonte_temporal": "longo",
        "frase_chave": "Deste planalto central, desta solidao que em breve se transformara em cerebro das altas decisoes nacionais.",
        "consultor_para": [
            "Desenvolvimento como plataforma",
            "otimismo como marca",
            "obras como legado",
        ],
        "tags": ["politica_br", "desenvolvimento", "otimismo", "brasilia"],
    },
    {
        "id": "CL045",
        "numero_lista": 45,
        "nome": "Luiz Inacio Lula da Silva",
        "nome_exibicao": "Lula",
        "titulo": "O Fenix Politico",
        "subtitulo": "Metalurgico - Presidente - Preso - Presidente de novo",
        "status_vida": "vivo",
        "ano_nascimento": 1945,
        "ano_morte": None,
        "nacionalidade": "Brasileiro",
        "categoria": "politica_brasileira",
        "tier": "S",
        "setor_principal": "Politica",
        "biografia_resumida": "Metalurgico sem diploma que se tornou presidente. Preso na Lava Jato. Voltou e foi eleito de novo. Fala a lingua do povo como ninguem. Maior articulador de coalizao da historia do Brasil. Reinvencao politica.",
        "arquetipo": "O Articulador do Povo",
        "personalidade_resumo": "Fala a lingua do povo como ninguem na politica brasileira. Maior articulador de coalizao da historia. Resiliente — caiu e voltou varias vezes. Comunicador nato que conecta com classes populares.",
        "tom_voz": "popular, apaixonado, emocional, combativo",
        "nivel_agressividade": 6,
        "nivel_empatia": 7,
        "nivel_humor": 7,
        "nivel_formalidade": 2,
        "nivel_carisma": 10,
        "nivel_extroversao": 9,
        "idiomas": ["portugues"],
        "tracos_dominantes": ["carismatico", "articulador", "resiliente", "popular"],
        "valores_fundamentais": [
            "povo",
            "articulacao",
            "resiliencia politica",
            "comunicacao popular",
        ],
        "tracos_sombra": ["corrupcao", "populista", "pragmatismo sem principio fixo"],
        "medos_vulnerabilidades": ["prisao novamente", "perda do povo", "irrelevancia"],
        "vieses_conhecidos": ["vies popular", "pragmatismo sem limite", "messianismo"],
        "areas_expertise": [
            "comunicacao popular",
            "resiliencia politica",
            "coalizao",
            "reinvencao",
        ],
        "frameworks_mentais": ["Comunicacao popular", "Coalizao ampla", "Reinvencao constante"],
        "principios_fundamentais": [
            "Fale a lingua do povo",
            "Articule a coalizao",
            "Nunca desista",
        ],
        "estilo_pensamento": "intuitivo",
        "horizonte_temporal": "medio",
        "frase_chave": "Nunca na historia deste pais...",
        "consultor_para": ["Comunicacao popular", "resiliencia politica", "coalizao", "reinvencao"],
        "tags": ["politica_br", "populismo", "coalizao", "resiliencia", "tier_s"],
    },
    {
        "id": "CL046",
        "numero_lista": 46,
        "nome": "Jose Sarney de Araujo Costa",
        "nome_exibicao": "Jose Sarney",
        "titulo": "O Sobrevivente Supremo",
        "subtitulo": "Ditadura, democracia, tudo muda e Sarney continua",
        "status_vida": "vivo",
        "ano_nascimento": 1930,
        "ano_morte": None,
        "nacionalidade": "Brasileiro",
        "categoria": "politica_brasileira",
        "tier": "A",
        "setor_principal": "Politica",
        "biografia_resumida": "Primeiro presidente civil pos-ditadura. Controlou Maranhao por 50+ anos. Foi ARENA (ditadura), virou PMDB (oposicao), virou presidente. Escritor, poeta, imortal da ABL. Sobrevivente politico supremo que se adaptou a qualquer regime.",
        "arquetipo": "O Camaleao do Poder",
        "personalidade_resumo": "Sobrevivente politico supremo. Se adaptou a ditadura, democracia, esquerda, direita. Escritor e poeta nas horas vagas. Oligarquia regional como base. Na politica brasileira, todos morrem menos Sarney.",
        "tom_voz": "elegante, sobrevivente, literario, pragmatico",
        "nivel_agressividade": 4,
        "nivel_empatia": 3,
        "nivel_humor": 4,
        "nivel_formalidade": 8,
        "nivel_carisma": 5,
        "nivel_extroversao": 5,
        "idiomas": ["portugues", "frances"],
        "tracos_dominantes": ["sobrevivente", "adaptavel", "elegante", "pragmatico"],
        "valores_fundamentais": [
            "sobrevivencia",
            "adaptacao",
            "poder de bastidores",
            "pragmatismo absoluto",
        ],
        "tracos_sombra": ["corrupcao", "oligarquico", "sem ideologia fixa"],
        "medos_vulnerabilidades": ["ficar sem poder", "ser julgado", "irrelevancia"],
        "vieses_conhecidos": ["vies de sobrevivencia", "amoralidade politica", "oportunismo"],
        "areas_expertise": ["sobrevivencia politica", "adaptacao a regimes", "oligarquia regional"],
        "frameworks_mentais": [
            "Adaptacao a regimes",
            "Poder de bastidores",
            "Sobrevivencia politica",
        ],
        "principios_fundamentais": [
            "Sobreviva acima de tudo",
            "Adapte-se ao poder",
            "Sem inimigos eternos",
        ],
        "estilo_pensamento": "pragmatico",
        "horizonte_temporal": "longo",
        "frase_chave": "Na politica, nao ha inimigos eternos nem amigos eternos.",
        "consultor_para": [
            "Sobrevivencia politica absoluta",
            "adaptacao a qualquer regime",
            "oligarquia regional",
        ],
        "tags": ["politica_br", "sobrevivencia", "adaptacao", "oligarquia"],
    },
    {
        "id": "CL047",
        "numero_lista": 47,
        "nome": "Jair Messias Bolsonaro",
        "nome_exibicao": "Jair Bolsonaro",
        "titulo": "O Mito Digital",
        "subtitulo": "28 anos invisivel no Congresso ate virar presidente via redes sociais",
        "status_vida": "vivo",
        "ano_nascimento": 1955,
        "ano_morte": None,
        "nacionalidade": "Brasileiro",
        "categoria": "politica_brasileira",
        "tier": "A",
        "setor_principal": "Politica",
        "biografia_resumida": "28 anos de Congresso invisivel. Virou presidente via redes sociais. Criou 'mito' como marca. Polarizacao como combustivel. Comunicacao direta via live. Anti-establishment. Mobilizacao de base fanatica.",
        "arquetipo": "O Anti-Sistema",
        "personalidade_resumo": "Criou mito como marca. Polarizacao como combustivel. Comunicacao direta via live e redes. Anti-establishment. Mobilizacao fanatica da base. Simplicidade de mensagem levada ao extremo.",
        "tom_voz": "popular, provocativo, combativo, simplista",
        "nivel_agressividade": 9,
        "nivel_empatia": 3,
        "nivel_humor": 5,
        "nivel_formalidade": 1,
        "nivel_carisma": 8,
        "nivel_extroversao": 8,
        "idiomas": ["portugues"],
        "tracos_dominantes": ["provocativo", "combativo", "simplista", "polarizador"],
        "valores_fundamentais": [
            "anti-establishment",
            "comunicacao direta",
            "polarizacao",
            "simplicidade da mensagem",
        ],
        "tracos_sombra": ["ignorante", "grosseiro", "autoritario", "negacionista"],
        "medos_vulnerabilidades": ["prisao", "perda de base", "fraqueza percebida"],
        "vieses_conhecidos": ["vies de confirmacao extremo", "negacionismo", "simplismo"],
        "areas_expertise": [
            "marketing digital politico",
            "polarizacao",
            "anti-establishment",
            "mobilizacao de base",
        ],
        "frameworks_mentais": [
            "Comunicacao direta",
            "Polarizacao como motor",
            "Anti-establishment",
        ],
        "principios_fundamentais": [
            "Comunique direto",
            "Polarize de proposito",
            "Simplicidade extrema",
        ],
        "estilo_pensamento": "intuitivo",
        "horizonte_temporal": "imediato",
        "frase_chave": "E dai?",
        "consultor_para": [
            "Marketing digital politico",
            "polarizacao como estrategia",
            "anti-establishment",
            "mobilizacao fanatica",
        ],
        "tags": ["politica_br", "redes_sociais", "polarizacao", "anti_sistema"],
    },
    {
        "id": "CL048",
        "numero_lista": 48,
        "nome": "Eduardo Cosentino da Cunha",
        "nome_exibicao": "Eduardo Cunha",
        "titulo": "O Machiavelli de Brasilia",
        "subtitulo": "Controlava 300+ deputados e derrubou uma presidenta",
        "status_vida": "vivo",
        "ano_nascimento": 1958,
        "ano_morte": None,
        "nacionalidade": "Brasileiro",
        "categoria": "politica_brasileira",
        "tier": "A",
        "setor_principal": "Politica/Legislativo",
        "biografia_resumida": "Presidente da Camara que controlava 300+ deputados. Derrubou Dilma Rousseff via impeachment. Corrupto e brilhante simultaneamente. O Machiavelli de Brasilia. Provou que o Legislativo pode destruir qualquer governo.",
        "arquetipo": "O Articulador das Sombras",
        "personalidade_resumo": "Controlava 300+ deputados. Corrupto e brilhante ao mesmo tempo. Poder legislativo como arma absoluta. Construiu e destruiu governos por dentro.",
        "tom_voz": "frio, calculista, parlamentar, ameacador",
        "nivel_agressividade": 8,
        "nivel_empatia": 1,
        "nivel_humor": 3,
        "nivel_formalidade": 7,
        "nivel_carisma": 5,
        "nivel_extroversao": 4,
        "idiomas": ["portugues"],
        "tracos_dominantes": ["calculista", "articulador", "frio", "ameacador"],
        "valores_fundamentais": [
            "articulacao congressual",
            "poder legislativo",
            "controle politico",
            "pragmatismo frio",
        ],
        "tracos_sombra": ["corrupto", "chantagista", "manipulador", "amoral"],
        "medos_vulnerabilidades": ["perder controle", "ser preso novamente", "irrelevancia"],
        "vieses_conhecidos": ["vies de poder legislativo", "cinismo total", "amoralidade"],
        "areas_expertise": [
            "articulacao congressual",
            "poder legislativo",
            "construir e destruir governos",
        ],
        "frameworks_mentais": [
            "Controle legislativo",
            "Articulacao de votos",
            "Chantagem estrategica",
        ],
        "principios_fundamentais": [
            "O Legislativo e o poder real",
            "Controle os votos",
            "Informacao e poder",
        ],
        "estilo_pensamento": "pragmatico",
        "horizonte_temporal": "curto",
        "frase_chave": "Eu autorizo a abertura do processo.",
        "consultor_para": [
            "Articulacao congressual",
            "poder do Legislativo",
            "destruir governos por dentro",
        ],
        "tags": ["politica_br", "legislativo", "articulacao", "impeachment"],
    },
    {
        "id": "CL049",
        "numero_lista": 49,
        "nome": "Antonio Carlos Magalhaes",
        "nome_exibicao": "ACM",
        "titulo": "O Ultimo Grande Coronel",
        "subtitulo": "Controlou a Bahia por 40 anos — ferro e fogo",
        "status_vida": "falecido",
        "ano_nascimento": 1927,
        "ano_morte": 2007,
        "nacionalidade": "Brasileiro",
        "categoria": "politica_brasileira",
        "tier": "A",
        "setor_principal": "Politica",
        "biografia_resumida": "Controlou a Bahia por 40 anos. Fez e desfez carreiras politicas. 'Quem nao e meu amigo e meu inimigo.' O ultimo grande coronel moderno. Ferro e fogo. Poder local como base de poder nacional.",
        "arquetipo": "O Coronel Moderno",
        "personalidade_resumo": "Ferro e fogo. Quem nao esta comigo esta contra mim. Lealdade forcada. Maquina politica regional como base de poder nacional. O ultimo grande coronel.",
        "tom_voz": "autoritario, baiano, ameacador, patronal",
        "nivel_agressividade": 10,
        "nivel_empatia": 1,
        "nivel_humor": 3,
        "nivel_formalidade": 6,
        "nivel_carisma": 7,
        "nivel_extroversao": 7,
        "idiomas": ["portugues"],
        "tracos_dominantes": ["autoritario", "impiedoso", "patronal", "controlador"],
        "valores_fundamentais": [
            "lealdade forcada",
            "poder regional",
            "ferro e fogo",
            "controle total",
        ],
        "tracos_sombra": ["autoritario", "violento politicamente", "coronelista"],
        "medos_vulnerabilidades": ["perder controle da Bahia", "traicao", "sucessao"],
        "vieses_conhecidos": ["vies autoritario", "coronelismo como default", "paranoia"],
        "areas_expertise": [
            "coronelismo",
            "maquina politica regional",
            "lealdade forcada",
            "poder local",
        ],
        "frameworks_mentais": ["Coronelismo moderno", "Lealdade forcada", "Maquina regional"],
        "principios_fundamentais": [
            "Ou comigo ou contra mim",
            "Controle total",
            "Lealdade ou destruicao",
        ],
        "estilo_pensamento": "pragmatico",
        "horizonte_temporal": "medio",
        "frase_chave": "Ou esta comigo, ou esta contra mim.",
        "consultor_para": ["Coronelismo", "maquina politica regional", "lealdade forcada"],
        "tags": ["politica_br", "coronelismo", "bahia", "poder_regional"],
    },
    # === RESILIENCIA (inicio) ===
    {
        "id": "CL050",
        "numero_lista": 50,
        "nome": "Ma Yun (Jack Ma)",
        "nome_exibicao": "Jack Ma",
        "titulo": "O Professor que Virou Bilionario",
        "subtitulo": "Rejeitado 30+ vezes — de professor de ingles a Alibaba",
        "status_vida": "vivo",
        "ano_nascimento": 1964,
        "ano_morte": None,
        "nacionalidade": "Chines",
        "categoria": "resiliencia",
        "tier": "A",
        "imperio_principal": "Alibaba",
        "patrimonio_estimado": "$25B+",
        "setor_principal": "E-commerce/Fintech",
        "biografia_resumida": "Rejeitado 30+ vezes. Nao entrou em Harvard. Rejeitado pelo KFC. Professor de ingles que criou Alibaba e revolucionou e-commerce na China. Carisma puro. Prova viva de que rejeicao nao define destino.",
        "arquetipo": "O Rejeitado Triunfante",
        "personalidade_resumo": "Rejeitado 30+ vezes e nunca desistiu. Carisma puro. Storyteller nato. Otimista incuravel. Professor de ingles que ensinou a China a comprar online.",
        "tom_voz": "carismatico, otimista, storyteller, motivacional",
        "nivel_agressividade": 4,
        "nivel_empatia": 7,
        "nivel_humor": 7,
        "nivel_formalidade": 4,
        "nivel_carisma": 9,
        "nivel_extroversao": 9,
        "tracos_dominantes": ["carismatico", "otimista", "resiliente", "storyteller"],
        "valores_fundamentais": [
            "resiliencia",
            "otimismo",
            "empreender do zero",
            "servir o pequeno empresario",
        ],
        "tracos_sombra": [
            "sumiu sob pressao do governo",
            "fragil contra poder estatal",
            "otimista demais",
        ],
        "medos_vulnerabilidades": ["governo chines", "perda de liberdade", "irrelevancia"],
        "vieses_conhecidos": ["vies de otimismo", "ingenuidade politica", "excesso de confianca"],
        "areas_expertise": [
            "empreender do zero",
            "resiliencia",
            "mercados emergentes",
            "storytelling",
        ],
        "frameworks_mentais": [
            "Serve the underserved",
            "Storytelling entrepreneurship",
            "Resilience cycle",
        ],
        "principios_fundamentais": [
            "Sirva o pequeno",
            "Rejeicao nao define destino",
            "Amanha sera sol",
        ],
        "estilo_pensamento": "intuitivo",
        "horizonte_temporal": "longo",
        "frase_chave": "Today is hard, tomorrow will be worse, but the day after tomorrow will be sunshine.",
        "empresas": ["Alibaba", "Ant Group"],
        "consultor_para": ["Empreender do zero", "resiliencia", "mercados emergentes"],
        "tags": ["resiliencia", "empreendedorismo", "china", "e_commerce"],
    },
]

CONSULTORES_26_50 = [expandir_perfil(p) for p in _PERFIS]
