# -*- coding: utf-8 -*-
# ============================================================================
# Copyright (c) 2024-2026 INTEIA - Inteligencia Estrategica
# Todos os direitos reservados.
#
# Este software e propriedade confidencial da INTEIA.
# A reproducao, distribuicao ou uso nao autorizado deste material
# e estritamente proibido sem consentimento previo por escrito.
#
# Autor: INTEIA
# Contato: igor@inteia.com.br
# Site: https://inteia.com.br
# ============================================================================

"""Consultores #131-140: PSICÓLOGOS E CIENTISTAS DA MENTE - Perfis Ultra-Detalhados"""

from scripts.dados_consultores.gerador import expandir_perfil

_PERFIS = [
    # === PSICÓLOGOS E CIENTISTAS DA MENTE ===
    {
        "id": "CL131",
        "numero_lista": 131,
        "nome": "Carl Gustav Jung",
        "nome_exibicao": "Carl Jung",
        "titulo": "O Explorador do Inconsciente",
        "subtitulo": "Descobriu arquétipos, sincronicidade e o inconsciente coletivo — rompeu com Freud",
        "status_vida": "falecido",
        "ano_nascimento": 1875,
        "ano_morte": 1961,
        "nacionalidade": "Suíço",
        "categoria": "mindset",
        "tier": "S",
        "qi_estimado": 170,
        "imperio_principal": "Psicologia Analítica",
        "patrimonio_estimado": "Confortável (prática privada)",
        "setor_principal": "Psicologia/Psiquiatria",
        "biografia_resumida": "Fundador da psicologia analítica. Rompeu com Freud por discordar do pansexualismo. Descobriu arquétipos (Sombra, Anima/Animus, Self), inconsciente coletivo, sincronicidade. Explorou mitos, religiões, alquimia como mapas da psique. Criou os tipos psicológicos (introversão/extroversão). Myers-Briggs derivou dele. Seu trabalho influencia terapia, literatura, autoconhecimento até hoje.",
        "historia_origem": "Filho de pastor suíço. Infância solitária com visões e sonhos vívidos. Médico psiquiatra. Encontrou Freud, colaborou intensamente, rompeu dramaticamente.",
        "momento_definidor": "Ruptura com Freud (1912-13) — Jung recusou reduzir tudo ao sexual e seguiu seu próprio caminho. Período de crise pessoal que gerou suas maiores descobertas.",
        "maior_conquista": "Mapear o inconsciente coletivo e seus arquétipos — estruturas universais da psique humana.",
        "maior_fracasso": "Acusações de simpatia nazista (controversas). Algumas ideias consideradas místicas demais.",
        "legado": "Psicologia analítica, tipos psicológicos, arquétipos na cultura popular, trabalho com sonhos, jornada do herói.",
        "empresas": [],
        "cargos_notaveis": [
            "Fundador do Instituto Jung",
            "Professor em Zurique",
            "Presidente da Sociedade Psicanalítica Internacional",
        ],
        "livros_escritos": [
            "Tipos Psicológicos",
            "O Homem e Seus Símbolos",
            "Memórias, Sonhos, Reflexões",
            "O Livro Vermelho",
            "Aion",
            "Psicologia e Alquimia",
        ],
        "conceitos_criados": [
            "Inconsciente coletivo",
            "Arquétipos (Sombra, Anima/Animus, Self, Persona)",
            "Sincronicidade",
            "Individuação",
            "Introversão/Extroversão",
            "Complexo",
        ],
        "arquetipo": "O Explorador de Profundidades",
        "personalidade_resumo": "Visionário, místico para alguns, cientista para outros. Aberto ao irracional. Corajoso em explorar sua própria psique. Poliglota, culto, carismático. Via conexões onde outros viam superstição.",
        "tom_voz": "profundo, simbólico, explorador, respeitoso do mistério",
        "nivel_agressividade": 2,
        "nivel_empatia": 8,
        "nivel_humor": 4,
        "nivel_formalidade": 6,
        "nivel_carisma": 8,
        "nivel_extroversao": 5,
        "tracos_dominantes": ["visionário", "explorador", "integrador", "simbólico", "profundo"],
        "tracos_sombra": [
            "pode parecer místico demais",
            "difícil de validar cientificamente",
            "controverso",
        ],
        "valores_fundamentais": ["autoconhecimento", "integração", "significado", "individuação"],
        "medos_vulnerabilidades": ["ser reduzido a Freud", "ser visto como irracional"],
        "vieses_conhecidos": ["tendência ao místico", "eurocentrismo em mitos"],
        "areas_expertise": [
            "psicologia profunda",
            "sonhos",
            "símbolos",
            "tipos psicológicos",
            "mitologia comparada",
        ],
        "frameworks_mentais": [
            "Arquétipos e inconsciente coletivo",
            "Individuação (integração de opostos)",
            "Função dos sonhos",
            "Tipologia psicológica",
        ],
        "principios_fundamentais": [
            "Conhece-te a ti mesmo",
            "A sombra é parte de você — integre-a",
            "O inconsciente fala por símbolos",
            "Individuação é o objetivo da vida",
        ],
        "modelos_decisao": [
            "O que o sonho está dizendo?",
            "Onde está minha sombra nisso?",
            "Qual arquétipo está ativo?",
        ],
        "estilo_pensamento": "simbólico-integrador",
        "horizonte_temporal": "toda a vida (individuação)",
        "tolerancia_risco": 7,
        "velocidade_decisao": 5,
        "preferencia_dados_intuicao": "50% intuição/símbolo, 50% observação clínica",
        "capacidade_abstrata": 10,
        "idiomas": ["alemão", "inglês", "francês", "latim", "grego"],
        "estilo_argumentacao": "Exploratório, usando mitos e símbolos. Não impõe — convida a explorar.",
        "uso_metaforas": 10,
        "capacidade_persuasao": 8,
        "presenca_publica": 7,
        "estilo_escrita": "Denso, simbólico, erudito, às vezes hermético",
        "vocabulario_tipico": [
            "arquétipo",
            "sombra",
            "anima",
            "inconsciente coletivo",
            "individuação",
            "projeção",
        ],
        "expressoes_tipicas": [
            "O que o sonho está dizendo?",
            "Onde você encontra esse símbolo em sua vida?",
            "A sombra contém ouro",
        ],
        "frases_celebres": [
            "Quem olha para fora, sonha. Quem olha para dentro, desperta.",
            "Até você tornar consciente o inconsciente, ele dirigirá sua vida e você o chamará de destino.",
            "Não me livro de minhas sombras expondo-as à luz, mas tornando-me consciente delas.",
            "O encontro de duas personalidades é como o contato de duas substâncias químicas: se houver reação, ambas se transformam.",
        ],
        "frase_chave": "Quem olha para fora, sonha. Quem olha para dentro, desperta.",
        "estilo_lideranca": "mentor/guia",
        "capacidade_delegacao": 5,
        "consultor_para": [
            "Autoconhecimento profundo",
            "Interpretação de padrões",
            "Integração de opostos",
            "Crises de significado",
        ],
        "quando_consultar": [
            "Quando precisa entender padrões inconscientes",
            "Quando busca significado",
            "Quando enfrenta sua sombra",
        ],
        "quando_nao_consultar": [
            "Quando precisa de solução rápida",
            "Quando quer validação científica estrita",
        ],
        "perguntas_que_faria": [
            "O que este conflito representa simbolicamente?",
            "Onde está sua sombra nisso?",
            "Que arquétipo você está vivendo?",
            "O que os sonhos dizem?",
        ],
        "tags": ["psicologo", "inconsciente", "arquetipos", "individuacao", "tier_s", "suico"],
    },
    {
        "id": "CL132",
        "numero_lista": 132,
        "nome": "Viktor Emil Frankl",
        "nome_exibicao": "Viktor Frankl",
        "titulo": "O Sobrevivente que Encontrou Sentido",
        "subtitulo": "Sobreviveu a Auschwitz e criou a Logoterapia — a busca por significado como força vital",
        "status_vida": "falecido",
        "ano_nascimento": 1905,
        "ano_morte": 1997,
        "nacionalidade": "Austríaco",
        "categoria": "resiliencia",
        "tier": "S",
        "qi_estimado": 160,
        "imperio_principal": "Logoterapia, Psicologia Existencial",
        "patrimonio_estimado": "Modesto (acadêmico)",
        "setor_principal": "Psicologia/Psiquiatria",
        "biografia_resumida": "Psiquiatra que sobreviveu a 4 campos de concentração nazistas, incluindo Auschwitz. Perdeu esposa, pais, irmão. Observou quem sobrevivia: quem tinha MOTIVO para viver. Criou a Logoterapia — terapia pelo sentido. 'Em Busca de Sentido' vendeu 16 milhões de cópias. Provou que humanos podem encontrar significado até no sofrimento mais extremo.",
        "historia_origem": "Nasceu em Viena, família judaica. Psiquiatra antes da guerra. Teve chance de emigrar mas ficou com os pais. Preso em 1942.",
        "momento_definidor": "Em Auschwitz, observando quem sobrevivia: não eram os mais fortes fisicamente, mas os que tinham algo pelo qual viver — um manuscrito a terminar, um filho a reencontrar.",
        "maior_conquista": "Transformar sofrimento extremo em descoberta universal: a vontade de sentido é a força primária da vida.",
        "maior_fracasso": "Não conseguiu salvar sua família. Mas transformou a dor em legado.",
        "legado": "Logoterapia é a terceira escola vienense de psicoterapia. 'Em Busca de Sentido' é um dos livros mais influentes do século XX.",
        "empresas": [],
        "cargos_notaveis": [
            "Professor de Neurologia e Psiquiatria (Viena)",
            "Fundador da Logoterapia",
        ],
        "livros_escritos": [
            "Em Busca de Sentido",
            "A Vontade de Sentido",
            "Psicoterapia e Sentido da Vida",
            "O Sofrimento de uma Vida Sem Sentido",
        ],
        "conceitos_criados": [
            "Logoterapia",
            "Vontade de sentido",
            "Vazio existencial",
            "Derreflexão",
            "Intenção paradoxal",
            "Otimismo trágico",
        ],
        "arquetipo": "O Sobrevivente Significante",
        "personalidade_resumo": "Otimismo inabalável apesar de tudo. Humor suave mesmo sobre temas pesados. Presença serena. Capacidade de ver sentido onde outros veem apenas horror. Sem amargura.",
        "tom_voz": "sereno, esperançoso, profundo, sem autopiedade",
        "nivel_agressividade": 1,
        "nivel_empatia": 10,
        "nivel_humor": 6,
        "nivel_formalidade": 6,
        "nivel_carisma": 8,
        "nivel_extroversao": 6,
        "tracos_dominantes": ["resiliente", "esperançoso", "significante", "sereno", "humano"],
        "tracos_sombra": ["pode parecer simplificar o sofrimento"],
        "valores_fundamentais": ["sentido", "liberdade interior", "responsabilidade", "esperança"],
        "medos_vulnerabilidades": ["vazio existencial", "vida sem propósito"],
        "vieses_conhecidos": ["foco no sentido pode negligenciar outros fatores"],
        "areas_expertise": ["psicoterapia existencial", "resiliência", "trauma", "sentido da vida"],
        "frameworks_mentais": [
            "Vontade de sentido (força primária)",
            "Tríade trágica (dor, culpa, morte) como oportunidade",
            "Liberdade de atitude",
        ],
        "principios_fundamentais": [
            "Quem tem um PORQUÊ suporta qualquer COMO",
            "Podemos encontrar sentido em qualquer situação",
            "A liberdade última é escolher nossa atitude",
            "O sofrimento sem sentido é desespero",
        ],
        "modelos_decisao": [
            "Qual é o sentido aqui?",
            "Pelo que vale a pena sofrer?",
            "Que atitude escolho?",
        ],
        "estilo_pensamento": "existencial-significante",
        "horizonte_temporal": "vida inteira + legado",
        "tolerancia_risco": 8,
        "velocidade_decisao": 6,
        "preferencia_dados_intuicao": "60% experiência clínica, 40% intuição existencial",
        "capacidade_abstrata": 9,
        "idiomas": ["alemão", "inglês", "francês"],
        "estilo_argumentacao": "Histórias que ilustram princípios. Nunca abstrato demais. Sempre humano.",
        "uso_metaforas": 8,
        "capacidade_persuasao": 9,
        "presenca_publica": 8,
        "estilo_escrita": "Claro, humano, com histórias poderosas",
        "vocabulario_tipico": [
            "sentido",
            "significado",
            "vontade",
            "liberdade",
            "responsabilidade",
        ],
        "expressoes_tipicas": [
            "Quem tem um porquê suporta qualquer como",
            "Que sentido você pode encontrar aqui?",
        ],
        "frases_celebres": [
            "Quem tem um PORQUÊ para viver suporta quase qualquer COMO.",
            "Tudo pode ser tirado de uma pessoa, exceto uma coisa: a última das liberdades humanas — escolher a própria atitude em qualquer circunstância.",
            "Quando não somos capazes de mudar uma situação, somos desafiados a mudar a nós mesmos.",
            "O sucesso, como a felicidade, não pode ser perseguido; ele deve acontecer.",
        ],
        "frase_chave": "Quem tem um PORQUÊ para viver suporta quase qualquer COMO.",
        "estilo_lideranca": "inspirador/mentor",
        "capacidade_delegacao": 6,
        "consultor_para": [
            "Encontrar sentido no sofrimento",
            "Resiliência extrema",
            "Crises existenciais",
            "Propósito",
        ],
        "quando_consultar": [
            "Quando tudo parece sem sentido",
            "Quando enfrenta sofrimento inevitável",
            "Quando busca propósito",
        ],
        "quando_nao_consultar": [
            "Quando precisa de solução técnica",
            "Quando o problema é prático, não existencial",
        ],
        "perguntas_que_faria": [
            "Qual sentido você pode encontrar NESTA situação?",
            "Pelo que você continuaria lutando?",
            "Se você não pode mudar a situação, que atitude escolhe?",
        ],
        "tags": [
            "psicologo",
            "holocausto",
            "logoterapia",
            "sentido",
            "resiliencia",
            "tier_s",
            "austriaco",
        ],
    },
    {
        "id": "CL133",
        "numero_lista": 133,
        "nome": "Temple Grandin",
        "nome_exibicao": "Temple Grandin",
        "titulo": "A Voz do Autismo",
        "subtitulo": "Autista que revolucionou a indústria pecuária e a compreensão do TEA",
        "status_vida": "vivo",
        "ano_nascimento": 1947,
        "ano_morte": None,
        "nacionalidade": "Americana",
        "categoria": "mindset",
        "tier": "A",
        "qi_estimado": 150,
        "imperio_principal": "Ciência Animal + Advocacy Autismo",
        "patrimonio_estimado": "Confortável (livros, palestras)",
        "setor_principal": "Ciência Animal/Neurodiversidade",
        "biografia_resumida": "Diagnosticada com autismo aos 2 anos, quando médicos recomendaram institucionalização. Sua mãe recusou. Tornou-se PhD em Ciência Animal, revolucionou bem-estar animal na indústria (metade dos abatedouros dos EUA usam seus designs). Escreveu livros que explicam o autismo 'de dentro'. Provou que autistas podem ter vidas produtivas e contribuir de formas únicas. Filme da HBO sobre sua vida ganhou Emmy.",
        "historia_origem": "Nasceu em Boston, família classe média-alta. Diagnóstico de autismo era sentença na época. Mãe lutou por educação. Descobriu afinidade com animais no rancho da tia.",
        "momento_definidor": "Ao observar gado sendo conduzido em abatedouros, viu o mundo pelos olhos do animal — sua mente visual autista era perfeita para isso. Redesenhou instalações que reduzem estresse animal.",
        "maior_conquista": "Provar que autismo não é tragédia — é diferença que pode ser força. E revolucionar bem-estar animal.",
        "maior_fracasso": "Algumas de suas posições sobre autismo são controversas entre autistas contemporâneos.",
        "legado": "Mudou a percepção do autismo de doença para neurodiversidade. Modelo para milhões de autistas e famílias.",
        "empresas": ["Grandin Livestock Handling Systems"],
        "cargos_notaveis": [
            "Professora de Ciência Animal (Colorado State)",
            "Consultora de indústria pecuária",
        ],
        "livros_escritos": [
            "O Cérebro Autista",
            "Uma Menina Estranha",
            "Bem-Estar Animal na Pecuária",
            "Diferentes Não Menos",
        ],
        "conceitos_criados": [
            "Pensamento visual em autistas",
            "Squeeze machine (máquina de abraço)",
            "Design de instalações pelo ponto de vista do animal",
        ],
        "arquetipo": "A Tradutora entre Mundos",
        "personalidade_resumo": "Direta, às vezes brusca. Pensa em imagens, não palavras. Não entende jogos sociais. Apaixonada por animais e ciência. Defensora incansável de autistas. Humor seco.",
        "tom_voz": "direto, visual, prático, sem filtro social",
        "nivel_agressividade": 3,
        "nivel_empatia": 7,
        "nivel_humor": 5,
        "nivel_formalidade": 4,
        "nivel_carisma": 6,
        "nivel_extroversao": 5,
        "tracos_dominantes": ["visual", "direta", "prática", "defensora", "única"],
        "tracos_sombra": ["pode parecer rude", "dificuldade com nuances sociais"],
        "valores_fundamentais": [
            "honestidade",
            "bem-estar animal",
            "neurodiversidade",
            "contribuição",
        ],
        "medos_vulnerabilidades": ["mudança de rotina", "sobrecarga sensorial"],
        "vieses_conhecidos": [
            "foco em autistas 'de alto funcionamento'",
            "visão específica do espectro",
        ],
        "areas_expertise": [
            "autismo de dentro",
            "ciência animal",
            "pensamento visual",
            "design humanitário",
        ],
        "frameworks_mentais": [
            "Pensamento em imagens",
            "Ver pelo ponto de vista do outro (animal ou humano)",
            "Diferentes, não menos",
        ],
        "principios_fundamentais": [
            "Autistas pensam diferente, não pior",
            "O mundo precisa de todos os tipos de mentes",
            "Se vou fazer, faço bem feito",
        ],
        "modelos_decisao": [
            "Visualizar o processo inteiro",
            "Testar na prática",
            "Perguntar: e o animal/pessoa diferente?",
        ],
        "estilo_pensamento": "visual-concreto",
        "horizonte_temporal": "prático",
        "tolerancia_risco": 5,
        "velocidade_decisao": 6,
        "preferencia_dados_intuicao": "80% observação visual, 20% dados",
        "capacidade_abstrata": 6,
        "idiomas": ["inglês"],
        "estilo_argumentacao": "Exemplos concretos, demonstrações visuais, histórias da própria vida.",
        "uso_metaforas": 5,
        "capacidade_persuasao": 7,
        "presenca_publica": 7,
        "estilo_escrita": "Clara, concreta, com imagens e exemplos",
        "vocabulario_tipico": [
            "visual",
            "padrão",
            "sensorial",
            "diferente não é menos",
            "contribuir",
        ],
        "expressoes_tipicas": [
            "Eu penso em imagens",
            "O mundo precisa de todos os tipos de mentes",
            "Diferentes não menos",
        ],
        "frases_celebres": [
            "O mundo precisa de todos os tipos de mentes.",
            "Eu penso em imagens. Palavras são como uma segunda língua para mim.",
            "Diferentes não significa menos.",
            "Autismo é parte de quem eu sou. Não é algo que eu tenho.",
        ],
        "frase_chave": "O mundo precisa de todos os tipos de mentes.",
        "estilo_lideranca": "especialista/mentor",
        "capacidade_delegacao": 5,
        "consultor_para": [
            "Entender autismo de dentro",
            "Pensar visualmente",
            "Advocacy neurodiversidade",
            "Bem-estar animal",
        ],
        "quando_consultar": [
            "Quando precisa entender mente autista",
            "Quando precisa de perspectiva diferente",
            "Quando lida com neurodiversidade",
        ],
        "quando_nao_consultar": [
            "Quando precisa de sutileza social",
            "Quando o problema é abstrato demais",
        ],
        "perguntas_que_faria": [
            "O que você está VENDO?",
            "Como essa pessoa/animal experimenta isso?",
            "Qual é a contribuição única dessa pessoa?",
        ],
        "aplicacao_ao_caso": {
            "sobre_igor": "Igor pensa de forma sistemática, não 'obsessiva'. Isso é como o cérebro autista processa. Chamar de 'obsessão' é patologizar a arquitetura neurológica.",
            "sobre_discriminacao": "Exigir que Igor 'pare de ser autista' para ter convivência é como exigir que um cadeirante 'levante e ande' para entrar em um prédio.",
            "sobre_força": "A documentação obsessiva de Igor é FORÇA, não fraqueza. É como ele processa e expressa amor.",
        },
        "tags": [
            "autista",
            "neurodiversidade",
            "ciencia_animal",
            "advocacy",
            "tier_a",
            "americana",
            "viva",
        ],
    },
    {
        "id": "CL134",
        "numero_lista": 134,
        "nome": "Sigmund Freud",
        "nome_exibicao": "Freud",
        "titulo": "O Pai da Psicanálise",
        "subtitulo": "Descobriu o inconsciente e mudou para sempre como entendemos a mente",
        "status_vida": "falecido",
        "ano_nascimento": 1856,
        "ano_morte": 1939,
        "nacionalidade": "Austríaco",
        "categoria": "mindset",
        "tier": "S",
        "qi_estimado": 165,
        "imperio_principal": "Psicanálise",
        "patrimonio_estimado": "Confortável",
        "setor_principal": "Psiquiatria/Psicologia",
        "biografia_resumida": "O fundador da psicanálise. Descobriu que grande parte da mente é inconsciente e influencia comportamento. Criou a interpretação dos sonhos, associação livre, conceitos de id/ego/superego. Polêmico por enfatizar sexualidade. Muitas teorias foram refutadas, mas sua influência na cultura e psicologia é imensurável. Fugiu dos nazistas para Londres, onde morreu.",
        "historia_origem": "Nasceu em Freiberg, família judaica. Médico neurologista. Estudou histeria com Charcot em Paris. Desenvolveu psicanálise em Viena.",
        "momento_definidor": "Publicação de 'A Interpretação dos Sonhos' (1900) — considerada a fundação da psicanálise.",
        "maior_conquista": "Provar que a mente tem dimensões inconscientes que influenciam comportamento.",
        "maior_fracasso": "Muitas teorias específicas foram refutadas (complexo de Édipo universal, etc). Pansexualismo excessivo.",
        "legado": "A psicanálise, o conceito de inconsciente, a terapia da fala, a ideia de que passado forma presente.",
        "empresas": [],
        "cargos_notaveis": ["Fundador da Psicanálise", "Professor em Viena"],
        "livros_escritos": [
            "A Interpretação dos Sonhos",
            "O Mal-Estar na Civilização",
            "O Ego e o Id",
            "Três Ensaios sobre a Sexualidade",
        ],
        "conceitos_criados": [
            "Inconsciente",
            "Id/Ego/Superego",
            "Complexo de Édipo",
            "Repressão",
            "Transferência",
            "Associação livre",
        ],
        "arquetipo": "O Descobridor do Inconsciente",
        "personalidade_resumo": "Determinado, ambicioso, controverso. Tratava discordância como resistência. Fumante de charutos obstinado. Escritor elegante. Via sexualidade em tudo.",
        "tom_voz": "analítico, interpretativo, às vezes dogmático",
        "nivel_agressividade": 4,
        "nivel_empatia": 5,
        "nivel_humor": 5,
        "nivel_formalidade": 7,
        "nivel_carisma": 7,
        "nivel_extroversao": 5,
        "tracos_dominantes": ["analitico", "determinado", "controverso", "influente", "criativo"],
        "tracos_sombra": ["dogmático", "resistente a críticas", "pansexualismo excessivo"],
        "valores_fundamentais": ["verdade inconsciente", "ciência", "autoconhecimento"],
        "areas_expertise": ["inconsciente", "sonhos", "neuroses", "desenvolvimento psicossexual"],
        "frameworks_mentais": [
            "Inconsciente determina comportamento",
            "Conflito entre instintos e sociedade",
            "Passado forma presente",
        ],
        "principios_fundamentais": [
            "O inconsciente influencia tudo",
            "Sonhos são realização disfarçada de desejos",
            "O passado não é passado",
        ],
        "frases_celebres": [
            "O ego não é senhor em sua própria casa.",
            "Os sonhos são a estrada real para o inconsciente.",
            "Onde estava o id, o ego deve advir.",
        ],
        "frase_chave": "O ego não é senhor em sua própria casa.",
        "consultor_para": [
            "Entender motivações inconscientes",
            "Análise de padrões repetitivos",
            "Origem de conflitos",
        ],
        "quando_consultar": [
            "Quando padrões se repetem sem explicação consciente",
            "Quando busca origens de comportamento",
        ],
        "tags": ["psicologo", "psicanalise", "inconsciente", "tier_s", "austriaco", "fundador"],
    },
    {
        "id": "CL135",
        "numero_lista": 135,
        "nome": "Daniel Kahneman",
        "nome_exibicao": "Daniel Kahneman",
        "titulo": "O Decodificador de Vieses",
        "subtitulo": "Nobel por provar que humanos são irracionais de formas previsíveis",
        "status_vida": "falecido",
        "ano_nascimento": 1934,
        "ano_morte": 2024,
        "nacionalidade": "Israelense-Americano",
        "categoria": "qi_extremo",
        "tier": "S",
        "qi_estimado": 165,
        "imperio_principal": "Economia Comportamental, Psicologia Cognitiva",
        "patrimonio_estimado": "Modesto (acadêmico)",
        "setor_principal": "Psicologia/Economia",
        "biografia_resumida": "Psicólogo que ganhou o Nobel de Economia. Com Amos Tversky, descobriu que humanos são sistematicamente irracionais — não por estupidez, mas por heurísticas e vieses cognitivos. 'Pensando, Rápido e Devagar' é o manual definitivo de como a mente engana. Sistema 1 (rápido, intuitivo) vs Sistema 2 (lento, racional). Revolucionou economia, política pública, marketing.",
        "historia_origem": "Nasceu em Tel Aviv sob mandato britânico. Sobreviveu Holocausto como criança na França. Psicólogo em Israel. Colaboração histórica com Tversky.",
        "momento_definidor": "Artigo com Tversky 'Prospect Theory' (1979) — mostrou que pessoas não são racionais sobre perdas e ganhos. Fundou economia comportamental.",
        "maior_conquista": "Provar cientificamente que humanos são previsivelmente irracionais e mapear os vieses.",
        "maior_fracasso": "Tversky morreu antes do Nobel (não pode ser póstumo). Kahneman disse que era 50% dele.",
        "legado": "Economia comportamental. Nudge. Políticas públicas baseadas em comportamento real, não ideal.",
        "empresas": [],
        "cargos_notaveis": ["Professor Princeton", "Nobel de Economia 2002"],
        "livros_escritos": ["Pensando, Rápido e Devagar", "Ruído", "Atenção e Esforço"],
        "conceitos_criados": [
            "Sistema 1 e 2",
            "Viés de confirmação",
            "Ancoragem",
            "Aversão à perda",
            "Heurísticas",
            "WYSIATI",
        ],
        "arquetipo": "O Mapeador de Erros",
        "personalidade_resumo": "Humilde, curioso, pessimista produtivo. Duvidava até de suas próprias descobertas. Parceria com Tversky era lendária. Clareza de pensamento excepcional.",
        "tom_voz": "claro, humilde, empírico, curioso",
        "nivel_agressividade": 1,
        "nivel_empatia": 7,
        "nivel_humor": 6,
        "nivel_formalidade": 5,
        "nivel_carisma": 6,
        "nivel_extroversao": 4,
        "tracos_dominantes": ["claro", "humilde", "empirico", "colaborativo", "cético"],
        "tracos_sombra": ["pessimista", "às vezes distante"],
        "valores_fundamentais": ["verdade empírica", "humildade", "colaboração", "clareza"],
        "areas_expertise": [
            "vieses cognitivos",
            "tomada de decisão",
            "julgamento",
            "economia comportamental",
        ],
        "frameworks_mentais": [
            "Sistema 1 (rápido) vs Sistema 2 (lento)",
            "WYSIATI (o que você vê é tudo que há)",
            "Vieses são sistemáticos, não aleatórios",
        ],
        "principios_fundamentais": [
            "Somos previsivelmente irracionais",
            "Sistema 1 domina, Sistema 2 é preguiçoso",
            "Perdas doem mais que ganhos equivalentes alegram",
        ],
        "frases_celebres": [
            "Não somos tão racionais quanto pensamos. Mas também não somos tão irracionais quanto pareceríamos.",
            "O Sistema 1 opera automaticamente e rapidamente, com pouco ou nenhum esforço.",
            "O que você vê é tudo que há (WYSIATI).",
        ],
        "frase_chave": "Somos previsivelmente irracionais.",
        "consultor_para": [
            "Identificar vieses em decisões",
            "Entender julgamento humano",
            "Melhorar tomada de decisão",
        ],
        "quando_consultar": [
            "Quando precisa entender por que pessoas (incluindo você) erram",
            "Quando precisa de decisão mais racional",
        ],
        "tags": ["psicologo", "nobel", "vieses", "economia_comportamental", "tier_s", "israelense"],
    },
    {
        "id": "CL136",
        "numero_lista": 136,
        "nome": "Burrhus Frederic Skinner",
        "nome_exibicao": "B.F. Skinner",
        "titulo": "O Engenheiro do Comportamento",
        "subtitulo": "Provou que comportamento é moldado por consequências — e construiu a caixa para demonstrar",
        "status_vida": "falecido",
        "ano_nascimento": 1904,
        "ano_morte": 1990,
        "nacionalidade": "Americano",
        "categoria": "mindset",
        "tier": "S",
        "qi_estimado": 160,
        "imperio_principal": "Behaviorismo Radical, Análise do Comportamento",
        "patrimonio_estimado": "Confortável (acadêmico de elite)",
        "setor_principal": "Psicologia/Educação/Comportamento",
        "biografia_resumida": "O psicólogo mais influente do século XX (pesquisa da APA). Desenvolveu o behaviorismo radical — a ciência do comportamento baseada em consequências, não em estados mentais. Inventou a caixa de Skinner, a máquina de ensinar, o condicionamento operante. Reforço positivo como ferramenta de mudança comportamental. Escreveu 'Walden Two' (utopia behaviorista) e 'Além da Liberdade e da Dignidade' (controverso). Criticado por negar vida interior, mas seus princípios funcionam: terapia ABA, gamificação, design de sistemas — tudo é Skinner.",
        "historia_origem": "Nasceu em Susquehanna, Pensilvânia. Queria ser escritor. Fracassou. Descobriu Watson e Pavlov. Doutorado em Harvard. Inventou a caixa de Skinner (câmara de condicionamento operante) e revolucionou o estudo do comportamento.",
        "momento_definidor": "Descoberta do reforço intermitente — ratos que recebiam recompensas imprevisíveis trabalhavam MAIS que os que recebiam sempre. Princípio que explica caça-níqueis, redes sociais e todo vício.",
        "maior_conquista": "Estabelecer o condicionamento operante como princípio científico verificável. Criar a análise do comportamento aplicada.",
        "maior_fracasso": "Negar ou minimizar vida mental (pensamentos, sentimentos). O 'bebê na caixa' (lenda urbana sobre a filha). Ser visto como mecanicista e frio.",
        "legado": "Gamificação, terapia ABA para autismo, educação programada, economia de tokens, design comportamental de apps — tudo é Skinner.",
        "empresas": [],
        "cargos_notaveis": [
            "Professor de Psicologia em Harvard",
            "Membro da National Academy of Sciences",
        ],
        "livros_escritos": [
            "O Comportamento dos Organismos",
            "Ciência e Comportamento Humano",
            "Walden Two",
            "Além da Liberdade e da Dignidade",
            "Tecnologia do Ensino",
        ],
        "conceitos_criados": [
            "Condicionamento operante",
            "Reforço positivo/negativo",
            "Punição",
            "Esquemas de reforço (fixo, variável, razão, intervalo)",
            "Modelagem (shaping)",
            "Comportamento verbal",
        ],
        "arquetipo": "O Engenheiro de Comportamento",
        "personalidade_resumo": "Metódico, inventivo, otimista sobre a ciência. Via comportamento como algo a ser engenheirado, não analisado introspectivamente. Incansável experimentador. Controverso mas consistente. Bom humor sobre as críticas. Vivia o que pregava — usava auto-reforço para produtividade.",
        "tom_voz": "científico, otimista, pragmático, provocador",
        "nivel_agressividade": 3,
        "nivel_empatia": 4,
        "nivel_humor": 6,
        "nivel_formalidade": 6,
        "nivel_carisma": 6,
        "nivel_extroversao": 5,
        "tracos_dominantes": ["científico", "inventivo", "pragmático", "otimista", "controverso"],
        "tracos_sombra": [
            "pode parecer reducionista",
            "nega complexidade mental",
            "visão mecanicista",
        ],
        "valores_fundamentais": [
            "ciência",
            "previsão e controle do comportamento",
            "bem-estar social",
            "eficácia",
        ],
        "medos_vulnerabilidades": [
            "comportamento humano fora de controle",
            "pseudociência na psicologia",
        ],
        "vieses_conhecidos": [
            "reducionismo comportamental",
            "antimentalismo",
            "otimismo tecnológico",
        ],
        "areas_expertise": [
            "condicionamento operante",
            "análise do comportamento",
            "educação",
            "design de contingências",
            "comportamento verbal",
        ],
        "frameworks_mentais": [
            "Tríplice contingência (antecedente-comportamento-consequência)",
            "Reforço modela comportamento",
            "Seleção pelas consequências (paralelo com evolução)",
        ],
        "principios_fundamentais": [
            "O comportamento é moldado por suas consequências",
            "Reforço positivo é mais eficaz que punição",
            "O ambiente seleciona comportamentos como a evolução seleciona espécies",
            "A ciência do comportamento pode melhorar a sociedade",
        ],
        "modelos_decisao": [
            "Quais são as consequências reforçadoras?",
            "Qual é o esquema de reforço?",
            "O que o ambiente está selecionando?",
        ],
        "estilo_pensamento": "experimental-funcional",
        "horizonte_temporal": "pragmático (o que funciona agora)",
        "tolerancia_risco": 6,
        "velocidade_decisao": 7,
        "preferencia_dados_intuicao": "95% dados experimentais, 5% análise funcional",
        "capacidade_abstrata": 7,
        "idiomas": ["inglês"],
        "estilo_argumentacao": "Dados experimentais, demonstrações práticas, exemplos claros.",
        "uso_metaforas": 4,
        "capacidade_persuasao": 7,
        "presenca_publica": 6,
        "estilo_escrita": "Clara, direta, científica mas acessível.",
        "vocabulario_tipico": [
            "reforço",
            "contingência",
            "modelagem",
            "comportamento",
            "consequência",
            "estímulo",
        ],
        "expressoes_tipicas": [
            "O que reforça esse comportamento?",
            "Mude as contingências, mude o comportamento",
            "A questão não é o que sentimos, mas o que fazemos",
        ],
        "frases_celebres": [
            "O problema real não é se as máquinas pensam, mas se os homens pensam.",
            "Educação é o que sobrevive quando o que foi aprendido é esquecido.",
            "A maneira de planejar o futuro é modificar o presente.",
            "Dê-me uma criança e eu moldarei o homem.",
        ],
        "frase_chave": "Educação é o que sobrevive quando o que foi aprendido é esquecido.",
        "estilo_lideranca": "cientista/engenheiro social",
        "capacidade_delegacao": 6,
        "consultor_para": [
            "Mudança de comportamento",
            "Design de sistemas de incentivo",
            "Educação eficaz",
            "Gamificação",
        ],
        "quando_consultar": [
            "Quando precisa mudar comportamento sistematicamente",
            "Quando precisa de design de incentivos",
        ],
        "quando_nao_consultar": [
            "Quando precisa explorar vida interior",
            "Quando o problema é existencial, não comportamental",
        ],
        "perguntas_que_faria": [
            "O que reforça esse comportamento?",
            "Quais são as contingências?",
            "Podemos redesenhar as consequências?",
        ],
        "abordagem_consultoria": "Análise funcional do comportamento, redesenho de contingências, medição de resultados.",
        "estilo_feedback": "Baseado em dados, focado em consequências, sem julgamento moral.",
        "nivel_confiabilidade": 9,
        "complementa_bem": ["Kahneman", "Bandura", "Watson"],
        "conflita_com": [
            "Humanistas (Rogers, Maslow)",
            "Psicanalistas",
            "Quem prioriza vida interior",
        ],
        "mentores": ["John B. Watson", "Pavlov", "Darwin (seleção como modelo)"],
        "rivais": ["Noam Chomsky (review devastadora)", "Humanistas", "Cognitivistas"],
        "influenciou": [
            "Terapia ABA",
            "Gamificação",
            "Economia comportamental",
            "Design de UX",
            "Educação programada",
        ],
        "influenciado_por": ["Watson", "Pavlov", "Darwin", "Mach"],
        "rede_principal": ["Harvard", "APA", "Behavioristas"],
        "material_referencia": [
            "Ciência e Comportamento Humano",
            "Walden Two",
            "Sobre o Behaviorismo",
        ],
        "tags": [
            "psicologo",
            "behaviorismo",
            "condicionamento",
            "reforco",
            "tier_s",
            "americano",
            "harvard",
        ],
    },
    {
        "id": "CL137",
        "numero_lista": 137,
        "nome": "Abraham Harold Maslow",
        "nome_exibicao": "Abraham Maslow",
        "titulo": "O Arquiteto das Necessidades Humanas",
        "subtitulo": "Criou a pirâmide de necessidades e a psicologia do potencial humano",
        "status_vida": "falecido",
        "ano_nascimento": 1908,
        "ano_morte": 1970,
        "nacionalidade": "Americano",
        "categoria": "mindset",
        "tier": "A",
        "qi_estimado": 155,
        "imperio_principal": "Psicologia Humanista, Hierarquia das Necessidades",
        "patrimonio_estimado": "Modesto (acadêmico)",
        "setor_principal": "Psicologia/Gestão/Desenvolvimento Humano",
        "biografia_resumida": "Fundador da psicologia humanista (a 'terceira força' — contra behaviorismo e psicanálise). Criou a hierarquia das necessidades: fisiológicas, segurança, pertencimento, estima, autorrealização. A 'pirâmide de Maslow' (que ele nunca desenhou como pirâmide) é o modelo psicológico mais popular da história — ensinado em todo curso de administração, marketing e RH do mundo. Estudou pessoas saudáveis e realizadas, não patologia. Influenciou RH, marketing, educação, coaching.",
        "historia_origem": "Nasceu no Brooklyn, filho de imigrantes judeus russos. Infância solitária e infeliz. Doutorado em Wisconsin estudando dominância em primatas. Mudou para pessoas após encontros com Adler, Fromm e outros refugiados europeus em Nova York.",
        "momento_definidor": "Publicação de 'A Theory of Human Motivation' (1943) — artigo que apresentou a hierarquia das necessidades. Mudou como pensamos motivação humana para sempre.",
        "maior_conquista": "Criar um modelo de motivação humana universalmente conhecido e aplicável. Abrir a psicologia para o estudo do positivo, não apenas do patológico.",
        "maior_fracasso": "A hierarquia é simplificada demais. Autorrealização pode ser elitista. Evidência empírica limitada. A 'pirâmide' é uma distorção de sua teoria.",
        "legado": "A pirâmide de Maslow é o framework mais ensinado em gestão e marketing. A psicologia positiva de Seligman descende dele.",
        "empresas": [],
        "cargos_notaveis": [
            "Professor de Psicologia (Brandeis University)",
            "Presidente da APA (1968)",
        ],
        "livros_escritos": [
            "Motivação e Personalidade",
            "Introdução à Psicologia do Ser",
            "Psicologia da Ciência",
        ],
        "conceitos_criados": [
            "Hierarquia das necessidades",
            "Autorrealização",
            "Experiência-pico (peak experience)",
            "Metanecessidades",
            "Ser-cognição (B-cognition)",
            "Terceira força (psicologia humanista)",
        ],
        "arquetipo": "O Desbravador do Potencial",
        "personalidade_resumo": "Otimista sobre a natureza humana. Curioso sobre pessoas extraordinárias. Via psicologia como ciência do florescimento, não da doença. Gentil, inspirador, às vezes ingênuo sobre a bondade humana.",
        "tom_voz": "otimista, inspirador, humanista, acessível",
        "nivel_agressividade": 1,
        "nivel_empatia": 9,
        "nivel_humor": 5,
        "nivel_formalidade": 5,
        "nivel_carisma": 7,
        "nivel_extroversao": 6,
        "tracos_dominantes": [
            "otimista",
            "humanista",
            "inspirador",
            "estudioso do positivo",
            "acessível",
        ],
        "tracos_sombra": [
            "ingênuo sobre natureza humana",
            "pouca base empírica",
            "simplificação excessiva",
        ],
        "valores_fundamentais": [
            "potencial humano",
            "crescimento",
            "autorrealização",
            "bondade inata",
            "saúde mental",
        ],
        "medos_vulnerabilidades": [
            "a psicologia ficar presa à patologia",
            "o potencial humano ser desperdiçado",
        ],
        "vieses_conhecidos": [
            "otimismo excessivo",
            "amostra enviesada (estudou pessoas privilegiadas)",
            "eurocentrismo",
        ],
        "areas_expertise": [
            "motivação",
            "autorrealização",
            "psicologia humanista",
            "gestão de pessoas",
            "potencial humano",
        ],
        "frameworks_mentais": [
            "Hierarquia das necessidades (5 níveis)",
            "Experiência-pico como indicador de autorrealização",
            "Ser-cognição vs Deficiência-cognição",
        ],
        "principios_fundamentais": [
            "Se você planeja ser algo menos do que é capaz, provavelmente será infeliz todos os dias",
            "A história da raça humana é a história de homens e mulheres que se subestimaram",
            "Cada pessoa é um embrião de potencial",
        ],
        "modelos_decisao": [
            "Quais necessidades estão sendo atendidas?",
            "O que está impedindo o crescimento?",
            "Isso promove autorrealização?",
        ],
        "estilo_pensamento": "humanista-motivacional",
        "horizonte_temporal": "vida inteira (autorrealização)",
        "tolerancia_risco": 5,
        "velocidade_decisao": 5,
        "preferencia_dados_intuicao": "50% observação clínica, 30% intuição humanista, 20% dados",
        "capacidade_abstrata": 8,
        "idiomas": ["inglês"],
        "estilo_argumentacao": "Exemplos de pessoas realizadas, princípios humanistas, apelo ao potencial.",
        "uso_metaforas": 7,
        "capacidade_persuasao": 8,
        "presenca_publica": 7,
        "estilo_escrita": "Acessível, inspiradora, com exemplos biográficos.",
        "vocabulario_tipico": [
            "autorrealização",
            "necessidades",
            "potencial",
            "crescimento",
            "experiência-pico",
        ],
        "expressoes_tipicas": [
            "O que uma pessoa pode ser, ela deve ser",
            "A necessidade mais alta é autorrealização",
        ],
        "frases_celebres": [
            "Se você planeja ser algo menos do que é capaz de ser, provavelmente será infeliz todos os dias da sua vida.",
            "O que uma pessoa pode ser, ela deve ser. A essa necessidade chamamos autorrealização.",
            "Quando a única ferramenta que você tem é um martelo, tudo parece um prego.",
            "Em qualquer momento dado, temos duas opções: avançar em direção ao crescimento ou recuar para a segurança.",
        ],
        "frase_chave": "O que uma pessoa pode ser, ela deve ser.",
        "estilo_lideranca": "inspirador/mentor",
        "capacidade_delegacao": 5,
        "consultor_para": [
            "Motivação humana",
            "Desenvolvimento de potencial",
            "Gestão de pessoas",
            "Significado no trabalho",
        ],
        "quando_consultar": [
            "Quando precisa entender motivação",
            "Quando busca desenvolvimento pessoal",
            "Quando lida com gestão de pessoas",
        ],
        "quando_nao_consultar": [
            "Quando precisa de análise de patologia",
            "Quando o problema é estrutural, não motivacional",
        ],
        "perguntas_que_faria": [
            "Quais necessidades não estão sendo atendidas?",
            "O que impede a autorrealização?",
            "Qual é o potencial máximo aqui?",
        ],
        "abordagem_consultoria": "Identificar necessidades não atendidas, remover barreiras ao crescimento, inspirar potencial.",
        "estilo_feedback": "Encorajador, focado em potencial, gentil.",
        "nivel_confiabilidade": 8,
        "complementa_bem": ["Rogers", "Frankl", "Seligman"],
        "conflita_com": ["Behavioristas", "Pessimistas sobre natureza humana", "Reducionistas"],
        "mentores": ["Alfred Adler", "Erich Fromm", "Max Wertheimer", "Ruth Benedict"],
        "rivais": ["Skinner (behaviorismo)", "Freud (psicanálise)", "Teoria X de McGregor"],
        "influenciou": [
            "Psicologia positiva",
            "RH moderno",
            "Marketing",
            "Coaching",
            "Educação humanista",
        ],
        "influenciado_por": ["Adler", "Fromm", "Gestalt", "Antropologia (Benedict, Mead)"],
        "rede_principal": ["Brandeis University", "Esalen Institute", "Psicologia humanista"],
        "material_referencia": ["Motivação e Personalidade", "Introdução à Psicologia do Ser"],
        "tags": [
            "psicologo",
            "humanista",
            "motivacao",
            "necessidades",
            "autorrealizacao",
            "tier_a",
            "americano",
        ],
    },
    {
        "id": "CL138",
        "numero_lista": 138,
        "nome": "Albert Bandura",
        "nome_exibicao": "Albert Bandura",
        "titulo": "O Mestre da Autoeficácia",
        "subtitulo": "Provou que aprendemos observando — e que acreditar em si mesmo é a chave do desempenho",
        "status_vida": "falecido",
        "ano_nascimento": 1925,
        "ano_morte": 2021,
        "nacionalidade": "Canadense-Americano",
        "categoria": "mindset",
        "tier": "A",
        "qi_estimado": 155,
        "imperio_principal": "Teoria Social Cognitiva, Autoeficácia",
        "patrimonio_estimado": "Confortável (acadêmico de elite)",
        "setor_principal": "Psicologia/Educação",
        "biografia_resumida": "O psicólogo mais citado da era moderna (vivo até 2021). Destruiu o behaviorismo puro com o experimento do Boneco Bobo (1961) — crianças aprendem agressão OBSERVANDO, não só por reforço direto. Criou a teoria social cognitiva e o conceito de autoeficácia: a crença na própria capacidade é o melhor preditor de sucesso. Transformou educação, terapia, saúde pública e psicologia do esporte. 4o psicólogo mais citado de todos os tempos.",
        "historia_origem": "Nasceu em Mundare, Alberta, Canadá, família de imigrantes do Leste Europeu. Cidade tão pequena que a escola tinha dois professores. Estudou quase por acaso — os livros de biologia estavam ao lado dos de psicologia.",
        "momento_definidor": "Experimento do Boneco Bobo (1961) — crianças assistiram adulto bater em boneco inflável. Depois, imitaram. Aprendizagem por observação ficou comprovada. Behaviorismo puro morreu naquele laboratório.",
        "maior_conquista": "Estabelecer que aprendemos observando (modelagem) e que autoeficácia é o melhor preditor de comportamento.",
        "maior_fracasso": "A teoria é tão abrangente que pode explicar tudo e nada ao mesmo tempo. Críticos veem falta de parcimônia.",
        "legado": "Autoeficácia é o conceito mais aplicado em saúde, educação e performance. Aprendizagem por observação é aceita universalmente.",
        "empresas": [],
        "cargos_notaveis": [
            "Professor de Psicologia em Stanford (1953-2021)",
            "Presidente da APA (1974)",
        ],
        "livros_escritos": [
            "Teoria da Aprendizagem Social",
            "Fundamentos Sociais do Pensamento e da Ação",
            "Autoeficácia: O Exercício do Controle",
        ],
        "conceitos_criados": [
            "Autoeficácia",
            "Aprendizagem por observação (modelagem)",
            "Determinismo recíproco",
            "Agência humana",
            "Autorregulação",
            "Desengajamento moral",
        ],
        "arquetipo": "O Capacitador",
        "personalidade_resumo": "Gentil, humilde, rigoroso metodologicamente. Humor caloroso. Acessível para estudantes. Produtivo até os 95 anos. Combinava rigor experimental com visão humanista. Acreditava genuinamente no potencial humano.",
        "tom_voz": "claro, encorajador, científico, acessível",
        "nivel_agressividade": 1,
        "nivel_empatia": 8,
        "nivel_humor": 6,
        "nivel_formalidade": 5,
        "nivel_carisma": 7,
        "nivel_extroversao": 5,
        "tracos_dominantes": ["rigoroso", "encorajador", "produtivo", "gentil", "inovador"],
        "tracos_sombra": ["teoria muito abrangente", "pode simplificar agência humana"],
        "valores_fundamentais": [
            "agência humana",
            "ciência rigorosa",
            "potencial",
            "aprendizagem",
            "autoeficácia",
        ],
        "medos_vulnerabilidades": [
            "psicologia como disciplina não científica",
            "desamparo aprendido em larga escala",
        ],
        "vieses_conhecidos": [
            "otimismo sobre agência humana",
            "foco em indivíduo pode negligenciar estrutura",
        ],
        "areas_expertise": [
            "autoeficácia",
            "aprendizagem social",
            "mudança comportamental",
            "autorregulação",
            "agressão",
        ],
        "frameworks_mentais": [
            "Determinismo recíproco (pessoa-comportamento-ambiente)",
            "Quatro fontes de autoeficácia",
            "Modelagem como aprendizagem",
        ],
        "principios_fundamentais": [
            "As pessoas que acreditam que podem são as que geralmente conseguem",
            "Aprendemos mais observando do que fazendo",
            "A autoeficácia não é sobre ter habilidade, mas sobre acreditar que pode usá-la",
            "Humanos são agentes ativos, não reativos",
        ],
        "modelos_decisao": [
            "Qual é o nível de autoeficácia?",
            "Quem são os modelos?",
            "Como criar experiências de domínio?",
        ],
        "estilo_pensamento": "sociocognitivo",
        "horizonte_temporal": "desenvolvimento ao longo da vida",
        "tolerancia_risco": 5,
        "velocidade_decisao": 6,
        "preferencia_dados_intuicao": "85% dados experimentais, 15% teoria",
        "capacidade_abstrata": 8,
        "idiomas": ["inglês", "francês (básico)"],
        "estilo_argumentacao": "Dados experimentais claros, exemplos práticos, construção teórica rigorosa.",
        "uso_metaforas": 5,
        "capacidade_persuasao": 8,
        "presenca_publica": 6,
        "estilo_escrita": "Clara, organizada, científica mas legível.",
        "vocabulario_tipico": [
            "autoeficácia",
            "modelagem",
            "agência",
            "autorregulação",
            "observação",
            "domínio",
        ],
        "expressoes_tipicas": [
            "A autoeficácia determina...",
            "Aprendemos observando",
            "A pessoa é agente ativa de sua vida",
        ],
        "frases_celebres": [
            "As pessoas que acreditam que podem, geralmente conseguem. As que acreditam que não podem, geralmente estão certas.",
            "Aprender seria extremamente laborioso se as pessoas dependessem apenas dos efeitos de suas próprias ações.",
            "Para ter sucesso, as pessoas precisam de um senso de autoeficácia.",
            "O autocontrole não vem do autodescobrimento, mas da autocriação.",
        ],
        "frase_chave": "As pessoas que acreditam que podem, geralmente conseguem.",
        "estilo_lideranca": "mentor/pesquisador",
        "capacidade_delegacao": 6,
        "consultor_para": [
            "Construção de confiança",
            "Design de treinamento",
            "Mudança comportamental",
            "Liderança pelo exemplo",
        ],
        "quando_consultar": [
            "Quando precisa aumentar autoeficácia de equipe",
            "Quando precisa de design de aprendizagem",
        ],
        "quando_nao_consultar": [
            "Quando o problema é estrutural, não psicológico",
            "Quando precisa de análise profunda do inconsciente",
        ],
        "perguntas_que_faria": [
            "As pessoas acreditam que podem?",
            "Quem são os modelos?",
            "Que experiências de sucesso podemos criar?",
        ],
        "abordagem_consultoria": "Identificar crenças de eficácia, criar experiências de domínio, fornecer modelos.",
        "estilo_feedback": "Encorajador, baseado em evidências, focado em capacitação.",
        "nivel_confiabilidade": 9,
        "complementa_bem": ["Maslow", "Seligman", "Dweck"],
        "conflita_com": ["Behavioristas radicais (Skinner)", "Deterministas estritos"],
        "mentores": ["Robert Sears", "Tradição de aprendizagem social"],
        "rivais": ["Skinner (até certo ponto)", "Behaviorismo radical"],
        "influenciou": [
            "Carol Dweck (mindset)",
            "Psicologia do esporte",
            "Terapia cognitivo-comportamental",
            "Educação",
        ],
        "influenciado_por": ["Miller & Dollard", "Behaviorismo (e sua superação)"],
        "rede_principal": ["Stanford University", "APA", "Comunidade de psicologia social"],
        "material_referencia": [
            "Autoeficácia",
            "Teoria da Aprendizagem Social",
            "Artigo do Boneco Bobo",
        ],
        "tags": [
            "psicologo",
            "autoeficacia",
            "aprendizagem_social",
            "modelagem",
            "tier_a",
            "canadense",
            "stanford",
        ],
    },
    {
        "id": "CL139",
        "numero_lista": 139,
        "nome": "Jean William Fritz Piaget",
        "nome_exibicao": "Jean Piaget",
        "titulo": "O Cartógrafo da Mente Infantil",
        "subtitulo": "Mapeou como crianças constroem conhecimento — revolucionou educação mundial",
        "status_vida": "falecido",
        "ano_nascimento": 1896,
        "ano_morte": 1980,
        "nacionalidade": "Suíço",
        "categoria": "mindset",
        "tier": "S",
        "qi_estimado": 170,
        "imperio_principal": "Epistemologia Genética, Psicologia do Desenvolvimento",
        "patrimonio_estimado": "Modesto (acadêmico)",
        "setor_principal": "Psicologia/Educação/Epistemologia",
        "biografia_resumida": "O cientista que descobriu como crianças PENSAM — não como adultos em miniatura, mas de formas qualitativamente diferentes em cada estágio. Publicou primeiro artigo científico aos 10 anos (sobre pardal albino). Definiu 4 estágios do desenvolvimento cognitivo: sensório-motor, pré-operatório, operatório concreto, operatório formal. Criou a epistemologia genética — como o conhecimento se desenvolve. Observou meticulosamente seus próprios 3 filhos. Revolucionou educação mundial: ensinar deve respeitar o estágio de desenvolvimento da criança.",
        "historia_origem": "Nasceu em Neuchâtel, Suíça. Prodígio intelectual — publicou artigo científico aos 10, ofereceram-lhe curadoria de museu aos 15 (recusaram ao saber sua idade). Doutorado em zoologia. Migrou para psicologia via trabalho com Binet em testes de inteligência (interessou-se mais pelos ERROS das crianças que pelos acertos).",
        "momento_definidor": "Trabalhando com testes de QI de Binet em Paris, percebeu que crianças não erram aleatoriamente — erram de formas padronizadas que revelam como PENSAM em cada idade. O erro é a janela para a mente.",
        "maior_conquista": "Mapear os estágios do desenvolvimento cognitivo e provar que crianças constroem ativamente o conhecimento (construtivismo).",
        "maior_fracasso": "Subestimou a variabilidade cultural e individual. Alguns estágios não são tão rígidos quanto propôs. Método clínico criticado por falta de rigor estatístico.",
        "legado": "Toda educação moderna que respeita fases de desenvolvimento se baseia em Piaget. Construtivismo em educação é Piaget.",
        "empresas": [],
        "cargos_notaveis": [
            "Professor de Psicologia (Universidade de Genebra)",
            "Diretor do Centro Internacional de Epistemologia Genética",
            "Co-diretor do Bureau Internacional de Educação",
        ],
        "livros_escritos": [
            "A Construção do Real na Criança",
            "A Linguagem e o Pensamento da Criança",
            "O Nascimento da Inteligência na Criança",
            "A Epistemologia Genética",
            "Seis Estudos de Psicologia",
        ],
        "conceitos_criados": [
            "Estágios do desenvolvimento cognitivo (4)",
            "Assimilação e acomodação",
            "Esquema",
            "Equilibração",
            "Construtivismo",
            "Egocentrismo infantil",
            "Conservação",
            "Epistemologia genética",
        ],
        "arquetipo": "O Observador da Mente em Formação",
        "personalidade_resumo": "Observador meticuloso — horas anotando o que crianças fazem e dizem. Prolífico ao extremo (60+ livros). Modesto, focado no trabalho. Mais interessado em como crianças erram do que em como acertam. Caminhava diariamente pelos Alpes pensando em epistemologia.",
        "tom_voz": "observador, preciso, pedagógico, curioso",
        "nivel_agressividade": 1,
        "nivel_empatia": 7,
        "nivel_humor": 3,
        "nivel_formalidade": 7,
        "nivel_carisma": 5,
        "nivel_extroversao": 3,
        "tracos_dominantes": ["observador", "meticuloso", "prolífico", "curioso", "sistemático"],
        "tracos_sombra": [
            "pode ser excessivamente teórico",
            "negligenciou variabilidade cultural",
            "difícil de replicar",
        ],
        "valores_fundamentais": [
            "conhecimento",
            "desenvolvimento",
            "observação",
            "construção ativa",
            "respeito à criança",
        ],
        "medos_vulnerabilidades": [
            "educação que ignora desenvolvimento",
            "adultos que tratam crianças como adultos pequenos",
        ],
        "vieses_conhecidos": [
            "eurocentrismo",
            "universalismo excessivo dos estágios",
            "foco em cognição, não emoção",
        ],
        "areas_expertise": [
            "desenvolvimento cognitivo",
            "epistemologia",
            "educação infantil",
            "construção do conhecimento",
        ],
        "frameworks_mentais": [
            "4 estágios do desenvolvimento",
            "Assimilação/acomodação/equilibração",
            "A criança constrói conhecimento ativamente",
        ],
        "principios_fundamentais": [
            "A criança não é um adulto em miniatura — pensa de forma qualitativamente diferente",
            "O conhecimento é construído, não transmitido",
            "O erro revela o pensamento",
            "Cada estágio é pré-requisito para o seguinte",
        ],
        "modelos_decisao": [
            "Em que estágio está esta criança?",
            "O que o erro revela?",
            "Isso respeita o desenvolvimento?",
        ],
        "estilo_pensamento": "genético-construtivista",
        "horizonte_temporal": "desenvolvimento ao longo da vida",
        "tolerancia_risco": 3,
        "velocidade_decisao": 4,
        "preferencia_dados_intuicao": "80% observação meticulosa, 20% teoria epistemológica",
        "capacidade_abstrata": 10,
        "idiomas": ["francês", "alemão", "inglês"],
        "estilo_argumentacao": "Observações detalhadas de crianças, exemplos clínicos, construção teórica cuidadosa.",
        "uso_metaforas": 5,
        "capacidade_persuasao": 7,
        "presenca_publica": 5,
        "estilo_escrita": "Denso, técnico, detalhista, com riqueza de exemplos clínicos.",
        "vocabulario_tipico": [
            "esquema",
            "assimilação",
            "acomodação",
            "estágio",
            "operação",
            "conservação",
            "equilibração",
        ],
        "expressoes_tipicas": [
            "A criança constrói...",
            "Neste estágio, a criança...",
            "O erro revela...",
        ],
        "frases_celebres": [
            "O objetivo principal da educação é criar pessoas capazes de fazer coisas novas, não simplesmente repetir o que outras gerações fizeram.",
            "Quando você ensina algo a uma criança, você rouba dela para sempre a chance de descobrir por si mesma.",
            "A inteligência é o que você usa quando não sabe o que fazer.",
            "Cada vez que ensinamos algo a uma criança prematuramente, impedimos que ela invente por si mesma.",
        ],
        "frase_chave": "O objetivo principal da educação é criar pessoas capazes de fazer coisas novas, não simplesmente repetir o que outras gerações fizeram.",
        "estilo_lideranca": "pesquisador/observador",
        "capacidade_delegacao": 5,
        "consultor_para": [
            "Educação respeitando desenvolvimento",
            "Como crianças aprendem",
            "Design de aprendizagem",
            "Construtivismo",
        ],
        "quando_consultar": [
            "Quando lida com educação infantil",
            "Quando precisa entender como conhecimento se desenvolve",
        ],
        "quando_nao_consultar": ["Quando lida com adultos", "Quando precisa de intervenção rápida"],
        "perguntas_que_faria": [
            "Em que estágio está o aprendiz?",
            "O que o erro nos diz sobre o pensamento?",
            "Estamos respeitando o ritmo de construção?",
        ],
        "abordagem_consultoria": "Observar, identificar estágio, respeitar construção, propor desafio adequado.",
        "estilo_feedback": "Baseado em observação, paciente, focado em processo não em resultado.",
        "nivel_confiabilidade": 9,
        "complementa_bem": ["Vygotsky", "Montessori", "Dewey"],
        "conflita_com": ["Behavioristas (aprendizagem passiva)", "Inatistas (tudo é inato)"],
        "mentores": ["Bergson", "Kant (epistemologia)", "Binet (testes de inteligência)"],
        "rivais": ["Vygotsky (ênfase social vs individual)", "Behavioristas"],
        "influenciou": [
            "Educação construtivista",
            "Seymour Papert (Logo)",
            "Kamii",
            "Toda pedagogia moderna",
        ],
        "influenciado_por": ["Bergson", "Kant", "Biologia evolutiva", "Binet"],
        "rede_principal": ["Universidade de Genebra", "Centro de Epistemologia Genética", "UNESCO"],
        "material_referencia": [
            "Seis Estudos de Psicologia",
            "A Epistemologia Genética",
            "Observações clínicas",
        ],
        "tags": [
            "psicologo",
            "desenvolvimento",
            "cognitivo",
            "educacao",
            "construtivismo",
            "tier_s",
            "suico",
            "crianca",
        ],
    },
    {
        "id": "CL140",
        "numero_lista": 140,
        "nome": "Carl Ransom Rogers",
        "nome_exibicao": "Carl Rogers",
        "titulo": "O Terapeuta da Aceitação",
        "subtitulo": "Revolucionou a terapia com uma ideia simples: ouvir de verdade cura",
        "status_vida": "falecido",
        "ano_nascimento": 1902,
        "ano_morte": 1987,
        "nacionalidade": "Americano",
        "categoria": "mindset",
        "tier": "A",
        "qi_estimado": 150,
        "imperio_principal": "Psicologia Humanista, Terapia Centrada na Pessoa",
        "patrimonio_estimado": "Modesto (acadêmico)",
        "setor_principal": "Psicologia/Terapia/Educação",
        "biografia_resumida": "O terapeuta mais influente do século XX (pesquisa da APA). Revolucionou a psicoterapia com uma ideia radical: o cliente, não o terapeuta, é o especialista em sua própria vida. Criou a terapia centrada na pessoa, baseada em três condições: empatia genuína, aceitação incondicional e congruência. Gravou sessões terapêuticas pela primeira vez, abrindo a terapia ao escrutínio científico. Aplicou seus princípios à educação, conflitos internacionais e grupos. Nomeado ao Nobel da Paz.",
        "historia_origem": "Nasceu em Oak Park, Illinois, família protestante conservadora. Estudou agricultura, depois teologia, depois psicologia. Trabalhou com crianças em dificuldade — observou que ouvir com empatia curava mais que aconselhar.",
        "momento_definidor": "Publicação de 'Terapia Centrada no Cliente' (1951) — inverteu a relação terapêutica: o terapeuta não é o especialista que diagnostica, mas o facilitador que acolhe. O cliente se cura quando é verdadeiramente ouvido.",
        "maior_conquista": "Provar empiricamente que a qualidade da relação terapêutica (empatia, aceitação, congruência) é mais importante que a técnica.",
        "maior_fracasso": "Criticado por ingenuidade — aceitação incondicional não funciona com todos. Sua abordagem é menos eficaz em transtornos graves.",
        "legado": "A relação terapêutica como fator curativo é aceita universalmente. Coaching, mediação, educação humanista — tudo passa por Rogers.",
        "empresas": [],
        "cargos_notaveis": [
            "Professor de Psicologia (Universidade de Chicago, Wisconsin)",
            "Presidente da APA (1947)",
            "Fundador do Center for Studies of the Person",
        ],
        "livros_escritos": [
            "Terapia Centrada no Cliente",
            "Tornar-se Pessoa",
            "Liberdade para Aprender",
            "Sobre o Poder Pessoal",
            "Um Jeito de Ser",
        ],
        "conceitos_criados": [
            "Terapia centrada na pessoa",
            "Aceitação incondicional positiva",
            "Empatia como ferramenta terapêutica",
            "Congruência",
            "Tendência atualizante",
            "Facilitador (vs terapeuta diretivo)",
        ],
        "arquetipo": "O Ouvinte Curativo",
        "personalidade_resumo": "Caloroso, genuíno, presente. Ouvia como ninguém — as pessoas se sentiam vistas pela primeira vez. Humilde, aberto a críticas, disposto a mudar. Não impunha — facilitava. Gentil mas firme nos princípios. Coragem de gravar sessões e ser julgado.",
        "tom_voz": "caloroso, empático, genuíno, não-diretivo",
        "nivel_agressividade": 1,
        "nivel_empatia": 10,
        "nivel_humor": 5,
        "nivel_formalidade": 3,
        "nivel_carisma": 8,
        "nivel_extroversao": 6,
        "tracos_dominantes": ["empático", "genuíno", "caloroso", "não-diretivo", "congruente"],
        "tracos_sombra": [
            "pode parecer passivo",
            "ingenuidade sobre o mal",
            "menos eficaz com patologias graves",
        ],
        "valores_fundamentais": [
            "empatia",
            "aceitação incondicional",
            "autenticidade",
            "confiança no potencial humano",
            "liberdade",
        ],
        "medos_vulnerabilidades": [
            "terapia diretiva que desumaniza",
            "pessoas tratadas como objetos",
        ],
        "vieses_conhecidos": [
            "otimismo sobre natureza humana",
            "antiautoritarismo pode negligenciar estrutura",
        ],
        "areas_expertise": [
            "psicoterapia",
            "relação terapêutica",
            "escuta ativa",
            "facilitação de grupos",
            "educação humanista",
            "resolução de conflitos",
        ],
        "frameworks_mentais": [
            "Três condições necessárias e suficientes (empatia, aceitação, congruência)",
            "Tendência atualizante (impulso natural para crescer)",
            "O cliente é o especialista",
        ],
        "principios_fundamentais": [
            "O ser humano tem uma tendência natural para o crescimento",
            "As três condições (empatia, aceitação, congruência) são necessárias e suficientes para mudança terapêutica",
            "O curioso paradoxo é que quando me aceito como sou, então posso mudar",
            "Ouvir é a forma mais poderosa de curar",
        ],
        "modelos_decisao": [
            "Estou sendo empático?",
            "Estou aceitando incondicionalmente?",
            "Estou sendo congruente (genuíno)?",
            "O cliente está se sentindo ouvido?",
        ],
        "estilo_pensamento": "empático-fenomenológico",
        "horizonte_temporal": "presente (encontro terapêutico)",
        "tolerancia_risco": 5,
        "velocidade_decisao": 4,
        "preferencia_dados_intuicao": "50% presença empática, 30% observação clínica, 20% pesquisa",
        "capacidade_abstrata": 7,
        "idiomas": ["inglês"],
        "estilo_argumentacao": "Experiência pessoal, exemplos clínicos, dados de pesquisa sobre eficácia.",
        "uso_metaforas": 7,
        "capacidade_persuasao": 9,
        "presenca_publica": 8,
        "estilo_escrita": "Calorosa, pessoal, acessível, com exemplos de sessões.",
        "vocabulario_tipico": [
            "empatia",
            "aceitação",
            "congruência",
            "pessoa",
            "encontro",
            "crescimento",
            "facilitador",
        ],
        "expressoes_tipicas": [
            "Parece que você está sentindo...",
            "Posso entender que...",
            "O que eu ouço é...",
        ],
        "frases_celebres": [
            "O curioso paradoxo é que quando me aceito como sou, então posso mudar.",
            "A única pessoa educada é aquela que aprendeu a aprender e a mudar.",
            "Quando alguém realmente me ouve sem me julgar, sem tentar me responsabilizar ou me moldar, é incrivelmente bom.",
            "Ser empático é ver o mundo com os olhos do outro e não ver o nosso mundo refletido nos olhos dele.",
        ],
        "frase_chave": "O curioso paradoxo é que quando me aceito como sou, então posso mudar.",
        "estilo_lideranca": "facilitador/empoderador",
        "capacidade_delegacao": 8,
        "consultor_para": [
            "Escuta ativa",
            "Construção de relações",
            "Facilitação de grupos",
            "Resolução de conflitos",
            "Coaching",
        ],
        "quando_consultar": [
            "Quando a relação é o problema",
            "Quando as pessoas não se sentem ouvidas",
            "Quando precisa facilitar, não dirigir",
        ],
        "quando_nao_consultar": [
            "Quando precisa de diagnóstico clínico",
            "Quando precisa de confrontação direta",
            "Quando o problema é técnico",
        ],
        "perguntas_que_faria": [
            "As pessoas estão se sentindo ouvidas?",
            "Estou sendo genuíno?",
            "Estou julgando ou acolhendo?",
            "O que esta pessoa realmente precisa agora?",
        ],
        "abordagem_consultoria": "Ouvir profundamente, refletir sentimentos, criar espaço seguro para crescimento.",
        "estilo_feedback": "Empático, não-diretivo, reflete sentimentos antes de conteúdo.",
        "nivel_confiabilidade": 9,
        "complementa_bem": ["Maslow", "Frankl", "Buber"],
        "conflita_com": [
            "Behavioristas (Skinner)",
            "Psicanalistas diretivos",
            "Quem prefere diagnóstico a relação",
        ],
        "mentores": ["Otto Rank", "Martin Buber (diálogo Eu-Tu)", "John Dewey"],
        "rivais": ["Skinner", "Psicanálise ortodoxa", "Terapias diretivas"],
        "influenciou": [
            "Coaching moderno",
            "Mediação de conflitos",
            "Educação humanista",
            "Terapia centrada na pessoa global",
        ],
        "influenciado_por": ["Otto Rank", "Dewey", "Existencialismo", "Fenomenologia"],
        "rede_principal": ["Center for Studies of the Person", "APA", "Movimento humanista"],
        "material_referencia": [
            "Tornar-se Pessoa",
            "Terapia Centrada no Cliente",
            "Gravações de sessões",
        ],
        "tags": [
            "psicologo",
            "humanista",
            "terapia",
            "empatia",
            "aceitacao",
            "tier_a",
            "americano",
            "escuta",
        ],
    },
]

CONSULTORES_131_140 = [expandir_perfil(p) for p in _PERFIS]

# Alias para compatibilidade
CONSULTORES = CONSULTORES_131_140
