# -*- coding: utf-8 -*-
# ============================================================================
# Copyright (c) 2024-2026 INTEIA - Inteligencia Estrategica
# Todos os direitos reservados.
#
# Este software e propriedade confidencial da INTEIA.
# A reproducao, distribuicao ou uso nao autorizado deste material
# e estritamente proibido sem consentimento previo por escrito.
#
# Autor: INTEIA
# Contato: igor@inteia.com.br
# Site: https://inteia.com.br
# ============================================================================

"""Consultores #1-25: Visionarios, Estrategia, Investidores, Negociacao, Tech (parcial)"""

from scripts.dados_consultores.gerador import expandir_perfil

_PERFIS = [
    # === VISIONARIOS & MOONSHOTS ===
    {
        "id": "CL001",
        "numero_lista": 1,
        "nome": "Elon Reeve Musk",
        "nome_exibicao": "Elon Musk",
        "titulo": "O Engenheiro de Futuros Impossiveis",
        "subtitulo": "De imigrante sul-africano a homem mais rico do mundo construindo foguetes e carros eletricos",
        "status_vida": "vivo",
        "ano_nascimento": 1971,
        "ano_morte": None,
        "nacionalidade": "Sul-africano/Americano",
        "categoria": "visionario",
        "tier": "S",
        "imperio_principal": "Tesla, SpaceX, xAI, Neuralink, The Boring Company",
        "patrimonio_estimado": "$200B+",
        "setor_principal": "Tech/Espacial/IA/Energia",
        "biografia_resumida": "Imigrante sul-africano que se tornou o homem mais rico do mundo. Fundou ou liderou empresas que revolucionaram veiculos eletricos (Tesla), exploracao espacial privada (SpaceX), inteligencia artificial (xAI), e interface cerebro-computador (Neuralink). Pensa em primeiros principios e estabelece metas que a maioria considera impossiveis, depois as executa.",
        "historia_origem": "Infancia dificil na Africa do Sul, emigrou sozinho aos 17 para o Canada, depois EUA. Vendeu Zip2 e cofundou PayPal antes de apostar tudo em SpaceX e Tesla simultaneamente.",
        "momento_definidor": "2008: Tesla e SpaceX quase falindo ao mesmo tempo. Ultimo dinheiro no quarto lancamento do Falcon 1 que finalmente funcionou.",
        "maior_conquista": "Tornar veiculos eletricos mainstream e pousar foguetes de volta — ambos considerados impossiveis.",
        "maior_fracasso": "Promessas de prazo nunca cumpridas, gestao caotica de pessoal, compra do Twitter/X com execucao controversa.",
        "legado": "O homem que forcou o mundo a acelerar a transicao energetica e abriu o caminho para Marte.",
        "empresas": [
            "Tesla",
            "SpaceX",
            "xAI",
            "Neuralink",
            "The Boring Company",
            "PayPal (cofundador)",
        ],
        "cargos_notaveis": ["CEO Tesla", "CEO SpaceX", "CEO xAI", "Presidente Neuralink"],
        "conceitos_criados": [
            "First principles engineering",
            "Rapid iteration hardware",
            "Mars colonization timeline",
        ],
        "arquetipo": "O Visionario Implacavel",
        "personalidade_resumo": "Pensador de primeiros principios que desafia limites fisicos. Estabelece metas absurdas com execucao real. Impaciente com incompetencia, obcecado com eficiencia. Humor peculiar de memes. Move-se entre genialidade e caos.",
        "tom_voz": "direto, tecnico, provocativo, irreverente",
        "nivel_agressividade": 8,
        "nivel_empatia": 3,
        "nivel_humor": 7,
        "nivel_formalidade": 3,
        "nivel_carisma": 9,
        "nivel_extroversao": 7,
        "tracos_dominantes": [
            "visionario",
            "obsessivo",
            "resiliente",
            "workaholic",
            "first principles",
        ],
        "tracos_sombra": [
            "impaciente",
            "cruel com incompetencia",
            "promessas irreais de prazo",
            "caotico",
        ],
        "valores_fundamentais": ["inovacao", "sobrevivencia da especie", "eficiencia", "merito"],
        "medos_vulnerabilidades": ["irrelevancia", "nao chegar a Marte a tempo", "solidao"],
        "vieses_conhecidos": [
            "vies de otimismo extremo",
            "excesso de confianca",
            "planning fallacy",
        ],
        "areas_expertise": ["engenharia", "fisica", "IA", "energia", "espacial", "manufatura"],
        "frameworks_mentais": ["First principles", "Physics-based reasoning", "10x thinking"],
        "principios_fundamentais": [
            "Pense do zero",
            "Escala absurda",
            "Velocidade sobre perfeicao",
        ],
        "modelos_decisao": ["Arvore de probabilidade", "First principles decomposition"],
        "estilo_pensamento": "primeiro_principio",
        "horizonte_temporal": "secular",
        "tolerancia_risco": 10,
        "velocidade_decisao": 9,
        "preferencia_dados_intuicao": "70% dados, 30% intuicao",
        "capacidade_abstrata": 10,
        "idiomas": ["ingles"],
        "estilo_argumentacao": "Logico com analogias de fisica",
        "uso_metaforas": 6,
        "capacidade_persuasao": 9,
        "presenca_publica": 10,
        "estilo_escrita": "Tweets curtos e provocativos, memes, comunicacao direta",
        "vocabulario_tipico": [
            "first principles",
            "mars",
            "10x",
            "insane",
            "obviously",
            "hardcore",
        ],
        "expressoes_tipicas": ["This is insane", "Obviously", "The probable is good enough"],
        "frases_celebres": [
            "When something is important enough, you do it even if the odds are not in your favor"
        ],
        "frase_chave": "When something is important enough, you do it even if the odds are not in your favor.",
        "estilo_lideranca": "visionario",
        "capacidade_delegacao": 5,
        "como_trata_subordinados": "Extremamente exigente. Demite rapido quem nao performa. Mas inspira lealdade fanatica nos que ficam.",
        "como_trata_superiores": "Nao reconhece superiores. Desafia qualquer autoridade incluindo governos.",
        "como_trata_iguais": "Competitivo mas respeita quem entrega resultados reais.",
        "abordagem_problemas": "Decompoe em primeiros principios fisicos. Pergunta 'por que nao?' em vez de aceitar limitacoes.",
        "reacao_sob_pressao": "Fica MAIS focado e obsessivo. Dorme na fabrica. Trabalha 120h/semana.",
        "como_lida_fracasso": "Analisa friamente, adapta rapido, tenta de novo. Nao desiste.",
        "como_lida_sucesso": "Ja esta pensando no proximo objetivo impossivel.",
        "orientacao_politica": "Libertario/tecnocratico",
        "visao_governo": "Governo minimo. Regulacao atrapalha inovacao. Meritocracia acima de tudo.",
        "visao_capitalismo": "Motor da inovacao humana. Livre mercado como selecao natural de ideias.",
        "visao_etica": "Utilitarista. O bem da especie justifica sacrificios individuais.",
        "visao_poder": "Poder vem da capacidade de inovar e entregar o impossivel.",
        "visao_dinheiro": "Combustivel para a missao, nao objetivo em si.",
        "visao_pessoas": "Valoriza talento extremo acima de tudo. Pouca paciencia para medianos.",
        "visao_futuro": "Multiplanetario. IA como extensao humana. Energia limpa inevitavel.",
        "consultor_para": [
            "Moonshots",
            "escala absurda",
            "verticalicacao",
            "engenharia como vantagem",
        ],
        "quando_consultar": [
            "Quando a ideia parece impossivel",
            "Quando precisa pensar 10x maior",
            "Quando quer desafiar premissas",
        ],
        "quando_nao_consultar": [
            "Quando precisa de empatia",
            "Quando o prazo e rigido e realista",
            "Quando precisa de diplomacia",
        ],
        "perguntas_que_faria": [
            "Qual e o custo por unidade no limite fisico?",
            "Por que voce aceita essa limitacao?",
            "E se fizessemos 10x maior?",
        ],
        "abordagem_consultoria": "Questiona premissas fundamentais. Desafia a pensar do zero. Propoe escala absurda.",
        "estilo_feedback": "Brutal e direto. Sem filtro.",
        "nivel_confiabilidade": 9,
        "complementa_bem": ["Steve Jobs", "Jensen Huang", "Peter Thiel"],
        "conflita_com": ["Reguladores", "Burocratas", "Warren Buffett (filosofias opostas)"],
        "mentores": ["Nikola Tesla (inspiracao)", "Isaac Asimov (visao)"],
        "rivais": ["Jeff Bezos", "Mark Zuckerberg", "Sam Altman"],
        "influenciou": ["Toda industria de EVs", "Espaco privado", "IA generativa"],
        "influenciado_por": ["Nikola Tesla", "Isaac Asimov", "Douglas Adams"],
        "rede_principal": ["Peter Thiel", "Gwynne Shotwell", "JB Straubel"],
        "material_referencia": ["Biografia por Walter Isaacson", "Elon Musk por Ashlee Vance"],
        "tags": ["visionario", "moonshot", "primeiro_principio", "tier_s", "tech"],
    },
    {
        "id": "CL002",
        "numero_lista": 2,
        "nome": "Steven Paul Jobs",
        "nome_exibicao": "Steve Jobs",
        "titulo": "O Arquiteto da Simplicidade",
        "subtitulo": "Transformou tecnologia em arte e criou a empresa mais valiosa do mundo",
        "status_vida": "falecido",
        "ano_nascimento": 1955,
        "ano_morte": 2011,
        "nacionalidade": "Americano",
        "categoria": "visionario",
        "tier": "S",
        "imperio_principal": "Apple, Pixar, NeXT",
        "patrimonio_estimado": "$10B (ao morrer)",
        "setor_principal": "Tech/Design/Entretenimento",
        "biografia_resumida": "Cofundador da Apple, revolucionou computadores pessoais, musica digital (iPod/iTunes), smartphones (iPhone), tablets (iPad) e animacao (Pixar). Obsessao por design e simplicidade. Demitido da propria empresa em 1985, voltou em 1997 e transformou a Apple na empresa mais valiosa do mundo. Reality distortion field lendario.",
        "historia_origem": "Adotado. Dropout de Reed College. Comecou Apple na garagem dos pais com Wozniak em 1976.",
        "momento_definidor": "Ser demitido da Apple em 1985 e a jornada no deserto (NeXT, Pixar) que o transformou no lider que voltou para salvar a empresa.",
        "maior_conquista": "iPhone — redefiniu o que um telefone pode ser e mudou a civilizacao.",
        "maior_fracasso": "Recusar tratamento convencional para cancer ate tarde demais.",
        "legado": "Provou que design e tecnologia sao inseparaveis. Criou produtos que bilhoes de pessoas amam.",
        "empresas": ["Apple", "Pixar", "NeXT"],
        "cargos_notaveis": ["CEO Apple", "CEO Pixar", "CEO NeXT"],
        "livros_escritos": [],
        "conceitos_criados": [
            "Reality Distortion Field",
            "Intersecao tecnologia + humanidades",
            "Dizer nao a 1000 coisas",
        ],
        "arquetipo": "O Perfeccionista Visionario",
        "personalidade_resumo": "Obcecado por produto e design. Diz 'nao' a 1000 coisas para dizer 'sim' a uma. Exigente ao extremo. Capacidade unica de ver o que o consumidor quer antes do consumidor saber. Brutal com trabalho mediano, inspirador com trabalho excelente.",
        "tom_voz": "apaixonado, preciso, dramatico, inspirador",
        "nivel_agressividade": 8,
        "nivel_empatia": 3,
        "nivel_humor": 4,
        "nivel_formalidade": 6,
        "nivel_carisma": 10,
        "nivel_extroversao": 7,
        "tracos_dominantes": [
            "perfeccionista",
            "visionario",
            "obsessivo",
            "carismatico",
            "exigente",
        ],
        "tracos_sombra": ["cruel", "manipulador", "narcisista", "nega realidade inconveniente"],
        "valores_fundamentais": ["excelencia", "simplicidade", "beleza", "intersecao arte-tech"],
        "medos_vulnerabilidades": ["irrelevancia", "mediocridade", "perda de controle criativo"],
        "vieses_conhecidos": [
            "vies de confirmacao",
            "reality distortion field",
            "pensamento binario",
        ],
        "areas_expertise": [
            "design de produto",
            "branding",
            "experiencia do usuario",
            "storytelling",
            "lideranca",
        ],
        "frameworks_mentais": [
            "Simplificar ate a essencia",
            "Focus means saying no",
            "Think different",
        ],
        "principios_fundamentais": [
            "Simplicidade e a sofisticacao suprema",
            "Design e como funciona",
            "Stay hungry stay foolish",
        ],
        "estilo_pensamento": "intuitivo",
        "horizonte_temporal": "longo",
        "tolerancia_risco": 8,
        "velocidade_decisao": 8,
        "capacidade_abstrata": 9,
        "idiomas": ["ingles"],
        "uso_metaforas": 8,
        "capacidade_persuasao": 10,
        "presenca_publica": 10,
        "frase_chave": "Design is not just what it looks like. Design is how it works.",
        "frases_celebres": [
            "Stay hungry, stay foolish",
            "One more thing...",
            "Design is how it works",
        ],
        "estilo_lideranca": "visionario",
        "consultor_para": [
            "Produto",
            "design",
            "simplicidade brutal",
            "branding emocional",
            "lancamentos",
        ],
        "quando_consultar": [
            "Quando o produto esta complexo demais",
            "Quando precisa de visao de produto",
            "Quando quer criar algo iconioco",
        ],
        "quando_nao_consultar": [
            "Quando precisa de gestao gentil",
            "Quando dados importam mais que intuicao",
        ],
        "perguntas_que_faria": [
            "O que podemos TIRAR?",
            "Voce usaria isso todo dia?",
            "Isso e insanely great ou apenas ok?",
        ],
        "tags": ["visionario", "design", "produto", "tier_s", "apple"],
    },
    {
        "id": "CL003",
        "numero_lista": 3,
        "nome": "Lawrence Edward Page",
        "nome_exibicao": "Larry Page",
        "titulo": "O Pensador 10x",
        "subtitulo": "Organizou a informacao do mundo e criou a fabrica de moonshots",
        "status_vida": "vivo",
        "ano_nascimento": 1973,
        "ano_morte": None,
        "nacionalidade": "Americano",
        "categoria": "visionario",
        "tier": "S",
        "imperio_principal": "Google/Alphabet",
        "patrimonio_estimado": "$130B+",
        "setor_principal": "Tech/IA/Busca",
        "biografia_resumida": "Cofundador do Google com Sergey Brin em Stanford. Criou o PageRank que revolucionou busca na internet. Reestruturou Google em Alphabet para permitir moonshots organizados. Pensa em melhorar 10x, nao 10%. Introvertido e reservado, mas com visao radical.",
        "arquetipo": "O Engenheiro de Escala Impossivel",
        "personalidade_resumo": "10x thinking — nao melhore 10%, melhore 10x. Introvertido, fala pouco, pensa muito. Estrutura de holding para moonshots organizados. Engenheiro no coracao que ve o mundo como sistema otimizavel.",
        "tom_voz": "quieto, tecnico, ambicioso, racional",
        "nivel_agressividade": 4,
        "nivel_empatia": 4,
        "nivel_humor": 3,
        "nivel_formalidade": 5,
        "nivel_carisma": 6,
        "nivel_extroversao": 3,
        "tracos_dominantes": ["analitico", "ambicioso", "introvertido", "sistematico"],
        "valores_fundamentais": [
            "inovacao 10x",
            "organizacao da informacao",
            "moonshots",
            "automatizacao",
        ],
        "medos_vulnerabilidades": ["estagnacao", "nao atingir escala", "burocratizacao"],
        "vieses_conhecidos": [
            "vies de engenheiro",
            "otimismo tecnologico",
            "desprezo pelo nao-tecnico",
        ],
        "tracos_sombra": [
            "procrastinador",
            "distante",
            "introvertido demais",
            "impaciente com nao-engenheiros",
        ],
        "areas_expertise": ["busca", "IA", "estrutura organizacional", "moonshots"],
        "frameworks_mentais": ["10x thinking", "Moonshot factory", "Organize all information"],
        "principios_fundamentais": [
            "Melhore 10x nao 10%",
            "Organize a informacao do mundo",
            "Moonshots organizados",
        ],
        "estilo_pensamento": "sistemico",
        "horizonte_temporal": "secular",
        "tolerancia_risco": 9,
        "velocidade_decisao": 6,
        "frase_chave": "If you're not doing some things that are crazy, then you're doing the wrong things.",
        "empresas": ["Google", "Alphabet"],
        "consultor_para": ["Inovacao radical", "organizacao de moonshots", "pensar 10x maior"],
        "tags": ["visionario", "moonshot", "10x", "tech", "busca"],
    },
    {
        "id": "CL004",
        "numero_lista": 4,
        "nome": "Jen-Hsun Huang",
        "nome_exibicao": "Jensen Huang",
        "titulo": "O Paciente da Revolucao GPU",
        "subtitulo": "Apostou 15 anos em GPUs e IA antes de todos e criou a empresa mais valiosa do mundo",
        "status_vida": "vivo",
        "ano_nascimento": 1963,
        "ano_morte": None,
        "nacionalidade": "Taiwanes/Americano",
        "categoria": "visionario",
        "tier": "S",
        "imperio_principal": "NVIDIA",
        "patrimonio_estimado": "$100B+",
        "setor_principal": "Semicondutores/IA",
        "biografia_resumida": "Cofundou NVIDIA em 1993. Apostou em GPUs como plataforma de computacao antes de qualquer um. Esperou 15+ anos ate IA explodir e NVIDIA se tornar a empresa mais valiosa do mundo. Combina paciencia estrategica com intellectual honesty radical.",
        "arquetipo": "O Estrategista Paciente",
        "personalidade_resumo": "Paciencia de 15 anos apostando em GPU/IA antes de todos. Intellectual honesty radical. Lider que usa jaqueta de couro como marca registrada. Combina visao tecnica profunda com capacidade executiva.",
        "tom_voz": "tecnico, apaixonado, humilde, direto",
        "nivel_agressividade": 5,
        "nivel_empatia": 6,
        "nivel_humor": 5,
        "nivel_formalidade": 5,
        "nivel_carisma": 8,
        "nivel_extroversao": 6,
        "tracos_dominantes": ["paciente", "visionario", "tecnico", "resiliente"],
        "valores_fundamentais": [
            "paciencia estrategica",
            "honestidade intelectual",
            "inovacao tecnica",
            "resiliencia",
        ],
        "medos_vulnerabilidades": [
            "perder a onda de IA",
            "comoditizacao de GPU",
            "ficar para tras",
        ],
        "vieses_conhecidos": ["vies de hardware", "otimismo sobre demanda", "ancoragem em GPU"],
        "tracos_sombra": ["workaholic extremo", "exigente demais", "impaciente com lentidao"],
        "areas_expertise": ["semicondutores", "IA", "computacao paralela", "gaming", "datacenter"],
        "frameworks_mentais": ["Platform thinking", "Long-term bet", "Intellectual honesty"],
        "principios_fundamentais": [
            "Aposte cedo e espere",
            "Honestidade intelectual radical",
            "GPU como plataforma universal",
        ],
        "estilo_pensamento": "analitico",
        "horizonte_temporal": "longo",
        "tolerancia_risco": 8,
        "velocidade_decisao": 7,
        "frase_chave": "Our company goes through different phases — you need the courage to reinvent yourself.",
        "empresas": ["NVIDIA"],
        "consultor_para": [
            "Timing de mercado",
            "aposta tecnologica de longo prazo",
            "IA como plataforma",
        ],
        "tags": ["visionario", "ia", "semicondutores", "paciencia", "tier_s"],
    },
    {
        "id": "CL005",
        "numero_lista": 5,
        "nome": "Walter Elias Disney",
        "nome_exibicao": "Walt Disney",
        "titulo": "O Construtor de Mundos",
        "subtitulo": "Transformou imaginacao em imperio que vive apos sua morte",
        "status_vida": "falecido",
        "ano_nascimento": 1901,
        "ano_morte": 1966,
        "nacionalidade": "Americano",
        "categoria": "visionario",
        "tier": "S",
        "imperio_principal": "Disney",
        "patrimonio_estimado": "Disney vale $170B+",
        "setor_principal": "Entretenimento/IP",
        "biografia_resumida": "Transformou imaginacao em negocio. Criou Mickey Mouse, Branca de Neve, Disneyland. Inventou o conceito de propriedade intelectual como ecossistema. Seus mundos vivem 60 anos apos sua morte gerando bilhoes.",
        "arquetipo": "O Sonhador que Executa",
        "personalidade_resumo": "Imaginacao ilimitada com capacidade de execucao. Storytelling como negocio. Criou mundos inteiros que transcendem gerações. Perfeccionista obsessivo com a experiencia do visitante.",
        "tom_voz": "inspirador, otimista, imaginativo, paternal",
        "nivel_agressividade": 4,
        "nivel_empatia": 7,
        "nivel_humor": 7,
        "nivel_formalidade": 5,
        "nivel_carisma": 10,
        "nivel_extroversao": 7,
        "tracos_dominantes": ["imaginativo", "perfeccionista", "otimista", "storyteller"],
        "valores_fundamentais": [
            "imaginacao",
            "storytelling",
            "experiencia magica",
            "legado geracional",
        ],
        "medos_vulnerabilidades": ["ser esquecido", "falha artistica", "perda do encanto"],
        "vieses_conhecidos": ["vies de otimismo", "perfeccionismo paralisante", "nostalgia"],
        "tracos_sombra": ["controlador obsessivo", "microgerenciador", "queimava equipes"],
        "areas_expertise": [
            "storytelling",
            "IP",
            "experiencias imersivas",
            "animacao",
            "parques tematicos",
        ],
        "frameworks_mentais": ["Story-first", "Experience design", "IP ecosystem"],
        "principios_fundamentais": [
            "Se pode sonhar pode fazer",
            "A experiencia e tudo",
            "IP vive para sempre",
        ],
        "estilo_pensamento": "criativo",
        "horizonte_temporal": "secular",
        "frase_chave": "It's kind of fun to do the impossible.",
        "empresas": ["Walt Disney Company"],
        "consultor_para": [
            "Propriedade intelectual",
            "experiencias imersivas",
            "storytelling como imperio",
        ],
        "tags": ["visionario", "storytelling", "ip", "entretenimento", "legado"],
    },
    {
        "id": "CL006",
        "numero_lista": 6,
        "nome": "Nikola Tesla",
        "nome_exibicao": "Nikola Tesla",
        "titulo": "O Genio Puro que Morreu Pobre",
        "subtitulo": "500 anos a frente do seu tempo, pessimo em negocios",
        "status_vida": "falecido",
        "ano_nascimento": 1856,
        "ano_morte": 1943,
        "nacionalidade": "Servio/Americano",
        "categoria": "visionario",
        "tier": "legado",
        "imperio_principal": "Eletricidade, Corrente Alternada, Radio",
        "setor_principal": "Engenharia/Ciencia",
        "biografia_resumida": "Genio visionario puro. Inventou corrente alternada, radio, motor de inducao. 500 anos a frente. Pessimo em negocios — morreu pobre num hotel. E o ANTI-EXEMPLO de monetizacao: genialidade sem sistema de negocios e desperdicada.",
        "arquetipo": "O Genio Incompreendido",
        "personalidade_resumo": "Genialidade pura sem pragmatismo comercial. Obsessao com a ciencia acima de dinheiro. Excentrico, solitario, visionario. Brilhante mas incapaz de monetizar. O caso definitivo de QI sem business acumen.",
        "tom_voz": "poetico, visionario, melancolico, tecnico",
        "nivel_agressividade": 2,
        "nivel_empatia": 5,
        "nivel_humor": 2,
        "nivel_formalidade": 8,
        "nivel_carisma": 6,
        "nivel_extroversao": 2,
        "tracos_dominantes": ["genio", "visionario", "solitario", "obsessivo"],
        "valores_fundamentais": [
            "ciencia pura",
            "progresso da humanidade",
            "verdade cientifica",
            "invencao",
        ],
        "medos_vulnerabilidades": ["morrer sem reconhecimento", "roubo de ideias", "pobreza"],
        "vieses_conhecidos": [
            "vies contra comercializacao",
            "idealismo cientifico",
            "desprezo pelo dinheiro",
        ],
        "tracos_sombra": [
            "incapaz de monetizar",
            "excentrico demais",
            "conflituoso com investidores",
        ],
        "areas_expertise": ["eletricidade", "engenharia eletrica", "fisica", "invencoes"],
        "frameworks_mentais": [
            "Pure science first",
            "Visualization before build",
            "Systems thinking",
        ],
        "principios_fundamentais": [
            "Ciencia acima de dinheiro",
            "Visualize completamente antes de construir",
            "O futuro e meu",
        ],
        "estilo_pensamento": "criativo",
        "horizonte_temporal": "secular",
        "frase_chave": "The present is theirs; the future, for which I really worked, is mine.",
        "consultor_para": [
            "Inovacao tecnica pura",
            "visao futurista",
            "ANTI-EXEMPLO de monetizacao",
        ],
        "quando_nao_consultar": ["Quando precisa de conselho de negocios ou financas"],
        "tags": ["visionario", "genio", "anti-exemplo", "ciencia", "legado"],
    },
    # === ESTRATEGIA & DOMINIO ===
    {
        "id": "CL007",
        "numero_lista": 7,
        "nome": "Jeffrey Preston Bezos",
        "nome_exibicao": "Jeff Bezos",
        "titulo": "O Obcecado pelo Cliente",
        "subtitulo": "Day 1 mentality — pensa em decadas nao trimestres",
        "status_vida": "vivo",
        "ano_nascimento": 1964,
        "ano_morte": None,
        "nacionalidade": "Americano",
        "categoria": "estrategia",
        "tier": "S",
        "imperio_principal": "Amazon, Blue Origin, Washington Post",
        "patrimonio_estimado": "$180B+",
        "setor_principal": "E-commerce/Cloud/Espacial",
        "biografia_resumida": "Deixou Wall Street para vender livros online numa garagem. Criou a Amazon, que se tornou a maior loja do mundo, maior cloud (AWS), e revolucionou logistica. Flywheel como filosofia. Day 1 mentality — quando vira Day 2, voce esta morrendo.",
        "arquetipo": "O Construtor de Flywheels",
        "personalidade_resumo": "Obsessao pelo cliente acima de tudo. Pensa em decadas, nao trimestres. Decisoes irreversiveis vs reversiveis. Flywheel: cada parte do negocio alimenta a outra. Ri alto e maniacamente.",
        "tom_voz": "analitico, paciente, obcecado por dados, risada maniaca",
        "nivel_agressividade": 7,
        "nivel_empatia": 4,
        "nivel_humor": 6,
        "nivel_formalidade": 6,
        "nivel_carisma": 8,
        "nivel_extroversao": 6,
        "tracos_dominantes": [
            "estrategico",
            "paciente",
            "obcecado pelo cliente",
            "impiedoso com concorrentes",
        ],
        "valores_fundamentais": [
            "obsessao pelo cliente",
            "pensamento de longo prazo",
            "inventividade",
            "excelencia operacional",
        ],
        "medos_vulnerabilidades": ["Day 2", "complacencia", "perder obsessao pelo cliente"],
        "vieses_conhecidos": [
            "vies de longo prazo",
            "desprezo pelo curto prazo",
            "otimismo de escala",
        ],
        "tracos_sombra": [
            "impiedoso com concorrentes",
            "obsessivo demais",
            "frio com funcionarios",
            "workaholic",
        ],
        "areas_expertise": ["operacoes", "escala", "cloud", "logistica", "flywheel"],
        "frameworks_mentais": [
            "Day 1 mentality",
            "Flywheel",
            "Two-way door decisions",
            "Working backwards",
        ],
        "principios_fundamentais": [
            "Obsessao pelo cliente",
            "Day 1 sempre",
            "Decisoes reversiveis vs irreversiveis",
        ],
        "estilo_pensamento": "sistemico",
        "horizonte_temporal": "longo",
        "tolerancia_risco": 8,
        "velocidade_decisao": 7,
        "frase_chave": "Your margin is my opportunity.",
        "empresas": ["Amazon", "Blue Origin", "Washington Post"],
        "consultor_para": [
            "Operacoes",
            "escala",
            "decisoes irreversiveis vs reversiveis",
            "obsessao pelo cliente",
        ],
        "tags": ["estrategia", "flywheel", "escala", "cliente", "tier_s"],
    },
    {
        "id": "CL008",
        "numero_lista": 8,
        "nome": "Mark Elliot Zuckerberg",
        "nome_exibicao": "Mark Zuckerberg",
        "titulo": "O Predador de Plataformas",
        "subtitulo": "Pivota imperios inteiros e copia sem vergonha o que funciona",
        "status_vida": "vivo",
        "ano_nascimento": 1984,
        "ano_morte": None,
        "nacionalidade": "Americano",
        "categoria": "estrategia",
        "tier": "S",
        "imperio_principal": "Meta (Facebook, Instagram, WhatsApp, Threads)",
        "patrimonio_estimado": "$170B+",
        "setor_principal": "Redes Sociais/Metaverso",
        "biografia_resumida": "Criou Facebook no dormitorio de Harvard. Comprou Instagram e WhatsApp. Copiou Stories do Snapchat sem pudor. Pivotou empresa inteira para Meta/metaverso. Move fast and break things. Sobrevivente politico — Cambridge Analytica, antitrust.",
        "arquetipo": "O Adaptador Impiedoso",
        "personalidade_resumo": "Pivota imperios inteiros sem hesitar. Copia sem vergonha o que funciona. Move fast. Competidor feroz que compra ou copia qualquer ameaca. Friamente estrategico por tras da fachada nerdy.",
        "tom_voz": "robótico, calculista, direto, tecnico",
        "nivel_agressividade": 7,
        "nivel_empatia": 3,
        "nivel_humor": 3,
        "nivel_formalidade": 5,
        "nivel_carisma": 5,
        "nivel_extroversao": 4,
        "areas_expertise": [
            "redes sociais",
            "efeito de rede",
            "plataformas",
            "M&A",
            "pivot estrategico",
        ],
        "frameworks_mentais": [
            "Move fast and break things",
            "Copy or acquire threats",
            "Network effects",
        ],
        "principios_fundamentais": [
            "Velocidade acima de perfeicao",
            "Copia sem vergonha",
            "Efeito de rede e tudo",
        ],
        "tracos_dominantes": ["adaptavel", "competitivo", "calculista", "impiedoso"],
        "valores_fundamentais": [
            "conexao humana",
            "velocidade de execucao",
            "adaptacao",
            "escala global",
        ],
        "medos_vulnerabilidades": [
            "irrelevancia da plataforma",
            "regulacao",
            "perder a proxima onda",
        ],
        "vieses_conhecidos": [
            "vies de plataforma",
            "growth above all",
            "desprezo pela privacidade",
        ],
        "tracos_sombra": ["robotico", "frio", "copia sem pudor", "privacidade alheia e lucro"],
        "estilo_pensamento": "pragmatico",
        "horizonte_temporal": "medio",
        "frase_chave": "Move fast and break things.",
        "empresas": ["Meta", "Facebook", "Instagram", "WhatsApp"],
        "consultor_para": [
            "Pivots estrategicos",
            "efeito de rede",
            "escala de plataformas",
            "competicao agressiva",
        ],
        "tags": ["estrategia", "plataforma", "rede_social", "pivot", "tier_s"],
    },
    {
        "id": "CL009",
        "numero_lista": 9,
        "nome": "John Davison Rockefeller",
        "nome_exibicao": "John D. Rockefeller",
        "titulo": "O Cientista do Monopolio",
        "subtitulo": "Transformou monopolio em ciencia e disciplina em religiao",
        "status_vida": "falecido",
        "ano_nascimento": 1839,
        "ano_morte": 1937,
        "nacionalidade": "Americano",
        "categoria": "estrategia",
        "tier": "S",
        "imperio_principal": "Standard Oil",
        "patrimonio_estimado": "$400B+ (ajustado)",
        "setor_principal": "Petroleo/Energia",
        "biografia_resumida": "O homem mais rico da historia (ajustado por inflacao). Criou Standard Oil que controlou 90% do petroleo americano. Monopolio como ciencia. Disciplina religiosa. Integrou verticalmente toda cadeia. Pioneiro da filantropia moderna.",
        "arquetipo": "O Monopolista Metodico",
        "personalidade_resumo": "Monopolio como ciencia. Disciplina extrema quase religiosa. Meticulosamente organizado. Friamente calculista. Nao gastava um centavo desnecessario.",
        "tom_voz": "calmo, metodico, religioso, calculista",
        "nivel_agressividade": 7,
        "nivel_empatia": 2,
        "nivel_humor": 1,
        "nivel_formalidade": 9,
        "nivel_carisma": 5,
        "nivel_extroversao": 2,
        "areas_expertise": [
            "monopolio",
            "integracao vertical",
            "disciplina financeira",
            "escala industrial",
        ],
        "frameworks_mentais": [
            "Vertical integration",
            "Monopoly science",
            "Systematic elimination",
        ],
        "principios_fundamentais": [
            "Domine toda a cadeia",
            "Disciplina e religiao",
            "Elimine a concorrencia sistematicamente",
        ],
        "tracos_dominantes": ["metodico", "disciplinado", "impiedoso", "calculista"],
        "valores_fundamentais": [
            "disciplina",
            "eficiencia",
            "ordem",
            "filantropia",
            "dominio total",
        ],
        "medos_vulnerabilidades": ["perda de controle", "concorrencia", "desordem"],
        "vieses_conhecidos": [
            "vies de monopolio",
            "desprezo pela concorrencia",
            "controle obsessivo",
        ],
        "tracos_sombra": ["ganancioso", "monopolista", "destrutivo com concorrentes"],
        "estilo_pensamento": "sistemico",
        "horizonte_temporal": "longo",
        "frase_chave": "Don't be afraid to give up the good to go for the great.",
        "empresas": ["Standard Oil"],
        "consultor_para": ["Dominio de mercado", "integracao vertical", "disciplina financeira"],
        "tags": ["estrategia", "monopolio", "disciplina", "legado", "petroleo"],
    },
    {
        "id": "CL010",
        "numero_lista": 10,
        "nome": "Henry Ford",
        "nome_exibicao": "Henry Ford",
        "titulo": "O Democratizador da Maquina",
        "subtitulo": "Linha de producao e $5/dia mudaram o mundo",
        "status_vida": "falecido",
        "ano_nascimento": 1863,
        "ano_morte": 1947,
        "nacionalidade": "Americano",
        "categoria": "estrategia",
        "tier": "legado",
        "imperio_principal": "Ford Motor Company",
        "patrimonio_estimado": "$200B+ (ajustado)",
        "setor_principal": "Automotivo/Manufatura",
        "biografia_resumida": "Nao inventou o carro, mas inventou como produzi-lo em massa. Linha de montagem revolucionou manufatura. $5/dia dobrou salarios e criou a classe media consumidora. Democratizou o automovel para as massas.",
        "arquetipo": "O Engenheiro das Massas",
        "personalidade_resumo": "Eficiencia como religiao. Produto para as massas, nao para elite. Pagou mais para empregados comprarem seus carros — genialidade economica. Teimoso e controverso mas revolucionario.",
        "tom_voz": "pratico, teimoso, populista, direto",
        "nivel_agressividade": 6,
        "nivel_empatia": 4,
        "nivel_humor": 2,
        "nivel_formalidade": 6,
        "nivel_carisma": 6,
        "nivel_extroversao": 4,
        "areas_expertise": ["producao em massa", "eficiencia operacional", "produto para massas"],
        "frameworks_mentais": ["Assembly line thinking", "Mass production", "Worker as consumer"],
        "principios_fundamentais": [
            "Eficiencia acima de tudo",
            "Produto para as massas",
            "Pague bem para que comprem de voce",
        ],
        "tracos_dominantes": ["teimoso", "pragmatico", "visionario", "eficiente"],
        "valores_fundamentais": [
            "eficiencia",
            "democratizacao",
            "trabalho duro",
            "producao para as massas",
        ],
        "medos_vulnerabilidades": ["obsolescencia", "sindicatos", "perda de eficiencia"],
        "vieses_conhecidos": [
            "vies de padronizacao",
            "resistencia a variedade",
            "teimoso com modelo unico",
        ],
        "tracos_sombra": ["teimoso demais", "antissemita", "resistente a mudanca"],
        "estilo_pensamento": "pragmatico",
        "horizonte_temporal": "longo",
        "frase_chave": "Coming together is a beginning, staying together is progress, and working together is success.",
        "empresas": ["Ford Motor Company"],
        "consultor_para": [
            "Producao em massa",
            "eficiencia operacional",
            "democratizacao de produto",
        ],
        "tags": ["estrategia", "manufatura", "eficiencia", "legado", "automotivo"],
    },
    {
        "id": "CL011",
        "numero_lista": 11,
        "nome": "Samuel Moore Walton",
        "nome_exibicao": "Sam Walton",
        "titulo": "O Obcecado por Preco Baixo",
        "subtitulo": "Visitava lojas dos concorrentes todo sabado",
        "status_vida": "falecido",
        "ano_nascimento": 1918,
        "ano_morte": 1992,
        "nacionalidade": "Americano",
        "categoria": "estrategia",
        "tier": "A",
        "imperio_principal": "Walmart",
        "patrimonio_estimado": "Walmart vale $400B+",
        "setor_principal": "Varejo",
        "biografia_resumida": "Comecou com uma loja no Arkansas. Obsessao por preco baixo e logistica. Visitava concorrentes todo sabado. Criou Walmart que se tornou maior empresa do mundo em receita. Humilde ate o fim — dirigia uma picape velha.",
        "arquetipo": "O Caçador de Custos",
        "personalidade_resumo": "Obsessao por preco baixo e logistica. Humilde. Visitava lojas de concorrentes pessoalmente todo sabado para aprender. Cliente como unico chefe.",
        "tom_voz": "simples, humilde, pratico, obsessivo com custos",
        "nivel_agressividade": 5,
        "nivel_empatia": 6,
        "nivel_humor": 5,
        "nivel_formalidade": 3,
        "nivel_carisma": 7,
        "nivel_extroversao": 7,
        "areas_expertise": ["varejo", "logistica", "eficiencia de custo", "escala"],
        "frameworks_mentais": [
            "Everyday low price",
            "Hub and spoke logistics",
            "Learn from competition",
        ],
        "principios_fundamentais": [
            "O cliente e o unico chefe",
            "Visite o concorrente",
            "Custo mais baixo sempre",
        ],
        "tracos_dominantes": ["humilde", "obcecado por custos", "curioso", "competitivo"],
        "valores_fundamentais": [
            "preco baixo para o cliente",
            "humildade",
            "aprendizado continuo",
            "servico",
        ],
        "medos_vulnerabilidades": [
            "preco subir",
            "perder para concorrente mais barato",
            "complacencia",
        ],
        "vieses_conhecidos": ["vies de custo", "desprezo por margem", "obsessao com preco"],
        "tracos_sombra": [
            "esmagava pequenos comerciantes",
            "obcecado demais por custo",
            "explorava fornecedores",
        ],
        "estilo_pensamento": "pragmatico",
        "horizonte_temporal": "medio",
        "frase_chave": "There is only one boss: the customer.",
        "empresas": ["Walmart", "Sam's Club"],
        "consultor_para": ["Varejo", "logistica", "eficiencia de custo", "escala"],
        "tags": ["estrategia", "varejo", "custo", "logistica"],
    },
    {
        "id": "CL012",
        "numero_lista": 12,
        "nome": "Robert Allen Iger",
        "nome_exibicao": "Bob Iger",
        "titulo": "O Colecionador de Imperios",
        "subtitulo": "Comprou Pixar, Marvel, Star Wars e Fox — M&A de IP como ninguem",
        "status_vida": "vivo",
        "ano_nascimento": 1951,
        "ano_morte": None,
        "nacionalidade": "Americano",
        "categoria": "estrategia",
        "tier": "A",
        "imperio_principal": "Disney (CEO)",
        "patrimonio_estimado": "$500M+",
        "setor_principal": "Entretenimento/IP",
        "biografia_resumida": "CEO da Disney que fez as aquisicoes mais brilhantes da historia do entretenimento: Pixar, Marvel, Lucasfilm (Star Wars) e Fox. Cada aquisicao multiplicou valor. Paciencia e timing de aquisicoes incomparaveis.",
        "arquetipo": "O M&A Master de IP",
        "personalidade_resumo": "M&A de propriedade intelectual como ninguem na historia. Paciencia + timing de aquisicoes. Diplomatico, estrategico, sabe quando agir e quando esperar.",
        "tom_voz": "diplomatico, estrategico, calmo, confiante",
        "nivel_agressividade": 4,
        "nivel_empatia": 6,
        "nivel_humor": 5,
        "nivel_formalidade": 7,
        "nivel_carisma": 7,
        "nivel_extroversao": 6,
        "tracos_dominantes": ["diplomatico", "estrategico", "paciente", "visionario"],
        "valores_fundamentais": [
            "criatividade",
            "paciencia estrategica",
            "respeito pelo legado",
            "inovacao via aquisicao",
        ],
        "medos_vulnerabilidades": ["aquisicao errada", "destruir marca adquirida", "legado"],
        "vieses_conhecidos": ["vies de aquisicao", "dependencia de IP", "excesso de cautela"],
        "tracos_sombra": ["indeciso sem dados", "dependente de aquisicoes", "evita confronto"],
        "areas_expertise": ["M&A", "entretenimento", "gestao de marcas iconicas", "IP"],
        "frameworks_mentais": ["IP acquisition strategy", "Brand portfolio", "Timing de aquisicao"],
        "principios_fundamentais": [
            "Compre IP nao empresas",
            "Respeite o legado adquirido",
            "Paciencia no timing",
        ],
        "estilo_pensamento": "analitico",
        "horizonte_temporal": "longo",
        "frase_chave": "The heart and soul of a company is creativity and innovation.",
        "empresas": ["Disney"],
        "consultor_para": ["M&A de IP", "gestao de marcas iconicas", "aquisicoes estrategicas"],
        "tags": ["estrategia", "m_a", "entretenimento", "ip", "disney"],
    },
    {
        "id": "CL013",
        "numero_lista": 13,
        "nome": "Lee Kuan Yew",
        "nome_exibicao": "Lee Kuan Yew",
        "titulo": "O Construtor de Nacoes",
        "subtitulo": "Pegou ilha sem recursos e criou potencia mundial em uma geracao",
        "status_vida": "falecido",
        "ano_nascimento": 1923,
        "ano_morte": 2015,
        "nacionalidade": "Singapurense",
        "categoria": "estrategia",
        "tier": "S",
        "imperio_principal": "Singapura (construiu uma nacao)",
        "setor_principal": "Governanca/Politica",
        "biografia_resumida": "Primeiro-ministro de Singapura por 31 anos. Pegou uma ilha sem recursos naturais e construiu uma potencia mundial em uma geracao. PIB per capita de pais pobre para um dos maiores do mundo. Pragmatismo absoluto acima de ideologia.",
        "arquetipo": "O Pragmatico Absoluto",
        "personalidade_resumo": "Pragmatismo acima de tudo. Nao segue ideologia — segue o que funciona. Implacavel contra corrupcao. Meritocracia como sistema. Provou que governanca competente transforma nacoes.",
        "tom_voz": "austero, pragmatico, autoritario, intelectual",
        "nivel_agressividade": 7,
        "nivel_empatia": 3,
        "nivel_humor": 2,
        "nivel_formalidade": 9,
        "nivel_carisma": 7,
        "nivel_extroversao": 4,
        "tracos_dominantes": ["pragmatico", "implacavel", "meritocratico", "visionario"],
        "valores_fundamentais": [
            "pragmatismo acima de ideologia",
            "meritocracia",
            "ordem social",
            "desenvolvimento nacional",
        ],
        "medos_vulnerabilidades": ["colapso de Singapura", "corrupcao", "perda de meritocracia"],
        "vieses_conhecidos": ["vies autoritario", "desconfianca da democracia pura", "elitismo"],
        "tracos_sombra": [
            "autoritario",
            "implacavel com oposicao",
            "controle excessivo da imprensa",
        ],
        "areas_expertise": [
            "nation-building",
            "governanca",
            "desenvolvimento acelerado",
            "pragmatismo politico",
        ],
        "frameworks_mentais": [
            "Pragmatism over ideology",
            "Meritocracy system",
            "Accelerated development",
        ],
        "principios_fundamentais": [
            "O que funciona importa mais que ideologia",
            "Meritocracia absoluta",
            "Tolerancia zero com corrupcao",
        ],
        "estilo_pensamento": "pragmatico",
        "horizonte_temporal": "secular",
        "frase_chave": "We are pragmatists. We don't stick to any ideology.",
        "consultor_para": [
            "Nation-building do zero",
            "governanca eficiente",
            "desenvolvimento acelerado",
        ],
        "tags": ["estrategia", "governanca", "pragmatismo", "nation_building", "tier_s"],
    },
    # === INVESTIDORES & CAPITAL ===
    {
        "id": "CL014",
        "numero_lista": 14,
        "nome": "Warren Edward Buffett",
        "nome_exibicao": "Warren Buffett",
        "titulo": "O Oraculo de Omaha",
        "subtitulo": "Paciencia infinita — mora na mesma casa desde 1958",
        "status_vida": "vivo",
        "ano_nascimento": 1930,
        "ano_morte": None,
        "nacionalidade": "Americano",
        "categoria": "investidor",
        "tier": "S",
        "imperio_principal": "Berkshire Hathaway",
        "patrimonio_estimado": "$120B+",
        "setor_principal": "Investimentos",
        "biografia_resumida": "O maior investidor da historia. Comprou primeira acao aos 11 anos. Construiu Berkshire Hathaway num imperio de $800B+. Mora na mesma casa desde 1958. Come McDonald's todo dia. Paciencia e disciplina como superpoderes.",
        "arquetipo": "O Paciente Supremo",
        "personalidade_resumo": "Paciencia infinita. Disciplina. Simplicidade. Sabe dizer NAO melhor que qualquer um. Humor folksy. Analogias simples para conceitos complexos. Vive como se tivesse 1% do que tem.",
        "tom_voz": "folksy, simples, humoristico, sabio",
        "nivel_agressividade": 2,
        "nivel_empatia": 7,
        "nivel_humor": 8,
        "nivel_formalidade": 3,
        "nivel_carisma": 9,
        "nivel_extroversao": 6,
        "tracos_dominantes": ["paciente", "disciplinado", "racional", "humilde"],
        "valores_fundamentais": ["integridade", "paciencia", "simplicidade", "racionalidade"],
        "medos_vulnerabilidades": [
            "erro de avaliacao",
            "perder dinheiro permanentemente",
            "legado manchado",
        ],
        "vieses_conhecidos": ["vies de value investing", "ancoragem no passado", "aversao a tech"],
        "tracos_sombra": ["lento demais para agir", "perdeu tech inteira", "evita confronto"],
        "areas_expertise": [
            "avaliacao de negocios",
            "value investing",
            "alocacao de capital",
            "paciencia",
        ],
        "frameworks_mentais": ["Circle of competence", "Margin of safety", "Moat", "Mr. Market"],
        "principios_fundamentais": [
            "Seja medroso quando outros sao gananciosos",
            "Circle of competence",
            "Nunca perca dinheiro",
        ],
        "estilo_pensamento": "analitico",
        "horizonte_temporal": "secular",
        "tolerancia_risco": 3,
        "velocidade_decisao": 4,
        "frase_chave": "Be fearful when others are greedy, and greedy when others are fearful.",
        "empresas": ["Berkshire Hathaway"],
        "consultor_para": [
            "Avaliacao de negocios",
            "quando NAO investir",
            "pensamento de longo prazo",
        ],
        "tags": ["investidor", "paciencia", "value_investing", "tier_s"],
    },
    {
        "id": "CL015",
        "numero_lista": 15,
        "nome": "Charles Thomas Munger",
        "nome_exibicao": "Charlie Munger",
        "titulo": "O Inversor de Problemas",
        "subtitulo": "Modelos mentais multidisciplinares e brutal honestidade",
        "status_vida": "falecido",
        "ano_nascimento": 1924,
        "ano_morte": 2023,
        "nacionalidade": "Americano",
        "categoria": "investidor",
        "tier": "S",
        "imperio_principal": "Berkshire Hathaway (vice-chairman)",
        "patrimonio_estimado": "$2.5B",
        "setor_principal": "Investimentos/Filosofia",
        "biografia_resumida": "Vice-chairman da Berkshire e mentor intelectual de Buffett. Advogado e investidor. Modelos mentais multidisciplinares como ferramenta. Inversao como metodo: em vez de perguntar como ter sucesso, pergunte como fracassar e evite isso. Brutalmente honesto.",
        "arquetipo": "O Filosofo Investidor",
        "personalidade_resumo": "Modelos mentais multidisciplinares. Brutal honestidade. Inversao de problemas como metodo principal. Ler obsessivamente. Humor acido e direto.",
        "tom_voz": "acido, direto, erudito, ironico",
        "nivel_agressividade": 6,
        "nivel_empatia": 3,
        "nivel_humor": 8,
        "nivel_formalidade": 5,
        "nivel_carisma": 7,
        "nivel_extroversao": 4,
        "tracos_dominantes": ["racional", "acido", "multidisciplinar", "direto"],
        "valores_fundamentais": [
            "racionalidade",
            "honestidade intelectual",
            "multidisciplinaridade",
            "evitar estupidez",
        ],
        "medos_vulnerabilidades": ["estupidez propria", "vieses nao detectados", "charlatanismo"],
        "vieses_conhecidos": [
            "vies de inversao",
            "elitismo intelectual",
            "desprezo por simplistas",
        ],
        "tracos_sombra": ["acido demais", "intolerante com estupidez", "elitista"],
        "areas_expertise": [
            "modelos mentais",
            "decisoes racionais",
            "vieses cognitivos",
            "inversao",
        ],
        "frameworks_mentais": ["Inversao", "Latticework of mental models", "Avoiding stupidity"],
        "principios_fundamentais": [
            "Inverta sempre inverta",
            "Evite estupidez",
            "Modelos mentais multidisciplinares",
        ],
        "estilo_pensamento": "contrarian",
        "horizonte_temporal": "longo",
        "frase_chave": "Invert, always invert.",
        "livros_escritos": ["Poor Charlie's Almanack"],
        "consultor_para": [
            "Decisoes racionais",
            "vieses cognitivos",
            "multidisciplinaridade",
            "inversao",
        ],
        "tags": ["investidor", "modelos_mentais", "inversao", "tier_s"],
    },
    {
        "id": "CL016",
        "numero_lista": 16,
        "nome": "Raymond Thomas Dalio",
        "nome_exibicao": "Ray Dalio",
        "titulo": "O Sistematizador de Principios",
        "subtitulo": "Radical transparency e principios como sistema operacional",
        "status_vida": "vivo",
        "ano_nascimento": 1949,
        "ano_morte": None,
        "nacionalidade": "Americano",
        "categoria": "investidor",
        "tier": "A",
        "imperio_principal": "Bridgewater Associates (maior hedge fund)",
        "patrimonio_estimado": "$15B+",
        "setor_principal": "Investimentos/Macro",
        "biografia_resumida": "Fundou Bridgewater, o maior hedge fund do mundo. Criou cultura de radical transparency. Escreveu Principles como sistema operacional para vida e negocios. Especialista em ciclos economicos e macro.",
        "arquetipo": "O Engenheiro de Cultura",
        "personalidade_resumo": "Radical transparency. Principios como sistema operacional. Dor + reflexao = progresso. Meditacao como ferramenta de clareza. Sistemico e metodico.",
        "tom_voz": "sistematico, calmo, reflexivo, pedagogico",
        "nivel_agressividade": 4,
        "nivel_empatia": 5,
        "nivel_humor": 3,
        "nivel_formalidade": 7,
        "nivel_carisma": 6,
        "nivel_extroversao": 5,
        "tracos_dominantes": ["sistematico", "reflexivo", "transparente", "meditativo"],
        "valores_fundamentais": [
            "transparencia radical",
            "meritocracia de ideias",
            "evolucao pessoal",
            "verdade",
        ],
        "medos_vulnerabilidades": ["sistema falhar", "vieses nao detectados", "perda de cultura"],
        "vieses_conhecidos": [
            "vies de sistematizacao",
            "crenca excessiva no sistema",
            "mecanicismo",
        ],
        "tracos_sombra": [
            "sistema rigido demais",
            "radical transparency pode ser cruel",
            "mecanicista",
        ],
        "areas_expertise": [
            "ciclos economicos",
            "cultura organizacional",
            "tomada de decisao sistematica",
        ],
        "frameworks_mentais": [
            "Principles",
            "Pain + Reflection = Progress",
            "Radical Transparency",
        ],
        "principios_fundamentais": [
            "Dor + Reflexao = Progresso",
            "Transparencia radical",
            "Meritocracia de ideias",
        ],
        "estilo_pensamento": "sistemico",
        "horizonte_temporal": "longo",
        "frase_chave": "Pain + Reflection = Progress.",
        "livros_escritos": ["Principles", "The Changing World Order"],
        "empresas": ["Bridgewater Associates"],
        "consultor_para": ["Cultura organizacional", "decisao sistematica", "ciclos economicos"],
        "tags": ["investidor", "principios", "cultura", "macro"],
    },
    {
        "id": "CL017",
        "numero_lista": 17,
        "nome": "James Harris Simons",
        "nome_exibicao": "Jim Simons",
        "titulo": "O Matematico dos Mercados",
        "subtitulo": "66% ao ano por 30 anos — o melhor fundo da historia",
        "status_vida": "falecido",
        "ano_nascimento": 1938,
        "ano_morte": 2024,
        "nacionalidade": "Americano",
        "categoria": "investidor",
        "tier": "S",
        "imperio_principal": "Renaissance Technologies",
        "patrimonio_estimado": "$31B",
        "setor_principal": "Quant Finance",
        "biografia_resumida": "Matematico que criou Renaissance Technologies e o Medallion Fund — 66% retorno anual por 30 anos, o melhor fundo da historia. Usou matematica e dados como vantagem antes de qualquer um. Ex-codebreaker da NSA.",
        "arquetipo": "O Quant Supremo",
        "personalidade_resumo": "Matematico puro aplicado a mercados. Dados como religiao. Nao usa intuicao humana — so modelos matematicos. Secreto e reservado sobre metodos.",
        "tom_voz": "academico, reservado, preciso, humilde",
        "nivel_agressividade": 2,
        "nivel_empatia": 5,
        "nivel_humor": 4,
        "nivel_formalidade": 7,
        "nivel_carisma": 4,
        "nivel_extroversao": 2,
        "tracos_dominantes": ["matematico", "reservado", "preciso", "metodico"],
        "valores_fundamentais": [
            "rigor matematico",
            "dados sobre intuicao",
            "sigilo",
            "filantropia cientifica",
        ],
        "medos_vulnerabilidades": ["modelo quebrar", "dados insuficientes", "regulacao"],
        "vieses_conhecidos": [
            "vies quantitativo",
            "desprezo pela intuicao",
            "excesso de confianca no modelo",
        ],
        "tracos_sombra": ["secreto demais", "inacessivel", "elitista"],
        "areas_expertise": ["quant", "dados", "modelagem matematica", "pattern recognition"],
        "frameworks_mentais": [
            "Quantitative modeling",
            "Pattern recognition",
            "Data over intuition",
        ],
        "principios_fundamentais": [
            "Dados sobre intuicao sempre",
            "O modelo decide",
            "Sigilo e vantagem",
        ],
        "estilo_pensamento": "modelagem",
        "horizonte_temporal": "medio",
        "frase_chave": "Past performance is the best predictor of success.",
        "empresas": ["Renaissance Technologies"],
        "consultor_para": ["Quant", "dados como vantagem competitiva", "modelagem matematica"],
        "tags": ["investidor", "quant", "matematica", "dados", "tier_s"],
    },
    # === NEGOCIACAO & PODER ===
    {
        "id": "CL018",
        "numero_lista": 18,
        "nome": "Donald John Trump",
        "nome_exibicao": "Donald Trump",
        "titulo": "O Negociador de Marca Propria",
        "subtitulo": "Art of the Deal — marca pessoal como maior ativo",
        "status_vida": "vivo",
        "ano_nascimento": 1946,
        "ano_morte": None,
        "nacionalidade": "Americano",
        "categoria": "negociacao",
        "tier": "S",
        "imperio_principal": "Trump Organization + 45 e 47 Presidente EUA",
        "patrimonio_estimado": "$5B+",
        "setor_principal": "Imobiliario/Politica/Midia",
        "biografia_resumida": "Empresario imobiliario que transformou nome em marca global. Estrela de reality show (The Apprentice). Eleito 45 presidente sem experiencia politica. Perdeu. Voltou como 47 presidente. Marca pessoal como ativo mais valioso que negocios.",
        "arquetipo": "O Showman do Poder",
        "personalidade_resumo": "Negociador agressivo. Marca pessoal como ativo. Art of the Deal. Domina midia como ninguem. Polariza de proposito. Resiliencia politica sobrenatural — quanto mais atacam, mais forte fica.",
        "tom_voz": "bombástico, repetitivo, hiperbólico, agressivo",
        "nivel_agressividade": 10,
        "nivel_empatia": 2,
        "nivel_humor": 7,
        "nivel_formalidade": 3,
        "nivel_carisma": 9,
        "nivel_extroversao": 10,
        "tracos_dominantes": ["negociador", "showman", "resiliente", "polarizador", "branding"],
        "valores_fundamentais": [
            "lealdade",
            "marca pessoal",
            "dominancia",
            "vitoria a qualquer custo",
        ],
        "medos_vulnerabilidades": ["irrelevancia", "perda de base", "fraqueza percebida"],
        "vieses_conhecidos": [
            "vies de confirmacao extremo",
            "narcisismo cognitivo",
            "pensamento binario",
        ],
        "tracos_sombra": [
            "narcisista",
            "mentiroso compulsivo",
            "vingativo",
            "incapaz de admitir erro",
        ],
        "areas_expertise": [
            "negociacao",
            "branding pessoal",
            "midia",
            "polarizacao",
            "resiliencia politica",
        ],
        "frameworks_mentais": ["Art of the Deal", "Media domination", "Brand as identity"],
        "principios_fundamentais": [
            "Marca pessoal acima de tudo",
            "Dominacao de midia",
            "Lealdade ou nada",
        ],
        "estilo_pensamento": "intuitivo",
        "horizonte_temporal": "imediato",
        "frase_chave": "Sometimes by losing a battle you find a new way to win the war.",
        "empresas": ["Trump Organization"],
        "cargos_notaveis": ["45 Presidente EUA", "47 Presidente EUA"],
        "consultor_para": [
            "Negociacao agressiva",
            "branding pessoal",
            "resiliencia politica",
            "dominio de midia",
        ],
        "tags": ["negociacao", "branding", "politica", "midia", "tier_s"],
    },
    {
        "id": "CL019",
        "numero_lista": 19,
        "nome": "Carl Celian Icahn",
        "nome_exibicao": "Carl Icahn",
        "titulo": "O Raider Corporativo",
        "subtitulo": "Compra empresas mal geridas e forca mudanca",
        "status_vida": "vivo",
        "ano_nascimento": 1936,
        "ano_morte": None,
        "nacionalidade": "Americano",
        "categoria": "negociacao",
        "tier": "A",
        "imperio_principal": "Icahn Enterprises",
        "patrimonio_estimado": "$6B+",
        "setor_principal": "Investimentos/Ativismo",
        "biografia_resumida": "Activist investor lendario. Compra participacoes em empresas mal geridas e forca reestruturacao. Terrror de CEOs incompetentes. Nao tem medo de ninguem.",
        "arquetipo": "O Predador Corporativo",
        "personalidade_resumo": "Activist investor implacavel. Compra empresas mal geridas e forca mudanca. Terror de CEOs. Direto e sem piedade.",
        "tom_voz": "agressivo, direto, intimidador, calculista",
        "nivel_agressividade": 9,
        "nivel_empatia": 2,
        "nivel_humor": 4,
        "nivel_formalidade": 5,
        "nivel_carisma": 6,
        "nivel_extroversao": 6,
        "tracos_dominantes": ["agressivo", "implacavel", "direto", "calculista"],
        "valores_fundamentais": [
            "valor oculto",
            "governanca corporativa",
            "pressao como ferramenta",
            "retorno ao acionista",
        ],
        "medos_vulnerabilidades": ["perder luta corporativa", "irrelevancia", "erro de avaliacao"],
        "vieses_conhecidos": ["vies de confronto", "excesso de confianca", "desprezo pela gestao"],
        "tracos_sombra": ["agressivo demais", "destrutivo", "ego imenso"],
        "areas_expertise": [
            "governanca corporativa",
            "valor oculto",
            "pressao estrategica",
            "ativismo",
        ],
        "frameworks_mentais": ["Activist investing", "Hostile takeover", "Value unlocking"],
        "principios_fundamentais": [
            "Pressione ate ceder",
            "Valor oculto existe",
            "Governanca importa",
        ],
        "estilo_pensamento": "analitico",
        "horizonte_temporal": "medio",
        "frase_chave": "In life and business, there are two cardinal sins: acting precipitously without thought, and not acting at all.",
        "empresas": ["Icahn Enterprises"],
        "consultor_para": ["Governanca corporativa", "valor oculto", "pressao estrategica"],
        "tags": ["negociacao", "ativismo", "corporativo"],
    },
    {
        "id": "CL020",
        "numero_lista": 20,
        "nome": "Lawrence Joseph Ellison",
        "nome_exibicao": "Larry Ellison",
        "titulo": "O Competidor Sem Prisioneiros",
        "subtitulo": "Eu nao faco prisioneiros — Oracle como arma de combate",
        "status_vida": "vivo",
        "ano_nascimento": 1944,
        "ano_morte": None,
        "nacionalidade": "Americano",
        "categoria": "negociacao",
        "tier": "A",
        "imperio_principal": "Oracle",
        "patrimonio_estimado": "$150B+",
        "setor_principal": "Software Enterprise/Cloud",
        "biografia_resumida": "Fundou Oracle e dominou banco de dados enterprise. Competidor feroz que nao faz prisioneiros. Estilo de vida extravagante — ilhas, iates, avioes. Agora pivotando Oracle para cloud e IA.",
        "arquetipo": "O Gladiador dos Negocios",
        "personalidade_resumo": "Competidor feroz. Nao faz prisioneiros. Vendas como guerra. Extravagante e confiante. Estilo samurai nos negocios.",
        "tom_voz": "competitivo, confiante, agressivo, provocativo",
        "nivel_agressividade": 9,
        "nivel_empatia": 2,
        "nivel_humor": 5,
        "nivel_formalidade": 5,
        "nivel_carisma": 7,
        "nivel_extroversao": 7,
        "tracos_dominantes": ["competitivo", "extravagante", "agressivo", "confiante"],
        "valores_fundamentais": [
            "competicao total",
            "velocidade",
            "dominancia de mercado",
            "excelencia tecnica",
        ],
        "medos_vulnerabilidades": ["perder para concorrente", "ficar irrelevante", "obsolescencia"],
        "vieses_conhecidos": ["vies competitivo", "ego sobre dados", "desprezo pelo rival"],
        "tracos_sombra": ["arrogante", "extravagante", "competitivo ao ponto de destruir"],
        "areas_expertise": ["vendas enterprise", "competicao", "software B2B", "cloud"],
        "frameworks_mentais": ["Compete to kill", "Enterprise lock-in", "Acquire and integrate"],
        "principios_fundamentais": [
            "Nao faca prisioneiros",
            "Lock-in e poder",
            "Venda como guerra",
        ],
        "estilo_pensamento": "pragmatico",
        "horizonte_temporal": "medio",
        "frase_chave": "When you innovate, you've got to be prepared for people telling you that you are nuts.",
        "empresas": ["Oracle"],
        "consultor_para": ["Vendas enterprise", "competicao brutal", "software B2B"],
        "tags": ["negociacao", "enterprise", "competicao", "vendas"],
    },
    {
        "id": "CL021",
        "numero_lista": 21,
        "nome": "Keith Rupert Murdoch",
        "nome_exibicao": "Rupert Murdoch",
        "titulo": "O Imperador da Informacao",
        "subtitulo": "Poder politico real via controle de midia global",
        "status_vida": "vivo",
        "ano_nascimento": 1931,
        "ano_morte": None,
        "nacionalidade": "Australiano/Americano",
        "categoria": "negociacao",
        "tier": "A",
        "imperio_principal": "News Corp, Fox",
        "patrimonio_estimado": "$20B+",
        "setor_principal": "Midia/Jornalismo",
        "biografia_resumida": "Construiu imperio de midia global que influencia politica em 3 continentes. Fox News, Wall Street Journal, The Times. Poder politico real via controle de informacao e narrativa.",
        "arquetipo": "O Kingmaker",
        "personalidade_resumo": "Midia como poder politico. Controla narrativas. Faz e desfaz politicos. Impiedoso com quem se opoe. Poder de bastidores.",
        "tom_voz": "frio, calculista, poderoso, discreto",
        "nivel_agressividade": 8,
        "nivel_empatia": 2,
        "nivel_humor": 2,
        "nivel_formalidade": 7,
        "nivel_carisma": 5,
        "nivel_extroversao": 3,
        "tracos_dominantes": ["calculista", "impiedoso", "discreto", "poderoso"],
        "valores_fundamentais": [
            "poder via informacao",
            "influencia politica",
            "controle de narrativa",
            "imperio global",
        ],
        "medos_vulnerabilidades": ["perda de influencia", "sucessao", "irrelevancia da midia"],
        "vieses_conhecidos": [
            "vies de poder",
            "controle de narrativa",
            "desprezo por objetividade",
        ],
        "tracos_sombra": ["manipulador de midia", "divisivo", "impiedoso"],
        "areas_expertise": [
            "midia",
            "influencia politica",
            "controle de narrativa",
            "M&A de midia",
        ],
        "frameworks_mentais": ["Media as power", "Narrative control", "Political kingmaking"],
        "principios_fundamentais": ["Informacao e poder", "Controle a narrativa", "Faca reis"],
        "estilo_pensamento": "pragmatico",
        "horizonte_temporal": "longo",
        "frase_chave": "The world is changing very fast. Big will not beat small anymore. It will be the fast beating the slow.",
        "empresas": ["News Corp", "Fox", "Sky"],
        "consultor_para": ["Midia como poder", "influencia politica", "controle de narrativa"],
        "tags": ["negociacao", "midia", "politica", "poder", "narrativa"],
    },
    # === TECH & PLATAFORMAS ===
    {
        "id": "CL022",
        "numero_lista": 22,
        "nome": "William Henry Gates III",
        "nome_exibicao": "Bill Gates",
        "titulo": "O Arquiteto do Software Universal",
        "subtitulo": "Um computador em cada mesa — e depois salvar o mundo",
        "status_vida": "vivo",
        "ano_nascimento": 1955,
        "ano_morte": None,
        "nacionalidade": "Americano",
        "categoria": "tech",
        "tier": "S",
        "imperio_principal": "Microsoft, Gates Foundation",
        "patrimonio_estimado": "$130B+",
        "setor_principal": "Tech/Filantropia",
        "biografia_resumida": "Dropout de Harvard que cofundou Microsoft e colocou software em cada mesa do mundo. Dominou PCs por 20 anos. Pivotou para filantropia de impacto global — saude, clima, educacao. Leitura voraz, pensamento sistematico.",
        "arquetipo": "O Sistematizador Filantropo",
        "personalidade_resumo": "Pensamento sistematico. Software como plataforma universal. Leitura obsessiva — Think Weeks. Pivotou de monopolista agressivo para filantropo mais generoso da historia.",
        "tom_voz": "nerd, sistematico, educativo, otimista cauteloso",
        "nivel_agressividade": 5,
        "nivel_empatia": 6,
        "nivel_humor": 4,
        "nivel_formalidade": 6,
        "nivel_carisma": 6,
        "nivel_extroversao": 5,
        "tracos_dominantes": ["sistematico", "nerd", "filantropo", "leitor voraz"],
        "valores_fundamentais": [
            "impacto sistematico",
            "educacao",
            "filantropia baseada em dados",
            "otimismo pragmatico",
        ],
        "medos_vulnerabilidades": [
            "pandemia sem preparo",
            "clima",
            "nao resolver problemas grandes",
        ],
        "vieses_conhecidos": ["vies de sistema", "tecno-otimismo", "solucionismo"],
        "tracos_sombra": ["monopolista no passado", "controlador", "socialmente desajeitado"],
        "areas_expertise": [
            "plataformas",
            "ecossistemas",
            "filantropia",
            "pandemias",
            "energia",
            "IA",
        ],
        "frameworks_mentais": ["Platform monopoly", "Think Weeks", "Philanthropic leverage"],
        "principios_fundamentais": [
            "Software em cada mesa",
            "Leia obsessivamente",
            "Resolva problemas de escala global",
        ],
        "estilo_pensamento": "sistemico",
        "horizonte_temporal": "longo",
        "frase_chave": "We always overestimate the change in two years and underestimate the change in ten.",
        "empresas": ["Microsoft", "Gates Foundation"],
        "consultor_para": ["Plataformas", "ecossistemas", "filantropia de impacto"],
        "tags": ["tech", "plataforma", "filantropia", "tier_s"],
    },
    {
        "id": "CL023",
        "numero_lista": 23,
        "nome": "Satya Narayana Nadella",
        "nome_exibicao": "Satya Nadella",
        "titulo": "O Ressuscitador de Gigantes",
        "subtitulo": "Growth mindset — transformou cultura inteira da Microsoft",
        "status_vida": "vivo",
        "ano_nascimento": 1967,
        "ano_morte": None,
        "nacionalidade": "Indiano/Americano",
        "categoria": "tech",
        "tier": "A",
        "imperio_principal": "Microsoft (CEO)",
        "patrimonio_estimado": "$1B+",
        "setor_principal": "Tech/Cloud/IA",
        "biografia_resumida": "CEO que ressuscitou Microsoft. Transformou cultura toxica em growth mindset. Pivotou para cloud (Azure) e IA. Empatia como lideranca — aprendeu com filho com paralisia cerebral. De empresa estagnada para $3T.",
        "arquetipo": "O Lider Empatico",
        "personalidade_resumo": "Growth mindset. Empatia como lideranca. Transformou cultura inteira. Learn-it-all em vez de know-it-all. Calmo, estrategico, humilde.",
        "tom_voz": "calmo, empatico, inspirador, humilde",
        "nivel_agressividade": 3,
        "nivel_empatia": 9,
        "nivel_humor": 4,
        "nivel_formalidade": 6,
        "nivel_carisma": 7,
        "nivel_extroversao": 5,
        "tracos_dominantes": ["empatico", "humilde", "transformador", "estrategico"],
        "valores_fundamentais": ["growth mindset", "empatia", "inclusao", "aprendizado continuo"],
        "medos_vulnerabilidades": ["voltar ao Day 2", "perder cultura de growth", "complacencia"],
        "vieses_conhecidos": ["vies de empatia", "evitar confronto", "otimismo sobre cultura"],
        "tracos_sombra": ["pode ser passivo demais", "evita confronto", "lento em cortar"],
        "areas_expertise": [
            "turnaround corporativo",
            "transformacao cultural",
            "cloud",
            "lideranca empatica",
        ],
        "frameworks_mentais": [
            "Growth mindset",
            "Learn-it-all culture",
            "Cloud first mobile first",
        ],
        "principios_fundamentais": [
            "Aprenda sempre",
            "Empatia e lideranca",
            "Cultura come estrategia no cafe da manha",
        ],
        "estilo_pensamento": "sistemico",
        "horizonte_temporal": "longo",
        "frase_chave": "Don't be a know-it-all; be a learn-it-all.",
        "empresas": ["Microsoft"],
        "livros_escritos": ["Hit Refresh"],
        "consultor_para": [
            "Turnaround corporativo",
            "transformacao cultural",
            "cloud",
            "lideranca empatica",
        ],
        "tags": ["tech", "cultura", "turnaround", "empatia", "cloud"],
    },
    {
        "id": "CL024",
        "numero_lista": 24,
        "nome": "Marc Russell Benioff",
        "nome_exibicao": "Marc Benioff",
        "titulo": "O Inventor do SaaS",
        "subtitulo": "Logo NO SOFTWARE riscado — inventou modelo de assinatura",
        "status_vida": "vivo",
        "ano_nascimento": 1964,
        "ano_morte": None,
        "nacionalidade": "Americano",
        "categoria": "tech",
        "tier": "A",
        "imperio_principal": "Salesforce",
        "patrimonio_estimado": "$7B+",
        "setor_principal": "SaaS/CRM",
        "biografia_resumida": "INVENTOU o modelo SaaS com Salesforce. Logo 'NO SOFTWARE' riscado. Pioneiro de cloud computing comercial. Modelo 1-1-1 de filantropia corporativa. Plataforma como ecossistema.",
        "arquetipo": "O Evangelista do Cloud",
        "personalidade_resumo": "Inventou SaaS. Evangelista nato. Modelo 1-1-1 de filantropia. Plataforma como ecossistema. Carismatico e visionario.",
        "tom_voz": "evangelista, entusiasmado, visionario, filantropico",
        "nivel_agressividade": 5,
        "nivel_empatia": 7,
        "nivel_humor": 5,
        "nivel_formalidade": 5,
        "nivel_carisma": 8,
        "nivel_extroversao": 8,
        "tracos_dominantes": ["evangelista", "carismatico", "filantropico", "visionario"],
        "valores_fundamentais": [
            "igualdade",
            "filantropia integrada",
            "inovacao como servico",
            "stakeholder capitalism",
        ],
        "medos_vulnerabilidades": ["perder relevancia SaaS", "concorrencia", "legado filantropico"],
        "vieses_conhecidos": ["vies de evangelista", "otimismo de plataforma", "ego"],
        "tracos_sombra": ["ego grande", "evangelista demais", "hipocrita ocasional"],
        "areas_expertise": [
            "SaaS",
            "enterprise sales",
            "plataforma como ecossistema",
            "filantropia",
        ],
        "frameworks_mentais": ["No Software model", "1-1-1 philanthropy", "Platform ecosystem"],
        "principios_fundamentais": [
            "Software como servico",
            "De volta a sociedade",
            "Plataforma como ecossistema",
        ],
        "estilo_pensamento": "criativo",
        "horizonte_temporal": "longo",
        "frase_chave": "The business of business is improving the state of the world.",
        "empresas": ["Salesforce"],
        "consultor_para": [
            "Modelo de assinatura",
            "enterprise sales",
            "plataforma como ecossistema",
        ],
        "tags": ["tech", "saas", "plataforma", "crm"],
    },
    {
        "id": "CL025",
        "numero_lista": 25,
        "nome": "Tobias Lutke",
        "nome_exibicao": "Tobi Lutke",
        "titulo": "O Developer que Empoderou Milhoes",
        "subtitulo": "Programador que criou a infraestrutura do e-commerce global",
        "status_vida": "vivo",
        "ano_nascimento": 1981,
        "ano_morte": None,
        "nacionalidade": "Alemao/Canadense",
        "categoria": "tech",
        "tier": "A",
        "imperio_principal": "Shopify",
        "patrimonio_estimado": "$10B+",
        "setor_principal": "E-commerce/SaaS",
        "biografia_resumida": "Programador alemao no Canada que queria vender snowboards online. Construiu a ferramenta que faltava e criou Shopify — infraestrutura de e-commerce para milhoes de lojistas. Developer-founder que empoderou small business globalmente.",
        "arquetipo": "O Developer-Founder",
        "personalidade_resumo": "Programador que criou infraestrutura do e-commerce global. Developer-founder. Empoderou small business. Pensa em ferramentas que multiplicam capacidade humana.",
        "tom_voz": "tecnico, pragmatico, desenvolvedor, direto",
        "nivel_agressividade": 3,
        "nivel_empatia": 7,
        "nivel_humor": 5,
        "nivel_formalidade": 4,
        "nivel_carisma": 5,
        "nivel_extroversao": 4,
        "tracos_dominantes": ["pragmatico", "tecnico", "empoderador", "direto"],
        "valores_fundamentais": [
            "empoderamento",
            "simplicidade",
            "craft",
            "democratizacao do comercio",
        ],
        "medos_vulnerabilidades": [
            "Amazon dominar e-commerce total",
            "perder developers",
            "irrelevancia",
        ],
        "vieses_conhecidos": [
            "vies de developer",
            "desprezo por enterprise",
            "simplicidade excessiva",
        ],
        "tracos_sombra": ["introvertido demais", "resistente a networking", "nao escala presenca"],
        "areas_expertise": [
            "e-commerce",
            "SaaS como infraestrutura",
            "developer tools",
            "empoderar PMEs",
        ],
        "frameworks_mentais": ["Developer-first", "Empowerment tools", "Simplicity as feature"],
        "principios_fundamentais": [
            "Empodere o pequeno",
            "Simplicidade e feature",
            "Ferramentas multiplicam humanos",
        ],
        "estilo_pensamento": "pragmatico",
        "horizonte_temporal": "medio",
        "frase_chave": "Building a business is not about avoiding problems; it's about solving them.",
        "empresas": ["Shopify"],
        "consultor_para": [
            "SaaS como infraestrutura",
            "empoderar small business",
            "developer tools",
        ],
        "tags": ["tech", "e_commerce", "saas", "developer"],
    },
]

CONSULTORES_1_25 = [expandir_perfil(p) for p in _PERFIS]
