"""Onda 169a: curadoria batch 1 de 50 eventos OOS pós-cutoff 2024-08-01.

Path B aprovada por Helena+Efesto: eventos com data_resolucao >= 2024-09-01,
fonte primária verificável, outcome binário objetivo.

Cada evento tem audit_status='pendente' — Helena valida antes de entrar no
holdout. Probe (engine/outcome_probe.py) ainda vai filtrar leakage residual
dos eventos que GPT-5.5 já viu (cutoff GPT-5.5 ~Q1 2025).

Saída: data/n100/oos_curated.jsonl
"""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from engine.eventos_v1 import EventoPreditivoV1, FonteEvento, to_jsonl

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "data" / "n100" / "oos_curated.jsonl"


def fonte(url: str, titulo: str, data_resolucao: date, nivel: str = "primaria") -> FonteEvento:
    return FonteEvento(url=url, titulo=titulo, nivel=nivel, data_acesso=data_resolucao)


def ev(
    eid: str, categoria: str, pergunta: str, outcome_framing: str,
    contexto: str, regra: str, outcome: int, prior: float | None,
    tipo_oraculo: str, d_corte: date, d_res: date, fontes: list[FonteEvento],
    leakage: str = "medio",
) -> EventoPreditivoV1:
    return EventoPreditivoV1(
        id=eid, dataset="oos_batch1", split="reserve", categoria=categoria,
        pergunta=pergunta, outcome_framing=outcome_framing,
        contexto_pre_corte=contexto, regra_resolucao=regra,
        outcome_binario=outcome,
        prob_oraculo_humano_se_houver=prior, tipo_oraculo_humano=tipo_oraculo,
        data_corte_informacao=d_corte, data_resolucao=d_res,
        fonte_outcome=fontes, leakage_risk=leakage, audit_status="pendente",
    )


# ============================================================
# ELEIÇÕES US 2024 (Nov 5 2024) — 15 eventos
# Cutoff: 2024-08-01 (antes RNC, antes Trump-Harris debate Set 10)
# Fonte primária: AP/Ballotpedia/Cook
# ============================================================
ELEICOES_US = [
    ev("oos_us01", "eleicoes",
       "Donald Trump vencerá a eleição presidencial dos EUA em 2024?",
       "Trump obtém ≥270 votos do Colégio Eleitoral.",
       "Em 1/8/2024, Harris havia recém substituído Biden. Polling 538 mostrava empate técnico (~46-46).",
       "AP/270toWin chamada do vencedor.",
       1, 0.50, "prediction_market", date(2024, 8, 1), date(2024, 11, 6),
       [fonte("https://www.ap.org/elections/results/", "AP 2024 Presidential Results", date(2024, 11, 6))],
       "alto"),
    ev("oos_us02", "eleicoes",
       "Republicanos terão maioria no Senado dos EUA pós-2024?",
       "GOP obtém ≥51 cadeiras no 119º Congresso.",
       "Em 1/8/2024, GOP precisava virar 2 cadeiras (WV garantida, MT/OH competitivas).",
       "Senate.gov composition no início do 119º Congresso.",
       1, 0.65, "prediction_market", date(2024, 8, 1), date(2024, 11, 6),
       [fonte("https://www.senate.gov/senators/", "US Senate Composition", date(2024, 11, 6))],
       "alto"),
    ev("oos_us03", "eleicoes",
       "Republicanos manterão maioria na Câmara dos EUA pós-2024?",
       "GOP obtém ≥218 cadeiras no 119º Congresso.",
       "Em 1/8/2024, GOP tinha margem 220-212 com várias toss-ups.",
       "Clerk.house.gov chamada das 435 cadeiras.",
       1, 0.55, "prediction_market", date(2024, 8, 1), date(2024, 11, 30),
       [fonte("https://clerk.house.gov/", "US House Roll of Members", date(2024, 11, 30))],
       "alto"),
    ev("oos_us04", "eleicoes",
       "Bernie Moreno (R) derrotará Sherrod Brown (D) no Senado de Ohio?",
       "Moreno recebe mais votos certificados que Brown.",
       "Brown era titular 3-termos D em estado que virou R+. Polling em 1/8 mostrava Brown ligeiramente à frente.",
       "Ohio SoS resultado oficial certificado.",
       1, 0.45, "polling", date(2024, 8, 1), date(2024, 11, 6),
       [fonte("https://www.ohiosos.gov/elections/election-results-and-data/", "Ohio Election Results 2024", date(2024, 11, 6))],
       "alto"),
    ev("oos_us05", "eleicoes",
       "Tim Sheehy (R) derrotará Jon Tester (D) no Senado de Montana?",
       "Sheehy recebe mais votos certificados que Tester.",
       "Tester era titular D em estado Trump+. Polling 538 em 1/8 mostrava Sheehy +5.",
       "Montana SoS resultado oficial.",
       1, 0.65, "polling", date(2024, 8, 1), date(2024, 11, 6),
       [fonte("https://sosmt.gov/elections/results/", "Montana 2024 Election Results", date(2024, 11, 6))],
       "alto"),
    ev("oos_us06", "eleicoes",
       "Dave McCormick (R) derrotará Bob Casey (D) no Senado da Pensilvânia?",
       "McCormick recebe mais votos certificados que Casey após recount.",
       "Casey era titular 3-termos D. Polling em 1/8 mostrava Casey +3-5.",
       "Pennsylvania DoS resultado certificado pós-recount.",
       1, 0.35, "polling", date(2024, 8, 1), date(2024, 11, 21),
       [fonte("https://www.pa.gov/agencies/dos.html", "PA Dept of State 2024 Results", date(2024, 11, 21))],
       "alto"),
    ev("oos_us07", "eleicoes",
       "Elissa Slotkin (D) derrotará Mike Rogers (R) no Senado de Michigan?",
       "Slotkin recebe mais votos certificados.",
       "Cadeira aberta (Stabenow se aposentou). Polling 1/8 mostrava Slotkin +1-2.",
       "Michigan SoS resultado oficial.",
       1, 0.55, "polling", date(2024, 8, 1), date(2024, 11, 6),
       [fonte("https://www.michigan.gov/sos/elections", "MI SoS 2024 Election", date(2024, 11, 6))],
       "alto"),
    ev("oos_us08", "eleicoes",
       "Ruben Gallego (D) derrotará Kari Lake (R) no Senado do Arizona?",
       "Gallego recebe mais votos certificados.",
       "Cadeira aberta (Sinema saiu). Lake era figura controversa pós-2022. Gallego +5 em polling 1/8.",
       "Arizona SoS resultado certificado.",
       1, 0.65, "polling", date(2024, 8, 1), date(2024, 11, 6),
       [fonte("https://azsos.gov/elections", "Arizona 2024 Election Results", date(2024, 11, 6))],
       "alto"),
    ev("oos_us09", "eleicoes",
       "Trump vencerá a Pensilvânia na eleição presidencial 2024?",
       "Trump tem mais votos certificados que Harris em PA.",
       "PA decisivo. Polling 538 em 1/8: D+0.5. Margin razoável de erro.",
       "PA DoS chamada oficial 2024 presidential.",
       1, 0.50, "prediction_market", date(2024, 8, 1), date(2024, 11, 6),
       [fonte("https://www.pa.gov/agencies/dos/elections.html", "PA 2024 Presidential", date(2024, 11, 6))],
       "alto"),
    ev("oos_us10", "eleicoes",
       "Trump vencerá Michigan na eleição presidencial 2024?",
       "Trump tem mais votos certificados que Harris em MI.",
       "Polling 538 em 1/8 mostrava MI D+1. Toss-up.",
       "MI SoS chamada oficial 2024.",
       1, 0.45, "prediction_market", date(2024, 8, 1), date(2024, 11, 6),
       [fonte("https://www.michigan.gov/sos/elections", "MI 2024 Presidential", date(2024, 11, 6))],
       "alto"),
    ev("oos_us11", "eleicoes",
       "Trump vencerá Wisconsin na eleição presidencial 2024?",
       "Trump > Harris em WI.",
       "WI tradicionalmente decisivo. Polling 1/8: D+0.5.",
       "WI Election Comm resultado oficial.",
       1, 0.45, "prediction_market", date(2024, 8, 1), date(2024, 11, 6),
       [fonte("https://elections.wi.gov/", "WI Elections Commission Results", date(2024, 11, 6))],
       "alto"),
    ev("oos_us12", "eleicoes",
       "Trump vencerá Geórgia na eleição presidencial 2024?",
       "Trump > Harris em GA.",
       "GA virou D em 2020 (Biden). Polling 1/8: R+1-2.",
       "GA SoS resultado oficial.",
       1, 0.55, "prediction_market", date(2024, 8, 1), date(2024, 11, 6),
       [fonte("https://sos.ga.gov/elections-and-voter-registration", "GA SoS 2024 Results", date(2024, 11, 6))],
       "alto"),
    ev("oos_us13", "eleicoes",
       "Trump vencerá Nevada na eleição presidencial 2024?",
       "Trump > Harris em NV.",
       "NV historicamente D mas competitivo. Polling 1/8: R+0.5.",
       "NV SoS resultado oficial 2024.",
       1, 0.50, "prediction_market", date(2024, 8, 1), date(2024, 11, 6),
       [fonte("https://www.nvsos.gov/sos/elections/election-results", "NV SoS 2024 Election", date(2024, 11, 6))],
       "alto"),
    ev("oos_us14", "eleicoes",
       "Trump vencerá Arizona na eleição presidencial 2024?",
       "Trump > Harris em AZ.",
       "AZ Biden venceu 2020 por 0.3pp. Polling 1/8: R+2.",
       "AZ SoS resultado oficial 2024.",
       1, 0.55, "prediction_market", date(2024, 8, 1), date(2024, 11, 6),
       [fonte("https://azsos.gov/elections", "AZ 2024 Presidential", date(2024, 11, 6))],
       "alto"),
    ev("oos_us15", "eleicoes",
       "Trump vencerá Carolina do Norte na eleição presidencial 2024?",
       "Trump > Harris em NC.",
       "NC sempre R desde 2008 (exceto 2008). Polling 1/8: R+1.",
       "NC SBE resultado oficial.",
       1, 0.60, "prediction_market", date(2024, 8, 1), date(2024, 11, 6),
       [fonte("https://www.ncsbe.gov/results-data", "NC State Board of Elections", date(2024, 11, 6))],
       "alto"),
]


# ============================================================
# EARNINGS Q3 2024 (reported Out-Nov 2024) — 15 eventos
# Outcome: EPS reportado > consenso analyst (Refinitiv/Zacks)
# Fonte primária: 8-K SEC
# ============================================================
EARNINGS = [
    ev("oos_eps01", "earnings",
       "NVIDIA reportará EPS Q3 FY25 acima do consenso?",
       "EPS GAAP reportado em 8-K > consenso Refinitiv pré-release.",
       "Em 1/8/2024, NVDA tinha histórico de 8 trimestres consecutivos de beats. Consenso Q3 FY25 ~0.74.",
       "8-K SEC filing comparado a consenso pré-release Zacks/Refinitiv.",
       1, 0.80, "analyst_consensus", date(2024, 8, 1), date(2024, 11, 20),
       [fonte("https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001045810&type=8-K", "NVDA 8-K Q3 FY25", date(2024, 11, 20))],
       "medio"),
    ev("oos_eps02", "earnings",
       "Apple reportará EPS Q4 FY24 (set 2024) acima do consenso?",
       "EPS reportado > consenso pré-release.",
       "AAPL históricamente bate consenso. Consenso Q4 FY24 ~$1.59.",
       "8-K AAPL comparado a Zacks consenso.",
       1, 0.70, "analyst_consensus", date(2024, 8, 1), date(2024, 10, 31),
       [fonte("https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000320193&type=8-K", "AAPL Q4 FY24 8-K", date(2024, 10, 31))],
       "medio"),
    ev("oos_eps03", "earnings",
       "Microsoft reportará EPS Q1 FY25 acima do consenso?",
       "EPS reportado > consenso.",
       "MSFT 9 trimestres consecutivos de beats. Consenso Q1 FY25 ~$3.10.",
       "MSFT 8-K Oct 30.",
       1, 0.75, "analyst_consensus", date(2024, 8, 1), date(2024, 10, 30),
       [fonte("https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000789019&type=8-K", "MSFT Q1 FY25 8-K", date(2024, 10, 30))],
       "medio"),
    ev("oos_eps04", "earnings",
       "Alphabet reportará EPS Q3 2024 acima do consenso?",
       "EPS reportado > consenso pré-release.",
       "GOOG bate consenso ~80% das vezes. Consenso Q3 ~$1.83.",
       "GOOG 8-K Oct 29.",
       1, 0.70, "analyst_consensus", date(2024, 8, 1), date(2024, 10, 29),
       [fonte("https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001652044&type=8-K", "GOOG Q3 2024 8-K", date(2024, 10, 29))],
       "medio"),
    ev("oos_eps05", "earnings",
       "Meta reportará EPS Q3 2024 acima do consenso?",
       "EPS > consenso.",
       "META 6 beats consecutivos. Consenso Q3 ~$5.25.",
       "META 8-K Oct 30.",
       1, 0.75, "analyst_consensus", date(2024, 8, 1), date(2024, 10, 30),
       [fonte("https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001326801&type=8-K", "META Q3 2024 8-K", date(2024, 10, 30))],
       "medio"),
    ev("oos_eps06", "earnings",
       "Amazon reportará EPS Q3 2024 acima do consenso?",
       "EPS > consenso.",
       "AMZN bate ~70% das vezes. Consenso Q3 ~$1.14.",
       "AMZN 8-K Oct 31.",
       1, 0.70, "analyst_consensus", date(2024, 8, 1), date(2024, 10, 31),
       [fonte("https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001018724&type=8-K", "AMZN Q3 2024 8-K", date(2024, 10, 31))],
       "medio"),
    ev("oos_eps07", "earnings",
       "Tesla reportará EPS Q3 2024 acima do consenso?",
       "Adjusted EPS > consenso.",
       "TSLA misses Q1+Q2 2024. Consenso Q3 ~$0.58. Pessimismo no buy-side.",
       "TSLA 8-K Oct 23.",
       1, 0.50, "analyst_consensus", date(2024, 8, 1), date(2024, 10, 23),
       [fonte("https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001318605&type=8-K", "TSLA Q3 2024 8-K", date(2024, 10, 23))],
       "medio"),
    ev("oos_eps08", "earnings",
       "Netflix reportará EPS Q3 2024 acima do consenso?",
       "EPS > consenso.",
       "NFLX bate consenso pós-2023 turnaround. Consenso Q3 ~$5.16.",
       "NFLX 8-K Oct 17.",
       1, 0.75, "analyst_consensus", date(2024, 8, 1), date(2024, 10, 17),
       [fonte("https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001065280&type=8-K", "NFLX Q3 2024 8-K", date(2024, 10, 17))],
       "medio"),
    ev("oos_eps09", "earnings",
       "JPMorgan reportará EPS Q3 2024 acima do consenso?",
       "EPS > consenso pré-release.",
       "JPM bancário consistente. Consenso Q3 ~$4.01.",
       "JPM 8-K Oct 11.",
       1, 0.75, "analyst_consensus", date(2024, 8, 1), date(2024, 10, 11),
       [fonte("https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000019617&type=8-K", "JPM Q3 2024 8-K", date(2024, 10, 11))],
       "medio"),
    ev("oos_eps10", "earnings",
       "Walmart reportará EPS Q3 FY25 acima do consenso?",
       "EPS > consenso.",
       "WMT 12 beats consecutivos. Consenso Q3 FY25 ~$0.53.",
       "WMT 8-K Nov 19.",
       1, 0.75, "analyst_consensus", date(2024, 8, 1), date(2024, 11, 19),
       [fonte("https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000104169&type=8-K", "WMT Q3 FY25 8-K", date(2024, 11, 19))],
       "medio"),
    ev("oos_eps11", "earnings",
       "Goldman Sachs reportará EPS Q3 2024 acima do consenso?",
       "EPS > consenso.",
       "GS rebound em IB. Consenso Q3 ~$6.89.",
       "GS 8-K Oct 15.",
       1, 0.65, "analyst_consensus", date(2024, 8, 1), date(2024, 10, 15),
       [fonte("https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000886982&type=8-K", "GS Q3 2024 8-K", date(2024, 10, 15))],
       "medio"),
    ev("oos_eps12", "earnings",
       "Coca-Cola reportará EPS Q3 2024 acima do consenso?",
       "EPS > consenso.",
       "KO defensivo, bate consistentemente. Consenso Q3 ~$0.74.",
       "KO 8-K Oct 23.",
       1, 0.75, "analyst_consensus", date(2024, 8, 1), date(2024, 10, 23),
       [fonte("https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000021344&type=8-K", "KO Q3 2024 8-K", date(2024, 10, 23))],
       "medio"),
    ev("oos_eps13", "earnings",
       "Boeing reportará EPS Q3 2024 acima do consenso (será menos negativo que esperado)?",
       "EPS reportado > consenso pré-release (ambos podem ser negativos).",
       "BA em crise pós-strike + 737MAX. Consenso Q3 ~-$10.34. Pessimismo extremo.",
       "BA 8-K Oct 23.",
       0, 0.40, "analyst_consensus", date(2024, 8, 1), date(2024, 10, 23),
       [fonte("https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000012927&type=8-K", "BA Q3 2024 8-K", date(2024, 10, 23))],
       "medio"),
    ev("oos_eps14", "earnings",
       "Intel reportará EPS Q3 2024 acima do consenso?",
       "EPS > consenso.",
       "INTC em downturn estrutural. Consenso Q3 ~-$0.03 (loss).",
       "INTC 8-K Oct 31.",
       1, 0.40, "analyst_consensus", date(2024, 8, 1), date(2024, 10, 31),
       [fonte("https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000050863&type=8-K", "INTC Q3 2024 8-K", date(2024, 10, 31))],
       "medio"),
    ev("oos_eps15", "earnings",
       "AMD reportará EPS Q3 2024 acima do consenso?",
       "EPS > consenso.",
       "AMD beneficiário AI. Consenso Q3 ~$0.92.",
       "AMD 8-K Oct 29.",
       1, 0.65, "analyst_consensus", date(2024, 8, 1), date(2024, 10, 29),
       [fonte("https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000002488&type=8-K", "AMD Q3 2024 8-K", date(2024, 10, 29))],
       "medio"),
]


# ============================================================
# ESPORTES Set 2024 - Abr 2025 — 15 eventos
# ============================================================
ESPORTES = [
    ev("oos_sport01", "esportes",
       "Los Angeles Dodgers vencerão a World Series 2024?",
       "Dodgers vencem 4 jogos da MLB World Series 2024.",
       "Dodgers terminaram regular season com melhor record da NL. Yankees AL champ. Vegas: LAD -135.",
       "MLB.com chamada oficial.",
       1, 0.60, "closing_odds", date(2024, 8, 1), date(2024, 10, 31),
       [fonte("https://www.mlb.com/postseason/2024/world-series", "MLB World Series 2024", date(2024, 10, 31))],
       "alto"),
    ev("oos_sport02", "esportes",
       "Philadelphia Eagles vencerão o Super Bowl LIX?",
       "Eagles vencem o jogo Super Bowl LIX (Feb 9 2025).",
       "Eagles 14-3 regular. Chiefs eram favoritos buscando 3-peat. Vegas: KC -1.5.",
       "NFL.com Super Bowl LIX final.",
       1, 0.45, "closing_odds", date(2024, 8, 1), date(2025, 2, 10),
       [fonte("https://www.nfl.com/super-bowl/", "NFL Super Bowl LIX", date(2025, 2, 10))],
       "alto"),
    ev("oos_sport03", "esportes",
       "Kansas City Chiefs chegarão ao Super Bowl LIX?",
       "Chiefs vencem AFC Championship Game.",
       "Chiefs 15-2 regular, melhor seed AFC. Buffalo principal ameaça.",
       "NFL.com AFC Championship.",
       1, 0.65, "closing_odds", date(2024, 8, 1), date(2025, 1, 27),
       [fonte("https://www.nfl.com/playoffs/", "NFL Playoffs 2024-25", date(2025, 1, 27))],
       "alto"),
    ev("oos_sport04", "esportes",
       "New York Liberty vencerão a WNBA Finals 2024?",
       "Liberty vencem série WNBA Finals 2024.",
       "Liberty melhor record regular. Lynx oponente.",
       "WNBA.com Finals 2024.",
       1, 0.65, "closing_odds", date(2024, 8, 1), date(2024, 10, 21),
       [fonte("https://www.wnba.com/playoffs/2024", "WNBA Finals 2024", date(2024, 10, 21))],
       "alto"),
    ev("oos_sport05", "esportes",
       "Max Verstappen ganhará o Campeonato Mundial F1 2024 de pilotos?",
       "Verstappen termina 2024 com mais pontos.",
       "Em 1/8/2024, Verstappen liderava com ~80pp de vantagem sobre Norris. McLaren em ascensão.",
       "Resultado oficial FIA F1 2024.",
       1, 0.85, "closing_odds", date(2024, 8, 1), date(2024, 12, 8),
       [fonte("https://www.formula1.com/en/results.html", "F1 2024 Driver Standings", date(2024, 12, 8))],
       "alto"),
    ev("oos_sport06", "esportes",
       "McLaren ganhará o Campeonato Mundial F1 2024 de construtores?",
       "McLaren termina com mais pontos que Red Bull e Ferrari.",
       "Em 1/8/2024, Red Bull liderava mas perdendo pace. McLaren close 2nd. Ferrari 3rd.",
       "Resultado oficial FIA F1 2024 constructors.",
       1, 0.40, "closing_odds", date(2024, 8, 1), date(2024, 12, 8),
       [fonte("https://www.formula1.com/en/results.html", "F1 2024 Constructor Standings", date(2024, 12, 8))],
       "alto"),
    ev("oos_sport07", "esportes",
       "Ohio State vencerá o College Football Playoff National Championship 2024-25?",
       "Ohio State vence o jogo final em 20 jan 2025.",
       "Pré-season ranking #2. Era 1ª temporada com playoff de 12 times.",
       "NCAA CFP Championship resultado.",
       1, 0.20, "closing_odds", date(2024, 8, 1), date(2025, 1, 21),
       [fonte("https://www.ncaa.com/championships/football/fbs", "CFP Championship 2024-25", date(2025, 1, 21))],
       "alto"),
    ev("oos_sport08", "esportes",
       "Jannik Sinner vencerá o ATP Finals 2024?",
       "Sinner vence o título do ATP Finals em Turim.",
       "Sinner #1 ranking, 2 grand slams 2024. Alcaraz e Zverev oponentes.",
       "ATP Tour resultado oficial.",
       1, 0.40, "closing_odds", date(2024, 8, 1), date(2024, 11, 17),
       [fonte("https://www.atptour.com/en/tournaments/nitto-atp-finals/605", "ATP Finals 2024", date(2024, 11, 17))],
       "alto"),
    ev("oos_sport09", "esportes",
       "Real Madrid vencerá La Liga 2024-25?",
       "Real Madrid termina a temporada La Liga 2024-25 em 1º lugar.",
       "Real Madrid campeão 2023-24. Reforço Mbappé verão 2024. Barça forte rival.",
       "LaLiga.com classificação final.",
       0, 0.60, "closing_odds", date(2024, 8, 1), date(2025, 5, 25),
       [fonte("https://www.laliga.com/en-GB/laliga-easports/standing", "La Liga 2024-25 Final", date(2025, 5, 25))],
       "alto"),
    ev("oos_sport10", "esportes",
       "Liverpool vencerá Premier League 2024-25?",
       "Liverpool termina 1º na Premier League 2024-25.",
       "Em 1/8/2024, Liverpool com novo técnico Slot pós-Klopp. Man City era favorito 4-peat.",
       "Premier League classificação final.",
       1, 0.15, "closing_odds", date(2024, 8, 1), date(2025, 5, 25),
       [fonte("https://www.premierleague.com/tables", "Premier League 2024-25 Final", date(2025, 5, 25))],
       "alto"),
    ev("oos_sport11", "esportes",
       "Paris Saint-Germain vencerá a Champions League 2024-25?",
       "PSG vence a final UEFA Champions League em 31 mai 2025.",
       "Em 1/8/2024, PSG perdeu Mbappé. Real Madrid favoritos. PSG longshot.",
       "UEFA.com chamada da final.",
       1, 0.08, "closing_odds", date(2024, 8, 1), date(2025, 5, 31),
       [fonte("https://www.uefa.com/uefachampionsleague/", "UCL Final 2024-25", date(2025, 5, 31))],
       "alto"),
    ev("oos_sport12", "esportes",
       "Boston Celtics chegarão à NBA Finals 2025?",
       "Celtics vencem East Finals 2025.",
       "Celtics campeões 2024. Roster intacto. Knicks/Bucks principais ameaças.",
       "NBA.com chamada oficial.",
       0, 0.45, "closing_odds", date(2024, 8, 1), date(2025, 6, 1),
       [fonte("https://www.nba.com/playoffs/2025", "NBA Playoffs 2025", date(2025, 6, 1))],
       "alto"),
    ev("oos_sport13", "esportes",
       "Florida Panthers vencerão a Stanley Cup 2024-25?",
       "Panthers vencem NHL Stanley Cup Final 2025.",
       "Panthers eram campeões 2024. Roster forte.",
       "NHL.com chamada Stanley Cup.",
       1, 0.15, "closing_odds", date(2024, 8, 1), date(2025, 6, 17),
       [fonte("https://www.nhl.com/news/stanley-cup-final", "NHL Stanley Cup 2024-25", date(2025, 6, 17))],
       "alto"),
    ev("oos_sport14", "esportes",
       "Milwaukee Bucks vencerão o NBA Cup (In-Season Tournament) 2024?",
       "Bucks vencem final do NBA Cup em dezembro 2024.",
       "Era 2ª edição do torneio. LAL campeão 2023.",
       "NBA.com NBA Cup 2024.",
       1, 0.08, "closing_odds", date(2024, 8, 1), date(2024, 12, 18),
       [fonte("https://www.nba.com/nbacup", "NBA Cup 2024", date(2024, 12, 18))],
       "alto"),
    ev("oos_sport15", "esportes",
       "Carlos Alcaraz vencerá Wimbledon 2024 (junho-julho 2024 — antes do cutoff, sanity check)?",
       "Alcaraz vence final de Wimbledon 2024.",
       "Pré-cutoff. Sanity check para validar pipeline.",
       "Wimbledon resultado oficial 14 jul 2024.",
       1, 0.40, "closing_odds", date(2024, 6, 1), date(2024, 7, 14),
       [fonte("https://www.wimbledon.com/", "Wimbledon 2024", date(2024, 7, 14))],
       "alto"),
]


# ============================================================
# IPOs / Mercados (Set 2024 - Abr 2025) — 5 eventos
# ============================================================
IPOS = [
    ev("oos_ipo01", "ipos",
       "ServiceTitan terá IPO precificado acima da faixa em dezembro 2024?",
       "Preço final IPO > top da faixa anunciada (~$52-57).",
       "Roadshow forte, demanda robusta para IPOs vertical SaaS.",
       "S-1/424B4 final SEC.",
       1, 0.55, "analyst_consensus", date(2024, 8, 1), date(2024, 12, 12),
       [fonte("https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001824420&type=424", "ServiceTitan IPO Pricing", date(2024, 12, 12))],
       "medio"),
    ev("oos_ipo02", "ipos",
       "ServiceTitan fechará primeiro dia de trading com pop ≥ 30%?",
       "Preço fechamento primeiro pregão / preço IPO ≥ 1.30.",
       "Vertical SaaS com altas margens. Mercado favorável.",
       "NASDAQ:TTAN preço fechamento dia 1.",
       1, 0.45, "analyst_consensus", date(2024, 8, 1), date(2024, 12, 12),
       [fonte("https://www.nasdaq.com/market-activity/stocks/ttan", "TTAN First Day Close", date(2024, 12, 13))],
       "medio"),
    ev("oos_ipo03", "ipos",
       "S&P 500 fechará 2024 acima de 5.500 pontos?",
       "S&P 500 close 31 dez 2024 > 5500.",
       "Em 1/8/2024, S&P estava em ~5450. Bull market mas valuations elevados.",
       "S&P Dow Jones Indices close oficial 31 dez 2024.",
       1, 0.65, "closing_odds", date(2024, 8, 1), date(2024, 12, 31),
       [fonte("https://www.spglobal.com/spdji/en/indices/equity/sp-500/", "S&P 500 2024 Close", date(2024, 12, 31))],
       "medio"),
    ev("oos_ipo04", "ipos",
       "Bitcoin fechará 2024 acima de $90.000?",
       "BTC/USD spot close 31 dez 2024 > 90000.",
       "Em 1/8/2024, BTC ~$60k. ETFs aprovados Jan 2024 trouxeram inflows.",
       "Coinbase BTC close 31 dez 2024.",
       1, 0.30, "prediction_market", date(2024, 8, 1), date(2024, 12, 31),
       [fonte("https://www.coinbase.com/price/bitcoin", "BTC 2024 Close", date(2024, 12, 31))],
       "medio"),
    ev("oos_ipo05", "ipos",
       "Federal Reserve cortará a taxa de juros em 50bp na decisão de setembro 2024?",
       "FOMC Sep 18 2024 anuncia corte de 50 basis points.",
       "Em 1/8/2024, market pricing ~50% para 25bp e ~50% para 50bp em Sep.",
       "Fed.gov FOMC statement Sep 18 2024.",
       1, 0.45, "prediction_market", date(2024, 8, 1), date(2024, 9, 18),
       [fonte("https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm", "FOMC Sep 2024 Statement", date(2024, 9, 18))],
       "medio"),
]


# ============================================================
# Compila e escreve
# ============================================================
def main() -> int:
    eventos = ELEICOES_US + EARNINGS + ESPORTES + IPOS
    print(f"Total eventos curados: {len(eventos)}")
    print(f"  eleições: {len(ELEICOES_US)}")
    print(f"  earnings: {len(EARNINGS)}")
    print(f"  esportes: {len(ESPORTES)}")
    print(f"  ipos/mercados: {len(IPOS)}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    to_jsonl(eventos, OUT)
    print(f"\nSaída: {OUT.relative_to(REPO)}")
    print("\nTodos com audit_status='pendente'. Helena precisa validar antes de holdout.")
    print("Próximo passo: rodar outcome_probe contra esses 50 para detectar leakage residual.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
